### ISSUE TITLE
[subtitles] [eng] «Nous devrons réduire la part de consommation de protéines carnées» - Mélenchon

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#101]
# Video title

«Nous devrons réduire la part de consommation de protéines carnées» - Mélenchon

# URL

https://www.youtube.com/watch?v=0_kz-S1E8S8

# Youtube subtitle language

Anglais

# Duration

2:11

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=player&tab=captions&v=0_kz-S1E8S8&bl=vmp&lang=en&ui=hd&action_mde_edit_form=1

**Comment by Blange1** [comment]
1ère relecture faite, modifications effectuées : 

"I tackled the subject with quinoa"  -->  "**My entry point** was quinoa"   (sinon on se demande quel est ce "subject" à "tackle")

"You did not become a vegetarian, right?" --> "you **have** not yet become a vegetarian , right?"
"No, I did not"  --> "No I **have** not" 

"intolerable for a society that shares values of compassion" --> "intolerable for a society that **promotes** values of compassion"

"to criticize cattle breeders that produce meat" --> "to criticize cattle breeders **who** produce meat"

" huge quantities of low-quality meat, that is like poison, flood the market" --> " huge quantities of low-quality, **poisonous** meat flood the market"

**Comment by Flupignon** [comment]
Nice !
