### ISSUE TITLE
[subtitles] [eng] L'Europe on la change ou on la quitte

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#103]
# Video title

L'Europe on la change ou on la quitte

# URL

https://www.youtube.com/watch?v=VYqu0NwmAF0

# Youtube subtitle language

Anglais

# Duration

3:52

# URL subtitles

https://www.youtube.com/timedtext_editor?ui=hd&action_mde_edit_form=1&tab=captions&v=VYqu0NwmAF0&ref=player&lang=en&bl=vmp

**Comment by Flupignon** [comment]
2:02 je termine ce soir.

**Comment by Flupignon** [comment]
Done

**Comment by Vimogo** [comment]
J'ai revu et les sous-titres sont en ligne.
