### ISSUE TITLE
[subtitles] [FR] L'Europe on la change ou on la quitte

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#104]
# Video title

L'Europe on la change ou on la quitte

# URL

https://www.youtube.com/watch?v=VYqu0NwmAF0

# Youtube subtitle language

Français

# Duration

3:52

# URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&ui=hd&v=VYqu0NwmAF0&action_mde_edit_form=1&lang=fr&ref=player

**Comment by Flupignon** [comment]
Je pose ça là pour celui ou celle qui se sent d'attaque.

**Comment by Flupignon** [comment]
OK pour vérification !

**Comment by Albapringe** [comment]
Je m'y mets.

**Comment by Albapringe** [comment]
Ouch ! C'est en mono, et sur oreille droite, en plus, ma plus faible. Inaccessible pour moi... Je passe mon tour.

**Comment by Flupignon** [comment]
Désolé je me suis trompé d'issue, la vidéo n'est pas prête pour vérif :s

**Comment by Flupignon** [comment]
@Albapringe si tu bosses dessus, n'oublie pas de changer le label dans la colonne en haut à droite ;)

**Comment by DevilFishGold** [comment]
Bonjour, j'ai fini la traduction de cette vidéo. Seule interrogation est à 1:18, je n'arrive pas à entendre correctement ce qu'il dit, j'ai essayé de déchiffrer sur les lèvres tant bien que mal, mais je ne sais pas si cela est correct.

**Comment by Bentham** [comment]
"L'Europe des faces de pierre", c'est ce que j'entends aussi !

**Comment by DevilFishGold** [comment]
Ah, ça me conforte dans ce que je pensais.
Pourriez-vous me dire combien de temps cela prend pour que la traduction soit effective?

**Comment by bayasahra** [comment]
correction 1 faite !! prêt pour la deuxième vérif

**Comment by bayasahra** [comment]
approuvé et en ligne ^^

**Comment by LucileDT** [comment]
@DevilFishGold Les sous-titres sont mis en ligne après que deux comptes google les aient validés :)
