### ISSUE TITLE
Fin d'année 

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#106]
Un joyeux Noël à vous tous ! :christmas_tree: :santa:

**Comment by Albapringe** [comment]
Très joyeux Noël également à tout le monde ! En espérant que notre plus beau cadeau nous sera donné le 23 avril prochain :)

**Comment by Bentham** [comment]
Un très joyeux Noëlchon à tous !

**Comment by Flupignon** [comment]
Joyeux Noël ! @Albapringe tu veux plutôt dire le 6 mai ! ;)

**Comment by LucileDT** [comment]
![noelchon](https://images-ext-1.discordapp.net/.eJwFwd12QzAAAOB3ce-ntTXWuyDUDjqVOna1Y0mU0opIpOvO3n3f92soMRp7o5OSL3vb7m_NhS0W7RcyCdpwbt2ZtC32riNNUQ57lMHcp3ESlsHUuyFDzREez4ePOlXpurbEvQP1qXFdS2gGHuUHIKN1fPJKRs2NemDepji5zOZ36Q9ftMgQ7qYucbCqPVTBoYWn9nx9CbMBBB2K6etu_Dlh9Sa2s9k6vgRkENq6PnZe6cDNpPPcTTbFo0rFk7CyiInx9w_D8UcJ.CokFQMEu01-9PGJGSuVf78Qv9TA)

**Comment by Albapringe** [comment]
@Flupignon Très juste, mais le 6 mai, le débat entre deux-tours sera passé, et si Mélenchon est au second tour, je ne voudrais rater ça pour rien au monde ! Ce serait le deuxième cadeau, un peu superficiel, certes, mais fort plaisant ! Et le 6 mai, le troisième, l'aboutissement obligé, car jamais 2 sans 3.

**Comment by bayasahra** [comment]
J'espère que vous passez tous de bonnes fêtes... Reposez vous bien... C'est le calme avant la tempête il va falloir souquer ferme ;)

**Comment by LucileDT** [comment]
Je compte faire passer à JLM + sa famille + son équipe un document pour leurs souhaiter de joyeuses fêtes, vous pouvez rajouter un mot dedans si vous voulez ici : https://docs.google.com/document/d/1P0fRr-3_S6yWnS4XiW3i0nfDTgVeNoHkk9e8g1LI_mw/edit?usp=sharing

**Comment by Ricyeam** [comment]
bonjour tout le monde, désolé j'ai été complètement absent pendant les fêtes. Je suis en train de voir tout ce qui a été fait, j'espère pouvoir débloque certaines choses (verif anglais…) assez rapidement dans la journée. J'espère que vous avez tous passé de joyeuses fêtes et que tout va bien de votre coté !!! Merci pour le boulot qui a été fait pendant ces 2 semaines.

Question: j'ai vu qu'il y a eu des critiques sur la LSF des voeux; avions nous contacté ce traducteur ou avons nous été impliqués dans son travail de quelque facons que ce soit?

**Comment by Flupignon** [comment]
Slt @Ricyeam ! Content de te revoir ! Ne sois pas désolé, tu as le droit de prendre des vacances quand même ! Pour les critiques LSF, il y a différents sons de cloche donc c'est dur de se faire une idée... Mais nous n'avons pas été "impliqué".

**Comment by Ricyeam** [comment]
arf j'ai regardé le live tourcoing… pas trop avancé ici du coup xD :/ 
thanks @Flupignon  ! :)
