### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON : Réunion publique au Lamentin en Martinique

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#107]
# Video title
MÉLENCHON : Réunion publique au Lamentin en Martinique

# URL
https://www.youtube.com/watch?v=4vhQIa0KAtw

# Youtube subtitles language
Français

# Duration
1:21:49

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&ui=hd&action_mde_edit_form=1&tab=captions&v=4vhQIa0KAtw&bl=vmp&ref=player

**Comment by Albapringe** [comment]
A l'attaque.

**Comment by Albapringe** [comment]
Le sous-titrage est presque terminé. Il manque cependant quelques passages très courts à compléter, faute d'avoir pu les comprendre. Si quelqu'un veut bien s'en charger, je lui en serai reconnaissant ;) :

- 0:00:51 à 0:00:57
- 0:01:12 à 0:01:20
- 0:04:08 à 0:04:11

Par ailleurs, des groupes de mots que je n'ai pas compris figurent au long du discours, et sont marqués : [???]

- à 0:03:17
- à 0:08:37
- à 0:10:25
- à 0:56:33
- à 1:04:12
- à 1:15:15

**Comment by Bentham** [comment]
Je regarde !

**Comment by Bentham** [comment]
J'ai rempli les trous quand j'ai pu. Je pense qu'on peut valider tel quel, les sous-titres ont l'air bons.

**Comment by bayasahra** [comment]
@Albapringe je vois que tu n'as pas chomé ;) je me colle à la première correction ;)

**Comment by bayasahra** [comment]
Fini. bon travail @Albapringe :)
C'est en ligne, je clos l'issue.
