### ISSUE TITLE
[subtitles] [eng] Orlando : « Un meurtre homophobe de masse »

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#108]
# Video title

Orlando : « Un meurtre homophobe de masse »

# URL

https://www.youtube.com/watch?v=0I5nlon7Mn0

# Youtube subtitle language

Anglais

# Duration

3:14

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=player&v=0I5nlon7Mn0&tab=captions&bl=vmp&lang=en&ui=hd&action_mde_edit_form=1

**Comment by Blange1** [comment]
Lu et approuvé !
