### ISSUE TITLE
[subtitles] [eng] Mélenchon : L'OTAN et les USA ne sont pas les «garants de la sécurité et de la stabilité en Europe».

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#109]
# Video title

Mélenchon : L'OTAN et les USA ne sont pas les «garants de la sécurité et de la stabilité en Europe».

# URL

https://www.youtube.com/watch?v=JzvRJs6q4tM

# Youtube subtitle language

Anglais

# Duration

0:58

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=en&ui=hd&action_mde_edit_form=1&tab=captions&v=JzvRJs6q4tM&bl=vmp&ref=player

**Comment by Blange1** [comment]
1ère relecture ok, modifications effectuées : 

" the EU thus strenghthens its cooperation" -->  "the EU thus **strengthens** its cooperation" 

"and with the USA, that both guarantee security and stability in Europe."  --> "and with the USA, **calling both the wardens of** security and stability in Europe — the USA! "

"But we just had a vote on US secret prisons in Europe where people are tortured!"  --> "**right after stating that the USA holds secret prisons** in Europe where people are tortured!"

**Comment by Vimogo** [comment]
C'est vérifié et en ligne.
