### ISSUE TITLE
[subtitles] [fr] Revue de la semaine n°7

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#11]
# Video title
REVUE DE LA SEMAINE # 7 -PAUVRETÉ, iTÉLÉ, MÉDIAS, PRIVATISATION DES BARRAGES

# 

# URL
https://www.youtube.com/watch?v=oWTHYsVUSPM

# Youtube subtitles language

Français

# Duration

22:48

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=oWTHYsVUSPM&bl=vmp&tab=captions&action_mde_edit_form=1&lang=fr&ref=player&forceedit=timedtext&ui=hd

**Comment by bayasahra** [comment]
lucile comment veux tu procéder ? là c'est mon issue essaie qui fait un doublon avec la tienne .... tu veux que je la supprime ou tu veux la "close" ???

**Comment by LucileDT** [comment]
@bayasahra dans ce cas, il vaut mieux que tu fasses un commentaire disant par exemple : 

Duplicata de l'issue #8 - je ferme l'issue.

Et après, tu cliques sur le bouton "Close and comment" :)
