### ISSUE TITLE
[subtitles] [en] Brexit : l'Europe actuelle, c'est la violence sociale, politique et guerrière

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#110]
# Video title

Brexit : l'Europe actuelle, c'est la violence sociale, politique et guerrière

# URL

https://www.youtube.com/watch?v=0bMoXv8Ru_A&t=2s

# Youtube subtitle language

Anglais

# Duration

1:33

# URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&v=0bMoXv8Ru_A&ui=hd&action_mde_edit_form=1&lang=en&ref=player

**Comment by LucileDT** [comment]
@obilya les labels de l'issue ne correspondent pas à la colonne dans laquelle elle se trouve, c'est normal ?

**Comment by obilya** [comment]
Pardon, c'est vrai !

**Comment by LucileDT** [comment]
Pas de soucis :)

**Comment by obilya** [comment]
Je redéplace ici car la dernière version des sous-titres n'a pas été publiée, il faut encore une relecture.

**Comment by Flupignon** [comment]
Pour moi les sous-titres sont visibles...

**Comment by obilya** [comment]
Oui mais c'est une ancienne version, il y a eu une autre correction (par moi) depuis.

**Comment by LucileDT** [comment]
J'ai relu et approuvé, @obilya est-ce que tu peux check si les modifications sont en ligne ?

**Comment by obilya** [comment]
Toujours pas, alors que j'ai moi-même fait encore une approbation :/

**Comment by Goutte** [comment]
J'ai approuvé aussi. Quelle tristesse, cette grande salle quasiment déserte...

**Comment by obilya** [comment]
Ah ça y est :D merci, je classe !
