### ISSUE TITLE
[Subtitles] [FR] La revue de la semaine n°2 : Syrie, médias, Orwell, CETA, lobbies, agriculture

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#111]
# Video title
La revue de la semaine n°2 : Syrie, médias, Orwell, CETA, lobbies, agriculture

# URL
https://www.youtube.com/watch?v=YxhxvRoCATY

# Youtube subtitles language
Français

# Duration
24:14

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&bl=vmp&ui=hd&v=YxhxvRoCATY&tab=captions&ref=player&action_mde_edit_form=1

**Comment by Albapringe** [comment]
J'avoue, celle vidéo est un peu datée, mais bon, comme elle n'est pas sous-titrée et que j'ai du temps à tuer, je m'y colle :)

**Comment by Albapringe** [comment]
Terminé, à l'exception d'un petit passage à 3:23. Je le mets direct en review 1.

**Comment by Bentham** [comment]
J'ai rajouté le petit 3:23, c'était une expression française désuète, "n'en pouvoir mais" :)

**Comment by Albapringe** [comment]
Sympa pour le retour ! J'aurai découvert une nouvelle ancienne richesse de notre langue ;)

**Comment by bayasahra** [comment]
je suis dessus ! (première correction)

**Comment by bayasahra** [comment]
Ah mais ! le sous titrage est déjà en ligne ^^... Ce qui veut dire qu'il y a eu plusieurs relectures... je vais survoler tout de même.
Je clos l'issue.
