### ISSUE TITLE
[Subtitles] [FR] La revue de la semaine n°1 : pauvreté, Hayange, démocratie, Alstom, Juppé et retraites.

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#112]
# Video title
La revue de la semaine n°1 : pauvreté, Hayange, démocratie, Alstom, Juppé et retraites.

# URL
https://www.youtube.com/watch?v=ynfJBfJKzFw

# Youtube subtitles language
Français

# Duration
21:16

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=ynfJBfJKzFw&ui=hd&action_mde_edit_form=1&ref=player&lang=fr&bl=vmp

**Comment by Albapringe** [comment]
Encore une de plus de terminée :)
A l'exception d'un nom à 12:11. Je la mets en review.

**Comment by Flupignon** [comment]
Serge Tchuruk (pdg d'Alstom). Je te laisse compléter, j'ai pas le temps là ;)

**Comment by Albapringe** [comment]
Done. Merci pour l'info :)

**Comment by bayasahra** [comment]
je suis sur la première correction !

**Comment by bayasahra** [comment]
Fini.
Bon travail Albapringe <3 !! (pas d'accent sur le "roder" à 20:28 ;) ça change vraiment tout le sens :p)
Je clos l'issue c'est en ligne.
