### ISSUE TITLE
[Subtitles] [FR] #RDLS12 - JACQUELINE SAUVAGE, CHRISTINE LAGARDE, CAISSIÈRE AUCHAN, INSCRIPTION LISTES ÉLECTORALES

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#113]
# Video title
#RDLS12 - JACQUELINE SAUVAGE, CHRISTINE LAGARDE, CAISSIÈRE AUCHAN, INSCRIPTION LISTES ÉLECTORALES

# URL
https://www.youtube.com/watch?v=OVp-swl3NuE

# Youtube subtitles language
Français

# Duration
23:10

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&ui=hd&action_mde_edit_form=1&bl=vmp&ref=player&tab=captions&v=OVp-swl3NuE

**Comment by Albapringe** [comment]
Sous-titrage terminé et prêt pour être vérifié :)

**Comment by Flupignon** [comment]
Et bah @Albapringe ! Une vraie formule 1 !

**Comment by bayasahra** [comment]
je fais la première correction ;)

**Comment by bayasahra** [comment]
Fini.
 Mon ti @Bentham  quand tu auras le temps ;)... j'ai plus insisté sur l'orthographe.
@Albapringe  Je serai plus disponible à partir de mercredi... ;)

**Comment by Bentham** [comment]
Je regarde ça !

**Comment by Bentham** [comment]
8:38 : on est d'accord, le mot "godot" n'est pas du tout adapté ici ? La seule acception de godot que j'aie trouvée en fait un synonyme de "jupon" et "cotillon".
J'imagine qu'il voulait dire "godet", et qu'il invente un terme d'argot plaisant pour cela. Je rajouterais bien une mention "(sic)", mais ça romprait un peu le rythme.
On laisse tel que et tant pis ?

**Comment by Albapringe** [comment]
En fait, il existe le terme godot en patois lorrain qui signifie verre. Mais, oui, si tu veux, tu peux le changer pour faciliter la compréhension du plus grand nombre.

**Comment by Bentham** [comment]
Merci @Albapringe j'apprends quelque chose ! On laisse tel quel alors.

**Comment by Bentham** [comment]
Fait !

**Comment by Bentham** [comment]
A revalider de votre côté :)

**Comment by bayasahra** [comment]
ahah <3 moi en cherchant godot j'avais trouvé "boire un godot" ==> boire un verre... donc j'ai supposé que ça allait plutôt bien :) je revalide ;) bravo pour le travail !!

**Comment by bayasahra** [comment]
c'est en ligne je clos l'issue ;)
