### ISSUE TITLE
[subtitles] [eng] #RDLS12 - JACQUELINE SAUVAGE, CHRISTINE LAGARDE, CAISSIÈRE AUCHAN, INSCRIPTION LISTES ÉLECTORALES

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#114]
# Video title

#RDLS12 - JACQUELINE SAUVAGE, CHRISTINE LAGARDE, CAISSIÈRE AUCHAN, INSCRIPTION LISTES ÉLECTORALES

# URL

https://www.youtube.com/watch?v=OVp-swl3NuE

# Youtube subtitles language

Anglais

# Duration

23:10

# Subtitles URL

https://www.youtube.com/timedtext_editor?ui=hd&tab=captions&v=OVp-swl3NuE&lang=en&ref=player&bl=vmp&action_mde_edit_form=1

**Comment by Flupignon** [comment]
7:00

**Comment by Flupignon** [comment]
Quelqu'un a fait les 30 premières secondes, je relirai à la fin.

**Comment by Flupignon** [comment]
8:12 reprise ce soir

**Comment by Flupignon** [comment]
Oui avec le petit, pas de réveillon !

**Comment by Flupignon** [comment]
18:10, ça devrait être prêt pour lundi soir ou mardi au plus tard.

**Comment by Flupignon** [comment]
Plus que 3 min à faire.

**Comment by Flupignon** [comment]
21:36

**Comment by Flupignon** [comment]
Fini !

**Comment by Flupignon** [comment]
Quelqu'un a le temps de valider les sous-titres ?

**Comment by LucileDT** [comment]
Je fais ça !

**Comment by LucileDT** [comment]
@Flupignon Tu as voulu dire quoi par "It was a trying trip" ?

**Comment by LucileDT** [comment]
https://www.buzzfeed.com/paulaveline/la-tres-etrange-traduction-en-langue-des-signes-des-voeux-de

**Comment by LucileDT** [comment]
C'est pas plutôt "drying trip" ?

**Comment by Flupignon** [comment]
Nope: https://www.merriam-webster.com/dictionary/trying

**Comment by Flupignon** [comment]
"éprouvant"

**Comment by LucileDT** [comment]
Merci :)

**Comment by Flupignon** [comment]
Je crois que c'est pour traduire "il faut quand même y rester" il me semble, parce que littéralement, ça le fait pas du tout :/

**Comment by Flupignon** [comment]
Par contre il faudrait que quelqu'un remette les sous-titres FR en forme, il y a des blocs de 4 lignes avec 2 mots sur une ligne et une ligne entière juste en-dessous... Je peux pas là, je vais me mettre sur la RDLS#13!

**Comment by Albapringe** [comment]
On débattait de ce sujet justement sur cette issue #116. Ça serait pas mal, je pense, qu'on harmonise tous notre manière de faire pour qu'on travaille de la même façon.

**Comment by Bentham** [comment]
Oui je suis d'accord. Je vais ouvrir une issue.

**Comment by Flupignon** [comment]
Sweet !

**Comment by Bentham** [comment]
#123, nous irons au bois. Venez donner votre avis !

**Comment by LucileDT** [comment]
@Flupignon JLM dit "il faut quand même y rester" pour dire qu'il faut y rester plusieurs jour sinon le corps a pas le temps de s'adapter au truc.

**Comment by Flupignon** [comment]
Haaaaaa -_- It makes sense now... Pourquoi pas "we had to stay there for a few days because..." ? Et puis juste après il y a un deuxième "trying", mais là ça me semble bon.

**Comment by LucileDT** [comment]
Impec, merci !

**Comment by LucileDT** [comment]
Je me suis arrêtée au milieu à peu près, à 10:54. Je reprends demain (sauf si quelqu'un veut s'en charger) :)

**Comment by Blange1** [comment]
Relu ! J'ai parfois simplifié certaines formulations parce qu'il parle vite et que ça fait beaucoup de texte à lire rapidement, mais globalement impeccable :)

**Comment by Flupignon** [comment]
Je ne vois pas les sous-titres. Peut-être qu'il faut une dernière validation de @Ricyeam ?

**Comment by Mattouk** [comment]
Hey,

J'ai corrigé quelques typos et reformulé un ou deux trucs pour que ça soit plus fluide, et j'avais oublié de submit, mais ça devrait apparaître maintenant.

**Comment by Flupignon** [comment]
Super ! Il reste juste la 13 à valider et la FAQ.
