### ISSUE TITLE
[subtitles] [eng] Jean-Luc Mélenchon défend la laïcité au Parlement européen

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#115]
# Video title

Jean-Luc Mélenchon défend la laïcité au Parlement européen

# URL

https://www.youtube.com/watch?v=JQbKFW65cJE&t=1s

# Youtube subtitles language

Anglais

# Duration

1:14

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&tab=captions&ref=player&ui=hd&v=JQbKFW65cJE&lang=en

**Comment by Blange1** [comment]
Bonjour, j'ai vu que cette vidéo attendait encore des sous-titres donc je l'ai sous-titrée sur Youtube, mais je viens de réaliser qu'il fallait être contributeur pour changer les labels. Du coup la prochaine fois il faut que je crée moi-même une "issue" pour les vidéos que je veux sous-titrer, c'est ça ? 

Je suis désolée si je n'ai pas respecté votre organisation, je suis nouvelle ici et je ne comprends pas très bien comment ça marche encore ! Du coup mes sous-titres sont ajoutés sur Youtube normalement

**Comment by bayasahra** [comment]
Merci pour ton travail Blange1 :)
Je ne comprends pas ton soucis... Tu ne peux pas changer les labels ?

**Comment by Blange1** [comment]
Pas de problème @bayasahra, je suis là pour ça :)

Non je ne peux pas changer les labels. Je peux seulement créer une "issue"

**Comment by bayasahra** [comment]
ah... il y a peut être un statut à avoir effectivement mais que Lucile ne saurait t'attribuer sans tarder. :)
Et non, ne refait pas une issue, qui a déjà été créée dans l'unique but de pouvoir y travailler. On ne créé surtout pas de doublon. :)

**Comment by Flupignon** [comment]
Oui je crois que c'est @LucileDT qui peut te permettre de changer les labels.

**Comment by LucileDT** [comment]
Oui, alors en fait, @Ricyeam et moi pouvons ajouter les gens en tant que "contributeurs" et à partir de ça, ils peuvent clore les issues et changer les labels : ça évite que des personnes mal intentionnées viennent désorganiser le travail volontairement.

Du coup, je viens d'ajouter @Blange1 en tant que contributeurice au projet, il n'y a plus qu'à accepter l'invitation qui a été envoyée par mail :)

@Blange1 Pas de soucis ! On n'en veut à personne de nous aider, au contraire ^_^

**Comment by obilya** [comment]
J'ai fait la 2e relecture et envoyé sur You Tube  mais la traduction anglaise n'est pas encore proposée dans la vidéo, c'est normal ? Il doit sans doute manquer une autre relecture.

**Comment by Flupignon** [comment]
Je viens d'approuver les sous-titres mais ce n'est toujours pas en ligne parce que j'ai modifié le timing.

**Comment by LucileDT** [comment]
J'ai relu, puis validé avec deux comptes différents, les sous-titres sont dispos !
