### ISSUE TITLE
[Subtitles] [FR] «UN CHAUFFEUR UBER NE GAGNE MÊME PAS LE SMIC» - MÉLENCHON

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#116]
# Video title
«UN CHAUFFEUR UBER NE GAGNE MÊME PAS LE SMIC» - MÉLENCHON

# URL
https://www.youtube.com/watch?v=IV-0iLADRFk

# Youtube subtitles language
Français

# Duration
8:55

# Subtitles URL
https://www.youtube.com/timedtext_editor?ui=hd&v=IV-0iLADRFk&action_mde_edit_form=1&ref=player&lang=fr&tab=captions&bl=vmp

**Comment by Bentham** [comment]
Ah c'est donc toi Albapringe qui travaille dessus ! Je supprime mon doublon et je te laisse faire le premier jet.

**Comment by Albapringe** [comment]
Désolé pour t'avoir grillé la politesse @Bentham. Du coup, je viens de finir, donc je te laisse procéder à la vérification ;)

**Comment by Bentham** [comment]
Hop c'est fait ! Je pense que les sous-titres sont bien tels quels, j'ai fait attention à l'orthographe et aux containers

**Comment by Albapringe** [comment]
Merci @Bentham ;) Par contre, je vois que tu rajoutes de nombreux retours à la ligne lors de la correction, est-ce que c'est lié à une pratique convenue ici, ou quelque chose de particulier ? Car tant qu'à faire, mieux vaut harmoniser nos façons de faire pour gagner du temps.

**Comment by Bentham** [comment]
Oui, c'est qu'on appelle les containers (il me semble). L'idée c'est de découper le texte de sorte que les sauts à la ligne suivent l'ordre de la grammaire. Ca rend la lecture beaucoup plus intuitive...
Pour ma part, je mets les sous-titres en taille 200 % (pour que ça soit visible pour tout le monde et dans tous les formats) et je découpe en conséquence.

Après, on n'a jamais discuté de ça, je serais intéressé par vos avis !

**Comment by Flupignon** [comment]
Parce qu'on peut pré-enregistrer une taille de sous-titres @Bentham ? Je croyais que c'était des options perso... Tu fais comment ?

**Comment by Bentham** [comment]
Non, j'active de mon côté en 200 % et je fais en fonction de ça ! De cette manière, l'utilisateur pourra mettre en 100 % ou en 200 %, comme il le désire, dans tous les cas l'affichage sera propre.

**Comment by Bentham** [comment]
Bon, sinon mauvaise nouvelle, la vidéo s'est fait _strike_ par France Inter, elle est donc maintenant indisponible... Je crois qu'on a bossé pour rien !

**Comment by Albapringe** [comment]
En effet... J'adore travailler pour rien. Vive la censure. J'ai manifesté ma déception sur la même vidéo présente sur la chaîne Youtube de France Inter, du coup.

**Comment by Flupignon** [comment]
Ou quand le service public privatise...

**Comment by LucileDT** [comment]
Si la vidéo revient en ligne, ou qu'on peut la voir dans d'autres pays, vous n'aurez pas "travaillé pour rien" ;)

**Comment by Bentham** [comment]
Le débat sur les blocs de sous-titres est lancé ici : #123

**Comment by Albapringe** [comment]
La vidéo est revenue :)

Edit : les sous-titres sont présents, je clos l'issue pour faire un peu de ménage ;)
