### ISSUE TITLE
[subtitles] [FR] «UN CHAUFFEUR UBER NE GAGNE MÊME PAS LE SMIC» - MÉLENCHON

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#117]
# Video title
«UN CHAUFFEUR UBER NE GAGNE MÊME PAS LE SMIC» - MÉLENCHON

# URL
https://www.youtube.com/watch?v=IV-0iLADRFk

# Youtube subtitles language
Français

# Duration
8:55

# Subtitles URL
https://www.youtube.com/timedtext_video?ref=player&v=IV-0iLADRFk

**Comment by Bentham** [comment]
J'ai l'impression que quelqu'un est en train de travailler dessus. Je vérifierai plus tard.

**Comment by quidam34** [comment]
BOnjour ce sujet est -il libre ? si oui on équipe sans occupe . merci

**Comment by Bentham** [comment]
Cette vidéo est déjà sous-titrée.

**Comment by quidam34** [comment]
rooo mais comment je le vois ? je viens de voir que le sujet était "closed" mais vous n'avez pas un label pour l'indiqué ?

**Comment by Bentham** [comment]
Quand une issue est fermée, ça signifie qu'il n'y a plus rien à faire.

**Comment by LucileDT** [comment]
@quidam34 il faudrait lire les tutoriels mis à disposition : beaucoup des questions que tu poses y trouvent une réponse.
