### ISSUE TITLE
[Subtitles] [FR] VOEUX DE JEAN-LUC MÉLENCHON - UNE FRANCE AU SERVICE DE LA PAIX

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#118]
# Video title
VOEUX DE JEAN-LUC MÉLENCHON - UNE FRANCE AU SERVICE DE LA PAIX

# URL
https://www.youtube.com/watch?v=u8Lta7F4SgY

# Youtube subtitles language
Français

# Duration
34:56

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=u8Lta7F4SgY&lang=fr&action_mde_edit_form=1&ref=player&bl=vmp&ui=hd

**Comment by Albapringe** [comment]
J'attaque cette vidéo. Celle-ci ne devrait pas faire l'objet de demandes de droits :)

**Comment by Albapringe** [comment]
Petite question : je vois qu'un traitement de la vidéo a été fait à posteriori du moment où j'ai commencé le sous-titrage. En effet, elle a été tronquée pour sa partie initiale (avant le début du discours). Ce qui a généré un décalage de plusieurs minutes de tous mes sous-titrages avec le contenu de la vidéo. Dites-moi qu'il y a un moyen de faire une translation de mon travail facilement, sinon, je crois que je vais pleurer. :'(

**Comment by Flupignon** [comment]
J'ai encore jamais essayé mais tu peux essayer avec ce site http://www.sync-subtitles.com/ (tu me diras si ça marche bien)

**Comment by Bentham** [comment]
@Albapringe si tu n'y arrives pas, je vais essayer de mon côté. Je pense qu'il y a moyen de bricoler un petit quelque chose

**Comment by Bentham** [comment]
@Albapringe Tu vas être content, j'ai réussi à décaler les timings ! J'espère que les modifications apparaissent de votre côté !

**Comment by Albapringe** [comment]
@Flupignon : j'ai essayé d'utiliser ton outil, mais je ne parviens pas à convertir les sous-titres YT en format valide.

@Bentham : Non, rien n'a changé pour moi.

**Comment by Bentham** [comment]
Le fichier avec les sous-titres resynchronisés est ici : http://www.filedropper.com/captions2
Il suffit de rentrer le captcha et de valider pour lancer le téléchargement.

En théorie il y aurait juste à les "importer" dans l'interface de sous-titrage de YouTube (menu Actions -> Importer un fichier), sauf qu'il ne veut pas enregistrer les modifications - c'est l'ancienne version qui revient à chaque fois !

Quelqu'un a une idée ?

**Comment by bayasahra** [comment]
oh merde alors !!! ... Je ne serais d'aucunes aides avec les logiciels, ou le temps que je les assimile même rapidement sera perdu. Hummm je peux rapidement refaire le timing si tu veux ... :)

**Comment by bayasahra** [comment]
ah mais n'imp Ben l'a fait .... lol ^^" j'ai rien dit <3

**Comment by Albapringe** [comment]
Je pense qu'il ne faut pas tergiverser trop longtemps et se donner jusqu'à dimanche pour avoir une solution à ce problème. Sinon, le mieux à mon avis sera de recommencer à zéro (misère...). Le taf va augmenter dans les prochains jours, avec les deux meetings du 8 et du 11 janvier et on risque de prendre du retard pour suivre la cadence...

**Comment by bayasahra** [comment]
LOL mais non :) @Albapringe , on était pas très présents Ben et moi ça va être différent les jours qui vont venir... on est assez efficaces tu t'en apercevras lol ;)... et c'est pas qu'une mauvaise chose de tergiverser ^^ ça peut s'avérer même fort utile parfois ;) ... J'ai quelques dossiers encore à faire informatiquement pour projet perso ... mais dès que je me suis débarrassée de ça je reprendrai le sous titrage :) Ne sois pas si inquiet

**Comment by Albapringe** [comment]
Je ne remets absolument pas en cause votre efficacité, loin de là ;) Mais on va avoir probablement quelque chose comme 3h30 de vidéos à sous-titrer la semaine prochaine, du lourd, quoi. Après, oui, on est pas tenus non plus de rendre les sous-titres pour le jour même, c'est vrai. :)

**Comment by Flupignon** [comment]
Vous pouvez pas les effacer les sous-titres avant d'importer le fichier ?

**Comment by Bentham** [comment]
Bayou, tu vois les sous-titres synchronisés ?? Ça ne marche pas chez moi, et apparemment pas chez @Albapringe non plus !

**Comment by bayasahra** [comment]
Mince non !!!! y'a toujours le décalage pour moi aussi !!! il faut refaire le timing nan ??? je  le fais rapidement dans la soirée :)

**Comment by Bentham** [comment]
Je contacte le service technique de Youtube sur leur forum, j'espère avoir une réponse, ça serait très utile de comprendre comment uploader des fichiers de sous-titres !

**Comment by Bentham** [comment]
Les sous-titres viennent d'être synchronisés. Est-ce le fait de l'un(e) d'entre vous, ou est-ce mon importation de fichier qui a mystérieusement fini par marcher ?

**Comment by Albapringe** [comment]
Perso, je n'ai rien fait, mais bonne nouvelle, je vais pouvoir reprendre. Il est grand temps que les sourds puissent avoir un sous-titrage au vu de la polémique sur la LSF.

Edit : je viens d'y aller et je n'ai pas de synchronisation. Tu l'as toujours ?

**Comment by Bentham** [comment]
Oui la synchronisation est toujours correcte chez moi. J'enregistre de nouveau pour voir si ça change quelque chose.

**Comment by Bentham** [comment]
haaaaa... J'ai enregistré et tout s'est désynchronisé !! Ca a l'air de bugger à mort leur interface là !

**Comment by Albapringe** [comment]
J'ai repris cette vidéo en réglant le problème du décalage normalement (j'ai eu énormément de chance, le décalage était presque rond, de 2:00.4 exactement, ce qui a nettement facilité la correction des ancrages temporels des containers). J'en suis à 18:30, je reprends demain :)

**Comment by Albapringe** [comment]
Terminé. Prêt pour une première relecture :)

**Comment by Vimogo** [comment]
Allez, je prends !

**Comment by Vimogo** [comment]
C'est fait !

**Comment by Vimogo** [comment]
Quelqu'un peut-il me confirmer que les sous-titres sont bien déjà en ligne, comme ils semblent l'être chez moi ?

**Comment by Albapringe** [comment]
Je confirme. Tu as fait des modifs ou pas ?

**Comment by Vimogo** [comment]
Non. Il y avait un seul endroit où le discours de Mélenchon a été modifié de "jusque et au delà" à "jusqu'au delà" mais considérant que cela clarifie le discours je n'ai apporté aucune modification.

**Comment by Albapringe** [comment]
OK, merci :) Comme les sous-titres sont en ligne, je clos donc cette issue.
