### ISSUE TITLE
[Subtitles] [FR] #RDLS13 : CONDITIONS DE TRAVAIL, AUCHAN, MULLIEZ, IMPÔT, SYRIE, TROPHÉE 100 000 ABONNÉS, ANNONCE FAQ

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#119]
# Video title
#RDLS13 : CONDITIONS DE TRAVAIL, AUCHAN, MULLIEZ, IMPÔT, SYRIE, TROPHÉE 100 000 ABONNÉS, ANNONCE FAQ

# URL
https://www.youtube.com/watch?v=hIrpyKHXry8

# Youtube subtitles language
Français

# Duration
26:42

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&ui=hd&lang=fr&v=hIrpyKHXry8&tab=captions&bl=vmp&action_mde_edit_form=1

**Comment by Albapringe** [comment]
Je commence celle-ci, mais je n'aurais pas le temps de la terminer aujourd'hui. Je laisserai dispo pour l'écriture à partir de 18h, donc soit quelqu'un peut prendre ma suite, soit je continuerai demain.

**Comment by Albapringe** [comment]
Fait jusqu'à 7:55

**Comment by Albapringe** [comment]
Coucou. Je viens de rentrer, mais je vois que tu t'es mis dessus, @Flupignon. Je t'assigne et je mets en mode "Someone is working".

**Comment by Flupignon** [comment]
Non erreur @Albapringe, je m'occupe de la version en anglais !

**Comment by Albapringe** [comment]
Ah, désolé pour l'erreur. Il y a pourtant quelqu'un qui a poursuivi le travail....

**Comment by Flupignon** [comment]
C'est pô moi, wallah !

**Comment by Albapringe** [comment]
... je dirais même plus, quelqu'un a fini le travail. Bon, ben, je laisse quelqu'un d'autre faire la révision car je suis partie prenante, donc, je ne vais pas le faire moi-même ;)

**Comment by bayasahra** [comment]
je suis dessus.

**Comment by bayasahra** [comment]
Fini. Prêt pour deuxième correction ^^

**Comment by Bentham** [comment]
Let's goooooo

**Comment by Bentham** [comment]
C'est envoyé ! Faudra ptet revalider de votre côté ! Et fermer l'issue derrière vous en sortant :)
