### ISSUE TITLE
[subtitles] [fr] Revue de la semaine n°8

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#12]
# Video title
RDLS # 8 : FILLON, NUCLÉAIRE, PRISON FERME POUR UN VOLEUR AFFAMÉ 

# URL
https://www.youtube.com/watch?v=4zZ0rOIMOPs

# Youtube subtitles language
Francais

# Duration
17:13

# Subtitles URL

https://www.youtube.com/timedtext_editor?ref=player&tab=captions&forceedit=timedtext&v=4zZ0rOIMOPs&ui=hd&lang=fr&action_mde_edit_form=1&bl=vmp

**Comment by Ricyeam** [comment]
Commentaire d'un utilisateur Youtube ce soir
"meuhlkjhil y a 12 minutes
> Hello les gens, je viens de terminer le sous-titrage français, mais ils ne seront pas publiés avant vérification d'autres utilisateurs. Si vous voulez accélérer le mouvement, vous pouvez vous rendre sur la page d'ajout des sous-titres et confirmer que le sous-titrage est correct. Merci pour nos amis sourds et malentendants :)﻿"

**Comment by Ricyeam** [comment]
Commentaires youtube

**"Dario Akimil y a 6 minutes**
> +meuhlkjh ok je vais voir, là je suis en train de mater ce qui se passe pour fillon, ça va me changer !﻿

**Ricyeam Telmoecil y a 3 minutes**
> [subtitle team] salut meuhlkjh, merci pour le boulot, en effet cet apres midi j'avais vu que quelqu'un avait commencé, c'est parfait ! si tu veux etre ajouté a l'équipe fais le moi savoir :) merci en tous cas!﻿

**Ricyeam Telmoecil y a 1 seconde**
> Dario si tu peux me faire savoir quand tu as vérifié, que je le valide dans notre suivi de projets ! merci﻿"

**Comment by Ricyeam** [comment]
Sous-titres vérifiés et corrigés (par user Dario + moi meme)

**Comment by Ricyeam** [comment]
Tweet public from @AymericUK (Ricyeam)
> "@jlm_2017 @JLMelenchon [github team] Ss-titres FR de la revue n°8 écrit et vérifiés! Envoyés pour validation https://www.youtube.com/watch?v=4zZ0rOIMOPs merci! "

**Comment by Ricyeam** [comment]
Sous-titres visibles sur la video officielle.

**Comment by LucileDT** [comment]
Trop d'efficacité.

**Comment by Bentham** [comment]
Bonjour à tous, c'est moi qui me suis occupé de sous-titrer la revue 8 en français sur le tube !
Je suis partant pour continuer sur les prochaines revues.

Et veuillez m'excuser si je ne poste pas au bon endroit, le fonctionnement de github reste assez obscur pour moi :)

**Comment by LucileDT** [comment]
Salut ! Pas de soucis :D 
Je compte rédiger une documentation pour ceux qui débarquent, du coup si tu as des questions, tu peux les poser ici : #19
