### ISSUE TITLE
[subtitles] [en] #RDLS13 : CONDITIONS DE TRAVAIL, AUCHAN, MULLIEZ, IMPÔT, SYRIE, TROPHÉE 100 000 ABONNÉS, ANNONCE FAQ

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#120]
# Video title

#RDLS13 : CONDITIONS DE TRAVAIL, AUCHAN, MULLIEZ, IMPÔT, SYRIE, TROPHÉE 100 000 ABONNÉS, ANNONCE FAQ

# URL

https://www.youtube.com/watch?v=hIrpyKHXry8

# Youtube subtitles language

Anglais

# Duration

26:42

# Subtitles URL

https://www.youtube.com/timedtext_editor?v=hIrpyKHXry8&tab=captions&ref=player&action_mde_edit_form=1&ui=hd&lang=en&bl=vmp

**Comment by Flupignon** [comment]
Mais il va trop vite le Jean-Luc, c'est dur de suivre le rythme ! x)

**Comment by Flupignon** [comment]
4:03

**Comment by Flupignon** [comment]
7:28

**Comment by Flupignon** [comment]
12:14

**Comment by Flupignon** [comment]
14:16

**Comment by Flupignon** [comment]
19:12

**Comment by Flupignon** [comment]
23:16. Je devrais avoir fini dans la journée ou ce soir.

**Comment by Flupignon** [comment]
Fini ! @Ricyeam @Blange1 à vous de jouer ( @LucileDT est sur tous les fronts, on va la ménager !). Il reste aussi la RDLS 12 à valider (entre autres).

**Comment by Blange1** [comment]
Je me mets dessus ce soir @Flupignon !
