### ISSUE TITLE
[subtitles] [en] MÉLENCHON - POURQUOI LE CODE DU TRAVAIL EST GROS ?

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#122]
# Video title

MÉLENCHON - POURQUOI LE CODE DU TRAVAIL EST GROS ?

# URL

https://www.youtube.com/watch?v=jnqujbuCNsM

# Youtube subtitles language

Anglais (américain) (une version en anglais existe déjà, mais elle me plait moyen...)

# Duration

1:58

# Subtitles URL

https://www.youtube.com/timedtext_editor?tab=captions&bl=vmp&lang=en-US&action_mde_edit_form=1&ref=player&v=jnqujbuCNsM&ui=hd

**Comment by Goutte** [comment]
J'ai viré les espaces avant les `!`, donc il faut revalider. Sinon, beau travail !
