### ISSUE TITLE
[subtitles] [eng] Revue de la semaine n°13

### ISSUE THREAD

**Issue by Blange1** [jlm2017/jlm-video-subtitles#124]
# Video title
RDLS13 : CONDITIONS DE TRAVAIL, AUCHAN, MULLIEZ, IMPÔT, SYRIE, TROPHÉE 100 000 ABONNÉS, ANNONCE FAQ 

# URL
https://www.youtube.com/watch?v=hIrpyKHXry8

# Youtube subtitles language
Anglais ou Français

# Duration
26:42

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=en&ui=hd&v=hIrpyKHXry8&tab=captions&bl=vmp&action_mde_edit_form=1&ref=player

**Comment by Flupignon** [comment]
Bonsoir @Blange1 il y a déjà l'issue #120  qui existe pour la version en anglais, je l'ai commencée hier soir.

**Comment by Flupignon** [comment]
Je m'y remet ce soir d'ailleurs, tu es dessus ?

**Comment by Blange1** [comment]
Bonsoir @Flupignon, au temps pour moi je ne l'avais pas vue. Ca m'a permis de voir que je peux créer une issue, mais toujours pas créer de label ni supprimer cette issue qui est en trop. Une astuce ?

**Comment by Blange1** [comment]
Non j'ai vu qu'il y avait déjà des sous-titres en cours sur youtube directement, j'ai regardé un peu et ils me paraissent de qualité donc je n'ai pas fini. Je pourrai m'occuper de la relecture si tu veux !

**Comment by Flupignon** [comment]
Avec plaisir ! Par contre il y a plein d'issues en anglais prêtes pour relecture si tu veux !

**Comment by Flupignon** [comment]
issues #99 #100 #101 #103 #105 #108 #109 #110 et #122 ! D'habitude @Ricyeam s'en charge mais il a l'air occupé en ce moment. Et @LucileDT se charge de relire l'issue #114

**Comment by LucileDT** [comment]
@Blange1 Bienvenue ! Je vous donne les droits pour clore les issues et y ajouter des labels :)

**Comment by LucileDT** [comment]
Vous devriez avoir reçu un mail :)

**Comment by Ricyeam** [comment]
Désolé les gens, en effet je n'étais pas trop présent récemment! Je vais essayer de rattraper ca aujourd'hui. et @Blange1 hier j'étais en déplacement avec retard d'avion et le soir je me sentais pas tip top, c'est pour ca que j'ai pas répondu :) Merci @LucileDT de l'avoir rajoutée en contributrice

**Comment by Blange1** [comment]
Pas de problème @Ricyeam, et merci @LucileDT de m'avoir donné les droits !

@Flupignon je me mets à la relecture :)

**Comment by Ricyeam** [comment]
IL y a pas un doublon avec #120 ??

**Comment by Flupignon** [comment]
Si @Blange1 n'avait pas vu

**Comment by Flupignon** [comment]
Je ne vois pas les sous-titres. Peut-être qu'il faut une dernière validation de @Ricyeam ?

**Comment by Blange1** [comment]
C'est parce qu'il n'y a eu qu'une seule relecture, non ? Comme pour la #114 je pense

**Comment by Flupignon** [comment]
Oui je pense. Il vaudrait mieux attendre la publication avant de fermer l'issue
