### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - ESPRIT DE CAMPAGNE #0 - #EDC0

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#125]
# Video title
MÉLENCHON - ESPRIT DE CAMPAGNE #0 - #EDC0

# URL
https://www.youtube.com/watch?v=3iOUqUp1r3w&list=PLnAm9o_Xn_3CFeesH6PnFXAi9CzDkayoj

# Youtube subtitles language
Français

# Duration
1:12:48

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&v=3iOUqUp1r3w&tab=captions&lang=fr&bl=vmp&ui=hd

**Comment by Albapringe** [comment]
C'est parti.

**Comment by bayasahra** [comment]
@Albapringe quand tu n'es pas en train de travailler sur la vidéo il faut enlever le "someone is working on this issue"... le "writing in progress" est indiqué alors et suffisant. :)

**Comment by Albapringe** [comment]
Mais j'étais dessus, là... ;)

**Comment by bayasahra** [comment]
ah ???? bizarre j'étais allée voir en Subtitles URL y'avait personne ^^ un tour de youtube surement, mais bon ça faisait plusieurs jours qu'il y avait ce label donc j'ai supposé que c'était un oubli ^^
Je l'ai également enlevé sur "[Subtitles] [FR] VOEUX DE JEAN-LUC MÉLENCHON - UNE FRANCE AU SERVICE DE LA PAIX" ça doit pas être une erreur tu ne peux être à deux endroits à la fois.

**Comment by Albapringe** [comment]
Non, en effet, sur les vœux, je n'y suis plus tant que le problème de synchro n'est pas résolu. Merci de l'avoir enlevé ;)

**Comment by Albapringe** [comment]
Ouf ! Ça y est, c'est fini pour celui-ci. Alors, comme d'hab', il y a des parties que je n'ai pas bien comprises, signalées par [???] : 
- à 0:27:19
- à 1:00:47 et suivants (je pense que par précaution, il serait mieux de vérifier la séquence vidéo en entier, vu que le bruit de fond peut me faire confondre des mots.)

**Comment by Bentham** [comment]
à 0:27:19 je dirais : "l’îlot Caret a disparu" -> https://fr.wikipedia.org/wiki/%C3%8Elet_Caret
à 1:00:47 : "Hier matin, c'qui s'est passé, c'est qu'on a été prévenus par un habitant de Saint-Vincent-de-Mercuze"...

Je verrai le reste si je m’attelle à la correction !

**Comment by Albapringe** [comment]
Modifs faites. Merci @Bentham :)

**Comment by Bentham** [comment]
J'ai comblé quelques petits [???]

**Comment by Bentham** [comment]
Je corrige !

**Comment by Bentham** [comment]
Corrigé jusqu'à 44:37

**Comment by Vimogo** [comment]
Je finis la première correction.

**Comment by Vimogo** [comment]
Voilà, j'ai corrigé les [???] après 44:37 (je vous conseille de faire comme moi et de passer l'extrait 10 fois en vitesse 0.5 pour comprendre lorsque cela vous arrive). Première vérification terminée et envoyée.

**Comment by Albapringe** [comment]
Merci pour le conseil, j'essaierai la prochaine fois.

**Comment by Bentham** [comment]
Les sous-titres sont en ligne et ont l'air bons, je ferme l'issue.
