### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON : «JE PROPOSE L'IMPÔT UNIVERSEL»

### ISSUE THREAD

**Issue by DevilFishGold** [jlm2017/jlm-video-subtitles#126]
# **Video title**
MÉLENCHON : «JE PROPOSE L'IMPÔT UNIVERSEL»

# **URL**
https://www.youtube.com/watch?v=tqJIgWDJG4Q&t=1358s

# **Youtube subtitles language**
Français

# **Duration**
54:25

# **Subtitles URL**
https://www.youtube.com/timedtext_video?ref=player&v=tqJIgWDJG4Q

**Comment by DevilFishGold** [comment]
Une personne ne faisant pas partie du groupe participe déjà à l'élaboration des sous-titres, je la laisse donc poursuivre son sous-titrage.

**Comment by bayasahra** [comment]
Très bonne décision Devil :) surtout que travailler à deux en même temps créé des complications et quasi toujours à une perte d'une partie du travail. Donc c'est bien de toujours vérifier comme tu l'as fait qu'il n'y ait personne qui sous titre en même temps que toi même anonymement. Bon réflexe :)

**Comment by Bentham** [comment]
Je m'y mets

**Comment by Bentham** [comment]
Je fais une pause le temps d'écouter notre Méluche sur RTL :)
Corrigé jusqu'à 4:39 (les sous-titres sont assez mauvais, faut recommencer)

**Comment by Bentham** [comment]
re

**Comment by Bentham** [comment]
Fait jusqu'à 16:31.

**Comment by Bentham** [comment]
J'y retourne un peu

**Comment by Bentham** [comment]
23:17

**Comment by LVAI** [comment]
Je m'y mets

**Comment by LVAI** [comment]
Hop, petite pause et je m'y remets d'ici 1h max.
J'ai publié jusqu'à 31:38.8 avec un trou à 29:44 : "les gens auront une qualification ascendante donc ??".

**Comment by LVAI** [comment]
C'est reparti

**Comment by LVAI** [comment]
Voilà j'ai avancé jusqu'à 38:22.7.
Petite contribution aujourd'hui.
Je m'arrête pour faire un peu de LSF ^^

Un doute à 32:29 : "Et je trouve ça dommage que vous le laissiez (?) complètement de votre réflexion." et à la suite "JLM : Ça ne dépend (?) pas de ma réflexion. Faites-moi l'honneur de penser que j'en suis capable."
Si quelqu'un a une idée lumineuse...

**Comment by Bentham** [comment]
Ouiiiii fais tout plein de LSF ! Comme ça tu pourras nous faire des vidéos à la pelle !

**Comment by Bentham** [comment]
"Et je trouve ça dommage que vous l'excluiez complètement de votre réflexion."
"Je ne l'exclus pas de ma réflexion ! Faites-moi l'honneur de penser que j'en suis capable."

Je pense !

**Comment by desintoxiquezvous** [comment]
bonjour, je suis nouveau ici, j'ai participé spontanément directement sur Youtube aux S/T de la RDLS15
après contact avec traducteur.insoumis il m'a orienté ici pour participer collaborativement ...
je me propose de sous titrer sur cette Issue en cours , je suis un peu paumé sur la façon de travailler en collaboratif sur ce site ( je ne suis pas du tout informaticien mais juste monteur video en retraite )
en allant sur le site collaboratif Youtube je vois que le ST de cette vidéo en est à la mn 38, y a t'il quelqu'un dessus, ou puis-je m'y mettre? j'ai du mal à comprendre les labels "working on this issue" qui est removed , on ne devrait pas être sur paused ?
je viens de m'inscrire sur le forum sous titreur pour voir comment ça marche, mais mon inscription n'est pas encore validée par l'admin
bon, en attendant d'avoir de vos nouvelles je m'y colle en local sur mon mac à partir de la mn38 avec la dictée vocale je vous tiens au courant de mon avancement ;)

**Comment by LVAI** [comment]
Bonjour @desintoxiquezvous et bienvenu !
Le marqueur (label) "Process: Someone is working" permet d'indiquer que l'un de nous est en train de sous-titrer la vidéo pour éviter de travailler en double pour rien et éviter d'écraser le travail de l'autre.
De cette manière, on voit bien quelles vidéo sont libres ou non depuis la [vue tabulaire](https://github.com/jlm2017/jlm-video-subtitles/projects/2) du projet.
Le marqueur "paused" n'est plus utilisé. N'hésite pas à aller lire les tuto #19 #32 #37 #38 pour en savoir plus. Et si tu as des questions, n'hésite pas !
Je vais l'ajouter pour indiquer que tu es en train de sous-titrer. Tu ne peux pas encore le faire car tu n'es pas "Collaborateur". Je pense que @LucileDT devrait pouvoir remédier à ça.
Ajoute un petit message quand tu arrêtes et j'enlèverai le marqueur.

**Comment by desintoxiquezvous** [comment]
merci de ta réponse, je pense faire de 38 a 44 mn environ dès que fini j’envoi un message

**Comment by Bentham** [comment]
Hello @desintoxiquezvous et bienvenue par ici ! Je regarde pour te rajouter collab', si c'est pas déjà fait.

**Comment by LVAI** [comment]
Merci Bentham !

**Comment by desintoxiquezvous** [comment]
Bonsoir , je m’arrête pour ce soir , je viens de faire de 38: à 45:34
je pense reprendre et finir demain ..si ça peut libérer quelqu’un sur une autre tâche..  ;)

**Comment by desintoxiquezvous** [comment]
je reprends la suite à partir de 45:34

**Comment by LVAI** [comment]
@desintoxiquezvous t'es toujours dessus ?

**Comment by desintoxiquezvous** [comment]
oui je finis dans 2 mn

**Comment by LVAI** [comment]
Aucune pression :)
Je suis juste impressionnée par ta ténacité !
J'avais encore jamais vu quelqu'un rester si longtemps sur le sous-titrage.
Prends ton temps bien sûr et tiens moi au courant quand tu veux que  je retire le marqueur.

**Comment by desintoxiquezvous** [comment]
Ca y est !
Je suis un monteur tenace (à la retraite) et ….. ON LACHE RIEN !
c’est fini , bon pour la vérification

**Comment by Vimogo** [comment]
Je fais la première relecture.

**Comment by Vimogo** [comment]
Terminée.

**Comment by DominDamid** [comment]
Je me colle à la relecture...

**Comment by DominDamid** [comment]
Ouf... petite pause à 27min31

**Comment by DominDamid** [comment]
Finalement ça a été une grande pause ;)
Je reprends.

**Comment by DominDamid** [comment]
Fini !

**Comment by DominDamid** [comment]
J'ai déplacé l'issue dans la cinquième colonne dans le tableau "projet", je crois qu'il ne reste rien à faire, si j'ai bien compris.

**Comment by LucileDT** [comment]
Merci à vous tous, c'est impeccable !
@desintoxiquezvous normalement, tu devrais pouvoir accepter l'invitation que @Bentham t'a envoyé en allant à cette adresse : https://github.com/jlm2017/jlm-video-subtitles/invitations
Une fois l'invitation acceptée, tu seras en mesure de mettre/enlever les labels et de déplacer les issues dans le tableau de bord :)

**Comment by LucileDT** [comment]
@DominDamid Tu peux à ce moment clore l'issue, en utilisant le bouton Close issue, à gauche de Comment, juste en dessous de la zone de rédaction de commentaire de l'issue :)

**Comment by DominDamid** [comment]
Ok !
