### ISSUE TITLE
[subtitles] [FR] MÉLENCHON : «LE PROBLÈME A UN NOM. IL A UNE ADRESSE.»

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#127]
# Video title
MÉLENCHON : «LE PROBLÈME A UN NOM. IL A UNE ADRESSE.»

# URL
https://www.youtube.com/watch?v=JXit0KrjnUw

# Youtube subtitles language
Français

# Duration
3:11

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=JXit0KrjnUw&ui=hd&action_mde_edit_form=1&ref=player&lang=fr&bl=vmp

**Comment by Bentham** [comment]
Je m'y colle !

**Comment by Bentham** [comment]
C'est le moment de l'expertise bayouesque.

**Comment by bayasahra** [comment]
ahaha je suis là je me colle à la première correction ;)

**Comment by bayasahra** [comment]
mdr vilain !! :) c'est faiiiiiit 
prêt pour deuxième validation.

**Comment by Albapringe** [comment]
J'attaque pour la dernière correction ;)

**Comment by Albapringe** [comment]
Terminé. Les sous-titres sont publiés, je clos l'issue.
