### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - Déboulé à Tourcoing

### ISSUE THREAD

**Issue by DevilFishGold** [jlm2017/jlm-video-subtitles#128]
# **Video title** 
MÉLENCHON - Déboulé à Tourcoing

# **Url**
https://www.youtube.com/watch?v=NNe0bXIJ9cQ&t=593s

# **Youtube subtitles language**
Français

# **Duration**
1:41:42

# **Subtitles URL**
https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&lang=fr&tab=captions&ui=hd&v=NNe0bXIJ9cQ&bl=vmp

**Comment by Albapringe** [comment]
Salut @DevilFishGold. Si c'est toi qui travaille dessus, pense à mettre le label "Someone is working on this issue" pendant que tu es dessus. ;)

**Comment by DevilFishGold** [comment]
Oh, en effet, merci de me le rappeler. Je ne suis pas encore vraiment familier avec ça, désolé... 
 Merci ^^'

**Comment by Flupignon** [comment]
Ça va venir !

**Comment by DevilFishGold** [comment]
Je me suis arrêté à l'instant à 1:00:03:0.
Je reprendrais demain matin.

**Comment by Albapringe** [comment]
Tu ne chômes pas, dis donc ! :)

**Comment by DevilFishGold** [comment]
Ahah ^^' 
Je reprend.

**Comment by DevilFishGold** [comment]
Voilà, je viens de finir le sous-titrage. 
Une personne peut s'occuper de la correction dorénavant :)

**Comment by Bentham** [comment]
Je commence !

**Comment by Bentham** [comment]
Corrigé jusqu'à 32:51.

@DevilFishGold merci beaucoup, tu as fourni énormément de boulot !!

Deux petits rappels de forme pour qu'on soit d'accord :
- n'oublie pas de mettre une espace avant les points d'interrogation et d'exclamation, avant les deux-points, avant le signe pourcentage
- une phrase au discours rapporté direct commence avec une majuscule. Par exemple, on va écrire ainsi : 

> On va pas dire : "Dans chaque entreprise, discutez !" Ah bah non, on sait comment ça va se finir !

C'est @Albapringe qui m'a appris cette règle d'ailleurs :)

**Comment by DevilFishGold** [comment]
Oh c'est rien comme "boulot" ^^
Alors, pour les espaces, c'est vrai, et personnellement je préfère faire comme ça. Mais je vais faire comme tu dis pour que je fasse comme vous alors. :) 
Très bien pour le discours rapporté. Je vais corriger ce que j'ai fais alors sur cette vidéo et sur celle que je suis en train de faire.

**Comment by Bentham** [comment]
Pour info, en anglais on ne met pas d'espace avant les points d'interrogation et d'exclamation, les deux-points, le signe pourcentage ; mais par convention on le met en français :)

**Comment by LucileDT** [comment]
@Bentham Ce n'est pas une convention, mais une règle qui vient de l'imprimerie :D

**Comment by Bentham** [comment]
@LucileDT En quoi les règles qui viennent de l'imprimerie ne sont-elles pas conventionnelles ? :)

Au sens où je l'entends, le langage lui-même n'est qu'un ensemble de conventions : les mots, la grammaire, l'orthographe... Pour moi, une convention, c'est juste une règle qu'on a fixée arbitrairement - au sens où il est purement conventionnel/arbitraire de désigner l'objet table par le mot "table" !

**Comment by Bentham** [comment]
J'y retourne

**Comment by Bentham** [comment]
Pour les curieux, qu'est-ce que vous comprenez à 53:09 ? J'entends quelque chose comme : "et j'étais au Sénat hein, c'est le puits de Bastos de la réaction"... Mais malheureusement ça ne veut rien dire !

**Comment by Flupignon** [comment]
Ma copine suggère "cul-de-basse-fosse"
       >https://fr.wiktionary.org/wiki/cul-de-basse-fosse

**Comment by Albapringe** [comment]
Je plussoie, c'est bien ça ^^

**Comment by Bentham** [comment]
Bien joué madame Flupi !
Correction faite jusqu'à 1:00:04.2

**Comment by Bentham** [comment]
Je m'y remets

**Comment by Bentham** [comment]
Allez c'est terminé. Y'a plus qu'à valider, je pense que c'est bon tel quel.

**Comment by DevilFishGold** [comment]
Tu en fais du boulot @Bentham. Chapeau!

**Comment by Vimogo** [comment]
Allez, je prends la deuxième vérification.

**Comment by Vimogo** [comment]
Voilà, c'est terminé, les sous-titres sont désormais disponibles.
