### ISSUE TITLE
[process] Youtube users help

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#13]
Je ne pense pas que on pourra contrôler toutes les traductions faites par des users youtube, en particulier en francais. Tout le monde ne voudra pas rejoindre et apprendre github, en plus de faire la traduction sur l'outil de youtube.

Du coup je propose que on ait un process ou qqun responsable pour:
 - repérer les contributions diverses et variées
 - répondre aux commentaires des users demandant qu'on valide leurs sous titres
 - créer sur le github une issue correspondante, et la faire évoluer

**Comment by Ricyeam** [comment]
je l'ai fait ce soir pour la RDLS8 (voir issue #12 ), mais je ne pense pas pouvoir suivre tout ce qui se passe tout le temps. Idées?

**Comment by bayasahra** [comment]
hummmm peut être avoir un correspondant dans le staff de mélenchon qui s'occupe des validations des traductions et autres contributions de tiers personnes... ceux qui savent où le travail en est... ce sont ceux qui valident le travail.... il faudrait qu'on puisse communiquer avec... lucile avait l'air d'avoir un contact serieux qui a bien répondu à ses tweets ... non ? et oui effectivement rameuter les gens qui font de la trad solo ici ou au moins leur filer nos 3 contacts si ils ne veulent pas s'embêter avec gith ( soit par mail facebook ou autre) pour qu'ils nous tiennent au courant de ce qu'ils font

**Comment by jillro** [comment]
Hello :) Je suis le contact sérieux. Je m'occupe du GitHub @jlm2017. Je suis entrain de mettre Lucile en contact avec la personne qui s'occupe de Youtube, cela répondra sûrement à quelques questions.

**Comment by LucileDT** [comment]
A priori, il n'y a qu'une personne qui s'occupe de la chaîne Youtube, et qui souhaite me contacter, donc je lui poserai des question concernant leur organisation à ce moment-là.
(@guilro a été trop rapide pour moi)

Ensuite, niveau contributions dans les commentaires, ce que je propose : 
- **surveiller les commentaires** parlant de sous-titres, c'est **indispensable**, mais très lourd (nombre de gens qui commentent les vidéos important, tout suivre me semble difficile...), du coup si vous voulez, je peux essayer de m'en charger. Si @bayasahra par exemple s'investit dans les sous-titres en français, ça me dégagerait ce temps-là.

- **répondre aux commentaires** est une très bonne idée : c'est comme ça que ce projet s'est monté, donc c'est important. Je pense qu'il faudrait éventuellement essayer de contacter les personnes par mail et voir si on ne peut pas les inviter sur facebook, peut-être que travailler avec le Github, ça leur irait aussi, on ne sait jamais ! Du coup, la personne qui s'occupe des commentaires devrait écrire des messages du genre : 
> Salut, merci de la contribution ! On essaye de s'organiser au niveau des personnes qui fabriquent les sous-titres, est-ce que ça te dirait de nous rejoindre ? Tu peux me répondre par mail à une.adresse.mail@mail.com

Ça rejoint ce que disait @bayasahra, que les personnes aient au moins nos contacts pour nous tenir au courant. En effet, c'est plus efficace à long terme par mail / facebook / twitter / signaux de fumée que via les commentaire Youtube, donc plus on rapatrie de gens sur d'autres moyens de communication que les commentaires Youtube, moins on aura à s'emmerder avec :)

- **créer une issue** pour les contributions extérieures, c'est super, j'ai vu ça ce matin @Ricyeam, j'étais contente, et puis ça permet de savoir qu'on avance et sur quelles vidéos, même si les personnes se sont pas sur le projet Github :)

@bayasahra pour compléter ce que tu dis, effectivement si la personne qui gère la chaîne pouvait coordonner le projet, ce serait super ! Malheureusement, j'ai bien peur qu'elle ne soit surchargée... c'est pour cette raison que j'avais tweeté JLM, c'est ce qu'il y a de plus simple pour l'instant pour leur signaler des choses (les notification Youtube sont pourries).

Autre idée : Je pourrais aussi proposer à la personne qui s'occupe de la chaîne de mettre en lien dans la vidéo par exemple le projet Github ou une de nos adresses mail par exemple, comme ça, ceux qui lisent la description pourraient directement nous contacter.

**Comment by Ricyeam** [comment]
Si l'équipe de JLM peut rajouter un ecran noir pour 1 ou 2 sec a la fin des videos, ca nous permet de rajouter des sous titres de crédit+et surtout contact pour ceux que ca interesse.
Et en effet, un lien dans la description de la vidéo sur une addresse mail (qu'on peut créer juste pour ca d'ailleurs) permettra a ceux qui veulent s'impliquer de nous contacter avant qu'il n'y ait de sous titres.

A propos des doublons et de la chaine de @Flupignon 
@Flupignon dit moi si je me trompe, mais je pense aussi que l'une des raisons pour ta chaîne perso c'etait pour augmenter ta visibilité et présence web - vu que tu cherches un boulot avec un master en traduction. A voir avec l'équipe de campagne, mais te créditer sur les vidéos que tu traduis (dans les sous titres) pourrait être un moyen d'éviter les doublons vidéos tout en gardant cet avantage de visibilité.
Disclaimer: @Flupignon ne m'a pas payé pour cette suggestion! c'est juste une idée soumise à discussion :)

**Comment by bayasahra** [comment]
@guilro merci de ta réponse rapide :) je savais que tu étais sérieux ;) donc on va patienter et attendre que la personne en charge du youtube nous contacte... ça serait bien qu'il nous laisse à tous ses coordonnées... chacun va avancer, surveiller, et donc signaler les choses à son rythme .... ça serait pas du luxe qu'on puisse tous le joindre pour les choses importantes. 
à bientôt

**Comment by Flupignon** [comment]
Non non pas du tout x)
Au contraire j'utilise un pseudo (un peu ridicule d'ailleurs, c'est une
consonance grolandaise) pour NE PAS être crédité. Militer pour JLM c'est
pas mortel pour chercher du taff...

**Comment by Flupignon** [comment]
J'ai vraiment créé la chaîne pour la visibilité de JLM chez les
non-francophones (image, titre et description) et parce que la validation
des sous-titres mettait souvent du temps.
Mais Lucile va en parler au staff de campagne et je la supprimerai s'ils
pensent que c mieux, ou ils recrééreont une chaîne officielle.

**Comment by Flupignon** [comment]
Le problème pour contacter les gens qui commentent les sous-titres c'est qu'il faut valider le copte google pour ça (donner son num) et tout le monde le fait pas (et ça se comprend)...
Sur ma chaîne youtube je me suis abonné à et ai essayé de contacter des gens intéressés pour faire des trads (https://www.youtube.com/channel/UCG2Ew2YF1gc7_I8gp1wFQcg)  ou qui ont déjà fait des trads (https://www.youtube.com/channel/UC0JeZ8fkNmLGzsfq98Bhy8Q) mais ils ne répondent pas....

**Comment by Flupignon** [comment]
By the way il y a la chaîne "JLM en español" (https://www.youtube.com/channel/UCvBtNUjZOJvZzc6ZoDJd4Og) qui est je crois gérée par Christian Rodriguez, responsable PG des relations internationales...

**Comment by bayasahra** [comment]
@Flupignon  bienvenue à toi :)
tu n'as pas à te justifier... tu as fait quelque chose de louable avec tes propres convictions et on te remercie du temps que tu donnes à la France insoumise :) .... personnellement je pense que ne pas diviser la chaîne fera quelque chose de plus puissant, en ne dispersant pas les différentes attractions on fait quelque chose de plus lisible, de plus accessible. Mais ton point de vue est compréhensible aussi :)

**Comment by Ricyeam** [comment]
@Flupignon ok, my bad then! je voulais juste qu'on s'assure que les interets/motivations de chacun soient préservés. Je pense que l'équipe de campagne @guilro nous laissera savoir ce qu'ils préferent, et on avisera à partir de là.
@Flupignon super pour les traducteurs espagnols ! Peut etre qu'ils seraient interessés pour rejoindre le github?
@bayasahra Le github est fait pour ca, pas la peine de contacter tout le monde par mail etc! Si c'est bien fait, ils checkent sur la page 'projet' l'avancement des sous-titres, et agissent en fonction. C'est en train de se mettre en place je pense.

**Comment by Flupignon** [comment]
J'attends les conseils du staff et j'agirai en conséquence ;)
J'ai reçu ce message sur youtube mais je n'arrive pas à la recontacter (impossible d'envoyer un MP) : 

"natalie23091989 
Bonjour, je suis franco-anglaise, linguiste diplômée et serais ravie de vous aider a traduire les interventions de JLM. Merci de m'envoyer un message prive si vous pensez pouvoir bénéficier de mes services. Bien chaleureusement, Natalie﻿"

**Comment by Ricyeam** [comment]
@Flupignon Mets un commentaire public sur son profil?

**Comment by Flupignon** [comment]
C à d?

**Comment by Ricyeam** [comment]
Page de la chaine de l'user, onglet discussion, ou sinon onglet 'a propos' et ensuite 'envoyer un message'

**Comment by Flupignon** [comment]
Ha pour leur demander leur avis ? ok ça marche je vous tiens au courant.

**Comment by Ricyeam** [comment]
et pour "natalie23091989 aussi, ca devrait marcher je pense? a tester

**Comment by Ricyeam** [comment]
L'user Bentham qui a fait la #12 a rejoins github et souhaite nous aider pour les ss-titres francais.

**Comment by Bentham** [comment]
Oui, bonjour à tous ! Bon, c'est mon troisième bonjour ici, mais je me perds un peu dans le github :)

**Comment by Flupignon** [comment]
Salut !

**Comment by Ricyeam** [comment]
J'ai fait une issue pour les presentations #17  Désolé Bentham on commence juste à s'organiser et beaucoup d'entre nous découvrent github aussi !:) d'ici quelques jours ca sera plus clair

**Comment by bayasahra** [comment]
@Bentham salut à toi :)
@Ricyeam les contacts autre part que gith c'est pour ceux qui ne veulent pas l'utiliser ... certains ne voudront peut être pas l'utiliser ce qui est compréhensible

**Comment by LucileDT** [comment]
Je vous propose un modèle de message à laisser en réponse aux commentaires des personnes intéressées par le sous-titrage ou à leur envoyer par mail : 
```
Bonjour,
Nous sommes un collectif de quelques personnes et nous prenons en charge la rédaction des sous-titres des vidéos de Jean-Luc Mélenchon. 

Vous pouvez nous joindre à l'adresse suivante : traducteurs.insoumis@gmail.com
Nous somme également présents sur Facebook : https://www.facebook.com/groups/1850626858504963
Vous pouvez participer au projet en vous rendant sur notre Github : https://github.com/jlm2017/jlm-video-subtitles
```

Qu'en pensez-vous ?

**Comment by Ricyeam** [comment]
Super 👍🏼 Par contre peut être qu'on ne devrait pas donner l'adresse du GitHub tout de suite? Les trolls vont certainement arriver dans les mois qui viennent, ça serait dommage de se faire pourrir. Je sais bien que @LucileDT veille, mais tu n'es pas sur le GitHub h24 (normal!) et ça serait bête de perdre du te,os à cleaner le dépôt juste à cause d'un troll non filtré.. non?

**Comment by LucileDT** [comment]
Tout ce qu'un troll peut faire, c'est poster des issues ou en commenter. Et je ne sais pas du tout à quoi ressemble la modération par Github au niveau des utilisateurs. 

Faut voir si vous avez peur d'être dérangés par ça.

**Comment by Ricyeam** [comment]
J'ai tendance à surestimer la propension à troller des membres d'une certaine extrême de l'échiquier politique - et pour moi mieux vaut prévenir que guérir… better safe than sorry comme ils disent ici.
Vous en pensez quoi tous?

**Comment by Bentham** [comment]
Je serais plutôt pour balancer le github après une première prise de contact, et pas directement...

Mais après sur les questions de communication et d'organisation j'ai tendance à faire confiance à @LucileDT

**Comment by LucileDT** [comment]
Ok pour l'envoi du lien vers Github seulement après un premier contact par mail alors :)

**Modèle de message à envoyer :**
```
Bonjour,
Nous sommes un collectif de quelques personnes et nous prenons en charge la rédaction des sous-titres des vidéos de Jean-Luc Mélenchon. 

Vous pouvez nous joindre à l'adresse suivante : traducteurs.insoumis@gmail.com
Nous somme également présents sur Facebook : https://www.facebook.com/groups/1850626858504963

N'hésitez pas à nous contacter pour participer au projet !
```

@Ricyeam est-ce que je peux éditer la description de l'issue pour y mettre une section "Comment prendre contact avec des volontaire" ?

**Comment by Goutte** [comment]
Bon, maintenant qu'on a un bot pour créer les issues, je pense que c'est résolu.
