### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - «JE SUIS AVEC LES GOODYEAR»

### ISSUE THREAD

**Issue by DevilFishGold** [jlm2017/jlm-video-subtitles#130]
# **Video title**
MÉLENCHON - «JE SUIS AVEC LES GOODYEAR»

# **URL**
https://www.youtube.com/watch?v=rN7vi62f100

# **Youtube subtitles language**
Français

# **Duration**
20:11

# **Subtitles Url**
https://www.youtube.com/timedtext_video?ref=player&v=rN7vi62f100

**Comment by DevilFishGold** [comment]
Arrêt à 10:53.0.

**Comment by DevilFishGold** [comment]
Le sous-titrage est fait.

**Comment by Vimogo** [comment]
Première correction faite mais comme dit pour l'instant je ne peux ni toucher aux labels ni déplacer donc si quelqu'un pouvait le faire pour moi ce serait génial.

**Comment by Bentham** [comment]
Fait !

**Comment by Albapringe** [comment]
Terminé, une dernière vérification s'impose. Si vous me faites assez confiance, une validation immédiate devrait pouvoir être faite, d'autant que les sous-titres sont déjà publiés. :)

**Comment by Vimogo** [comment]
Fait.
