### ISSUE TITLE
[Subtitles] [FR] POINT PRESSE : 500 PARRAINAGES, HOLOGRAMME, 18 MARS - MÉLENCHON 

### ISSUE THREAD

**Issue by Vimogo** [jlm2017/jlm-video-subtitles#131]
# Video title
POINT PRESSE : 500 PARRAINAGES, HOLOGRAMME, 18 MARS - MÉLENCHON 

# URL
https://www.youtube.com/watch?v=aNKvbEl0OnQ

# Youtube subtitles language
Français

# Duration
20:54

# Subtitles URL
https://www.youtube.com/timedtext_video?ref=player&v=aNKvbEl0OnQ

**Comment by Vimogo** [comment]
Je ne trouve pas comment ajouter des labels :/

**Comment by Albapringe** [comment]
Tu n'es apparemment pas encore contributeur. Il te faut attendre l'attribut de ce droit par @LucileDT ou @Ricyeam.

**Comment by Vimogo** [comment]
Tant pis cela ne m'empêchera pas de commencer à traduire.

**Comment by Albapringe** [comment]
Je vais les mettre pour toi, dans ce cas. Signale simplement par commentaire à chaque fois que tu es dessus ou non, pour la gestion des labels.

**Comment by Bentham** [comment]
La fougue de la jeunesse !

Attention cependant, je vois actuellement deux personnes en train de rentrer des sous-titres français en même temps.

**Comment by LucileDT** [comment]
@Vimogo fait désormais partie des contributeurs :D

**Comment by Vimogo** [comment]
Merci @LucileDT. Cependant je ne trouve toujours pas les options en suivant les guides. Des captures d'écran sauraient être utiles ici je pense.
En tout cas, je viens de finir la rédaction des sous-titres donc si quelqu'un pouvait éditer le label et déplacer l'issue ce serait très aimable.

**Comment by Albapringe** [comment]
En effet, c'est bizarre, tu n'as toujours pas la vignette "Collaborator". Bon, je le fais pour toi ;)

**Comment by LucileDT** [comment]
@Vimogo as-tu accepté l'invitation ? Tu dois avoir reçu un mail avec un lien pour le faire. Si ce n'est pas le cas, dis-le moi, je renverrai l'invitation !

**Comment by LucileDT** [comment]
@Vimogo Pour ce qui est des options pour lesquelles tu veux des captures d'écran, fais-moi la liste, je m'en occuperai :)

**Comment by Vimogo** [comment]
J'ai trouvé l'invitation, cependant le lien me renvoie une erreur 404. Puis-je l'obtenir de nouveau ?  Et pour les options je verrai si je les trouve une fois celles-ci débloquées donc.

**Comment by Albapringe** [comment]
Je viens de terminer la première correction. Juste une chose @Vimogo, nous avons convenu que le retour à la ligne ne se faisait que lors d'un changement de locuteur, aussi, tu n'es pas obligé d'en insérer dans les sous-titres dans les autres cas.

**Comment by Vimogo** [comment]
Très bien, merci pour la remarque, ce sera pris en compte.

**Comment by Bentham** [comment]
Je fais une correction rapide

**Comment by Bentham** [comment]
Fait, et en ligne. Je clos l'issue.
