### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - Réunion publique au Mans

### ISSUE THREAD

**Issue by DevilFishGold** [jlm2017/jlm-video-subtitles#133]
# **Video title**
MÉLENCHON - Réunion publique au Mans

# **URL**
https://www.youtube.com/watch?v=odyu0ggGko4

# **Youtube subtitles language**
Français

# **Duration**
2:05:31

# **Subtitles Url**
https://www.youtube.com/timedtext_video?v=odyu0ggGko4

**Comment by DevilFishGold** [comment]
Je commence.

**Comment by DevilFishGold** [comment]
Je me suis arrêté à 33:01.4

**Comment by DevilFishGold** [comment]
Je reprends.

**Comment by DevilFishGold** [comment]
Je me suis arrêté à 1:05:02.

**Comment by DevilFishGold** [comment]
Je reprends. :)

**Comment by DevilFishGold** [comment]
Voilà... Le sous-titrage vient d'être fini... Ce fut long et laborieux mais c'est fait ! Je voulais absolument finir cela le plus tôt possible et c'est bon ! :) 
Vous allez pouvoir effectuer la vérification. Je sais qu'il y a des passages où il faudra tronqué (j'ai vu vos posts sur la longueur des blocs que trop tard). S'il le faut, et/ou si vous n'avez pas la motivation, je retravaillerais les blocs demain. :)

**Comment by quidam34** [comment]
pour la suite je propose de travailler autrement . Je m'occupe de fournir la totalité du texte sur un fichier text. 2 personnes a la suite corrige . Ensuite il n'y a plus qu'a mette en place sur youube et 1 vérificateur de la mise en plce et voilà !    vous en pensez quoi ? j'ai mis un sujet la dessus a lire sur la page d'accueil mais je sais pas ou vu que c'est pas pratique ce site je trouve .

**Comment by quidam34** [comment]
j'ai retravaillé les longueur. arret des changement a 3.44

**Comment by Bentham** [comment]
Bonjour quidam34, il vaut mieux laisser des blocs de sous-titres assez longs, c'est beaucoup plus facile à lire pour les malentendants !

**Comment by quidam34** [comment]
arf c'est le contraire donc désolé

**Comment by Milsabor** [comment]
Bonsoir ! Je suis en train de m'attaquer à la relecture si c'est OK. Y'aurait-il moyen de m'accorder la permission pour les labels svp? :)

**Comment by Albapringe** [comment]
Malheureusement, nous n'avons pas les droits suffisants pour te donner les droits: seuls @LucileDT et @Ricyeam peuvent le faire. Mais, je le fais pour toi, pas de pb.

**Comment by Milsabor** [comment]
Super, merci beaucoup !

**Comment by Flupignon** [comment]
@LucileDT est aux USA (je crois qu'elle est déjà partie) donc il faudra attendre un peu ;)

**Comment by Milsabor** [comment]
Mis en pause à 1:04:02. Je reprendrai demain.
N.B. : à 12:09, JLM dit "10 abstentions", mais en énumère 16, et il y a bien eu ces 16 là dans le vote (vérifié sur le scrutin public sur le site du Sénat). J'ai donc mis le 16 entre crochets parce qu'il dit "10" mais c'est un bafouillage qui rend le propos confus ^^
à 50:44 j'ai aussi été interloqué, mais JLM dit bien "pas besoin d'être un aigle pour comprendre tout ça"

**Comment by Albapringe** [comment]
Cette expression a déjà été usitée par Mélenchon dans une RDLS, et avait déjà soulevé quelques confusions entre un aigle/un nègre en fonction de la prononciation, mais c'est bien de l'aigle dont il s'agit ;)
Quand un terme ne correspond pas à ce qui devrait, est erroné, ou s'il s'agit d'un néologisme, on met en général : (sic) après le terme en question, même si ton choix est recevable en l'occurrence. :)
J'enlève les labels, n'hésite pas à revenir poster un commentaire quand tu reprendras.

**Comment by Flupignon** [comment]
Il utilise souvent cette expression.

**Comment by Milsabor** [comment]
Je reprends.

**Comment by Milsabor** [comment]
Mise en pause à 1:43:23:1.
1:11:15 : JLM dit "c'est une petite incidente" (?) je ne comprends pas l'expression, quelqu'un a-t-il une idée? J'ai laissé comme ça pour l'instant.
1:38:23 à 1:38:26:4 : toute la partie sur le "Ach !" n'avait pas été sous-titrée, normal? ^^ Je l'ai sous-titrée, n'hésitez pas à retirer s'il n'est pas souhaitable de la laisser.

**Comment by Bentham** [comment]
Oui "c'est une petite incidente" ! C'est mis pour "c'est une petite [remarque] incidente", c'est-à-dire une incise, un aparté.
Tu as bien fait de sous-titrer la partie "Ach" :)

Bravo pour ton boulot c'est top ! Tu as vu la dernière méthode de sous-titrage ? Ca pourrait te simplifier la tâche : https://youtu.be/q68KAKVCOP4

**Comment by Milsabor** [comment]
Je reprends.
Je ne sais pas si mon micro sera d'assez bonne qualité, j'essaierai quand je ferai du sous-titrage et non de la correction. Merci pour les bons conseils !

**Comment by Milsabor** [comment]
Relecture (1) terminée, jusqu'à l'ajout de "la Marseillaise" en conclusion du discours. Bonne fin de soirée !

**Comment by LucileDT** [comment]
@Milsabor et @quidam34 ont été rajoutés à la liste des contributeurs.

@Bentham, @Flupignon et @bayasahra sont désormais administrateurs et peuvent ajouter des contributeurs en passant par Settings > Collaborators.

**Comment by Flupignon** [comment]
Thx!

**Comment by quidam34** [comment]
voici les erreurs relevé par le site "bon patron.com' j’attends votre avis : j'ai rien corrigé juste mis en noir ce qui poserait peut-être problème. J'ai corrigé quand j'étais certain ! 
je suis toujours en cours .

Par contre qui met une virgule avant un et ?     ", et" j'ai regardé sur un site mais c'est plutôt rare ! 


en cours toujours !   les "c'est-à-dire" sans les tirets sont récurent aussi

**Comment by LucileDT** [comment]
Je pense que si la personne qui parle reprend sa repsiration et marque bien la pause avant le "et", alors la virgule est justifiée.

**Comment by quidam34** [comment]
lucile : ce n'est pas la règle grammatical ça ! 

mon équipe finit cette vidéo dans lçà journée nous en somme a la correction finale.

juste une chose : s'il reprend son souffle au milieu d'une phrase on met une virgule au milieu de la phrase ?

question c'est qui c'est quoi "désintoxiquez vous ? " parce qu'il c'est inscrit sur le forum et ne connaissant pas j'ai pas ouvert la porte  ! ??

**Comment by LucileDT** [comment]
@quidam34 Pourriez-vous me citer la règle grammaticale ?

@desintoxiquezvous a demandé à nous rejoindre, et voyant le lien vers votre forum, a demandé à s'inscrire dessus.

**Comment by quidam34** [comment]
Correction orthographique finit!  je désire juste diviser des texte de plus de quatres lignes parfois et qui gâche l'image !    Oui j'ai vu depuis pour desintoxiquezvous merci
