### ISSUE TITLE
[subtitles] [eng] #RDLS14 - FRANCE INTER, TRUMP ET LA CHINE, FILLON ET INTERNET, LE CAC40 SE GAVE,

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#134]
# Video title

#RDLS14 - FRANCE INTER, TRUMP ET LA CHINE, FILLON ET INTERNET, LE CAC40 SE GAVE,

# URL

https://www.youtube.com/watch?v=xSxMAU-DZsc

# Youtube subtitles language

Anglais

# Duration

19:13

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&lang=en&action_mde_edit_form=1&ref=player&tab=captions&v=xSxMAU-DZsc&ui=hd

**Comment by Flupignon** [comment]
4:33

**Comment by Flupignon** [comment]
C'était pas du gâteau cette FAQ, mais les sous-titres sont prêts ! Le style est très oral, j'ai donc dû faire de grosses adaptations à certains moments. Bon courage @Ricyeam et @Blange1 !

**Comment by Flupignon** [comment]
10:05

**Comment by Flupignon** [comment]
15:56 Je devrais avoir terminé ce soir.

**Comment by Flupignon** [comment]
17:20

**Comment by Flupignon** [comment]
Fini ! A vous de jouer @Blange1 et @Ricyeam ;)

**Comment by Blange1** [comment]
@Flupignon J'allais me mettre dessus mais je vois sur youtube qu'elle a été publiée !

**Comment by Flupignon** [comment]
Nice! Du coup il reste les RDLS 13 et 12 à valider. Je me remets surla trad de la 15 ce soir vers 21 h / 21 h 30, tupeux l'avancer entre temps si tu veux. Je pense qu'il faut se mettre à plusieurs sur celle-là, elle est longue, et mon fils me laisse peu de temps en ce moment...

**Comment by Flupignon** [comment]
La FAQ 1 est aussi à valider
