### ISSUE TITLE
[Subtitles] [FR] #RDLS14 - FRANCE INTER, TRUMP ET LA CHINE, FILLON ET INTERNET, LE CAC40 SE GAVE, 

### ISSUE THREAD

**Issue by Vimogo** [jlm2017/jlm-video-subtitles#135]
# Video title
#RDLS14 - FRANCE INTER, TRUMP ET LA CHINE, FILLON ET INTERNET, LE CAC40 SE GAVE,

# URL
https://www.youtube.com/watch?v=xSxMAU-DZsc

# Youtube subtitles language
FR

# Duration
19:13

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd&tab=captions&v=xSxMAU-DZsc&ref=player

**Comment by Vimogo** [comment]
Je remercie le fantôme qui avait commencé sans poster sur le Github avant moi et avait avancé les sous-titres jusque environ 3:30 et je vais personnellement me coucher après les avoir avancé jusque 8:04.

**Comment by Albapringe** [comment]
Salut @Vimogo. Mets juste un petit commentaire quand tu as terminé complètement le sous-titrage de la vidéo, afin qu'on reçoive des notifications comme quoi la vidéo est prête à la relecture. En tout cas, merci pour ton travail et ta célérité ! ;)

Edit : je m'attaque à la relecture.

**Comment by Flupignon** [comment]
C'est déjà en ligne, queluu'un d'autre a dû s'en chargé....

**Comment by Vimogo** [comment]
C'est ma traduction qui est en ligne.

**Comment by Vimogo** [comment]
Et bien reçu pour les notifs.

**Comment by Vimogo** [comment]
Bon bah du coup je bouge ça comme terminé.

**Comment by Albapringe** [comment]
En fait, je pense que des gens ont dû valider sans faire de révision, car j'ai pointé malgré tout quelques erreurs ici ou là. Ces modifications demandant confirmation pour être appliquées, ce serait bien que quelqu'un passe derrière ma correction quand il aura le temps.

**Comment by Vimogo** [comment]
Je fais cela.

**Comment by Vimogo** [comment]
J'ai fait une première validation des nouveaux sous-tires (avec deux correction, un là à la place d'un la et un toujours à la place d'un tous). Il en faut encore une.

**Comment by Bentham** [comment]
J'y vais
