### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON : «JE PROPOSE LA SÉCURITÉ SOCIALE INTÉGRALE»

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#136]
# Video title
MÉLENCHON : «JE PROPOSE LA SÉCURITÉ SOCIALE INTÉGRALE»

# URL
https://www.youtube.com/watch?v=7Q9oWk0yxB4&t=61s

# Youtube subtitles language
Français

# Duration
48:41

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&lang=fr&bl=vmp&tab=captions&ui=hd&v=7Q9oWk0yxB4&action_mde_edit_form=1

**Comment by Albapringe** [comment]
C'est parti. Normalement, pas de strike vu les références aux médias.

**Comment by quidam34** [comment]
Je suis dessus vos labels en anglais me fatigue ! je reviens dire quand j'ai finit. Finit pour l'instant.

**Comment by quidam34** [comment]
Bon je recommence ! Albapringe ca veut dire quoi "Normalement, pas de strike ' ? j'suis dessus là je reviens dire quand j’arrête : Voilà fait de 20'39  à 24'55 Je l'ai fait sans parlé mais je vais bien^tot recommencer . Vérifié mes fautes et aussi si je devais arqué "immigré" ou "émigrés" ??? ainsi que parfois quand celui qui parle est hors champs si c'est bien heu je sais plus comment difficile parfois !

**Comment by quidam34** [comment]
Aller ! je m'en refais une petite série !  au boulot

**Comment by quidam34** [comment]
Désolé ! je n'ai pas pu revenir dire que j'avais arrêté hier a cause que mon internet est tombé en rade ! Le technicien devait venir cet après midi .... j'ai annulé car j'ai vais vérifié mon installation intérieur . (un sms "orange" qui vous dit que si la panne vient de chez vous c'est 79 euros... ) cela fait vérifié l'installation intérieur ! ce que j'ai fait ce matin... le fil passe par la chambre de ma fille et le fil n'a jamais été collé au mur par le papa et.... ma fille a eu l'idée de laissé notre lapin teddy dans une partie de la chambre a liberté ! Vous avez compris (pour rappel les lapin sont des rongeurs ;-)...)  Bon pour me faire pardonner ... j'y retourne de suite ! Avec toutes mes excuses !!!

**Comment by quidam34** [comment]
albapringe ? Personne n'a travaillé dessus depuis moi . J'ai peur de faire une bétise vu que je suis arrivé sur l'ongle directement marqué sur la page youtube : "envoyé pour examen" 

ps je pense finir dans la journée. Parce que demain on le metting de ce soir à faire !  ;-)

**Comment by quidam34** [comment]
bon je piétine depuis tout à l'heure alors en attendant vous pouvez reprendre le flambeau !

**Comment by quidam34** [comment]
C'est leur du meeting : Pause !

**Comment by quidam34** [comment]
C'est repartit !

**Comment by quidam34** [comment]
C'est repartit !

**Comment by quidam34** [comment]
terminé pour ce soir ...

**Comment by quidam34** [comment]
mais attention j'ai fait le texte pour les 6 mn suivantes !

**Comment by quidam34** [comment]
visible sur le forum : http://www.sous-titreur.forum-insoumis.fr/   inscrivez vous et demandé vous si ce n'est pas plus pratique ?

**Comment by quidam34** [comment]
(aller voir comment je propose de travailler ici : http://www.sous-titreur.forum-insoumis.fr/viewtopic.php?f=4&t=4&sid=259d96ddd6b42901a2c0b50b152dfeab

**Comment by quidam34** [comment]
bon je suis a jour du texte que j'avais déjà mis sur fichier texte je recommence un peu

**Comment by quidam34** [comment]
Voilà j'ai finit pour de suite. J'ai laissé un grand champs texte avec la réaction a faire et le cisellage que je me prosose de faire ce soir !

**Comment by quidam34** [comment]
Fait  et finit pour ce soir !

**Comment by quidam34** [comment]
je recommence !

**Comment by quidam34** [comment]
j'ai finit même si le texte n'est pas corrigé ne vous occupé pas de la correction mon équipe va s'en occuper

**Comment by desintoxiquezvous** [comment]
bonjour, je suis nouveau ici, j'ai participé spontanément directement sur Youtube aux S/T de la RDLS15 
après contact avec traducteur.insoumis il m'a orienté ici pour participer collaborativement ...
je me propose de sous titrer sur cette Issue en cours , je suis un peu paumé sur la façon de travailler en collaboratif sur ce site ( je ne suis pas du tout informaticien mais juste monteur video en retraite )
en allant sur le site collaboratif Youtube je vois que le ST de cette vidéo en est à la mn 38, y a t'il quelqu'un dessus, ou puis-je m'y mettre? j'ai du mal à comprendre les labels "working on this issue" qui est removed , on ne devrait pas être sur paused ? 
je viens de m'inscrire sur le forum sous titreur pour voir comment ça marche, mais mon inscription n'est pas encore validée par l'admin
bon, en attendant d'avoir de vos nouvelles je m'y colle en local sur mon mac avec la dictée vocale ;)

**Comment by LVAI** [comment]
@quidam34 une idée de quand les sous-titres que tu as fait seront corrigés par ton équipe ?

**Comment by quidam34** [comment]
C'est bientôt finit oui on fait tout ! on vous dirs pour que vous refassiez une ultime lecture . Ca va bientôt être fait !

**Comment by quidam34** [comment]
roooo nous prenons notre rhyme de croisière désolé .... aujourd'hui nous finissons trois vidéo y compris celle là

**Comment by quidam34** [comment]
comment je change le label ?

**Comment by quidam34** [comment]
merci de changer de label nous en somme a la deuxième relecture et correction  !!!!!

**Comment by Goutte** [comment]
À votre service !!!!!

**Comment by Goutte** [comment]
Beaucoup de fautes d'orthographe ! À partir de la 20e minute il y en a souvent une par ligne ! Parfois deux !

Qui a fait la 1e relecture ?

La ponctuation, notamment au niveau des espaces autour des virgules, est souvent défaillante.

---

J'ai relu jusqu'à la césure, à 26 minutes.

**Comment by quidam34** [comment]
Est ce que j'ai dit que la correction était finit ! pour info notre correction se fait directement sur le fichier ".sbv" que je re upload en lui est place sur la vidéo donc normal que vous ne voyez rien ... sur notre forum on ne travaille pas comme ici  ! Cette manière de corriger est bien plus rapide et permet aussi le passage dans un correcteur d'orthographe dans un premier temps et la relecture ensuite par deux personnes différentes.. (soit trois relectures en quelque sorte ! )  Je disais donc que le sujet devait juste ne plus être dans la colonne comme quoi le sous titrage n'était pas finit ! Vous viendrait me dire s'il reste des fautes quand je vous direz "c'est finit !" :-)

**Comment by LucileDT** [comment]
Ah, alors @quidam34 si vous pouviez créer une issue qui décrit votre méthode, ce serait l'idéal svp.

**Comment by quidam34** [comment]
Ma correctrice vient me dire qu'elle a l'impression qu'elle a fait du boulot pour rien ! que quelqu'un a corrigé en ligne !  Elle a pas dit tout mais a cité deux exemples concret ! @LucileDT  Je vais uploder la correction d'ici la fin de matinée. les correction qui ont pu être faite ici seront écrasé  ....

**Comment by Bentham** [comment]
@quidam34, nous ne pouvons pas travailler comme ça. N'importez pas votre fichier.

**Comment by Goutte** [comment]
@quidam34 Par pitié, n'importez pas votre fichier !

**Comment by desintoxiquezvous** [comment]
ça commence à bien faire  ton délire megalomaniaque , je te joint un extrait video que j'ai fait en refilmant avec ma tablette ton travail si bien fait et vérifié 2 fois avant que je ne soit obligé de repasser derrière

**Comment by quidam34** [comment]
Eh ben désolé c'est fait  ! Cela a trés bien fonctionné ! et i vous ne vous occupiez pas des vidéos dont on s'occupe ?

**Comment by quidam34** [comment]
@Bentham Vous ne voulez ou ne pouvez pas travailler comme cela ? Mélenchon veut qu'on aille de l'avant ! Pas vous ?
@Goutte désolé nous avons dit que nous nous en occupions ! 
@desintoxiquezvous que diable êtes venu faire sur le forum ? Il existe une nouvelle manière de corrigé bien plus rapide informez vous ! Votre doléance est donc sans objet ! 

il nous reste une dernière relecture Mais c'est en cours ok les gens les gens du forum s'en occupe !

**Comment by quidam34** [comment]
Vos labels en anglais ! grrrrrr 
J'ai copier le texte de tout vos labels et traduit sur google , je garde la page ouverte  ! ce qui explique le bidouillage dessous !

**Comment by domi41** [comment]
@quidam34 _Fasciste: Qui utilise les méthodes du fascisme, totalitaire._

> “Le problème avec ce monde est que les personnes intelligentes sont pleines de doutes tandis que les personnes stupides sont pleines de confiance.”
― Charles Bukowski

@desintoxiquezvous @Goutte Ne vous laissez pas décourager ! La démocratie, c'est aussi éduquer le maillon faible !

**Comment by Bentham** [comment]
Ne nous emportons pas, les amis. Visiblement nous n'arrivons pas à nous entendre avec @quidam34, donc il va juste falloir trouver un terrain d'entente.
Je suis assez d'accord pour qu'on se répartisse les vidéos. Mais comment ?

Il me semble pour ma part que l'idée que j'avais proposée serait la plus pratique : nous vous laissons TOUTES les vidéos sorties avant le passage de JLM chez Ruquier, celle-ci y compris - ça en fait un paquet. Vous aurez plein de boulot utile à abattre.

**Comment by quidam34** [comment]
@domi41 les dérives et les mots blessants je les croyaient réservés aux adorateurs de la Marine à bout d'argument ! ! 
@Bentham je propose le contraire ! et puis comme déjà dit les nouvelles vidéos vont bientôt se multiplier et vous serez vite submergé ! J'ai écrit une issue sur ma technique sur la demande de @LucileDT vous devriez la lire !

**Comment by desintoxiquezvous** [comment]
Et si vous aviez vérifié réellement le boulot en disant tout est ok et que c'est bon et en demandant la validation , alors que c'était ni fait ni à faire de la mn 42 à la fin.
Et si vous étiez un peu plus respectueux des gens qui passent derrière pour retoucher ? ,
Bon d'accord c'est un peu trop demander à votre ego.

et .. retirez moi de votre forum, qui ne sert qu'a vous valoriser..
je me contenterais de travailler sur GitHub avec le restant des équipes, qui eux travaillent en collaboration et dans les règles 
ciao

**Comment by Bentham** [comment]
@quidam34 combien faut-il qu'il y ait de gens à vous dire que vous avez tort pour que vous puissiez enfin imaginer que vous n'avez pas raison ? **Personne** ici ne soutient votre façon de penser. Comment puis-je mieux vous le faire comprendre ?

**Comment by quidam34** [comment]
@desintoxiquezvous et si ma tante en avait ?  lol  Bon je vais vous faire un dessin : si vous désirez corriger a notre méthode c'est sur le forum ... Mais notre méthode qui n'est là que pour faire gagner du temps n'est pas compatible avec la vôtre .  Donc inutile de corriger sur la vidéo ce n'est pas là que nous le faisons .  Donc forcement vos correction passent à la trappe ! Désolé mais nous avons indiqué ici que nous nous en occupions.

**Comment by quidam34** [comment]
@Bentham Ce n'est pas une façon de pensé mais une façon de faire, vous n'avez donc rien compris ! 
@desintoxiquezvous c'est amusant ne pas respecter notre travail c'est ce que disait l'une des correctrices du forum !  Il doit y avoir un problème non ?
@Bentham quand a qui prendra quelle vidéo il suffit que la prochaine on marque qu'elle nous est réservée ! Les sous-titreuses du forum (et moi) on se tourne les pouces là .... Tandis que vous vous avez pleins de vidéos en souffrance . Commencé par terminé votre travail. Ah et pour éviter la prochaine fois de se tourner les pouces et d'attaquer plusieurs boulots en même temps , il existe la possibilité des sous-titrer à plusieurs en même temps la même vidéo ! Mais bon vu le tollé sur le modernisme de la manière de corriger. J'attends une prochaine nouvelle vidéo pour vous en démonter l'efficacité !

**Comment by Bentham** [comment]
Bon je m'inscris sur votre forum pour ouvrir une discussion avec tout le monde.

**Comment by quidam34** [comment]
J'ai déjà eû une mauvaise expérience ....

**Comment by Bentham** [comment]
Si vous ne voulez pas permettre le dialogue je ne peux rien de plus pour vous.

**Comment by quidam34** [comment]
C'est vous le principale site non ? j'ai proposé que la prochaine soit la notre c'est si compliqué ?

**Comment by Bentham** [comment]
Soyons clairs, vous ne voulez pas que je puisse discuter avec vos collaborateurs ?

**Comment by Goutte** [comment]
@quidam34 Prière de faire preuve d'un peu de respect et de vous relire avant de poster des commentaires. Vos lacunes en orthographe et en grammaire sont pénibles à lire.

**Comment by fkevv** [comment]
J'ai l'impression d'assister à un dialogue de sourds... Il faudrait simplement trouver un moyen de travailler en collaboration sans se marcher les uns sur les autres. Ici les "labels" jouent ce rôle. Votre forum @quidam34 fonctionne surement différemment. Je trouve dommage qu'on arrive à ce genre de débats quand nos intérêts sont commun. Peut importe, si quelqu'un à une idée pour que tous cela fonctionne correctement, tout le monde en serai surement ravi! :)

**Comment by desintoxiquezvous** [comment]
dernière intervention pour moi sur ce sujet avec @quidam34
c'est ne pas respecter votre travail de dire que vous demandez une validation pour un boulot mal fini, et en plus avoir la mauvaise foi de ne pas le reconnaître?  
..et en plus de critiquer ceux qui refont le travail derrière 
vous répondez toujours à côté sur ce sujet, étonnant non?
vous êtes un type à polémique, peut être très bon en technique et très rapide, ce que je n'ai jamais nié, mais avec un ego monstrueux
pour ma part je ne vous répond plus

**Comment by LVAI** [comment]
M. @quidam34 
Je suis surprise de lire que vos sous-titreuses se tournent les pouces : Bentham a souligné qu'il y a de nombreuses vidéos en attente de sous-titres. Pourquoi ne voulez-vous pas les sous-titrer ?
Sur Mattermost, Bentham vous avait déjà proposé de prendre en charge toutes ces vidéos un peu plus anciennes et vous aviez accepté. Pourquoi voulez-vous aujourd'hui faire autrement ?
Pour le partage du travail, je crois que vous êtes d'accord que ce site GitHub est le site principal - même si vous préférez l'organisation de votre propre forum, ce qui peut se comprendre. Peut-on envisager une chose : quand une vidéo sort et que vous souhaitez la traduire, vous créez une fiche (issue) ici, selon ce modèle #1 ? La fiche apparaîtra à votre nom, nous ne nous en occuperons pas. Pas besoin de changer les marqueurs (labels) ni rien. Simplement clôturer la fiche quand vous avez terminé pour notre information. Qu'en dîtes vous ?
Par ailleurs, je me permets de demander si nous pouvons garder le sous-titrage des Revues de la Semaine ?

**Comment by fkevv** [comment]
Je suis d'accord avec @LVAI en attendant, j'ai fait une relecture, j'ai juste complété un moment ou les dialogues étaient compliqué à comprendre, peut importe, j'ai aussi vue que @quidam34 avait mit le labels "2e lecture" donc si c'est toujours d'actualité je vous laisse finir, sinon vous pourez changer le label pour: Process [6]: Approved. Voilà :)

**Comment by Flupignon** [comment]
Mon Dieu... No comment !
