### ISSUE TITLE
[Subtitles] [FR]  MÉLENCHON FAQ - AUTOROUTES, VOTE OBLIGATOIRE, PARRAINAGES, NUCLÉAIRE, AGRICULTURE, PROSTITUTION, GPA

### ISSUE THREAD

**Issue by Vimogo** [jlm2017/jlm-video-subtitles#137]
# Video title

MÉLENCHON FAQ - AUTOROUTES, VOTE OBLIGATOIRE, PARRAINAGES, NUCLÉAIRE, AGRICULTURE, PROSTITUTION, GPA

# URL
https://www.youtube.com/watch?v=eJCyfrRn4KY

# Youtube subtitles language
[FR]

# Duration
35:06

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=eJCyfrRn4KY&ref=player&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd

**Comment by Vimogo** [comment]
Allez je me lance !

**Comment by Vimogo** [comment]
Je vais manger, j'en suis à 7:24.0.

**Comment by Vimogo** [comment]
Je reprends.

**Comment by Vimogo** [comment]
Bon, c'est finit pour moi pour ce soir, je suis arrivé à 17:18.6.
Et c'était drôle de passer une heure à sous-titrer l'importance du symbole Phi avant mon bac blanc de philo de demain. Bonne nuit à tous.

**Comment by Albapringe** [comment]
Qu'est-ce que tu fais là au lieu de réviser, alors ? :) Bentham va te gronder !

**Comment by Bentham** [comment]
Tant que la philo est faite, hein... Et tant pis pour les calculs d'intégrales !

(Mais là c'est Albapringe qui va gronder)

**Comment by Flupignon** [comment]
Merde pour demain ! ;) (et oui tu devrais plutôt réviser !)

**Comment by Bentham** [comment]
Je m'y colle ! Avec une nouvelle technique de transcription qui a l'air folle :)

**Comment by Bentham** [comment]
Allez c'est terminé. J'ai dû sous-titrer 20 minutes de vidéo en 1h30, je crois que la technique fonctionne très bien ! Je vous fais une vidéo là-dessus.

**Comment by Albapringe** [comment]
Çà a l'air bien, ton truc. Vite, vite ! ;)

**Comment by Bentham** [comment]
@Albapringe J'ai mis à jour #129 avec une nouvelle vidéo !

**Comment by Bentham** [comment]
Allez les chatons on essaie de la valider dès que possible ! Je pense pas qu'il y ait beaucoup de corrections à faire, et les FAQ sont les vidéos qui "buzzent" le plus :)

**Comment by Albapringe** [comment]
Je m'y colle.

**Comment by Albapringe** [comment]
Terminé. Dernière relecture en attente.

**Comment by Vimogo** [comment]
J'y suis.

**Comment by Vimogo** [comment]
La vidéo est en ligne avec les sous-titres.

**Comment by Albapringe** [comment]
@Vimogo Dans cette situation, tu peux normalement clore l'issue :)
Je le fais pour cette fois-ci.
