### ISSUE TITLE
Proposition de changement de la manière de travailler 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#139]
J'ai la possibilité rien qu'en parlant d'écrire dans un fichier texte. Il est donc très facile pour moi de retranscrire la totalité une vidéo de JLM. D'ailleurs c'est avec cette méthode que j'ai écrit ce texte comme vous pourrez le constater c'est très efficace. J'utilise une fonction du Mac et je pense que si d'autres personnes font comme moi on pourrait livrer un fichier texte d'une vidéo. Se débrouiller pour la mettre ici. Ainsi un correcteur voir deux pourrait corriger les fautes. Pour celui qui fait les sous-titres le travail sera simplifié puisqu'il n'aura plus qu'à faire des copier coller. Enfin une dernière personne pourrait s'occuper d'une vérification finale de la vidéo et vérifier si les textes sont bien carré avec l'image. Qu'en pensez-vous ? J'attends vos réponses.

**Comment by Albapringe** [comment]
Si je comprends bien, tu proposes de faire le texte, à charge pour les suivants de le découper et de l'insérer au bon endroit sur Youtube, c'est cela ? (avec les corrections, si besoin, cela s'entend)

**Comment by quidam34** [comment]
Oui et avec corrections par un ou deux correcteur avant. C'est cela

**Comment by Flupignon** [comment]
Pas besoin de transcrire le discours de Florange du coup :)

**Comment by Sramyaguchi** [comment]
J'avais fait un pari sur le Discord que vous auriez traduit tout le
discours moins de 24h après la mise en ligne du discours tellement vous
allez vite.

Du coup, j'vais devoir envoyer mon don de 17,89 euros.

Yannick

**Comment by LucileDT** [comment]
@quidam34 la méthode que tu proposes n'est pas adaptée à ce que YouTube nous contraint à faire pour mettre en ligne les sous-titres : au moins deux comptes Google doivent valider les sous-titres avant qu'ils soient mis en ligne. Donc au final, ta proposition demande de faire des vérifications supplémentaires, ce qui est pénible.

De plus, grâce à toi, @Bentham a proposé une méthode qui permet d'être très rapide, où on utilise comme toi la reconnaissance vocale, puis où on fait le timing des sous-titres à la volée. Je pense que c'est plus adapté à la manière de travailler qu'on a que ce que tu proposes, qui demande des intermédiaires en plus, et donc potentiellement ralentit la mise en ligne des sous-titres.

**Comment by quidam34** [comment]
Ma manière de travaillé a évoluer depuis puisque c'est Youtube qui se charge de la mise en place du texte. Maos pourtant notre équipe y arrive non ? Question d'organisation c'est tout  !
