### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - ÉLECTIONS AMÉRICAINES - VICTOIRE DE TRUMP 

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#14]
# Title
MÉLENCHON - ÉLECTIONS AMÉRICAINES - VICTOIRE DE TRUMP 

# Url
https://youtu.be/Kq5iJsBbBes

# Language
Francais

# Url subtitles

**Comment by Ricyeam** [comment]
Commencé par youtube user Dario  contacté par mail 

Dario: 
"Salut voici le lien de la vidéo que je finis

https://www.youtube.com/timedtext_editor?ref=psf&bl=vmp&ui=hd&lang=fr&v=Kq5iJsBbBes&action_mde_edit_form=1&tab=captions

et voici le lien d'origine qu'on trouve sur la chaîne


https://www.youtube.com/watch?v=Kq5iJsBbBes

si tu veux me parler, le plus simple c'est de faire un commentaire et d'utiliser le bouton répondre comme ça je le vois direct !"

**Comment by Ricyeam** [comment]
Youtube user Dario à Ricyeam, par mail:

"Ok, j'ai fini de transcrire, j'ai laissé pour finition car j'ai eu deux problèmes : à 3:43 je n'ai pas compris (Fogiel avec sa manie de couper la parole ! ) et idem à 6:17. Pour github, comme tout est en Anglais, j'attends demain que tu me contacte, on verra en direct la démarche !"

**Comment by bayasahra** [comment]
pour user Dario
Mélenchon 3:43 ==> Voilà pourquoi ils sont restés à la maison.
Mélenchon 6:17 ==> que les marchandises continuent à circuler.
Quand il estime avoir fini le signaler j'irais vérifier

**Comment by Ricyeam** [comment]
Je pense qu'il a mis les sous titres pour validation, si c'est le cas tu peux les modifier directement. SInon dis le moi et je lui envoie un mail

**Comment by bayasahra** [comment]
corrigé et validé

**Comment by Flupignon** [comment]
Quelqu'un pourrait valider cette vidéo ?

**Comment by bayasahra** [comment]
c'est fait ^^

**Comment by Flupignon** [comment]
Thx !

**Comment by Flupignon** [comment]
C'est bon j'ai tout  pigé maintenant x)
