### ISSUE TITLE
{Subtitles] [FR] APRÈS LE BREXIT, LA GUERRE SEUL PROJET EUROPÉEN ? - MÉLENCHON

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#140]
# Video title
APRÈS LE BREXIT, LA GUERRE SEUL PROJET EUROPÉEN ? - MÉLENCHON

# URL
https://www.youtube.com/watch?v=xU5OtxsbvNQ

# Youtube subtitles language
Français

# Duration
1:29

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&tab=captions&bl=vmp&lang=fr&ui=hd&v=xU5OtxsbvNQ

**Comment by Albapringe** [comment]
Fini, je laisse à la première relecture.

**Comment by Bentham** [comment]
J'y suis !

**Comment by Bentham** [comment]
Impec' !
