### ISSUE TITLE
[subtitles] [eng] APRÈS LE BREXIT, LA GUERRE SEUL PROJET EUROPÉEN ? - MÉLENCHON

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#141]
# Video title

APRÈS LE BREXIT, LA GUERRE SEUL PROJET EUROPÉEN ? - MÉLENCHON

# URL

https://www.youtube.com/watch?v=xU5OtxsbvNQ

# Youtube subtitles language

Anglais

# Duration

1:29

# Subtitles URL

https://www.youtube.com/timedtext_editor?v=xU5OtxsbvNQ&ref=player&lang=en&action_mde_edit_form=1&tab=captions&ui=hd&bl=vmp

**Comment by Flupignon** [comment]
à vous @Ricyeam et @Blange1 :)

**Comment by Blange1** [comment]
1ère relecture finie !

**Comment by Flupignon** [comment]
Cool ! N'oublie pas les RDLS ;)

**Comment by Flupignon** [comment]
Ah bah c'est en ligne. Des fois une seule révision suffit... Je comprends pas pourquoi.

**Comment by Blange1** [comment]
@Flupignon Peut-être que quelqu'un l'a fait en dehors des réseaux de traduction ! 
Ca roule pour les RDLS, par contre la RDLS12 #114 c'est déjà moi qui ai fait la première relecture
