### ISSUE TITLE
[Subtitles] [FR] COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ?

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#142]
# Video title
COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ?

# URL
https://www.youtube.com/watch?v=p4WrCjgCbaA&t=2s

# Youtube subtitles language
Français

# Duration
4:36

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&bl=vmp&v=p4WrCjgCbaA&action_mde_edit_form=1&tab=captions&ui=hd&lang=fr

**Comment by Albapringe** [comment]
Les sous-titres ayant déjà été fait par un anonyme, j'attaque direct la première correction.

**Comment by Albapringe** [comment]
J'ai terminé. Une vérification me semble indispensable car les sous-titres originels étaient moyens, donc j'ai pu passer à côté d'erreurs, par inattention.

**Comment by spidersouris** [comment]
Je dirais de rajouter une virgule entre « médicament » et « donc » pour le premier texte (de 0:00 à 0:06) et d'utiliser les guillemets françaises à la place des guillemets anglais pour le numerus clausus (de 0:41 à 0:47), « Ce n'est pas possible » (de 3:11 à 3:22), « Mélenchon, oh, il raconte des trucs » (de 3:23 à 3:31) et « Ce n'est pas possible qu'il y en ait » (de 4:17 à 4:26).

D'autres petits correctifs : entre 3:11 et 3:22, « Egal... et ben » devrait devenir « Égal... eh ben », entre 4:09 et 4:17, « Et bah oui » devient « Eh bah/ben oui ».

Pour « Et donc, les chiffres qu'il y a là, ils sont béton armé ! » (de 4:26 à 4:31), je n'en suis pas sûr, mais il faudrait peut-être utiliser un s pour « béton » et « armé », non ? J'ai rarement entendu cette expression, mais ça me paraîtrait logique.

**Comment by Bentham** [comment]
@Spidersouris Oh une souris araignée !! N'hésite pas à venir te présenter ici : https://github.com/jlm2017/jlm-video-subtitles/issues/17

**Comment by Bentham** [comment]
Je vérifie

**Comment by LucileDT** [comment]
@Spidersouris n'hésite pas à corriger toi-même directement depuis l'outil de sous-titrage YouTube :)

**Comment by quidam34** [comment]
arf désolé je crois que je me trompe de vidéo
