### ISSUE TITLE
[subtitles] [FR] #RDLS15 - FLORANGE, ÉNERGIE, ARME NUCLÉAIRE, DISPARITION DES SINGES, SOUFFRANCE ANIMALE, C. MANNING

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#147]
# Video title
#RDLS15 - FLORANGE, ÉNERGIE, ARME NUCLÉAIRE, DISPARITION DES SINGES, SOUFFRANCE ANIMALE, C. MANNING

# URL
https://www.youtube.com/watch?v=wRWG8RdT4fU

# Youtube subtitles language
Français

# Duration
29:33

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&v=wRWG8RdT4fU&ui=hd&lang=fr&tab=captions&action_mde_edit_form=1&bl=vmp

**Comment by Bentham** [comment]
Il va être important d'intervenir vite sur celle-là, elle est tournée dans un train et le son est particulièrement mauvais.

Je finis de la regarder et je me lance.

**Comment by Bentham** [comment]
Hop !

**Comment by Bentham** [comment]
Fait jusqu'à 16:56. A avancer aussi vite que possible, je pense.

**Comment by Albapringe** [comment]
J'ai quelques minutes, je continue derrière toi, Ô grand modo ;)

**Comment by Bentham** [comment]
Soyez béni mon fils.

**Comment by Albapringe** [comment]
Je libère à 19:06

**Comment by Bentham** [comment]
@Albapringe Tu n'as pas enlevé le label "Working", erreur d'inattention ?

**Comment by Albapringe** [comment]
Yes, sorry.

**Comment by Albapringe** [comment]
Bon, je voulais reprendre, mais il y a déjà 2 personnes dessus...

**Comment by Bentham** [comment]
On croise les doigts pour qu'ils cassent pas tout ! :)

**Comment by Bentham** [comment]
Je me demande s'il y a pas des gens qui se rendent dans l'interface de sous-titrage juste pour suivre la vidéo avec les sous-titres déjà rentrés...?

**Comment by Albapringe** [comment]
C'est pas impossible... Mais alors, faudra peut-être faire un petit truc dans ce cas là.  Introduire au début un container "En cours de rédaction, merci de laisser l'équipe de sous-titrage terminer le travail" et pourquoi pas, un lien avec nos coordonnées pour les anonymes qui sous-titrent non officiellement.

**Comment by Bentham** [comment]
Quel talent Albapringe ! C'est une super idée.

**Comment by Bentham** [comment]
On devrait le faire systématiquement en cas de grosse vidéo

**Comment by Bentham** [comment]
Notre inconnu a libéré la vidéo... Sans qu'il y ait la moindre modification :/

J'ajoute le message au début

**Comment by Albapringe** [comment]
Comment ça, sans rien ? Il reste 10 secondes à faire de mon côté.

**Comment by Bentham** [comment]
Moi dix minutes... Damned

**Comment by Bentham** [comment]
Ah ils me disent que je suis en train de modifier mon brouillon... Faudrait que je trouve un moyen de l'annuler, mais j'ai pas envie de tout casser

**Comment by Bentham** [comment]
Tu peux enregistrer les sous-titres complets de ton côté, avec Actions->Télécharger ?
Je vais essayer l'action "Ignorer les modifications" pour voir si c'est à ça que ça sert

**Comment by Albapringe** [comment]
C'est fait pour ma part.

**Comment by Bentham** [comment]
Ok j'essaie.

**Comment by Bentham** [comment]
Parfait, c'est bien à ça que ça sert. Ca supprime le brouillon en cours. Merci Alba :)

**Comment by Albapringe** [comment]
Great ! Bon, je le mets en review. Si tu n'as pas eu le temps d'ici là, je le ferai dans la soirée.

**Comment by Bentham** [comment]
Je ne pense pas y toucher d'ici là, si tu es chaud pour voir ça ce soir je te la laisse.

Sinon, est-ce que ce message te conviendrait, au début d'une vidéo en cours ?

//** Bonjour ! **\\
Vous êtes actuellement dans l'interface de sous-titrage. Par malheur, votre présence ici nous empêche d'avancer la transcription ! Nous vous invitons donc à revenir un peu plus tard sur cette vidéo en activant les sous-titres, qui seront bientôt terminés.
Si vous voulez aider à la transcription, rejoignez-nous en envoyant un message à traducteurs.insoumis@gmail.com, nous serons heureux de vous accueillir :)

Merci de votre compréhension,
L'équipe "Traducteurs Insoumis"

**Comment by Albapringe** [comment]
Nickel ! Le tout sera d'arriver les premiers sur la vidéo pour mettre ça immédiatement.

**Comment by Vimogo** [comment]
Je m'occupe de la vérification.

**Comment by Vimogo** [comment]
Bon je vais manger, la correction en est à 16:04.05.

**Comment by Vimogo** [comment]
Oki je reprends, on essaye de terminer ce coup-ci.

**Comment by Vimogo** [comment]
Bien, première vérification terminée.
Attention au rédacteur vers la fin, souvent des fautes, notamment des espaces avant les virgules, pas de majuscule en début de phrase et quelques oublis de parties de phrases.
De plus lors des dialogues pour faire un retour à la ligne il ne faut pas mettre plein d'espace sinon avec le décalage des sous-titres générés par le plein écran le saut de ligne ne fonctionnera pas, la façon appropriée est d'utiliser le raccourci CTRL + MAJ.

**Comment by Bentham** [comment]
Merci pour la révision. Le rédacteur de la fin est un anonyme qui a bloqué la vidéo toute l'après-midi... Mais bon le travail est fait en tout cas.

**Comment by Albapringe** [comment]
Allez, je m'attelle à la dernière

**Comment by Vimogo** [comment]
@Bentham pardon alors, j'ai essayé de comprendre ce que disaient vos posts mais en les lisant en différé je n'avais pas saisi.

**Comment by Albapringe** [comment]
Terminé. Publié et clôture de l'issue.

**Comment by Albapringe** [comment]
En fait, j'ignore ce qu'il s'est passé, mais aucune de mes modifs n'a été prise en compte. Il est trop tard, donc je laisse tomber.

**Comment by Bentham** [comment]
Bon j'essaie de revoir ça rapido

**Comment by Albapringe** [comment]
Mais, qu'est-ce que tu fais ici ? J'ai cru que tu allais voter, moi :)

**Comment by Bentham** [comment]
Prends-moi pour un poisson rouge !

**Comment by Bentham** [comment]
Allez, bim, à valider. Pas mal de fautes corrigées en deuxième partie de vidéo.

**Comment by Albapringe** [comment]
OK, je m'y mets.

**Comment by Bentham** [comment]
Tout est corrigé hein, normalement il y a vraiment juste à valider !

**Comment by Albapringe** [comment]
Validé :)

**Comment by LucileDT** [comment]
Pour ce qui est de votre message, vous pourriez le mettre sur toutes les vidéos qui ne sont pas encore sous-titrées, ça permettrait de rapatrier les bonnes âmes errantes.
