### ISSUE TITLE
[subtitles] [en]  #RDLS15 - FLORANGE, ÉNERGIE, ARME NUCLÉAIRE, DISPARITION DES SINGES, SOUFFRANCE ANIMALE, C. MANNING

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#149]
# Video title

#RDLS15 - FLORANGE, ÉNERGIE, ARME NUCLÉAIRE, DISPARITION DES SINGES, SOUFFRANCE ANIMALE, C. MANNING

# URL

https://www.youtube.com/watch?v=wRWG8RdT4fU

# Youtube subtitles language

Anglais

# Duration

29:33

# Subtitles URL

https://www.youtube.com/timedtext_editor?ui=hd&action_mde_edit_form=1&bl=vmp&v=wRWG8RdT4fU&tab=captions&lang=en&ref=player

**Comment by Flupignon** [comment]
Tu es dessus @Mattouk ?

**Comment by Mattouk** [comment]
Nope, mais je vais m'y mettre dans une petite heure

**Comment by Flupignon** [comment]
Fais attention car quelqu'un (un anonyme certainement) s'y est mis. Aux dernières nouvelles il en était à environ 3 ou 4 min. Si ça n'a pas bougé, c'est que tu peux y aller. J'avais juste fai les 2 premières minutes.

**Comment by Mattouk** [comment]
Ok, j'ai commencé par corriger la traduction sur l'OPA hostile de Mittal sur Arcelor, c'était un peu flou

**Comment by Mattouk** [comment]
@Flupignon 
Bon, j'en suis à 6'53", j'ai essayé de corriger ce qu'avait fait l'anonyme également, dis-moi si le boulot te conviens.

**Comment by Flupignon** [comment]
Tu as oublié de valider ton travail. Quand tu as fini, il fait cliquer sur "envoyer pour examen" en haut à droite. Si tu retournes sur l'éditeur, ton travail devrait être sauvegardé, mais on ne peut pas le voir si tu ne valides pas.

**Comment by LucileDT** [comment]
@Mattouk est ajouté aux contributeurs :)

**Comment by Mattouk** [comment]
@Flupignon En effet, après 1h du mat les neurones connectent moins bien, c'est corrigé ;)
@LucileDT Merci!

**Comment by Flupignon** [comment]
8:19

**Comment by Flupignon** [comment]
12:49

**Comment by Flupignon** [comment]
13:33

**Comment by Flupignon** [comment]
Quelqu'un s'est mis dessus en ano à partir de 12 min et quelques.

**Comment by Flupignon** [comment]
16:21 (+correction de la trad ano de 12:40 à 14:00)

**Comment by Flupignon** [comment]
19:09

**Comment by Flupignon** [comment]
24:41

**Comment by Flupignon** [comment]
27:07

**Comment by Flupignon** [comment]
Je dois juste relire la partie de 2:16 à env 4:00 et c'est prêt !

**Comment by Flupignon** [comment]
3;57 - 7:06

**Comment by Flupignon** [comment]
Finitos les patatos !

**Comment by Mattouk** [comment]
Impressionnant, quelle bête de travail.

J'ai corrigé quelques typos, sinon c'est ok

**Comment by LucileDT** [comment]
@Mattouk Dans ce cas, est-ce que tu peux mettre à jour les labels et déplacer l'issue dans le tableau pour dire qu'il ne manque qu'une seule validation ? :)

**Comment by Mattouk** [comment]
Done deal!
