### ISSUE TITLE
[communication] Demande de configuration du compte Github des contributeurs au projet

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#15]
# Date
28 novembre 2016

# Type
Internal

# Media used
Mail + Facebook group

# Purpose
Ask for setup notifications in Github to be sure to receive it.

# Content
**From @LucileDT**
> Merci de bien vouloir activer les notifications Github :
> 
> -    Connectez-vous à Github
> -   Cliquez sur votre avatar et sélectionnez Settings
> -    Dans la colonne de gauche, cliquez sur Notifications
> -    Dans le cadre "How you receive notifications", activez les cases :
>       -  Automatically watch repositories
>       -  Participating Web
>       -  Watching Web
> 
> 
> Vous pouvez activer ou désactiver les notifications par mail à votre convenance (pour ma part, je les garde active et j'applique un filtre dans ma boîte mail pour les mettre directement dans un dossier).
> 
> Quand vous actualiserez la page, vous verrez apparaître une petite cloche en haut à droite. Il y aura une petite pastille bleue dessus si vous avez des notifications (par exemple, nouveau commentaire sur une issue que vous surveillez, ou création d'une issue, ou quelqu'un qui vous assigne à une issue...).
> 
> Ricyeam, c'est pour ça qu'hier, tu n'avais pas la petite cloche en haut à droite.
> 
> Je fais suivre ce message sur facebook aussi, pour que Baya puisse l'avoir (je n'ai pas son mail).

# Answer
```none```

**Comment by LucileDT** [comment]
**Personnes ayant configuré leur compte :**
- [x] @LucileDT
- [x] @DarckCrystale 
- [x] @Ricyeam 
- [x] @bayasahra 
- [ ] @Flupignon 

Rajout le 01/12/16
- [x] @Bentham 
- [ ] @ClaireEV 

Merci d'avance !

**Comment by bayasahra** [comment]
c'est fait lucile ;)

**Comment by LucileDT** [comment]
Merci :D

**Comment by LucileDT** [comment]
Il me manque encore @ClaireEV et @Flupignon, est-ce que vous avez configuré vos notifications ?

**Comment by Ricyeam** [comment]
Et @dalipokim aussi

**Comment by Flupignon** [comment]
@LucileDT tu pourrais me redonner l'adresse gmail stp pour twitter sur le projet ?

**Comment by dalipokim** [comment]
Qu'est-ce qui se passe ?

2016-12-03 11:32 GMT+01:00 Ricyeam <notifications@github.com>:

**Comment by LucileDT** [comment]
L'adresse : traducteurs.insoumis@gmail.com :)

**Comment by Flupignon** [comment]
Thx !
