### ISSUE TITLE
[subtitles] [FR] MÉLENCHON - LA CASTE ET SES MARIONNETTES

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#150]
# Video title
MÉLENCHON - LA CASTE ET SES MARIONNETTES

# URL
https://www.youtube.com/watch?v=3JG3dL4TsH0&feature=push-u-sub&attr_tag=PJqLaS43vZ8-6

# Youtube subtitles language
Français

# Duration
1:40

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=3JG3dL4TsH0&tab=captions&ref=player&action_mde_edit_form=1&bl=vmp&ui=hd&lang=fr

**Comment by Bentham** [comment]
D'après youtube, une personne est dans l'interface de sous-titrage. A vérifier avant de s'y mettre !

**Comment by Bentham** [comment]
Première correction faite !

**Comment by Albapringe** [comment]
Je me colle à la dernière.

**Comment by Albapringe** [comment]
Terminé et publié.
