### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - « IL FAUT SORTIR DU NUCLÉAIRE ET PASSER AU 100% RENOUVELABLE»

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#151]
# Video title
MÉLENCHON - « IL FAUT SORTIR DU NUCLÉAIRE ET PASSER AU 100% RENOUVELABLE»

# URL
https://www.youtube.com/watch?v=Rudtj9ZJONo

# Youtube subtitles language
Français

# Duration
7:37

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&v=Rudtj9ZJONo&tab=captions&action_mde_edit_form=1&bl=vmp&ref=player&ui=hd

**Comment by Albapringe** [comment]
C'est parti.

**Comment by Albapringe** [comment]
Prêt pour relecture.

**Comment by Bentham** [comment]
J'y go. (d'agneau)

(cette blague ne vous sera pas facturée)

**Comment by Bentham** [comment]
Ah, cette journaliste qui n'écoute rien... Pauvre Jean-Luc !

C'est fait et en ligne en tout cas. Mais attention les amis, n'oublions pas le petit chapeau de Benoît ! (et non Benoit, donc)
