### ISSUE TITLE
Bonjour comment travailler à trois sur la même vidéo ... c'est possible 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#152]
Bonjour à tous !

Force est de constater qu'il existe un handicap pour sous-titrés les vidéos. En effet nous ne pouvons travailler que sur une seule vidéo à la fois ce qui fait que si nous étions 10, nous travaillons sur 10 vidéos. Ainsi certaine qui font par exemple une heure de temps vont être créés en plus d'une semaine, voir plus. Donc je me suis posé la question, comment faire pour pouvoir travailler à trois ou plus plus sur la même vidéo. Je viens de tester mon idée et cela fonctionne. Ainsi nous pouvons diviser une vidéo en trois parties. Une personne s'occupe de la première partie, une autre de la deuxième et la dernière de la troisième partie. Avec mon idée, impossible d'effacer le travail de l'autre. Ainsi les vidéos sont sous-titrés rapidement surtout quand il s'agit d'une vidéo très longue. Pour le sous-titreur, inutile d'érré d'un sujet à l'autre à la recherche d'une vidéo dont une personne n'est pas dans en train de s'occuper. J'ai testé personnellement et cela marche ! Mon équipe se propose de faire cette démonstration sur une vidéo existante vierge de tout sous-titre. Par ailleurs nous avons terminé de sous-titrer 2 vidéos de manière classique. Il ne nous reste plus que la correction orthographique et je vous en parlerai sur l'issue de chaque vidéo en question. Cordialement Jean-Michel.

**Comment by quidam34** [comment]
???

**Comment by quidam34** [comment]
arf aucune réaction c'est fou comme cela intéresse !

**Comment by LucileDT** [comment]
@quidam34 Votre manière de vous exprimer est passablement désagréable : vous pourriez faire l'effort d'être aimable. Comme nous vous l'avons déjà dit, nous sommes des bénévoles, nous avons tous une vie professionnelle et personnelle (voire scolaire) à mener à côté de la rédaction des sous-titres, donc nous ne sommes pas tout le temps collé à notre écran à lire les questions des uns et des autres.

De plus, si vous faisiez un effort de présentation, et que vous parliez de choses concrètes en les décrivant précisément, nous serions plus en mesure de vous comprendre et de réagir à ce que vous proposez. Voici un exemple : 

> Bonjour à tous !
> 
> Vous avez remarqué que nous ne pouvons pas travailler simultanément sur la même vidéo, au risque de perdre le travail de certaines personnes. C'est un problème car les vidéos longues mettent du coup bien plus de temps à être sous-titrées.
> 
> Je me suis donc demandé comment résoudre ce problème, et j'ai déterminé une solution. Nous l'avons testée et elle fonctionne. Voici ce que je propose : 
> > *ici, décrire la solution proposée*
> 
> Grâce à cette méthode, nous pouvons par exemple découper les longues vidéos en trois parties, avec un bénévole qui s'occupe de chacune d'entre elles. Le travail des autres bénévoles n'est pas effacé : ainsi, les vidéos longues peuvent être sous-titrées bien plus rapidement, et ça offre aux sous-titreurs disponibles plus de contenu à sous-titrer, sans qu'ils aient besoin de chercher une vidéo sur laquelle personne ne travaille.
> 
> Nous pouvons faire une démonstration de cette méthode sur une vidéo vierge de tous sous-titres.
> Cordialement, Jean-Michel

Bien sûr, présenter la méthode dont vous parlez plutôt que de la garder secrète comme vous l'avez fait, en n'en décrivant que les résultats, serait très apprécié.

Pour ma part, je serais ravie que vous nous expliquiez comment vous fonctionnez, car ça résoudrait une des grosses problématiques du sous-titrage des longues vidéos.

D'avance, merci.

**Comment by Goutte** [comment]
Bonjour à tous !

@quidam34 Patience ! Parfois, ça prend des semaines pour obtenir une réponse (une fois, j'ai reçu une réponse un an après). À vouloir tout, tout de suite, tout le temps, on obtient la société de surconsommation débile dans laquelle nous nous noyons.

Il y a un vieux proverbe africain qui dit _"Si tu veux aller vite, vas-y tout seul, mais si tu veux aller loin, vas-y à plusieurs."_

---

J'ai lancé une nouvelle discussion sur l'édition collaborative, afin de diffuser l'ambiance présente dans ce fil.

C'est par là : #154

**Comment by quidam34** [comment]
arf !  j'ai pas donné la solution pour la tester avant et surtout pour susciter votre curiosité !

**Comment by LucileDT** [comment]
C'est la pire des idées que vous puissiez avoir. Nous ne sommes pas ici dans une logique de suspense à l'américaine. Maintenant, soit vous prenez le temps de vous expliquer, soit je trouverai un moyen de vous empêcher de continuer à polluer notre espace.

**Comment by domi41** [comment]
@quidam34 Êtes-vous prêt à divulguer votre solution ?

**Comment by quidam34** [comment]
La solution ne vous conviendra pas ! Elle contient des manipulations qui nécessiterait l'intervention d'une personne de chez vous et donc n'est pas comme youtube a pu l'imaginer. Il faut tout simplement une deuxième vidéo identique sur youtube et ensuite réunir les fichier timecodes sur le même fichier et les réuploader sur Youtube ! Sur le forum c'est moi qui m'occupe de toute les manipulation qui sont sans risque si l'on a été très attentif dans son travail. Quand j'ai écris ce sujet (pardon issue ! ) je ne savais pas que vous souhaitiez a ce point ne pas être insoumis ! Sur ce coup là en tout cas !   ;-)   Je vous rassure , je taquine  ! Il n'y a jamais aucan fond de méchanceté chez moi, vous apprendrez à me connaitre !
