### ISSUE TITLE
[Subtitles] [FR] La mer a le goût du futur

### ISSUE THREAD

**Issue by desintoxiquezvous** [jlm2017/jlm-video-subtitles#153]
bonjour, je viens de sous-titrer sur Youtube , en français, l'ensemble de la vidéo 
# VIDEO TITLE
la mer a le goût du futur

# URL
https://www.youtube.com/watch?v=Aasyb8vtxpI&t=207s

# YOUTUBE SUBTITLES LANGUAGE
Français

# DURATION
16mn 31

# SUBTITLES URL
https://www.youtube.com/timedtext_editor?tab=captions&ref=player&v=Aasyb8vtxpI&ui=hd&lang=fr&action_mde_edit_form=1&bl=vmp

cordialement

**Comment by LucileDT** [comment]
Bonsoir !

Je n'ai pas le temps de t'aider avec tout ça, j'espère que @Bentham peut passer pour te donner un coup de pouce et t'expliquer pour ce qui te manque :/

**Comment by Bentham** [comment]
Bonjour @desintoxiquezvous, tu es maintenant collaborateur. Il s'agit maintenant seulement d'ajouter les labels "Language: French", et "Process: [2] Ready for review (1)", pour indiquer que la première correction est attendue. Quand tu te mettras au travail, tu mettras le label "Process: Someone is working on this issue", et tu l'enlèveras quand tu arrêteras de travailler.

Il faut aussi ajouter une "card" ici : https://github.com/jlm2017/jlm-video-subtitles/projects/2
Clique sur "Add cards", et dans la liste qui apparaît fait glisser "La mer a le goût du futur" dans la colonne "Prêt pour correction (1)"

Il faudrait que je fasse une vidéo un de ces quatre pour montrer comment ça marche, je ferai ça quand j'aurai le temps !

**Comment by clement20** [comment]
C'est parti pour la première relecture.

**Comment by clement20** [comment]
13:26 : Difficile à comprendre le nom de la société française qui fait des sous-marins.

**Comment by clement20** [comment]
16:20 : La mère de notre monde ou La mer de notre monde?
D'un côté c'est la mer Méditerranée, mais c'est aussi la Bonne Mère. J'opte quand-même pour la mer.

**Comment by clement20** [comment]
Ok pour la première relecture, à mes deux remarques ci-dessus près.

**Comment by LucileDT** [comment]
@desintoxiquezvous + @clement20 super boulot :+1: 

@Bentham je plussoie, si tu me fais une vidéo pour chaque étape, je serais ravie \*-\*
Tu peux regarder la documentation pour voir ce qui est donné comme informations aux nouveaux : https://github.com/jlm2017/jlm-video-subtitles
