### ISSUE TITLE
Edition collaborative en temps réel

### ISSUE THREAD

**Issue by Goutte** [jlm2017/jlm-video-subtitles#154]
Discutons ici des différentes approches que nous trouvons pour éditer des sous-titres collaborativement (en temps réel)

J'ai trouvé un site qui a l'air prometteur : [Amara](http://amara.org/fr/).

## Together.Js

Couplé à un plugin firefox comme [Together.js](https://togetherjs.com/), il y a peut-être moyen de moyenner, comme qui dirait !

Peut-être peut-on utiliser le plugin directement avec Youtube, à voir.

J'ai bien envie d'essayer, en tout cas, couplé à un outil de communication comme [Jitsi Meet](https://meet.jit.si/) !

---

Bref, je ne sais pas où vous vous donnez rendez-vous (je boycotte facebook, pardon pour l'inconvénience, mais j'ai lu et compris son CLUF, et ... juste ... non.), mais si des gens sont motivés pour essayer, on pourrait se créer un salon comme https://meet.jit.si/insoumis par exemple.

J'y attendrai des aventuriers et aventurières motivés pour tester des choses nouvelles, je suis convaincu qu'il y en a plein par ici ;)

**Comment by Goutte** [comment]
(il faudrait ajouter des labels à cette discussion, tiens)

**Comment by quidam34** [comment]
J'ai ouvert une discutions a ce sujet et la solution est déjà trouvé la votre semble hasardeuse !

**Comment by Goutte** [comment]
@quidam34 Hasardeuse ? Qu'est-ce qui vous fait dire cela ?

Je souhaite simpement tester cette solution avec quelqu'un, pour me faire un avis dessus, sans en préjuger. En outre, si vous pensez avoir déjà trouvé la solution, pourquoi ne pas la partager ? Enfin, je ne pense pas que vous compreniez bien le concept de collaboration en temps réel. (ie. voir le curseur des collaborateurs sur son propre écran)

**Comment by LucileDT** [comment]
@Goutte pour tout dire, @quidam34 nous fait miroiter une éventuelle solution dont il parle ici : #152 
Iel a tendance a avoir un langage peu sympathique, ne pas respecter nos conventions, n'a pas lu la documentation, se plaint et a également prononcé à l'encontre de notre organisation des termes peu sympathiques (dictat il me semble, enfin des équivalent).

Pour ce qui concerne la communication : nous passons principalement par le Github, et certains d'entre nous se retrouvent sur Facebook, mais ça n'a globalement pas un très grand intérêt pour le groupe, donc pas de souci si tu ne souhaites pas t'y inscrire. Tu peux également nous retrouver ici : #25 
On a un canal de discussion privé, tu n'as qu'à te signaler dans le channel Aide sous-titres (il me semble qu'il s'appelle comme ça) et on t'y rajoutera.

Je suis actuellement au bord du burn out (sans rire) car je me suis engagée comme sys admin des initiatives insoumises sur internet, du coup je suis un peu surbookée ^-^' sinon, je t'aurais volontiers aidé.e avec tes tests :( Désolée !
