### ISSUE TITLE
[subtitles] [en] MÉLENCHON - LA CASTE ET SES MARIONNETTES

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#157]
# Video title

MÉLENCHON - LA CASTE ET SES MARIONNETTES

# URL

https://www.youtube.com/watch?v=3JG3dL4TsH0&t=13s

# Youtube subtitles language

Anglais

# Duration

1:40

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&v=3JG3dL4TsH0&lang=en&ref=player&action_mde_edit_form=1

**Comment by LucileDT** [comment]
@BSAJenko je t'ai ajouté aux collaborateurs, tu devrais pouvoir éditer l'issue + y rajouter les labels que tu veux :)

**Comment by fkevv** [comment]
Merci :)

**Comment by Flupignon** [comment]
@FROISSARTKevin n'oublie pas qu'en anglais, il n'y a pas d'espace entre un signe de ponctuation double (?/!/:/;) et la lettre qui précède ;)

**Comment by Flupignon** [comment]
C'est bon, il faut une dernière validation.
