### ISSUE TITLE
[Subtitles] [EN] "COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ?"

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#158]
# Video title

"COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ?"

# URL

https://www.youtube.com/watch?v=p4WrCjgCbaA&t=149s

# Youtube subtitles language

Anglais

# Duration

4:36

# Subtitles URL

https://www.youtube.com/timedtext_editor?lang=en&v=p4WrCjgCbaA&ui=hd&ref=player&action_mde_edit_form=1&tab=captions&bl=vmp

**Comment by Flupignon** [comment]
Quelqu'un a fait une traduction, peut-être est-ce toi @BSAJenko ? Je la relirai demain.

**Comment by fkevv** [comment]
Oui, j'ai fait la traduction.

2017-01-30 0:57 GMT+01:00 Flupignon <notifications@github.com>:

**Comment by Flupignon** [comment]
C'est prêt ! J'ai fait pas mal de modifications parce que ta première trad était assez littérale. Il ne faut pas avoir peur de dépasser la version française et d'expliciter, ou ça devient incompréhensible pour un anglophone.

**Comment by Flupignon** [comment]
Par exemple, des phrases au présent en français passent très mal en anglais si elles ne sont pas mises au passé.

**Comment by Blange1** [comment]
Relu et approuvé ! J’ai fait quelques petites modifs à certains endroits qui permettaient de raccourcir un peu la longueur du bloc de sous-titres (ex : « they spend their time explaining » --> « they keep explaining »)

**Comment by Flupignon** [comment]
Salut @Blange1 et merci pour l'approbation ! Je suis sur le meeting hologramme en ce moment. J'ai fini pour ce soir et je n'aurai pas beaucoup de temps demain, si tu veux donner un coup de main fais toi plaisir !

**Comment by Blange1** [comment]
Salut @Flupignon, j'ai commencé de mon côté la RDLS17, j'en ai encore pour un bout de temps donc si je fais celle-là en priorité je risque de pas avoir le temps d'aider tout de suite sur l'hologramme. Par contre, on peut aussi décider de faire passer l'hologramme en priorité (ce qui ne serait pas absurde) et de remettre la RDLS17 à plus tard. Qu'en penses-tu ?

**Comment by Flupignon** [comment]
Oui je pensais faire ça.

**Comment by Blange1** [comment]
Ok ça marche, je vais essayer de m'y mettre un peu ce soir !

**Comment by Flupignon** [comment]
Cool ! On enchaîne la RDLS dans la foulée, en espérant que la prochaine arrive pas trop vite et surtout qu'elle ne soit pas trop longue...
