### ISSUE TITLE
[subtitles] [fr] REVUE DE LA SEMAINE #5

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#16]
# Video title
REVUE DE LA SEMAINE #5 - FICHAGE GÉNÉRALISÉ, ÉLECTIONS, ÉGALITÉ FEMMES-HOMMES, GRÈVE DANS LA SANTÉ

# URL
https://www.youtube.com/watch?v=kt9V0BXujyI

# Youtube subtitles language
Français

# Duration
19:14

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=kt9V0BXujyI&ui=hd&forceedit=timedtext&action_mde_edit_form=1&ref=player&lang=fr&bl=vmp&tab=captions

**Comment by Ricyeam** [comment]
Utilisateur Youtube Dario par mail à Ricyeam

"re ! J'ai fini de transcrire la revue de la semaine #5 et je l'ai envoyé pour examen."

**Comment by Flupignon** [comment]
Hey ! Du coup si l'admin a pas encore validé, nous aussi quand on te relit on doit "envoyer pour examen" ?

**Comment by Ricyeam** [comment]
@Flupignon Il me semble que en fait le créateur de la vidéo n'a pas besoin de valider les sous-titres. Du moment que un autre utilisateur que celui qui a écrit les sous titres le fait, c'est bon. Donc oui, "envoyer pour examen"

**Comment by Flupignon** [comment]
La revue N°5 est prête en français !

**Comment by Ricyeam** [comment]
Ok super! Peux-tu t'occuper de modifier l'avancement dans la page projet correspondante? Et aussi de changer le label, et close l'issue. Dans la page projet, c'est juste du drag&drop! (si pas de 2e revue, passe directement à approuvé) Merci beaucoup!

**Comment by Flupignon** [comment]
Personne veut relire ?

**Comment by Flupignon** [comment]
Ok, je viens de comprendre le système !

**Comment by bayasahra** [comment]
corrigé et validé

**Comment by Ricyeam** [comment]
@bayasahra pourrais-tu déplacer l'issue dans la colonne qui correspond, dans la page du projet? merci

**Comment by bayasahra** [comment]
@Ricyeam  je pense qu'elle est dans la bonne colonne ... elle n'est ni en ligne , ni encore approuvée par le staff youtube

**Comment by Flupignon** [comment]
Mais @Ricyeam, quand la vidéo est "approved" mais pas en ligne, on la met quand même dans la dernière colonne ? Ou c'est vraiment que quand c'est en ligne ?

**Comment by Ricyeam** [comment]
Quand qqun d'autre que la personne qui les as écrit corrige et fait la révision de sous-titres, et ensuite approuve les sous-titres (avec correction), les sous-titres sont automatiquement mis en ligne. Au debut on pensait que les createurs de la vidéo devaient les approuver, mais en fait non. Si  tu fais le test, les ss-titres sont visibles maintenant.

**Comment by Flupignon** [comment]
Bah ça marche pas avec moi... Ça me l'a fait une fois seulement. Pour corriger, vous faites bien "Ajouter des sous-titres" dans Youtube, ou je me trompe ?

**Comment by Ricyeam** [comment]
ben oui c'est ca… tu peux pas voir les sous titres là?

**Comment by Flupignon** [comment]
Pardon javais pas capté, je me suis emmêlé les pinceaux je parlais de l'issue #14 mais c parce que c'est moi qui l'ai corrigé certainement... Il faut que quelqu'un relise. Du coup j'enlève "approved" ?

**Comment by bayasahra** [comment]
ok je pensais qu'on devait attendre une validation du staff de Mélenchon ... je les ai déplacé.
