### ISSUE TITLE
[Subtitles] [FR] #RDLS16 - VENISE, DROIT À L'IVG, JEU VIDÉO, BD, NÉGAWATT, PRIMAIRE PS, FILLON

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#160]
# Video title
#RDLS16 - VENISE, DROIT À L'IVG, JEU VIDÉO, BD, NÉGAWATT, PRIMAIRE PS, FILLON

# URL
https://www.youtube.com/watch?v=6HG7IsmGD38

# Youtube subtitles language
Français

# Duration
42:25

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=6HG7IsmGD38&ui=hd&action_mde_edit_form=1&ref=player&bl=vmp&lang=fr&tab=captions

**Comment by Albapringe** [comment]
C'est parti.

Une personne travaille dessus, malgré le message... Je reprends plus tard.

**Comment by desintoxiquezvous** [comment]
je peux en faire un bout en commençant vers la minute 30 par exemple histoire d'avancer plus vite, ou tu préfère continuer seul ?

**Comment by Albapringe** [comment]
Tant que quelqu'un est dessus, ce n'est pas utile de tenter quoi que ce soit, je le crains.

**Comment by desintoxiquezvous** [comment]
ok

**Comment by Albapringe** [comment]
Le sous-titrage a été libéré. Je continue là où la personne s'est arrêtée, et si tu veux, tu peux effectivement commencer à 30:01.

**Comment by desintoxiquezvous** [comment]
je viens de faire la reconnaissance vocale de 30:01 à la fin (j'ai tout le texte correspondant)
je commence le sous titrage  je te signalerai ou je m’arrête

**Comment by Flupignon** [comment]
Je crois que je ne vais pas traduire cette revue en anglais, elle est trop longue... J'ai failli abandonné la dernière en route, mais là... ça prend vraiment beaucoup de temps à traduire :( Peut-être des extraits sur la chaîne en anglais ? Qu'en pensez-vous ?

**Comment by desintoxiquezvous** [comment]
je viens de finir de 29:55 à la fin
stop pour moi

**Comment by clement20** [comment]
Est-ce normal que le label "Someone is working ..." soit encore présent? Ne faudrait-il pas le supprimer et passer en correction?

**Comment by Albapringe** [comment]
Non, je suis toujours dessus ;)

**Comment by LucileDT** [comment]
@Flupignon je plussoie les extraits, et oui, JLM s'est lâché sur la durée o_o

**Comment by Albapringe** [comment]
J'ai complété, mais gros souci, ton travail, @desintoxiquezvous, semble avoir disparu. Je me suis arrêté à 29:55 et il n'y a rien après. Je ne suis pas sûr que le travail simultané soit une bonne idée, en définitive.
Petite incompréhension à 25:16 signalée par [???] à compléter.

**Comment by desintoxiquezvous** [comment]
bonjour, c'est étrange cette disparition , si je vais dans mon brouillon youtube je les vois bien en grisé, je suis sûr de les avoir envoyés , d'ailleurs dans "mes contributions" youtube ils sont marqués comme envoyés il y a peut être un délai ? ou alors ça bug j’hésite a les renvoyer je ne voudrais pas écraser ton travail;
![capture](https://cloud.githubusercontent.com/assets/25301326/22415624/2ee1307c-e6c9-11e6-8d8e-7840e5f6ae9e.jpeg)
![capture2](https://cloud.githubusercontent.com/assets/25301326/22415627/3365f182-e6c9-11e6-93be-79647b9f786c.jpeg)

bon ce que je peux faire c'est poser ici le pdf du texte comme ça il n'y a pas à réécrire le texte
[RDLS16 de 30mn a la fin.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/738343/RDLS16.de.30mn.a.la.fin.pdf)
tiens moi au courant ...

**Comment by desintoxiquezvous** [comment]
une question: je viens de cliquer sur le bouton "action" au dessus des sous titres,et avec le sous menu "télécharger" j'ai récupéré  un fichier caption.sbv de 29Ko qui, je pense, doit correspondre aux timing des sous titres 
ce fichier peut-il servir a quelqu'un de la communauté ou est-ce réservé a mon compte?

**Comment by Flupignon** [comment]
@desintoxiquezvous regarde l'image : en haut à droite de l'écran, il y a un bouton "modifier", clique dessus :p 
Et tout le monde peut télécharger le sous-titre (pour conversion ou conservation par exemple).

**Comment by desintoxiquezvous** [comment]
@Albapringe bon je viens de recharger mon fichier sbv et c'est bien mon brouillon qui est revenu prêt a être rediffusé, le pb c'est que je ne vois ta contribution que jusqu’à 6:44 ,au moment ou j'ai commencé a sous-titrer, rien ensuite jusqu’à ma propre contribution a 30: ... si j’envoie je pense peut être effacer le travail que tu as fait derrière donc je m'abstiens
il faudrait trouver un admin youtube qui nous indique vraiment la marche à suivre en collaboratif sinon on est mal ...

**Comment by desintoxiquezvous** [comment]
@Flupignon pas du tout , moi quand je tente désormais de retoucher les s/t j'ai ça
![capture3](https://cloud.githubusercontent.com/assets/25301326/22418137/e8b79d34-e6d7-11e6-88a7-0e8b13285293.jpeg)
youtube me dit vous êtes en train de modifier votre précédent brouillon, mais je ne vois pas le travail @Albapringe après 6:44 je ne vois que ce qu'il a fait jusqu'a 6:44 et le mien ensuite à partir de 30:
pourtant j'ai envoyé déja envoyé ce travail hier soir et apparemment il n’apparait pas .
je pense que les cookies de youtube me ramènent a ma dernière intervention et pas a la situation actuelle
je vais essayer de me connecter sous un autre compte youtube et voir si je vois ou en est le travail (vu d'un compte "vierge")

**Comment by Flupignon** [comment]
Peut-être qu' @Albapringe n'a  pas enregistré son travail ?

**Comment by desintoxiquezvous** [comment]
@Flupignon @Albapringe bingo ! je vois le travail jusqu'a 29:56 en changeant de compte 
et donc je ne m'explique pas que le travail que j'ai envoyé hier sous mon autre compte n'apparaisse pas

**Comment by desintoxiquezvous** [comment]
@Flupignon  @Albapringe mondieumondieumondieu que faire? comme dit plus haut, j'ai mis le pdf du texte de 30:00 à la fin sur ce fil , ça serait peut plus sur que @Albapringe le récupère et finisse le taf (si il a le temps) j'attends des réponses avisées..........

**Comment by desintoxiquezvous** [comment]
@Flupignon @Albapringe ou alors je refais le boulot,moi en partant de ce nouveau compte 
.................bon ça y est c'est renvoyé, croisons les doigts

**Comment by LucileDT** [comment]
@desintoxiquezvous merci pour ta patience :3 Et oui, malheureusement le travail des sous-titres sur l'outil YouTube ne fonctionne pas en collaboratif, c'est pour ça qu'on évite de bosser à deux sur une même vidéo en général :x

**Comment by Albapringe** [comment]
@desintoxiquezvous Tu as renvoyé quelque chose ? Parce que rien n'a changé pour moi. Il y a toujours seulement ma portion jusqu'à 29:56.

**Comment by desintoxiquezvous** [comment]
@Albapringe @LucileDT et bien oui apparemment j'ai renvoyé de nouveau ma contribution et rien n'apparait,il faudrait savoir qui est l'administrateur réel de la chaine qui a mis la vidéo en ligne, normalement si j'en crois le support google ,lui doit voir toutes les soumissions .
https://support.google.com/youtube/answer/6054623?hl=fr
je n'ai pas dans ma fenêtre l'onglet "voir les versions provisoires"
donc n'en sachant pas plus comment procède t-on ?
veux tu récupérer mon pdf  et continuer la suite ou je réessaye a partir d'un autre compte youtube "vierge"?
https://github.com/jlm2017/jlm-video-subtitles/files/738343/RDLS16.de.30mn.a.la.fin.pdf

**Comment by Albapringe** [comment]
Je pense que je vais poursuivre la version en cours à partir de ton pdf, c'est sûrement la meilleure solution. Merci pour le texte, d'ailleurs.

**Comment by desintoxiquezvous** [comment]
@Albapringe @LucileDT ok je te laisse faire alors
il faudra vraiment qu'on établisse une procédure de travail chronologique et de répartition bien ficelée pour éviter toutes ces pertes de temps
il faudrait savoir quand même qui est l'administrateur youtube de la chaine, lui doit voir toutes les contributions et versions provisoires, non?
je suis sur qu'il y a quelque chose qui cloche puisque youtube encourage à le faire dans ses pages support, est-ce que c'est le fait de travailler simultanément a plusieurs sur une vidéo ? je ne crois pas, car par exemple sur un clip très populaire il pourrait y avoir plusieurs dizaines de fans sous titrant en même temps ...

a suivre

**Comment by LucileDT** [comment]
@desintoxiquezvous c'est bien de le faire à plusieurs en même temps qui casse le truc, on tombe régulièrement sur le problème.

Pour ce qui est de l'administrateur de la chaîne, j'ai son numéro de téléphone, et il est complètement débordé, ils ne sont que 2 à gérer la chaîne, donc c'est la galère totale. J'ai cherché à le joindre récemment mais pas de réponse :(

**Comment by Albapringe** [comment]
Ça y est, prêt pour première relecture :) Il faudra supprimer le premier container, et tirer le second jusqu'au début, petit oubli de ma part.

**Comment by DominDamid** [comment]
J'ai quelques minutes pour commencer la première relecture ; je m'y mets.

**Comment by DominDamid** [comment]
Terminé !
Bon boulot Albapringe, il n'y avait presque rien à modifier.
Dans le doute, j'ai laissé l'encart de mise en garde au début.

Une incertitude encore : une fois terminée cette première relecture, j'ai cliqué sur YouTube sur "non terminé", et non sur "approuver" ; est-ce que c'est bien ainsi qu'il faut faire ? Ou est-ce que du coup mes modifications ne sont visibles que par moi ?

**Comment by Albapringe** [comment]
Normalement, c'est "approuver". Je pense que c'est mieux que tu le fasses, car sinon, techniquement, on est toujours en "1ère relecture".

**Comment by desintoxiquezvous** [comment]
je commence la 1ere relecture

**Comment by DominDamid** [comment]
**@desintoxiquezvous** À la suite de ce qui a été dit plus haut, j'ai vérifié et ma première relecture semble avoir été enregistrée. 
Pour être sûr que cela n'apparaît pas sur mon compte seulement, tu peux regarder à 38:58.4, il doit y avoir "Alors, parce que ça allait être _Mme_ Le Pen" si ma correction est passée, tandis que ce sera "Alors, parce que ça allait être Madame Le Pen" si elle n'a pas été enregistrée.
Comme ça, ta relecture sera la deuxième relecture et on peut finaliser le processus sur cette vidéo dès que tu auras fini.

**Comment by desintoxiquezvous** [comment]
Le 31 janv. 2017 à 19:51, DominDamid a écrit :
apparemment non , c'est toujours "madame Le Pen " donc ça n'a pas été enregistré
je suppose que tu as fait d'autres modifs, mais pour l'instant je ne peut pas me recoller a une 2eme lecture (je viens de m'en faire 5 h)

la solution que j'ai testé pour savoir ou on en est c'est d'ouvrir un 2eme compte youtube indépendant du tiens et  d'aller voir sur la vidéo et faire comme si on allait contribuer aux s/t mais sans rien envoyer, et la on voit la derniere version en cours 
d'autre part je ne sait pas si j'ai le droit d'approuver une seconde lecture , il ne faut pas que ce soit un compte différent?

**Comment by Albapringe** [comment]
Normalement, ceux qui ont contribué ne peuvent pas relire, mais en l'occurrence, comme j'ai fait "l'intégralité" (même si la fin est un copier-coller de ton travail, @desintoxiquezvous), tu peux faire la correction. Attention à la gestion des labels, là, on ne sait plus trop où on en est.

**Comment by desintoxiquezvous** [comment]
pourtant j'avais envoyé mon boulot (avant de voir qu'il n'avait pas été pris en compte par Youtube) et ça a été pourtant reconnu (par Youtube) à l'envoi depuis mon compte Youtube 
il faudrait vraiment comprendre le parallélisme entre l'avancement vu par Youtube et l'avancement par nous même dans GitHub,je n'arrive pas à savoir qui décide de quoi, et finalement qui donne le bon à diffuser auprès de youtube 
une procédure écrite bien complète serait nécessaire à tous pour comprendre la chronologie des avancements (au niveau de Youtube)
concernant la 2 eme relecture je m'y colle,mais qui se charge d'approuver à la fin on change de colonne ou bien ??

**Comment by desintoxiquezvous** [comment]
Je commence la 2ème relecture

**Comment by desintoxiquezvous** [comment]
@Albapringe c'est le bordel , je ne vois que mon précédent brouillon, je ne vois rien entre 6:45 et 29:55 ça reste sur l'état dans lequel j'avais laissé mon brouillon, impossible d'avoir tes corrections,donc je me déconnecte et me reconnecte sous un autre compte Youtube qui s'appelle "village de courcerault" et là miracle je vois tout, donc je m'y attaque 
C.EST DONC LA SEULE SOLUTION,quand on veut voir ou en est réellement le travail il faut se connecter sous un autre compte sur lequel on n'a pas travaillé
au boulot...

**Comment by desintoxiquezvous** [comment]
@Albapringe bon fini, c'est ok pas de retouches.
je viens de valider l'envoi sur youtube en disant "S/T terminé" a partir de mon compte" village de courcerault" je ne sais pas si ça sert à quelque chose je m'y perd vraiment entre les comptes 
bon, voila la suite au prochain numéro,bonne nuit

**Comment by Albapringe** [comment]
Les sous-titres ne sont pas publiés. Il manque donc à minima un relecteur qui ne soit pas ceux qui sont intervenus. Je remets en "Relecture 2"

**Comment by desintoxiquezvous** [comment]
tu vois je te l'avais dit, j'ai validé à partir d'un autre compte youtube,mais du même ordi, youtube a du repérer l'adresse IP et donc si on veut faire ça c'est:  autre ordi, autre compte et autre IP .... faut squatter l'ordi de la belle mère, chez elle, sur son compte Youtube :-D

**Comment by Albapringe** [comment]
Non, je pense que tu as été considéré comme premier relecteur puisque DominDamid n'a pas eu une validation correcte.

**Comment by desintoxiquezvous** [comment]
bon décidément,  je n'y comprend rien entre le système de validation de youtube et celui, ici de GitHub; 

qui décide quoi? ou se trouve l'administrateur de la video, celui qui a autorisé l'ouverture à la collaboration des sous titres de cette vidéo , c'est un des admin ici sur GitHub ?,ou c'est un responsable quelque part ailleurs chez JLM dans l'équipe de tournage 
qu'est ce qui fait, ou dit, que la validation n'est pas correcte...il faut vraiment un "sous titreur" puis un "premier lecteur" puis un "2eme" puis un "valideur" tous différents ? donc au moins 4 personnes?
et quid de ceux qui sous titres dans leur coin en anonyme, qui décide que leur travail est validé ou non?

c'est vrai que je suis ici depuis peu et que j'ai peut être un peu de mal a travailler en collaboratif mais vraiment c'est obscur

par ailleurs dans la procédure d'écriture il faudrait préciser que lorsqu'on s'arrête en cours de route et qu'on enleve le label Process: Someone is working on this issue, et que si on laisse travailler quelqu'un d'autre et qu'il stoppe a son tour on ne peut pas reprendre derrière car on ne voit que son propre travail précédent et pas ce qui a été  ajouté, ça fait qu'on ne sait pas comment reprendre même si on indique le time code début et fin il reste une incertitude, et en plus youtube n'a pas l'air de prendre en considération le travail fait,  c'est ce qui nous est arrivé....
bref.....on en rediscute plus tard

**Comment by Albapringe** [comment]
Tu as lu les tutos ?
Le principe est : un sous-titreur (et un seul à la fois), puis un premier relecteur qui approuve, puis un dernier qui valide. Soit 3 personnes dans le processus en situation optimale.
Ceci implique évidemment d'avoir validé correctement chaque étape sur Youtube (c-à-d avoir cliqué sur les bons boutons "Approuver", etc.)
Dans le cas où plusieurs personnes interviennent sur le sous-titrage, ça fonctionne bien si on ne travaille pas à deux **en même temps**, mais successivement.

**Comment by desintoxiquezvous** [comment]
oui j'avais bien vu le tuto, mais même si on travaille successivement à la rédaction on ne peut le faire qu'UNE fois car on ne voit que son propre brouillon et pas l'avancement réel du travail, c'est ça qui est troublant, si on reprend, on en reste à son propre état précédent (et pourtant Youtube valide ce nouveau travail si on continue...et pourtant il n'apparaitra pas!)
j'en tire comme conclusion que:
- si quelqu'un sous titre on attend qu'il dise qu'il a arrêté pour reprendre ( c'est ce que prévoit la procédure, logique!)  si on reprend derriere,soit on va jusqu'au bout, soit, si on s'arrete en cours de route on ne reprendra PAS ensuite après quelqu'un d'autre sous peine de voir le travail pas pris en compte malgré sa validation par youtube....
- qu'effectivement on ne doit pas travailler sur les sous titres ,puis sur la relecture ensuite 
pour moi, travaillant principalement par la méthode de reconnaissance vocale,je continuerai en amont

**Comment by LVAI** [comment]
Bonjour @desintoxiquezvous 

Je crois que vous avez rencontré un bug sur le sous-titrage de cette vidéo.
Peut-être dû au fait que vous ayez travaillé à un moment en simultané ? Ou autre chose. Je ne sais pas.

J'ai travaillé en collaboration sur une autre vidéo. On était trois à se relayer et tout se passait bien :smiley: On voyait bien les ajouts et corrections des autres.

**Comment by LucileDT** [comment]
@desintoxiquezvous une remarque : ce procédé est imposé par YouTube, c'est le seul moyen que nous avons d'être autonomes, et donc de ne pas avoir besoin d'un administrateur de la chaîne qui valide notre travail.

Concernant votre problème : vous avez effectivement rencontré un bug, ou vous avez travaillé en même temps @Albapringe sur la vidéo.

**Comment by desintoxiquezvous** [comment]
bonjour @LVAI et @Albapringe 
c'est peut être effectivement un bug ??? avez vous repris plusieurs fois le travail ou juste une fois ?
bon,on verra pour la prochaine...
quant à moi je vais continuer ma méthode qui consiste à faire le plus possible de fichier texte par reconnaissance vocale, puis de le passer dans un correcteur orthographique et mettre un pdf à dispo sur l'issue correspondante (sachant toutefois que des sous titreurs choisissent de taper le texte directement dans les containers plutôt que d'avoir un texte au km)
l'avantage c'est d'avoir un texte déjà bien propre, corrigé grammaticalement qui permettrait au relecteur un travail plus rapide
le sous titrage est également bien plus rapide ensuite,en entrant l'ensemble du texte dans un seul container au début on voit le texte dans la fenêtre image et donc on voit ou on peut faire une césure judicieuse
à l'écoute, on pause la vidéo la ou on a décidé de couper ,on place le curseur sur le premier mot suivant dans le container puis "enter" le conteneur suivant est créé à la bonne place et ainsi de suite, c'est presque du temps réel (il suffit d'agrandir le container qui ne fait que 2sec vers la droite pour continuer à voir le texte à l'écran durant la lecture)
c'est aussi peut être une bonne méthode pour avancer plus vite: un sous titreur commence le boulot et un autre fait de la reconnaissance vocale plus loin dans le texte selon la demande du sous titreur actif et lui laisse à dispo le pdf (surtout valable pour les vidéos longues )

**Comment by LVAI** [comment]
@desintoxiquezvous , j'ai travaillé sur l'issue #91 . Vous pouvez aller la regarder et voir tous les changement s de main. On a sous-titré cette vidé d'1h 5 minutes par 5 minutes donc on s'est relayé plus d'une fois ! Sans jamais de problème :)

Je valide votre méthode d'écriture en continue puis relecture personnelle puis segmentation en sous-titres. Mais pour ma part j'ai du mal à l'utiliser car lorsque je fais de la synthèse vocale, je n'ai pas la main sur la vidéo et donc je passe mon temps à changer de fenêtre pour revenir sur la vidéo, à changer la vitesse de la vidéo pour vérifier ce que j'entends etc et c'est très long. Donc je fais un mixte en écrivant par paragraphe de plusieurs minutes (mais pas toute la vidéo).

**Comment by desintoxiquezvous** [comment]
je ne fait pas comme ça , je lis la vidéo sur mon Ipad ou sur un portable à côté de moi, sur lequel j'ai branché mon casque et que je met régulièrement en pause entre chaque phrase et je parle au micro sur mon IMac pour redire chaque phrase  et donc je reste en permanence sur la fenêtre de reconnaissance c'est bien plus pratique ....

**Comment by desintoxiquezvous** [comment]
désolé @LVAI  j'ai oublié de vous mentionner en début de mon texte précédent est ce que vous le voyez quand même ?

**Comment by LVAI** [comment]
Oui tout à fait :) Je suis abonnée pour cette page donc je reçois tous les échanges. Donc aucun soucis.
Je note votre méthode. J'essayerai de l'appliquer mais il faut que je me trouve un micro !

**Comment by LucileDT** [comment]
@desintoxiquezvous certaines personnes ici font comme vous, d'ailleurs @Bentham a fait une vidéo ici pour expliquer cette méthode : #129 :smile: 
Ne vous en faites pas, chacun est libre de ses méthodes !

De plus, vous pouvez activer le système de notifications directement sur l'interface Github avec la méthode suivante :
> - Connectez-vous à Github
> - Cliquez sur votre avatar et sélectionnez Settings
> - Dans la colonne de gauche, cliquez sur Notifications
> - Dans le cadre "How you receive notifications", activez les cases :
>   - Automatically watch repositories
>   - Participating Web
>   - Watching Web
> 
> Vous pouvez activer ou désactiver les notifications par mail à votre convenance (pour ma part, je les garde active et j'applique un filtre dans ma boîte mail pour les mettre directement dans un dossier).
> 
> Quand vous actualiserez la page, vous verrez apparaître une petite cloche en haut à droite : ![capture du 2016-12-03 10 41 51](https://cloud.githubusercontent.com/assets/23707217/20858425/34fe478a-b945-11e6-8c02-856afdd743c7.png)
> 
> 
> 
> 
> Il y aura une petite pastille bleue dessus si vous avez des notifications (par exemple, nouveau commentaire sur une issue que vous surveillez, ou création d'une issue, ou quelqu'un qui vous assigne à une issue...) : ![capture du 2016-12-03 10 41 23](https://cloud.githubusercontent.com/assets/23707217/20858426/3720dbb8-b945-11e6-8fbd-b77393cabb07.png)

À retrouver sur la FAQ : #19

**Comment by desintoxiquezvous** [comment]
@LucileDT merci
@LVAI si vous avez une webcam incorporée vous pouvez vous servir de celle ci, elle est reconnue normalement par le système de reconnaissance vocale mais le résultat est moins bon qu'avec un micro externe (il faut se mettre près de l'ecran pour éviter les bruits parasites) il faut également bien régler la sensibilité du niveau d'entrée son de l'ordi à 0db (sur le mac c'est dans paramètres système /sons, sur PC je ne sais pas )

**Comment by Albapringe** [comment]
Aucun volontaire pour faire la dernière relecture pour clore cette issue ? La RDLS a été publiée depuis plusieurs jours, maintenant. En théorie, les retouches devraient être mineures.

**Comment by LVAI** [comment]
Moi je peux le faire

**Comment by Albapringe** [comment]
Merci à toi @LVAI ! Déjà que tu es bien chargée par ailleurs :)

**Comment by LVAI** [comment]
Je vois pas de quoi tu parles :rofl:

**Comment by LVAI** [comment]
Bon les enfants j'ai pas pu avancer beaucoup. J'ai fait la relecture jusqu'à 11:12.4.
Le texte est de très bonne qualité ! 
J'ai pas encore fait la vérification de la synchro.

Vous pouvez continuez si vous avez du temps, sinon je m'y remets dès que je peux !

**Comment by LVAI** [comment]
Bon les enfants je suis fatiguée je crois mais je ris toute seule en relisant quand je tombe sur "j'étais vraiment vidé, je ne suis pas allé au pot.".
Comment c'est puéril ? Oui mais j'assume ! Et pis je suis fatiguée j'ai dit :rofl:
Ah en tout cas j'ai bien ris !
Et bien sûr juste après "J'aime bien, d'habitude, après". J'ai re-ris :rofl: 
Voilà, voilà...

**Comment by LVAI** [comment]
Hop j'ai fini la relecture : orthographe, ponctuation.
Demain je fais le calage sur le son et j'approuve.

**Comment by LVAI** [comment]
Voilà relecture, correction + vérif de la synchro des sous-titres terminées.
J'ai mis à jour certains bloc de sous-titres pour améliorer un peu le découpage quand il respectait mal - à mon sens - le rythme de la phrase.

Par exemple : [8:04.0] "aussi gaspillant jusqu'à l'absurde, hein, que celui que nous avons sous les yeux avec cet abus permanent, constant, du recours à l'énergie"  + "électrique, parce que dans notre pays, c'est la part la plus importante de la source d'énergie, compte tenu du fait que, comme on y a développé un parc nucléaire". J'ai remis "électrique" dans le bloc précédent pour ne pas couper le groupe nominal.

Je m'assure bien entendu que la synchro reste bonne après modif. Et j'essaye qu'on reste dans une longueur de sous-titre entre 1 ligne et demi (pour avoir du volume à lire) et 3 lignes (pour que ce ne soit pas trop dense).

J'ai aussi découpé les blocs au moment de la présentation des livres pour que les sous-titres ne prennent pas trop de place et qu'on voit bien les couvertures.

Je vais voir pour créer un post de discussion sur le découpage des sous-titres :) chacun fait comme il veut mais on peut se donner des grandes lignes de conduite comme pour la méthodologie de travail, des conseils.

En tout cas vraiment vous avez fait du super boulot sur cette vidéo ! Je suis impressionnée. C'est vraiment de la qualité ! Bravo.

Par contre ce qui est bizarre c'est qu'au début j'avais les boutons "non terminé" et "valider" et maintenant je suis revenue à "enregistrer pour examen". J'ai enregistré... Mais c'est bizarre, non ?

**Comment by Bentham** [comment]
Ho je n'avais pas vu qu'elle n'avait pas été terminée celle ci !

Je fais la dernière correction en vitesse.

**Comment by Bentham** [comment]
C'est tout bon pour le Chonchon !

**Comment by Bentham** [comment]
Il faudra une dernière petite main pour valider apparemment. Vous pouvez le faire sans vérifier, tout est bon.

**Comment by Albapringe** [comment]
Done. Merci @Bentham :)
