### ISSUE TITLE
[Subtitles] [FR] "COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ?" 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#161]
# Video title
COMMENT FINANCER LE REMBOURSEMENT À 100% DES SOINS DE SANTÉ PRESCRITS ? 

# URL
https://youtu.be/p4WrCjgCbaA

# Youtube subtitles language
FRANÇAIS

# Duration
4'36

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=watch&action_mde_edit_form=1&ui=hd&v=p4WrCjgCbaA&ref=wt&lang=fr&tab=captions

**Comment by LucileDT** [comment]
Pourriez-vous utiliser le modèle fourni ici : #1 ?

**Comment by Goutte** [comment]
J'ai revu la vidéo. Certains sous-titres s'étalent sur quatre lignes, ce qui fait un beaucoup, et certains sont coupés à des endroits improbables, mais c'est mineur.
