### ISSUE TITLE
MÉLENCHON - «IL Y A UN INTÉRÊT GÉNÉRAL HUMAIN» 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#162]
Je retrouve pas une issue ici la dessus ....

https://youtu.be/jj1_Ow5jrlo

Ce sera finit au plus tard demain midi . C'est sous titré reste l'hoorthographe

**Comment by LucileDT** [comment]
@quidam34 pourriez-vous prendre le temps de lire la documentation ou comptez-vous continuer à vous éparpiller partout de cette manière ?

**Comment by quidam34** [comment]
cette vidéo et chez vous ou pas ?

**Comment by Goutte** [comment]
La vidéo est déjà référencée ici #82 

Je l'ai trouvée en cherchant _"général humain"_ dans la recherche des issues.
