### ISSUE TITLE
[subtitles] [en] AU FIL DE LA FRANCE - 1000 POINTS DE DIFFUSION DU PROGAMME : MERCI !

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#164]
# Video title
AU FIL DE LA FRANCE - 1000 POINTS DE DIFFUSION DU PROGAMME : MERCI !

# URL
https://www.youtube.com/watch?v=l6xhk9ltlCE

# Youtube subtitles language
Langue des sous-titres (Anglais)

# Duration
2:36
# Subtitles URL
https://www.youtube.com/timedtext_video?ref=player&v=l6xhk9ltlCE

**Comment by Goutte** [comment]
À 1:39 le sous-titre est décalé. (trop en avance, trop court, il devrait commencer à 1:43 et finir à 1:52)
Je ne peux pas changer ça, et ça doit certainement être le cas en français aussi.
La traduction dans l'ensemble est tout à fait correcte, je me suis permis quelques changements pour fluidifier la lecture et faire une traduction moins littérale, mais trois fois rien.

**Comment by fkevv** [comment]
Très bien, je m'en occupe aux alentours de 18h30. Une question au passage, vaut-il mieux traduire phrase par phrase le plus précisément possible, ou alors les exprimer autrement mais de manière plus compréhensible en gardant le sens de la phrase?

**Comment by Goutte** [comment]
Je suis partisan d'une traduction la plus littéraire possible (par opposition à une traduction littérale, au mot-à-mot). En essayant de garder le ton "bon enfant" de JLM, cela va de soi.

**Comment by Flupignon** [comment]
@FROISSARTKevin la traduction précise n'existe pas ! Il faut se détacher des structures du français pour les restituer dans des structures anglaises, sinon les anglophones n'y comprendront rien. J'ai relu ta trad de l'issue #158. Regarde les modifs que j'ai apportées (je ne prétends pas avoir fait la meilleure trad du monde, mais c'est plus compréhensible pour un anglophone je pense). D'ailleurs il faut relire cette issue.

@Goutte +1

**Comment by fkevv** [comment]
Merci pour la correction, possible de citer un passage (si possible) pour que je visualise mieux le genre de propos a modifier?

**Comment by fkevv** [comment]
ok j'ai compris, une écriture plus littéraire, plus relâché.

**Comment by FROISSARTKevin** [comment]
@Goutte Il se trouve que ne sait pas comment changer l'emplacement des sous titres, quelqu'un pourrait les modifier?

**Comment by ladoamy** [comment]
elle n'est pas encore approuvee cette video?

**Comment by Irish39** [comment]
Salut les gens,
bon, je ne sais pas si j'ai bien fait. Première contribution: j'ai effectué une deuxième relecture de ce vidéo. Quelques trucs à modifier pour que cela soit compréhensible par un anglophone. J'ai "approuvé" le vidéo. J'espère que c'est comme ça qu'il faut faire. Si je comprend bien maintenant il faut le déplacer dans la 4'ème colonne... J'y vais.
