### ISSUE TITLE
[subtitles] [eng] Les 10 premières mesures de Mélenchon à l'Élysée

### ISSUE THREAD

**Issue by JeremyRJMR** [jlm2017/jlm-video-subtitles#165]
# Video title
Les 10 premières mesures de Mélenchon à l'Élysée

# URL
https://www.youtube.com/watch?v=brJu7qMJdVc

# Youtube subtitles language
Anglais

# Duration
6:48

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&lang=en&v=brJu7qMJdVc&ref=player&action_mde_edit_form=1

**Comment by fkevv** [comment]
Bonjours, la vidéo a t-elle déjà été traduite? je n'y est pas accès pour le moment. Si c'est le cas, je m'occupe ce soir de l'écriture/lecture.

**Comment by fkevv** [comment]
pas le temps ce soir malheureusement

**Comment by JeremyRJMR** [comment]
Oui normalement les sous-titres sont ecrits et accessible via l'interface de youtube.

Je les joins ici au cas ou ca ne passe pas sur youtube. Indiquez moi si j'ai rate quelque chose au niveau du partage sur youtube pour les prochaines fois (je demarre au niveau du travail collaboratif, donc pardonnez moi d'etre un peu poussif au debut ;-))

[captions.txt](https://github.com/jlm2017/jlm-video-subtitles/files/742875/captions.txt)

**Comment by LucileDT** [comment]
@JeremyRJMR tu es ajouté aux collaborateurs, il faut que tu acceptes l'invitation et tu pourras changer les labels des issues et les déplacer dans les tableaux de bord :)

Pour ce qui concerne les sous-titres, il faut systématiquement les envoyer à l'aide du bouton bleu en haut à droite, au dessus de la zone dans laquelle on voit la vidéo. Si ce n'est pas fait, les autres rédacteurs ne pourront pas voir le travail déjà effectué ;)

**Comment by fkevv** [comment]
Bonjour, quelque fautes de frappe, rien de bien méchant; la correction a été faites ;)

**Comment by Flupignon** [comment]
Je m'y mets. Attention Kevin, en anglais, contrairement au français, il n'y a pas d'espace avant une ponctuation double (! / ? / : / ;).

**Comment by JeremyRJMR** [comment]
Effectivement, merci pour ce rappel. C'est une faute que je fais regulierement en anglais, je ferai attention la prochaine fois ;-)

**Comment by Flupignon** [comment]
Aufait @JeremyRJMR, tu utilise quels outils pour traduire ?

**Comment by JeremyRJMR** [comment]
Comment ca ? Juste l'interface de youtube et wordreference.com quand je butte sur un mot.
Apres au niveau du contenu, j'ai choisi de traduire de facon assez litterale car j'ai remarque que inevitablement quand on commence a s'eloigner du texte original, on a tendance a adapter en fonction de sa propre interpretation. Pas facile de ne pas travestir les propos.

**Comment by Flupignon** [comment]
Oui mais quand c'est trop littéral, ça finit par ne pas vouloir dire grand chose... Il faut savoir que les dictionnaire de type wordreference ou reverso sont collaboratifs et qu'ils ne sont pas toujours très fiables. Ils ont ceci dit quelques bons côtés : il y a bcp plus d'entrées qu'un dictionnaire bilingue classique (larousse...). 

Dans le même genre, j'utilise aussi un site qui s'appelle linguee. C'est une base de données de traductions qui utilise des sites bilingues (sites de l'UE, du gouvernement canadien, de l'unesco...). Là encore, les traductions ne sont pas toujours terribles, mais ça peut donner des idées. Quand on tique sur une traduction qui a l'air trop franchouillarde, il ne faut pas hésiter à utiliser des dictionnaires unilingues anglais (oxford, merriam webster, cambridge) et des dictionnaires de synonymes en anglais, ça aide beaucoup quand on bloque pour reformuler une phrase.

Enfin, pour des phrases idiomatiques, faire une recherche internet accompagné du mot "idiom" permet souvent de faire de bonnes trouvailles. 
>Par exemple, dans cette vidéo, tu as traduit "considérer comme acquis" par "consider as an acquired thing" qui sonne bizarre en anglais. Si tu fais une recherche "considéré comme acquis" dans linguee, une expression revient souvent "take(n) for granted"
>>Comme linguee n'est pas complètement fiable, tu fais une recherche "taken for granted idiom" avec google (j'ajoute souvent "-linguee" pour éliminer les résultats de recherche linguee qui viendront souvent en premier) et là, tu tombes sur des entrées idiomatiques de dictionnaires en anglais, ce qui te permet de confirmer ou non qu'une expression existe bien dans la langue cible.

C'est une façon de travailler parmi d'autres, mais elle marche pas mal.

**Comment by Flupignon** [comment]
Je vous laisse aussi un lien avec des procédés de base en traduction à connaître. Ils permettent de fluidifier certaines formulations :

https://fr.wikibooks.org/wiki/Proc%C3%A9d%C3%A9s_de_traduction_de_l'anglais_en_fran%C3%A7ais

**Comment by Flupignon** [comment]
Fait jusqu'à 5:00. Bientôt fini.

**Comment by Flupignon** [comment]
Il reste 2 / 3 phrases à la fin mais je suis crevé.

**Comment by Flupignon** [comment]
C'est bon pour cette vidéo, mais comme j'ai fait des modifs, il faut une dernière approbation.
