### ISSUE TITLE
Comment je peux changer le label ?

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#166]
Comment je peux changer le label ?

**Comment by domi41** [comment]
Vous ne pouvez pas. Vous ne pourrez pas tant que vous continuerez à vous comporter comme un enfant gâté, irresponsable et toxique.

**Comment by quidam34** [comment]
Vous le prenez comme cela ? dans ce cas mon équipe bosse de son coté et le travail sera donc fait deux fois.... mais je vous informe que correction, pour nous,  se fait sur les fichiers .sbv  donc quand nous avons finit,  j'upload la totalité des sous titres et je remplace ceux en place.... on a pas finit de faire le travail en deux fois !  De plus je vous fait remarqué que c'est ce que je fais depuis un moment d'indiqué ou j'en suis .... mais que pour autant les labels ne sont pas changés  ! !!

**Comment by Goutte** [comment]
@domi41 Du calme !
@quidam34 Des menaces de terrorisme ? Sérieusement ?

> c'est ce que je fais depuis un moment d'indiqué ou j'en suis .... mais que pour autant les labels ne sont pas changés !

Pouvez-vous m'indiquer de quelles issues et commentaires vous parlez ?

**Comment by quidam34** [comment]
J'ai 56 ans il me parle pas comme un gosse ok .....   j'invite à voir le boulot sur le forum que j'ai créer en francais de a a z ou tout le monde est responsable de l'équivalent des labels ici . Bref un fonctionnement bien plus en adéquation à l'idée politique de jlm .... 

> "Pouvez-vous m'indiquer de quelles issues et commentaires vous parlez ?" 

 ben le mieux c'est que je les changes moi ! tout le monde gagnera du temps !

**Comment by quidam34** [comment]
ps : travailler en parallèle ok, mais pas en freinant le travail qu'on fait sur notre forum.

**Comment by Bentham** [comment]
Libre à vous de traiter les vidéos les plus anciennes, comme je vous l'ai indiqué. Nous serons très heureux de les voir avancées. Nous nous occuperons seulement des nouvelles vidéos,  de notre côté, et de celles qui sont en cours ici. De cette façon tout le monde est gagnant et personne ne se marche sur les pieds. C'est bon pour vous ?

**Comment by domi41** [comment]
Si vous ne voulez pas qu'on vous parle comme à un enfant, ne vous comportez pas en tant que tel ! Sur Internet, l'âge physique n'a aucune importance, seul l'âge mental compte.

**Comment by quidam34** [comment]
je crois que plus on avance dans la campagne et plus les vidéos à sous-titrer vont devenir nombreuses  ! Je ne vois pas bien l'intérêt dans ce cas d'aller perdre du temps sur des vidéos qui n'intéressent plus  trop personne pour l'instant ! l'important et l'urgence n'est pas là  !  Je n'ai pas perdu vos deux adresses elle se trouve  dans le forum intitulé "sous-titrage à faire de sujet plus ancien et moins pressant donc...."  Par contre petite information ; j'ai 8 heures par jour à consacrer à ce travail et environ  6 jours sur 7 . (bien que je travaille si si j'y arrive lol) Perso, mon point faible la correction orthographique .

**Comment by quidam34** [comment]
mon age mental va bien merci !

**Comment by Bentham** [comment]
Le problème, c'est que c'est la correction orthographique qui est le point le plus difficile et qui demande le plus de coopération. Rentrer le texte non-corrigé est un processus assez rapide (il suffit d'utiliser la reconnaissance vocale), ce n'est donc pas le problème.

Je comprends que vous ayez envie de vous rendre utile, et je respecte ce désir. Mais vous voyez qu'ici notre équipe comprend au total 23 personnes, et que vous 3 sur le forum avez tendance à bloquer le travail de tout le monde. Il serait plus facile de montrer à vos collaborateurs comment fonctionne ce github et qu'ils puissent migrer ici (je peux faire une vidéo pour expliquer le fonctionnement).

A vous de voir si vous êtes capable d'abandonner votre rôle de chef de troupe - auquel vous semblez tenir, ce que je comprends fort bien - pour endosser l'humble rôle d'un collaborateur anonyme.

**Comment by quidam34** [comment]
> il suffit d'utiliser la reconnaissance vocale

désolé de ne pas partager votre avis.... mes sous titreuses sont unanimes  la reconnaissance vocal ne leur fait pas gagner du temps et plutôt le contraire et je partage leur avis. 
J'ai déjà expliqué ! je ne participe pas sur un site dont les labels sont en anglais ainsi que tous les menus, la complexité du site a de quoi en faire fuir plus d'un  ! avez vous fait un recensement de ceux qui sont venu et repartit ? Leurs avez-vous demandé pourquoi il ne sont pas restés ? ?  Oui vous allez me dire "c'est une question d'habitude" sauf que beaucoup doivent abandonner en chemin parce que l'habitude est trop longue à prendre ici et l'anglais ne rebute pas que moi !  !!! Vous imaginez que j'avais 4 onglets de traduction google ouvert tout le temps dans mon navigateur pour traduire vos labels !. Venez donc vous en rendre compte sur le forum et faite la différence !  23 personnes ? pouvez me dire combien dans les 12 dernières heures ?  Perso je ne m'attaquerais jamais au sous titrage Anglais ni a la langue des signes ... Le forum c'est trois personnes mais tous les jours. Et puis il suffit de nous réserver des vidéos surtout qu'on est capable de travailler a trois en même temps pour coller à l'actualité ... J'imagine que voir le sous titrage finit 15 jours après la sortie de la vidéo c'est perdre de l'audience sur cette vidéo.... C'est passé, sourd ou pas on passe a autre chose.   Bon alors nous revoilà à la case départ .. J'aimerais pourvoir changer les labels.

**Comment by LucileDT** [comment]
Bonjour, 
@quidam34 l'argument de l'âge ne sert à rien ici. Vous faites preuve d'une mauvaise volonté crasse, c'est pénible à voir. J'ai pris des heures à rédiger une documentation précise, **vous devez la lire** avant de dire que tout est incompréhensible. Elle se trouve ici : https://github.com/jlm2017/jlm-video-subtitles

De plus :
# Pour changer les labels
Je vous ai déjà répondu plusieurs fois, mais je vais le refaire : vous **devez accepter l'invitation** que vous avez reçu par mail, ou en cliquant ici : https://github.com/jlm2017/jlm-video-subtitles/invitations

Merci.

**Comment by quidam34** [comment]
merci lucille. j'vais pas dans cette boite créer pour l'occasion.

**Comment by LucileDT** [comment]
Un grand hourra pour quidam qui peut enfin changer les labels !

**Comment by LucileDT** [comment]
De plus, vous pouvez activer le système de notifications directement sur l'interface Github avec la méthode suivante :
> - Connectez-vous à Github
> - Cliquez sur votre avatar et sélectionnez Settings
> - Dans la colonne de gauche, cliquez sur Notifications
> - Dans le cadre "How you receive notifications", activez les cases :
>   - Automatically watch repositories
>   - Participating Web
>   - Watching Web
> 
> Vous pouvez activer ou désactiver les notifications par mail à votre convenance (pour ma part, je les garde active et j'applique un filtre dans ma boîte mail pour les mettre directement dans un dossier).
> 
> Quand vous actualiserez la page, vous verrez apparaître une petite cloche en haut à droite : ![capture du 2016-12-03 10 41 51](https://cloud.githubusercontent.com/assets/23707217/20858425/34fe478a-b945-11e6-8c02-856afdd743c7.png)
> 
> 
> 
> 
> Il y aura une petite pastille bleue dessus si vous avez des notifications (par exemple, nouveau commentaire sur une issue que vous surveillez, ou création d'une issue, ou quelqu'un qui vous assigne à une issue...) : ![capture du 2016-12-03 10 41 23](https://cloud.githubusercontent.com/assets/23707217/20858426/3720dbb8-b945-11e6-8fbd-b77393cabb07.png)

À retrouver sur la FAQ : #19
