### ISSUE TITLE
Question : à partir de quand les sous tritres sont-ils publié?

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#168]
Bonjour, je me demandais à partir de quand les sous titres étaient publiés et par qui. Voici par exemple une vidéo approuvé, revu 2 fois, mais elle n'a pas l'air mise en ligne : https://github.com/jlm2017/jlm-video-subtitles/issues/101 Voilà, je voulais juste savoir comment ça marche :).

**Comment by Flupignon** [comment]
Normalement après approbation par 2 personnes, ça devrait être bon (après si des modifs ont été effectuées, il en faut peut-être une troisième)

**Comment by fkevv** [comment]
ok merci :)

**Comment by LucileDT** [comment]
En général, une personne vérifie que les sous-titres sont bien en ligne et ferme l'issue correspondante, si c'est le cas. On met plus ou moins longtemps à sortir des sous-titres, ceci dit.
Il nous est arrivé un cas extrême où suite à un bug, nous avons mis un mois avant que nos sous-titres soient validés.
