### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - POUR UNE SÉCURITÉ SOCIALE DU LOGEMENT

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#170]
# Video title
MÉLENCHON - POUR UNE SÉCURITÉ SOCIALE DU LOGEMENT

# URL
https://www.youtube.com/watch?v=Bf0vb6mJTjg&t=5s

# Youtube subtitles language
Français

# Duration
30:42

# Subtitles URL
https://www.youtube.com/timedtext_editor?forceedit=captions&tab=captions&bl=vmp&ref=player&action_mde_edit_form=1&lang=fr&v=Bf0vb6mJTjg

**Comment by Albapringe** [comment]
Je suis parti.

**Comment by Albapringe** [comment]
Pause à 7:56.

**Comment by desintoxiquezvous** [comment]
#170 @Albapringe @quidam34 pourquoi cette issue est dans la colonne "prêt pour correction 2 en cours " alors qu'apparemment elle est en cours de rédaction arrêtée a 7:56  ? 
difficile a suivre ....

**Comment by Albapringe** [comment]
Le changement de label est inapproprié. Je ne sais pas ce qu'a fait quidam. Je corrige.

**Comment by Albapringe** [comment]
Reprise.

**Comment by desintoxiquezvous** [comment]
attends !  je suis dessus en ce moment, c.est truffé d'erreurs à partir de la min 40 il y a eu des copier coller inappropriés et 1 conteneur sur 3 n'est plus à sa place c'est une vrai galère , je suis arrivé à 52 mn 
je te tiens au courant

**Comment by Albapringe** [comment]
On ne parle visiblement pas de la même vidéo, car la mienne s'arrête à 30:42.

**Comment by desintoxiquezvous** [comment]
excuse moi je te réponds sur la tablette , et je n'avais pas vu qu'on est pas sur le même film je suis en réalité sur pas vu à la télé #8 "la pauvreté "qui est en relecture finale et qui en réalité est truffé d'erreurs  comme je te le disais précédemment 
continue de ton côté , je te contacterais à la fin concernant mon travail actuel

**Comment by desintoxiquezvous** [comment]
effectivement je viens de te répondre , concernant ma vidéo "pas vu à à la télé #8" elle est actuellement au stade 5 donc je l'ai prise pour relecture finale ,et comme je te le disais elle est truffée d'erreurs à partir de 42 (containers pas à leur place ou mauvais textes, il y a du avoir des copier coller foireux) donc je retouche , 
ce qui m'inquiete c'est que comme s'en était au stade relecture finale Youtube ne me donne le choix d'envoi que "non termine" ou "approuver" or suite à mes retouches il faudrait peut être une nouvelle relecture car apparemment la 1 ere relecture n'a pas été faite du tout , le statut n'était donc pas à la bonne place
que dois je faire , si je l'envois "approuver" est ce qu'elle est encore modifiable ensuite, ou pas ? 
si j'envoie "non termine" est ce que mes modifs seront enregistrées ou pas afin de remettre le statut en lecture 
help!

**Comment by Albapringe** [comment]
Tu approuveras et tu demandes une nouvelle lecture en commentaire, même si les sous-titres sont publiés. Mais ce serait bien d'exposer ce problème sur l'issue du PVTV 8, plutôt que sur cette issue.

**Comment by desintoxiquezvous** [comment]
exact, mais bentham vient de me contacter , je vois avec lui 
merci

**Comment by Albapringe** [comment]
Pause à 17:04

**Comment by desintoxiquezvous** [comment]
@Albapringe 
Si ça peut t'aider, voilà le texte en pdf de la min 20 à la minute 20:52
[Pour une SS logement 20 à 25_52min.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/748646/Pour.une.SS.logement.20.a.25_52min.pdf)

**Comment by Albapringe** [comment]
Allez, je reprends. Merci à toi, @desintoxiquezvous, ton texte me sera très utile :)

**Comment by desintoxiquezvous** [comment]
je pense que c'est une bonne méthode si on se met d'accord, le premier rédacteur travaille par exemple en direct sur une partie du texte, un autre propose de lui faire une partie plus loin en offline  et lui envoie le texte un peu plus tard en pdf. ( le premier rédacteur pouvant lancer lui même une demande à la communauté sur une partie de texte qui l'intéresserait ) le texte envoyé devrait déjà être corrigé un maximum pour éviter trop de retouche dans les containers 
cette méthode n'est à conseiller si le 1er rédacteur ne tape pas le texte directement dans les containers mais préfère récupérer un texte long (5,10 mn) et le découper en dynamique suivant ma méthode #171 
https://youtu.be/JcU7XDS-BSM
ceci éviterais les dysfonctionnements quand 2 personnes tentent de travailler en même temps sur la même Issue 

c'est une méthode parmi d'autre qui, bien sûr, peut ne pas convenir à tous les sous titreurs mais qui peut, peut-être en aider quelques uns....
à suivre ...

**Comment by Albapringe** [comment]
Terminé pour le sous-titrage, prêt pour relecture. A noter qu'il y a ici où là des passages que je n'ai pas compris, annotés par [???] à compléter. 
Perso, je suis preneur de la méthode que tu proposes, @desintoxiquezvous, ça permet d'aller quand même plus vite. Pour ma part, je ferai un appel (via commentaire) à une contribution de ce type à chaque fois que j'aurai une nouvelle vidéo à sous-titrer, si de bonnes âmes sont prêtes à le faire à ce moment-là.

**Comment by desintoxiquezvous** [comment]
oui, ça peut gagner du temps, on fera appel aux bonnes volontés ..
perso je suis absent 8 jours mais après pas de pb pour aider .....

**Comment by Vimogo** [comment]
C'est bon pour la première.

**Comment by obilya** [comment]
Pourquoi cette vidéo est dans Ready for 1st review en anglais alors que le label est French et que le surtitrage a vraiment l'air d'être en français ? Il faut l'enlever d'ici, non ?

**Comment by LucileDT** [comment]
Tu as tout à fait raison, j'avais d^u faire une fausse manip :/ Merci !

**Comment by houlenn** [comment]
Je pars pour la deuxième relecture !

**Comment by houlenn** [comment]
Sous-titres en ligne, je ferme !
