### ISSUE TITLE
[subtitles] [en] MONSIEUR HAMON, CHOISISSEZ !

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#172]
# Video title
MONSIEUR HAMON, CHOISISSEZ !

# URL
https://www.youtube.com/watch?v=tQIsWprmxDA&t=

# Youtube subtitles language
Langue des sous-titres (Anglais)

# Duration
10:44

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=en&action_mde_edit_form=1&ref=player&tab=captions&v=tQIsWprmxDA&bl=vmp&ui=hd

**Comment by fkevv** [comment]
Soirée mouvementé, je continue demain ;) 0:00 -> 2:30

**Comment by fkevv** [comment]
Bonjour, je ne comprend pas la phrase a 5:27->5:36 quelqu’un pour m'aider svp :) ?

**Comment by fkevv** [comment]
5:38, je m'arrête là pour ce matin, je continue ce soir.

**Comment by Goutte** [comment]
> How do you want to repeal every brutality that Bruno Leroux, the president of the PS exprecienced [...]

Je propose quelque chose du genre (plus dans l'esprit de ce que JLM essaye de dire, selon moi) :

> How do you expect to fight back the bullying of the president of the PS Bruno Leroux, [...]

Je n'ai rien changé dans l'éditeur, je te laisse juger ;)

**Comment by fkevv** [comment]
@Goutte Ah ok, j'avais juste pas compris le sens en français :)
How do you expect to fight back the bullying of the PS president Bruno Leroux, [...] Merci

**Comment by fkevv** [comment]
quelqu'un a continué jusque 8:40, je fini ce soir

**Comment by ladoamy** [comment]
Hello

je voudrais contribuer a la traduction de cette video. mais je n'ose pas encore faire des modifications/rajouts avant de vous consulter. Quelle est la régle générale? Je previens dans ce chat avant de modifier quoi que ce soit? je demande l'avis de tout le monde? 
quelles sont les differentes etapes? combien de relectures y aura t il? se font elles à la toute fin?

**Comment by Flupignon** [comment]
Bonjour @ladoamy et bienvenue ! Nous n'avons pas vraiment de méthode rigoureuse car nos disponibilités et nos capacités ne sont pas les mêmes. Tout dépend aussi de ton niveau. Personnellement je me permets souvent de faire des modifications car j'ai fait des études de traduction et suis rompu à cet exercice qui nécessite des techniques bien particulières (@Blange1  a aussi l'air d'être habitué à traduire mais est moins disponible en ce moment). Une traduction amateur est cependant une bonne base de travail pour un premier jet.

**Comment by fkevv** [comment]
@ladoamy Salut, premièrement nous écrivons les traductions, ensuite elles sont relue par deux personnes différentes puis envoyée. Si tu souhaite comment la traduction d'une vidéo qui n'a pas encore été traduite, il te suffit de créer un nouvelle "Issue" et de suivre le modèle ci joint: https://github.com/jlm2017/jlm-video-subtitles/issues/1 Ensuite il faut que quelqu'un t’envoie une invitation pour que tu es le rôle de collaborateur et pour pouvoir avoir la possibilité de mettre des "labels" Tu comprendra rapidement de quoi il s'agit en les voyant. Si tu souhaite vérifier une vidéo déjà traduite, le plus simple est d'aller dans "projects" et de regarder dans les différentes colonnes les vidéos qui t’intéresse. Voilà, si t'a des questions n'hésite pas . Tu peux aussi m'ajouter sur Discord si tu y es: Traducteur Insoumis φ#2706

**Comment by Goutte** [comment]
La [version française de ces sous-titres](https://github.com/jlm2017/jlm-video-subtitles/blob/master/subtitles/2017/2017-02-01.monsieur-hamon-choisissez.fr.af2QQs5HoUljCTDebz5OXB1An6p-FE9S.sbv#L233) est coupée un peu n'importe comment.

Elle contient aussi quelques coquilles.

Je ne la trouve pas dans les issues ?

**Comment by LucileDT** [comment]
@ladoamy Bienvenue ! Tu peux aussi consulter la faq ici : #19

**Comment by obilya** [comment]
J'ai fait la 1ère relecture jusqu'à 1:20.

**Comment by Goutte** [comment]
Une autre relecture jusqu'à 3:14

**Comment by LucileDT** [comment]
@Goutte désolée, je n'avais pas vu ton commentaire : si nous n'avons pas d'issue qui va avec, c'est que ce sont d'autres personnes que nous qui s'en sont chargées (peut-être quidam, ou des indépendants).

**Comment by obilya** [comment]
Continué la 1ère relecture jusqu'à 3:59:6

**Comment by obilya** [comment]
J'ai un problème : j'ai fait des corrections mais c'est la version d'avant ces corrections qui s'affiche quand je clique sur "modifier". La première phrase dans la version la plus récente était "Hello. I come before you..." alors que dans l'ancienne c'était "Hello, I present myself...". Est-ce que c'est pareil pour vous ? Si la dernière version est perdue, ça veut dire qu'il faut refaire toute la 1ère relecture ?

**Comment by obilya** [comment]
Je crois que j'ai compris pourquoi ça fait ça, c'est parce que comme j'ai fait "enregistrer" ma version, YouTube attend que quelqu'un d'autre ait vérifié ce que j'ai fait avant de le rendre visible même à cet endroit-là. C'est possible que ce soit ça ?

**Comment by Goutte** [comment]
Je ne vois pas ta nouvelle version, même quand je lance l'éditeur.
Tu as édité des sous-titres qui étaient déjà soumis, c'est ça ? Je ne sais pas ce qu'il se passe.

Si tu veux, je peux réessayer tout à lheure (ou demain).

**Comment by Goutte** [comment]
Tu vas rire, en lançant l'éditeur avec un autre navigateur, et un autre compte google, je vois _"I express myself"_.

Il est possible que nous soyons entrés dans l'enfer des contributions chevauchées.
Les modifications que j'avais apportées n'ont jamais été validées, et tu as commencé à faire des modifications par-dessus. Qui sait ce qu'il va se passer ?

Essaye de lancer l'éditeur avec un autre compte google, si tu peux, et dis-nous ce qu'il se passe pour toi ! C'est une bonne occasion d'enquêter pour comprendre ce qu'il se passe !

**Comment by obilya** [comment]
Ahah....eh bien avec un autre compte google, j'ai "Hello, I present myself" quand j'arrive sur la page, et quand je clique sur modifier "I express myself". Au secouuuuuurs

**Comment by Goutte** [comment]
Essaye "Looks Good" avec ton deuxième compte. On va voir si ta contribution est dans une espèce de "file d'attente" ?

**Comment by obilya** [comment]
Comment ça ? Que j'écrive "looks good" au début de la vidéo ?

**Comment by Goutte** [comment]
Non non non, pardon je ne suis pas clair ; quand je lance l'éditeur, il me propose un bouton bleu "Looks Good", qui doit se traduire par "Ça m'a l'air bon", je ne sais pas exactement ce que Youtube a mis.

**Comment by obilya** [comment]
J'ai cliqué sur le bouton bleu avec la version "Hello. I come before you"

**Comment by Goutte** [comment]
Je vois toujours "I present myself". Je ne sais plus trop quoi en penser...

**Comment by obilya** [comment]
En fait, You Tube ne prend plus en compte mes mises à jour sur cette page. Mon brouillon est bien sauvegardé mais j'ai beau le renvoyer, il me dit que la communauté a travaillé sur la traduction depuis que j'ai posté ma version. Donc j'ai l'impression que moi je ne peux rien faire sur cette vidéo. Quelqu'un d'autre veut essayer ?

**Comment by Goutte** [comment]
Peux-tu nous faire passer le fichier de brouillon, qu'on essaye ?

Youtube vient de me débloquer l'accès à la traduction du titre de la vidéo, chose qui était verrouillée auparavant. Peut-être y a-t-il une hierarchie cachée ?

**Comment by obilya** [comment]
GitHub me dit qu'il n'accepte pas mon fichier .sbv qui contient ma dernière version, est-ce que je peux l'envoyer par mail à quelqu'un sinon ?

**Comment by Goutte** [comment]
@obilya Envoie-moi un email ([edited])

**Comment by Goutte** [comment]
J'ai mis ton fichier en ligne. A vous de me dire si ça a fonctionné ou pas !

_Rappel : si oui, ça commencera par "I come before you..." au lieu de "I present myself"._

**Comment by obilya** [comment]
Ca a marché :D dans l'éditeur du moins, mais en fait l'ancienne version ("I present myself") est déjà publiée sur You Tube (c'est pour ça que le sujet a dû être classé par Robot Insoumis). Du coup on continue à travailler sur la traduction ? Moi je pense qu'il vaudrait mieux continuer à relire (il reste encore environ 5 min à faire).

**Comment by Goutte** [comment]
Pas de souci, une fois que tes modifications auront été revues, validées, et publiées, @RobotInsoumis re-téléchargera la nouvelle version pour la mettre ici.

Dis-nous quand tu as fini, je ferai une relecture !

**Comment by obilya** [comment]
super ! j'ai fait jusqu'à 5:14 (since we fought them during many years), je continuerai ce week-end ou bien quelqu'un peut prendre le relais. Ahh ça fait du bien quand ça marche, merci @Goutte ;)

**Comment by obilya** [comment]
Je ne comprends pas pourquoi RobotInsoumis a classé ce sujet, les relectures n'ont pas été faites. Je m'y remets.

**Comment by obilya** [comment]
Prêt pour 2e relecture

**Comment by Goutte** [comment]
J'ai validé !
