### ISSUE TITLE
Salon projet

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#173]
Bonjour, j'aimerai participer aux discussions et organisations des projets, voir m'investir dans quelque chose d'autre, savez-vous à qui je peux m'adresser pour qu'on me permette d’accéder au salon?

**Comment by quidam34** [comment]
Pouvez vous m'expliquer ce que vous voullez dire ? Le salon c'est quoi pour vous ? Le tchat ?

**Comment by fkevv** [comment]
Le salon vocal du Discord, je n'y ai pas accès http://prntscr.com/e3hh3k

**Comment by LucileDT** [comment]
@FROISSARTKevin Salut ! Le Discord n'a pas de lien avec le Github, très peu d'entre nous sont sur les deux plates-formes. Tu as réussi à résoudre ton problème ?
