### ISSUE TITLE
Gagner du temps : faire la correction à partir du fichier .sbv

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#174]
Pour gagner du temps il est possible de faire la correction non pas sur Youtube mais sur le fichier texte de sous-titrage. Une fois le sous-titrage terminé, rendez-vous dans le menu "action"en haute a gauche.Choisir "téléchargé" une fenêtre vous demande soit d'ouvrir le fichier soit de le télécharger. Choisissez de le télécharger. Placez le sur votre disque dur. Perso , je le mets dans un dossier 'sous-titre" sous dossier " au nom de la vidéo par exemple "sécurité sociale integrale.sbv" Ceci afin de ne pas s'emmêler les pinceaux avec d'autres fichiers plus tard, on ne sait jamais. (éviter les accents dans votre titre)  Renommer le suffixe de votre fichier en ".txt" dans mon exemple "securite sociale integrale.txt"  Vous pouvez ainsi l'ouvrir avec votre traitement de texte préféré et précédé à une première correction orthographique par votre logiciel.  Perso je rentre les noms propres dans mon dictionnaire "ajouter au dictionnaire" et vérifie sur le net les mots inconnus au bataillon  (et parfois jlm en invente !  lol) Je les ajoute aussi,  une fois vérifié.

Si vous voulez terminer votre travail prenez soins d'enregistrer votre travail dans le format .txt le plus simple. Pas .doc etc etc... Histoire que tout le monde puisse ouvrir le fichier sur le format le plus simple qui n'embrouillera pas le fichier . Le fichier ressemble à cela. Inutile de vous dire que l'on ne touche pas aux timecodes"

...............
0:00:02.300,0:00:04.560
Le portrait de Jean-Luc Mélenchon avec vous Karine Bécard

0:00:04.560,0:00:05.060
aïe aÏe aïe

0:00:05.960,0:00:07.900
oui, vous avez raison de dire aïe aïe 
...............
Comment se partager le fichier ? D'abord, il faut savoir que sur le forum nous avons la possibilité d'ajouter des pièces jointes à nos messages . Donc voici comment nous organisons notre tâche : **a)** Je m'occupe de rapatrier les fichier .sbv" , je fais la correction orthographique via mon logiciel (ça c'est vite fait! )  
**b)** J'édite le sujet d'origine qui concerne la vidéo et j'ajoute la pièce jointe. 
**c)** Je change l'attribut du titre du sujet en "Vérification texte 1 à faire" (l'équivalent de vos labels mais, en Français) 
**d)** La personne qui décide de faire la première correction peut changer l'attribut du sujet d'origine en " 1er correction Françoise" par exemple . Nota : Chaque sous-titreur à la permission d'édition ce qui est super pratique.
**e)** Une ne fois corriger il lui suffit d'uploader le fichier .txt en répondant dans le sujet. 
Une deuxième correctrice prend le relais ! 
**f)** Une fois corrigé une deuxième fois,  il lui suffit d'uploader le fichier .txt en répondant dans le sujet avec la pièce jointe. Une deuxième correctrice prend le relais ! 
**g)** Une fois récupéré la deuxième pièce jointe, ne pas oublier de remettre le dernier fichier récupéré en .sbv . Sur le forum, c'est moi qui m'occupe d'uploader le fichier sur youtube via "importer un fichier " qui prendra la place des écritures en place (avec le message " Si vous importez un fichier, celui-ci remplacera la piste Français. " de mise en garde. Voilà vous savez tout . 
Évidemment ce boulot se fait sur un ordinateur. De toutes façons comment faire autrement ?

Jm dit "le toxique".

**Comment by desintoxiquezvous** [comment]
@quidam34 @Bentham Ben voila c'est exactement  ce qui c'est passé sur l'issue #91 tout le travail de montage et de correction à été fait hors Youtube, et à la réimportation ça a bugué on ne sait pas pourquoi et PERSONNE n'a vérifié en finale sur Youtube , ce qu'on doit ABSOLUMENT faire , vu que c'est là que tout se passe à la fin

**Comment by quidam34** [comment]
@desintoxiquezvous  @Bentham Absolument pas ! je vérifie ensuite ! Le tout c'est de se mettre tout le monde sur le même mode de travail. Et surtout d'être plus rigoureux sur la gestion de qui fait quoi.... ce qui est impossible dans votre mod de fonctionnement . La manière dont nous fonctionnons sur le forum interdit que l'on se marche sur les pieds !  Et c'est surement ce qui c'est peut-être passé pour le cas qui vous intéresse! Si Youtube propose cela c'est que c'est une possibilité correct . Y compris de faire le sous titrage lui-même ne externe de Youtube.  Pour infos voici comment on se marche pas sur les pieds . "label" en francais , utilisable par tous et adaptable pour chaque membre  :  
![vu forum](https://cloud.githubusercontent.com/assets/25107399/22546967/9edc38cc-e93f-11e6-9f4d-d45f2d6974e7.jpg)

**Comment by desintoxiquezvous** [comment]
je maintiens qu'il y a eu probablement un bug à la réimportation sur Youtube et que ça n'a pas été vérifié en totalité SUR Youtube après la réimportation , j'ai été apparemment le premier à le faire sinon quelqu'un l'ayant réellement relu avant moi aurait fait le même constat: qui aurait foutu ce bordel en décalant, supprimant ou inversant des containers ? ça ne peut venir que d'un pb de time code, ou autre, mal réimporté..
un peu moins de mauvaise foi serait la bienvenue

**Comment by quidam34** [comment]
Pourtant j'ai employé le même procédé sur le vidéo " [FR] MÉLENCHON - Réunion publique au Mans" sans encombre. La vidéo est bien plus longue pourtant ! Quand a " ça ne peut venir que d'un pb de time code, ou autre, mal réimporté.." je vais vérifié le fichier réimporté !  Bref il fallait un coupable c'est moi et mes idées novatrices . Sans preuve formel mais c'est pas grave !   jean-michel le toxique lol !

**Comment by desintoxiquezvous** [comment]
Loin de moi de critiquer le travail fait, le texte est très bien fait, bien synchro etc de même que la correction ( j'ai moi même travaillé sur Mac avec Subtitler de la même façon sur les S/T vf du film Catastroika ) 
En plus quand on travaille en équipe, comme toi, avec des gens tapant vite c'est sûrement mieux.
personnellement, seul, et tapant lentement je préfère la méthode vocale, (c'est juste une info pour aider ceux qui sont comme moi.)

il n'empêche qu'a un moment il y a eu un raté quelque part,et que si on avait juste validé la vidéo (en voyant relecture 1 et 2 faites) on balançait un sous titrage incompréhensible sur les 10 mn finales.

Un bug quelque part ça peut arriver à tout le monde il n'y a pas de quoi faire Kalimero, la preuve j'ai perdu moi même 12 mn de S/T sur l'issue #160, Youtube ne les avait pas pris en compte
c'est pour ça qu'on vérifie et donc je ne sais pas ou s'est produit le problème ,mais c'est arrivé...
je ne suis pas là pour accuser qui que ce soit, j'aurai pu me contenter de t'envoyer un mail en te disant de t'y remettre, mais comme j'en était arrivé à 42 mn sans aucun pb en relecture et que j'ai commencé a voir les incohérences je me suis dit qu'il fallait retoucher la suite et ça m'a pris ... 4h de plus....(je ne suis pas très rapide,comme déjà dit )
Bon, voilà, la leçon à en tirer c'est qu'avant la validation finale il faut tout vérifier sur Youtube, dans la totalité, en temps réel. 
On travaille tous à aider JLM comme on peut, on essaie juste faire ça au mieux ... ;-)

**Comment by LucileDT** [comment]
@quidam34 pourriez-vous nous donner le fichier que vous avez importé ? Pour vérifier. 

Comme le dit @desintoxiquezvous, nous essayons tous ici de travailler du mieux que nous pouvons faire. Tout le monde peut se planter !

**Comment by quidam34** [comment]
bon ben cette méthode de correction n'a pas l'air de vous emballer !  Pourtant en utilisant l'import et l'export cela nous permet actuellement de pouvoir travailler en même temps sur les sous titrages de la même vidéo en même temps ! Comment ? ben devinez !  Comme jlm et son hologramme quoi .... ;-)
