### ISSUE TITLE
No description, website, or topics provided. 

### ISSUE THREAD

**Issue by Goutte** [jlm2017/jlm-video-subtitles#176]
Sur la page d'accueil du github.

Que marquer ici ?

_Initiative citoyenne pour le sous-titrage des vidéos des insoumis._

Postez vos suggestions !

**Comment by LucileDT** [comment]
@Goutte je ne comprends pas la question :/

**Comment by Goutte** [comment]
Sur la page d'accueil de ce dépôt GitHub, il y a une description du dépôt a remplir. Pour l'instant, il n'y en a pas (c'est affiché _No description, website, or topics provided._).

Je peux m'en occuper si tu le souhaites, mais je n'ai pas les permissions !

**Comment by LucileDT** [comment]
Je ne vois pas de quel endroit tu parles, tu pourrais me faire un screenshot ?

**Comment by Goutte** [comment]
![screen](https://cloud.githubusercontent.com/assets/592545/22782395/348455d0-eec7-11e6-8f09-99b9414b7a8f.png)

**Comment by LucileDT** [comment]
Ah effectivement.

Dans ce cas, je trouve que ta proposition est très bien ! Sauf qu'on s'occupe principalement (voire exclusivement) de la chaîne de Jean-Luc Mélenchon :/

**Comment by Goutte** [comment]
> Sauf qu'on s'occupe principalement (voire exclusivement) de la chaîne de Jean-Luc Mélenchon :/

Pas faux. C'est carrément dans le nom du dépôt.

_Initiative citoyenne pour le sous-titrage des vidéos du porte-parole de la France Insoumise._

(héhé)

**Comment by LucileDT** [comment]
Faut voir avec les autres aussi, du style @Bentham, @Albapringe, @desintoxiquezvous, @DevilFishGold, @clement20, @FROISSARTKevin, @Flupignon, @quidam34, @Vimogo, @dalipokim, etc.

**Comment by Bentham** [comment]
"du porte-parole de la France Insoumise", c'est un peu lourdingue comme périphrase !

Je serais plutôt pour quelque chose comme : "Initiative citoyenne pour le sous-titrage des vidéos de la chaîne de Jean-Luc Mélenchon."

Ou alors, pour être complet : 

"Initiative citoyenne pour le sous-titrage des vidéos de la chaîne Youtube de Jean-Luc Mélenchon, porte-parole de la France Insoumise."

**Comment by Vimogo** [comment]
Soyons complets tant qu'à faire. Alors pour la deuxième proposition de @Bentham.

**Comment by desintoxiquezvous** [comment]
D'accord avec la 2ème proposition de @Bentham

**Comment by Goutte** [comment]
Je pense qu'on a un consensus, avec un fort taux d'abstention !
