### ISSUE TITLE
[subtitles] [en] MÉLENCHON : « MON BULLETIN DE VOTE EST UN COUP DE BALAI »

### ISSUE THREAD

**Issue by fkevv** [jlm2017/jlm-video-subtitles#178]
# Video title
MÉLENCHON : « MON BULLETIN DE VOTE EST UN COUP DE BALAI »

# URL
https://www.youtube.com/watch?v=EDC1-D4qYV8

# Youtube subtitles language
Langue des sous-titres (Anglais)

# Duration
7:39

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&v=EDC1-D4qYV8&tab=captions&bl=vmp&ui=hd&lang=en&action_mde_edit_form=1

**Comment by fkevv** [comment]
Un peu fatigué mais j'ai fait 1min donc de 0:00->1:00 je continue demain.

**Comment by fkevv** [comment]
A 1:24, je comprend pas ce que dit la journaliste

**Comment by Bentham** [comment]
Je dirais : "Elle éclabousse, globalement, cette affaire Fillon, tous les parlementaires - vous avez raison. Vous avez vous-même été dix-huit ans sénateur, est-ce que vous avez constaté ces pratiques-là, qui aujourd'hui se retournent contre les politiques ?"

Pour la première phrase, on pourrait simplifier en :  "Cette affaire Fillon éclabousse globalement tous les parlementaires - vous avez raison."

**Comment by fkevv** [comment]
Ok merci ;)

**Comment by fkevv** [comment]
Help a 2:24 comment traduire 'leur dégagisme"
j'ai traduit par "their get-outism" mais bon, qu'est ce que vous en pensez?

**Comment by Flupignon** [comment]
"Hell-with-'emism" ?

**Comment by fkevv** [comment]
Hum, je sais pas trop, "hell" c'est un peu fort non?

**Comment by fkevv** [comment]
Ah oui, "hell with" signifie grossièrement s’en foutre" mais pourquoi l’employer ici

**Comment by FROISSARTKevin** [comment]
Aussi, 2:51 comment on traduit, "second tour", on pourrait second lap/round mais en politique.. pas d'idée

**Comment by fkevv** [comment]
1->3:05

**Comment by Goutte** [comment]
Idées en vrac :

This is going to turn badly => This is going to turn **sour**

If we don't hear the anger of people => If we don't **listen to** the anger of people

_"get-outism"_, je trouve ça bien. Mais il y a peut-être déjà un mot en anglais à cet effet ?

i propose to the assembly to right => I suggest the assembly to **write**

N'oublie pas qu'en anglais `I` est en majuscule !

Quelqu'un connaît le nom de la présentatrice ?

**Comment by Flupignon** [comment]
Anne-Claire Coudray

**Comment by Goutte** [comment]
Quelques notes additionnelles, qui me semblent être de bonne pratique : 

- En début de vidéo, toujours mentionner les noms complets, utiliser des acronymes ensuite.
- _Monsieur_ s'abbrévie `M.`, pas `Mr.` (c'est _Monseigneur_)

J'ai effectué les corrections susmentionnées, ainsi que d'autres.

Continue le bon travail :+1: !

**Comment by Goutte** [comment]
My bad, je dis des bêtises, on est en anglais, _Mister_ c'est bien `Mr`. (les sous-titres français pour cette vidéo font cette erreur, en revanche)

**Comment by fkevv** [comment]
Hahaha, désolé, un peu de fatigue ce soir, merci pour cette première relecture @Goutte bon le "I" j'y pense rarement à l'ordi, mais je vais reprendre l'habitude sans soucis, et Anne-Claire Coudray @Flupignon la présentatrice je suppose? pour Get-out'ism ça me semble bien, mais je pense pas qu'il y est de mot prévu à cet effet. Enfin bon, l'écriture de sous titres me fatigue physiquement et moralement rapidement, je devrai vérifier ma vue, ou bien je ne suis peut être pas le seul. En général je ne fait pas plus de 4min de traduction (en vidéo j'entend bien) Et pour l’anecdote, je suis en 1eS j'ai un niveau B2 confirmé en espérant avoir le C1 en terminale, a l'université si besoin. Mon niveau avancé d'anglais ma malheureusement pas permit de progresser pendant 2 ans (niveau des autres élèves trop bas pour apprendre quoi que ce soit) Les  vidéos de méluche me permettent enfin de connaitre du nouveau voc et comme la fait @Goutte merci de me donner vos corrections, pour que je puisse progresser ;) Bonne nuit tout le monde.

**Comment by fkevv** [comment]
Ah oui, Anne-Claire Coudray est bien la présentatrice ;)

**Comment by Goutte** [comment]
Elle est quand même bien biaisée, cette présentatrice, elle attaque direct avec une [question chargée](https://en.wikipedia.org/wiki/Loaded_question). Je comprends un peu mieux que JLM ait une réaction allergique aux journalistes, quand on voit l'absence d'honnêteté intellectuelle d'ACC... Bref, on est pas là pour juger, mais tout de même, quelle infâmie ! je pense qu'il gagnerait à être entraîné par le [CFAR](http://www.rationality.org/), notre insoumis favori, pour avoir le vocabulaire nécessaire pour déconstruire et déglinguer ce genre de questions moisies, en éduquant les spectateurs au passage.

_What do you think you know and how do you think you know it ?_

**Comment by fkevv** [comment]
Help à 4:46 traduction et sens de plate-bande ?

**Comment by fkevv** [comment]
3:05->5:45

**Comment by fkevv** [comment]
Bon, j'ai terminer à vous de jouer !

**Comment by Flupignon** [comment]
Pour le meeting hologramme j'ai utilisé "kick-outism" c'est peut-être un peu plus marqué, à débattre.

**Comment by Flupignon** [comment]
je suis à fond sur le meeting, j'essaie de corriger après @FROISSARTKevin ;)

**Comment by fkevv** [comment]
Pas de soucis ;) le meeting est plus important @Flupignon

**Comment by Goutte** [comment]
@obilya Toujours dessus ?

**Comment by obilya** [comment]
mince je suis désolée, j'avais oublié d'enlever le label. j'ai relu jusqu'à 1.54.6
