### ISSUE TITLE
[subtitles] [fr]  MÉLENCHON : « MON BULLETIN DE VOTE EST UN COUP DE BALAI » 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#179]
# Video title
 MÉLENCHON : « MON BULLETIN DE VOTE EST UN COUP DE BALAI » 

# URL
https://youtu.be/EDC1-D4qYV8

# Youtube subtitles language
Langue des sous-titres : Français 

# Duration
7'39

# Subtitles URL
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&bl=watch&ref=wt&ui=hd&v=EDC1-D4qYV8&lang=fr&tab=captions

**Comment by quidam34** [comment]
Bonjour , pour éviter de se marcher sur les pieds ce sous titrage est exclusivement réservé au forum de sous-titrage et a son équipe. Attention tout travail fait en dehors du forum risquerait d'être effacer en raison notamment de la méthode différente de travail que nous avons au niveau de la correction.

**Comment by quidam34** [comment]
A noté que quelqu'un a déjà commencé nous prenons le relais. Pourtant je ne vois pas de sujet ici !

**Comment by fkevv** [comment]
@quidam34 des anonymes prennent parfois en charge les sous-titres directement via youtube ;)

**Comment by quidam34** [comment]
Oui! j'imaginais bien un truc comme ca ! J'y retourne... Merci de votre réponse.

**Comment by quidam34** [comment]
Normalement nous avons finit ! Une dernière vérification  à la fraiche demain .

**Comment by LucileDT** [comment]
@quidam34 merci de nous avoir prévenus, d'avoir fait l'effort d'utiliser notre mise en forme, et de nous avoir signalé votre avancement, c'est super ! 👌

**Comment by quidam34** [comment]
@LucileDT On va y arrivé on va y arrivé ! :-) Une dernière correction en cours ... la vidéo a été validé sur une version pas finit grrrr .

**Comment by quidam34** [comment]
@LucileDT une question ! j'ai uploader l'ultime version. (l'autre ayant été mise  en ligne par erreur) Mais il m'indique a l'enregistrement que ma nouvelle version ne sera pas visible sur la vidéo car elle doit être valider. Je suppose que c'est la propriétaire de la chaine youtube qui peut accepter de mettre la nouvelle version à la place de l'ancienne ? comment cela fonctionne ? 

ps : pour info la nouvelle version doit avoir  a 1:05.6 le mot vague et pas vage de l'ancienne version .(information donné pour être certain qu'on est bien sur la bonne version)

**Comment by fkevv** [comment]
Je pense qu’après une modification sur une version déjà approuver la nouvelle version doit être de nouveaux approuver, ce n'est qu'une hypothèse.

**Comment by fkevv** [comment]
J'ai fait la modification a 1:05:06 j'imagine que maintenant une ou deux personnes doivent approuver la modification

**Comment by quidam34** [comment]
Oui mais c'est la modification de la version précédente truffé de fautes .... Il existe la version sans faut mais ou est-elle ? J'ai remis en place la version totalement corrigé normalement qui peut la valider ? Je suppose qu'en arrivant sur le sujet il y aura le bouton "valider" en haut a droite maoi j'ai eu ce message une fois fait . 
![sans titre](https://cloud.githubusercontent.com/assets/25107399/22637376/cf4e970c-ec41-11e6-8b1d-68c68ef2d4f4.jpg)

**Comment by quidam34** [comment]
c'est bon cela semble être bon ! je me suis débrouillé ! :-)  Je suis pleins de ressources ! :-)

**Comment by Goutte** [comment]
J'ai relu la version actuellement publiée en ligne, corrigée, et je l'ai sauvegardée.

À noter: _Monsieur_ en français s'écrit `M.`, pas `Mr.`.

**Comment by quidam34** [comment]
Ca c'est aps très grave mais on note  :-)

**Comment by LucileDT** [comment]
@quidam34 YouTube oblige à ce que deux comptes google valident les sous-titres après leur publication, c'est pour ça qu'on a mis nos procédures en place :)

**Comment by Vlavv** [comment]
Je viens de refaire une passe sur toute la vidéo, j'espère ne pas avoir créé de conflits.

Bonne soirée.
