### ISSUE TITLE
[subtitles] [eng] Discours en hommage à Fidel

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#18]
# Video title
MÉLENCHON - HOMMAGE À FIDEL CASTRO 

# URL
https://www.youtube.com/watch?v=O6Q48L6JMtA

# Youtube subtitles language
Anglais

# Duration
11:52

# URL subtitles
https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&forceedit=timedtext&ui=hd&v=O6Q48L6JMtA&tab=captions&bl=vmp&lang=en

**Comment by Flupignon** [comment]
Je pense qu'il faut le corriger.

**Comment by Ricyeam** [comment]
Issue originale de @Flupignon 
"
Quelqu'un a traduit le discours > https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&forceedit=timedtext&ui=hd&v=O6Q48L6JMtA&tab=captions&bl=vmp&lang=en

Je ne vois pas qui. "

**Comment by Ricyeam** [comment]
J'ai mis le label "correction/revision" pour qu'on sache que le sosus titres existent et qu'ils doivent etre corrigés. @Flupignon tu veux le faire?

**Comment by Flupignon** [comment]
Je vais essayer aujourd'hui si j'ai le temps. J'espère que la personne en question ne le prendra pas mal...

**Comment by Ricyeam** [comment]
Non je ne pense pas, de toutes façons les révisions sont nécessaires avant que les sous titres ne puissent être validés :)

**Comment by LucileDT** [comment]
Pour ce qui est du travail collaboratif, il vaut mieux quand on contribue être capable d'accepter la critique :)

Normalement, la personne qui a écrit les sous-titres devrait être dans cet état d'esprit ^_^

**Comment by Flupignon** [comment]
Bon j'ai terminé la trad, mais je suis trop fatigué pour me relire... Je compte sur vous demain ;)

**Comment by Flupignon** [comment]
Du coup @bayasahra tu pourrais aussi relire et valider cette vidéo aussi stp ?

**Comment by Ricyeam** [comment]
@Flupignon je vais peut etre le faire ce soir

**Comment by bayasahra** [comment]
@Flupignon
Désolé j'étais pas sur l'ordi.
 Les sous titre en anglais je ne serai pas d'une grande aide ^^ .... je m'occupe plutôt des sous titres français. Je pourrais à la limite corriger les timings mais c'est tout... c'est pourquoi mieux vaut quelqu'un qui puisse gérer correctement l'anglais... la relecture juste pour du timing serait un temps que je pourrais utiliser à meilleur escient sur une autre vidéo :)

**Comment by Ricyeam** [comment]
Sinon @ClaireEV peut le faire en Anglais, si ca te dit @ClaireEV  ?

**Comment by LucileDT** [comment]
Je peux aussi checker ce soir si personne n'a pu s'en charger :)

**Comment by ClaireEV** [comment]
je verrais ce que je peux faire ! je vous dirais en rentrant, je finis les cours dans 1h.

**Comment by Ricyeam** [comment]
C'est fait. J'ai corrigé quelques ponctuations, et un "warning, warning" qui trainait

**Comment by Flupignon** [comment]
Ah mais j'avais mis "beware" !

**Comment by Ricyeam** [comment]
Oui, il y avait both "warning warning" and "beware beware"… du coup j'ai laissé les beware ;)
