### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - Discours sur l'abolition de l'esclavage à Champagney

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#180]
# Video title
MÉLENCHON - Discours sur l'abolition de l'esclavage à Champagney

# URL
https://www.youtube.com/watch?v=jO8TCOMU2i8

# Youtube subtitles language
Français

# Duration
36:27

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&lang=fr&action_mde_edit_form=1&v=jO8TCOMU2i8&ui=hd&tab=captions&bl=vmp&captions-r=1

**Comment by Albapringe** [comment]
J'attaque cette nouvelle vidéo.

S'il y a une âme qui s'en sent la motivation, je suis preneur d'un texte de la minute 20:00 à la fin. Cette requête sera valable jusqu'à ce que je dise par commentaire que le délai est dépassé (parce que j'aurai atteint la minute 20:00).

**Comment by Bentham** [comment]
Allez je m'y colle !

**Comment by Bentham** [comment]
Help 25:03 : "Et on se souvient de cette scène extraordinaire de (?)"

Pour les enquêteurs en herbe, peut-être à rechercher dans la bio de Toussaint Louverture ?

**Comment by fkevv** [comment]
@Bentham Et on se souvient de cette scène extraordinaire de Delgrès
https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=fort+delgr%C3%A8s

**Comment by Bentham** [comment]
Quel talent, bien joué Sherlock !

**Comment by fkevv** [comment]
No problem ;)

**Comment by Bentham** [comment]
@Albapringe 

[JLM discours Champagney.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/752569/JLM.discours.Champagney.pdf)

Ici même !

**Comment by Albapringe** [comment]
Super ! J'incorporerai le tout quand j'aurai fini :)

**Comment by Albapringe** [comment]
Terminé. Prêt pour 1ère relecture.

**Comment by LucileDT** [comment]
Trop d'efficacité !

**Comment by Bentham** [comment]
Je corrige jusqu'à 20 minutes. Je considère que le reste a déjà fait l'objet d'une relecture :)

**Comment by Bentham** [comment]
@Albapringe Pourquoi la majuscule à "Noir" ? Même quand il désigne une personne, ce mot semble garder sa minuscule : https://fr.wiktionary.org/wiki/noir

**Comment by Bentham** [comment]
Allez c'est fait !

**Comment by Albapringe** [comment]
@Bentham, en fait, je mets une majuscule quand il s'agit d'un nom, et minuscule si c'est un adjectif (un Noir, mais une personne noire). Il semblerait que c'est ce qui se fasse par convention, un peu de manière analogue à la nationalité.

**Comment by Bentham** [comment]
Ah... Bon après une petite recherche sur google, je vois que le sujet fait débat. L'ancien usage est plutôt de mettre la majuscule, mais apparemment il y a de plus en plus de voix pour dire que cet usage tend à essentialiser l'ensemble des noirs, comme si la couleur de peau pouvait par elle-même constituer un groupe ethnique homogène...

J'ai remplacé par une minuscule jusqu'à la minute 20, mais je peux réverter. On se met d'accord sur l'usage qu'on adopte ? (perso je pencherais plutôt pour la minuscule, à toi de voir ce que tu en dis)

**Comment by Albapringe** [comment]
Hélas, ce débat est bien malheureux, qui consiste à ramener un mot à une considération ethnique. Pour ma part, l'usage de la majuscule ou minuscule m'est totalement indifférent. Si tu as corrigé ainsi, laissons ainsi.

**Comment by Bentham** [comment]
Justement, je pense que le débat est provoqué par le fait que la majuscule tend à lui donner une connotation ethnique !

Bon, disons qu'on choisira la minuscule à l'avenir alors (à moins qu'il y ait des avis divergents sur le github ?).

**Comment by Vimogo** [comment]
Personnellement je suis pour la minuscule.

**Comment by Albapringe** [comment]
Et bien, à l'unanimité, on adopte désormais la minuscule :)

Je clos l'issue, les ST sont déjà disponibles.
