### ISSUE TITLE
[subtitles] [en] MÉLENCHON : Double meeting à Lyon et Paris #JLMHologramme

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#182]
# Video title

MÉLENCHON : Double meeting à Lyon et Paris #JLMHologramme

# URL

https://www.youtube.com/watch?v=XlnQ801wWf4&t=235s

# Youtube subtitles language

Langue des sous-titres (Anglais)

# Duration

1:46:25

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&lang=en&ref=player&v=XlnQ801wWf4&ui=hd&action_mde_edit_form=1

**Comment by Flupignon** [comment]
Bon, ça va être trèèès long à faire, mais j'ai déjà fait plus long, alors avec du renfort, on devrait y arriver.

**Comment by Bentham** [comment]
Ho les gars, grosse motivation là !!

**Comment by Albapringe** [comment]
Je suis heureux que vous fassiez un sous-titrage en anglais, il y a une personne prête à relayer la vidéo si les sous-titres en anglais existent :
https://www.youtube.com/watch?v=XlnQ801wWf4&lc=z131izwikkeodnnmm22ut3eidxemcrxbi04

**Comment by Flupignon** [comment]
Super je vais essayer de faire vite.

**Comment by Flupignon** [comment]
16:50

**Comment by quidam34** [comment]
arf désolé j'ai confondu le sous titrage anglais et francais ! désolé les gars

**Comment by Flupignon** [comment]
21:01

**Comment by Flupignon** [comment]
24:21

**Comment by Flupignon** [comment]
25:49

**Comment by Jhnapri** [comment]
Il Ya t'il besoin d'aide la dessus, et si oui quelle séquence traduire please?

**Comment by Flupignon** [comment]
Bonjour @jhnapri tu es nouveau ? Tu peux traduire n'importe quelle séquence, l'important c'est de ne pas travailler à deux en même temps sur la vidéo. Quand tu vois le label rouge "Someone is working on this issue", il ne faut pas traduire et attendre qu'il soit retiré.

**Comment by Bentham** [comment]
@Jhnapri A voir ce que Mister @Flupignon en pense, mais quand le label rouge "someone is working [...]" est mis, je crois que tu peux traduire n'importe quelle séquence suffisamment éloignée de 25:49 (par exemple de 45:00 à 55:00...). Il suffit de coller ici le texte correspondant à ta traduction, et l'importation se fera au moment adéquat.

**Comment by Jhnapri** [comment]
@Flupignon Nouvelle pour etre precise :) Je viens de me presenter dans le groupe de presentation,
C'est compris, Label rouge, quelqu'un est dessus. il faut encore que je me familiarise avec l'interface mais ca me parait assez instinctif. Ya t'il des plannings de mis en place pour optimiser le temps? Qui est disponible quand pour faire un relai?
@Bentham donc il est possible de traduire une sequence assez eloigne pour ne pas gener le process? Quand tu ecris coller ici le texte correspondant a la traduction tu veux dire ici, ou sur youtube directement?

Merci pour vos infos utiles

**Comment by Bentham** [comment]
@Jhnapri Voilà, tu as compris. On n'a encore jamais travaillé comme ça, mais ça me semble plus efficace.
Quand une personne est en train de travailler dans l'interface, il ne faut surtout pas s'y rendre et faire des modifications, puisque sur les deux il y aura forcément un contributeur qui perdra son travail.
Tu peux donc partager ta traduction ici. Il y aurait deux moyens de le faire : 
- le plus simple, c'est que la mettes dans un fichier, et que tu l'uploades ici (par un simple drag'n'drop dans cette fenêtre de texte)
- la plus adaptée à un travail collaboratif, c'est peut-être d'utiliser un outil comme framapad. Tu mets le timing entre crochets et ton texte ensuite. Par exemple : https://mensuel.framapad.org/p/JLM_trad[ENG]#182

Et pour une collaboration parfaite, tu peux annoncer ici sur quel timing tu es en train de travailler !

**Comment by Jhnapri** [comment]
Merci @Bentham ca m'a l'air clair. Je commence des demain.

**Comment by Flupignon** [comment]
Ça n'écrase pas le fichier précédent ? Si ça marche, tu peux même commencer à 35:00, je commence à fatiguer...

**Comment by Bentham** [comment]
@Flupignon ce que je propose à Jhnapri c'est de rédiger le texte **en-dehors** de l'interface quand quelqu'un est en train de bosser, et de le mettre à disposition de tout le monde. Du coup y'aura plus qu'à faire un copier-coller quand le moment se présentera... Je sais pas si c'est clair.

**Comment by Flupignon** [comment]
Si si très clair, mais c'est juste que la dynamique du texte influence en partie les choix de traduction, la longueur des phrases ou les ajouts/omissions, et je préfère la visualiser directement sur l'éditeur de sous-titres. 
Il y a une vraie différence entre la traduction d'un texte simple et la traduction de sous-titres je trouve. 
Sinon frampad c'est super, mais c'est peut-être plus adapté pour la transcription dans ce contexte ?

**Comment by Flupignon** [comment]
30:40

**Comment by Flupignon** [comment]
J'ai oublié d'enlever le label rouge hier soir désolé..... Je m'y remets du coup.

**Comment by Flupignon** [comment]
Wow je viens de me rendre compte que mon avatar Cartman en policier avec une matraque qui dit "respect my authority" pourrait être super mal interprété avec ce qu'il se passe, je le change tout de suite....

**Comment by Jhnapri** [comment]
Oui je comprends ce que tu veux dire @Flupignon pour la dynamique. Es-tu encore dessus ce matin? Je fais 12:00 20:00 aujourd'hui au boulot. Je peux peut-etre aider a avancer ce matin... tu es a combien de minutes?

**Comment by Flupignon** [comment]
Oui je suis dessus en ce moment. Commence vers 45:00 pour être large ;)
J'en suis à 31:00

**Comment by Jhnapri** [comment]
Ok je commence a 45minutes

**Comment by Jhnapri** [comment]
Voila un premier essai, dites moi ce que vous en pensez et je me lance quand je peux pour la suite:

[De 45:00 à 46:28]
And because I take these questions very seriously, I can tell because I have known them closely; we must, when we study, have the time and the resources to do so. Not to have to do something else at the same time. The 50% of our young people who work while studying at the same time, exhaust themselves, that is not good! That is not good! 
We have to put in place an independent studying allowance (Allocation d'autonomie d'etude). And there will be one. In addition, in addition, regarding all professional studies, where it seems that the average of the age is often a bit higher than in the other studies, well I would like this fact to end, that 100% of a range of age, 100% of a promotion, be constrained to work every evening and every weekend while they study. 
That is why, will be entitled to this studying allowance, all the students from 16 years old, doing professional studies. Ah Ah! Here is something which is going to change the social roles repartition in this country.

[De 46:30 à 47:10]
We need my friends, 60.000 more professors, teachers, in all sorts, to compensate the loss that we had under Sarkozy, and for those which have not been replaced by Francois Hollande. And you know I am not going to stop by saying that, you are applauding and you will come on the 19th of February to ask what will be the cost, because everybody is going to ask you how much would it cost. And what is the cost of stupidity? What is the cost of death? What are those unilateral accountancies?  We need professors, we need to hire people to educate children, it enriches a country it does not impoverish it. Knowledge is an investment not an expense.

**Comment by Flupignon** [comment]
41:47 Par contre je ne vois pas tes modifs @Jhnapri ... As-tu bien envoyé ton texte pour examen ? Si je reprends, j'irai jusqu'à 44:30 et je ferai un saut jusqu'à 1:00:00

**Comment by Flupignon** [comment]
44:34 - trou pour @Jhnapri  - et de 59:33 à 1:01:51

**Comment by Flupignon** [comment]
Je te dis après @Jhnapri je donne le goûter au petit.

**Comment by Flupignon** [comment]
Je pense que tu devrais reformuler les phrases, elles collent trop aux formulations orales hachées. 
Par exemple : 

we must, when we study, have the time and the resources to do so. Not to have to do something else at the same time.

Je reformulerais ça comme ça, pour fluidifier la lecture, sinon ça devient vite difficile à comprendre pour un anglophone (il faut peut-être encore faire des modifications en lecture dynamique) :

When we study, we must have the time and the resources to do so. We should not have to work during our studies. (on pourrait même éviter d'écrire 'we' mais plutôt 'students'/'they')

**Comment by Jhnapri** [comment]
@flupignon je prends les remarques en compte et ferai les modifications nécessaires :) Ca a du sens! Par contre je suis encore novice il faudra que je regarde comment envoyer le texte pour examen. La je commence le travail dans 1:00 et n'aurais pas le temps mais j'essaye de faire ca dans la soirée! J'ai avancé un peu plus hier sur la traduction donc j'enverrai tout ca. Et merci pour le trou je ferai ça aussi vite que je peux ! Bonne journée à tous

**Comment by Flupignon** [comment]
Pour 'envoyer pour examen', c'est très simple, il y a un bouton bleu en haut à droite de l'écran. Il faut cliquer quand tu a fini et cocher 'non le travail n'est pas terminé, laisser d'autres utilisateurs travailler'.

**Comment by Flupignon** [comment]
00:00 à 44:34 — trou pour @Jhnapri — 59:33 à 1:07:59

**Comment by Bentham** [comment]
Flupi tant que tu étais sur la vidéo tu aurais pu importer le texte de @Jhnapri non ? Que ce soit elle ou toi qui le fasse ne change rien à l'affaire :)

**Comment by Flupignon** [comment]
Il faut rajouter le timing manuellement ?

**Comment by Bentham** [comment]
Tu peux utiliser la technique ici : https://youtu.be/tg5NzbiRqI0?t=6m9s
Ca se fait très rapidement.
Sinon je m'en occupe, sans problème !

(ou alors ici pour faire encore plus vite : https://youtu.be/q68KAKVCOP4?t=7m41s )

**Comment by Flupignon** [comment]
Merci (désolé j'ai pas trop suivi la technique ces derniers temps). Et en plus je peux mettre un visage sur ton nom !

**Comment by Flupignon** [comment]
1:10:09

**Comment by LucileDT** [comment]
Ahah, bienvenue @Jhnapri ! Tu dois avoir reçu un mail, il faut accepter l'invitation que je t'ai envoyé et comme ça, tu pourras ajouter/enlever des labels par exemple :)

**Comment by Flupignon** [comment]
1:19:00

**Comment by Jhnapri** [comment]
Merci, avec vos precieux conseils j'y suis arrivee. Je pense pouvoir encore ameliorer le contenu mais je demanderai a mon homme de relire et de me dire si c'est correct puisqu'il est british. Je reprends des que possible.

**Comment by Flupignon** [comment]
Ah oui ? Ce serait super s'il avait le temps de relire le meeting en entier. Tu pourrais voir avec lui s'il a le temps ? Rien ne vaut l’œil d'un native speaker !

**Comment by Flupignon** [comment]
1:23:44

**Comment by Jhnapri** [comment]
Je vais lui demander s'il peut tout relire @flupignon il me dira s'il y a quoi que se soit à modifier.

**Comment by Flupignon** [comment]
Super ! Merci beaucoup à vous deux ;)

**Comment by LucileDT** [comment]
@Jhnapri Génial, merci à vous deux !

**Comment by Flupignon** [comment]
1:26:05

**Comment by Flupignon** [comment]
1:29:26

**Comment by Jhnapri** [comment]
Bonsoir, j'ai convaincu Callum de relire toute la premiere partie jusqu'au moment ou je me suis arretee, c'est a dire aux alentour de la 58' minute. Il a corrige quelque fautes de tapes, et suggere une ou deux modifications en terme de mots choisis ("bad" au lieu de "noxious" - "break from this" au lieu de "break with all this") En terme de petites erreurs on a remplaces "sits" par "seats", "An hallucinogenic" s'ecrit en deux mots. Il faut encore que je finesse ma partie, je vais beaucoup moins vite que toi @Flupignon mais je n'ai peut etre pas la bonne technique encore, j'ai l'impression de perdre du temps alors je relirai les conseils pratique de @Bentham. Je vais alle m'occuper de mon fils de 19mois mais j'essaie de reprendre demain. bonne soiree. Johanna

**Comment by Flupignon** [comment]
Merci beaucoup à vous deux pour la rédaction et la correction ! C'est vraiment super de pouvoir être corrigé par un native-speaker ! Callum a-t-il fait les modifications ou faut-il que je les fasse ?

Pour la vitesse il y a deux raisons : j'ai du temps (je suis au chômage même si je dois m'occuper de mon petit aussi) et j'ai fait des études de traduction, j'ai donc l'habitude de l'exercice même si c'est très loin d'être parfait (normalement, un traducteur doit traduire vers sa langue d'origine et non l'inverse).

**Comment by Jhnapri** [comment]
@flupignon je comprends. Nous avons fait les modifications directement mais j'ai pensé que je devrais écrire ce qui avait été modifié au cas où...
Es-tu à la recherche d'un emploi? Je recherche à embaucher quelqu'un mais ici à Preston.

**Comment by Flupignon** [comment]
Oui je suis à la recherche d'un emploi (même si je compte m'y mettre après les élections) mais malheureusement, je ne compte pas m'installer en Angleterre, j'ai ma petite famille ici. Mais merci beaucoup pour la proposition, c'est très gentil !

**Comment by Jhnapri** [comment]
Je comprends tout à fait. 
En ce qui concerne le reste du discours on refera une relecture quand se sera terminé si ça peut aider. Bonne soirée!

**Comment by Flupignon** [comment]
Super !  Je suis dessus là, j'avance pas mal. Bonne soirée à vous trois !

**Comment by Flupignon** [comment]
1:36:44 + un copié/collé de la Marseillaise à la fin à partir de 1:42:05.

On voit le bout !

**Comment by LucileDT** [comment]
@Jhnapri Pas de soucis pour le fait de ne pas être tout le temps là ! Tout le monde ici travaille sur son temps libre, on ne demande pas de service minimum :)

**Comment by Flupignon** [comment]
Bon je m'y remets. Le premier jet devrait être fini demain si tout se passe comme prévu.

**Comment by Jhnapri** [comment]
Merci @LucileDT Super @Flupignon tu as bien avancé! Je vais essayé de finir ma partie demain matin, j'ai pas trouvé le temps aujourd'hui. Et on relira comme prévu. À demain.

**Comment by Flupignon** [comment]
J'ai fini ! J'ai commencé à relire ta partie (de 45:00 à 46:42) et j'ai fait quelques modifications (tournures de phrases et découpage des blocs de sous-titres). Pour ce qui est du vocabulaire, j'ai fait quelques changements, dont les changements suivants, à confirmer par Callum (merci encore Callum !) :

professional studies > vocational education (en me basant sur les fiches wikipedia fr/eng)
studying allowance > student allowance
social roles repartition > sharing out of social roles (plus courant il me semble)

Je fatigue alors je relirai le reste demain.

**Comment by fkevv** [comment]
Il y a des relectures en cours ?

**Comment by Bentham** [comment]
Félicitations les chatons, traduire et sous-titrer près de deux heures de vidéo c'est un _tour de force_** !


 ** à prononcer "touw de fowce" (avec l'accent anglais)

**Comment by Flupignon** [comment]
Mewci @Bentham !

**Comment by Flupignon** [comment]
@FROISSARTKevin v'est pas encore tout à fait l'heure de la relecture en fait, il reste un passage à terminer.
Je remets le label "writing in progress"

**Comment by Flupignon** [comment]
Il reste à relire et finir la partie qui va de 55:36 à 1:00:00.

**Comment by Flupignon** [comment]
Pardon @Jhnapri tu es dessus ?

**Comment by Jhnapri** [comment]
Hey guys! Salut @Flupignon oui je viens de finir ma partie ca y est! Je relis une fois ou deux et je sors. :)

**Comment by Jhnapri** [comment]
Et merci pour la relecture de ma partie, c'est super!

**Comment by Flupignon** [comment]
Ok je relis après et ça devrait être bon ! Merci encore pour ta participation ;)

**Comment by Jhnapri** [comment]
J'espere que ca ne t'a pas donne trop de travail... Je vois qu'il y a eu pas mal de correction.

**Comment by Flupignon** [comment]
Non au contraire, ça le facilite !

**Comment by Flupignon** [comment]
57:55

**Comment by Flupignon** [comment]
Fini pour de vrai !

**Comment by ladoamy** [comment]
bon desolee, jai pas pu avancer autant que jaurais voulu... vie de jeune maman, que voulez vous! promis je ferai plus la prochaine fois. Bonne nuit les gens. 

7:11

**Comment by Bentham** [comment]
Bravo pour ta première contribution @ladoamy !

**Comment by ladoamy** [comment]
20:14

je fais une pause pour suivre #JLMchiffrage

**Comment by ladoamy** [comment]
salut

je viens de me rendre compte que les modifs que jai faites n'ont pas ete enregistrees...
est ce que j'ai rate une etape?

**Comment by Flupignon** [comment]
Bonjour @ladoamy tu as bien enregistré les modifications avant de quitter ? (cf bouton "envoyer vers...")

**Comment by ladoamy** [comment]
non je n'ai jamais enregistre avant de quitter car je voyais que ca senregistrait automatiquement.. mais cest tres bizarre, cette fois, je vois que les modifs ont ete prises en compte apres tout. 
(je ny comprends rien.) mais bon, le principal c'est que tout netait pas perdu.

**Comment by ladoamy** [comment]
29:20

**Comment by obilya** [comment]
58:56

**Comment by Heneark** [comment]
Si j'ai bien compris, la relecture était déjà effectuée jusqu'à 58:56 ? En tous cas, j'ai repris à partir de là (quelques corrections mineures type coquilles, du très bon anglais sinon!) et envoyé ma contribution, les sous-titres sont maintenant affichés sur la vidéo.
