### ISSUE TITLE
 [subtitles] [fr] MÉLENCHON : Double meeting à Lyon et Paris #JLMHologramme 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#183]
# Video title
MÉLENCHON : Double meeting à Lyon et Paris #JLMHologramme

# URL
https://youtu.be/XlnQ801wWf4

# Youtube subtitles language
Langue des sous-titres (Français)

# Duration
1:46:25

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=XlnQ801wWf4&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd

**Comment by quidam34** [comment]
Bonjour ! nous aimerions que notre forum s'occupe en exclusivité du sous titrage.  Merci de ne pas y participer. Nous allons, en plus, tester le travail à plusieurs sur la même vidéo ! Si je vous assure c'est possible je suis pleins de ressource !  :-)

**Comment by quidam34** [comment]
Toujours en cours .... ca avance doucettement ! Le travail a deux en même temps sur la même vidéo fonctionne !

**Comment by quidam34** [comment]
Tout le sous titrage sera mis d'un coup d'un seul dans la journée. Nous attendons d'ici a ce soir la correction orthographique de tout le texte !

**Comment by Goutte** [comment]
Où en êtes-vous ?

**Comment by Goutte** [comment]
J'ai relu trois phrases, c'est encore truffé de fautes ; je mets le label "correction requise". J'ai commencé à corriger, mais c'est titanesque, ce travail de correction, à cause de la faible qualité des sous-titres...

**Comment by Salem2612** [comment]
@Goutte : T'en es où de cette vidéo ? Tu as déjà relu quoi ? Tu t'es arrêté où ? La synchro n'est pas bonne entre les sous titres et la voix, c'est galère à repositionner.

**Comment by Goutte** [comment]
J'ai presque rien relu, ça m'a trop déprimé, il y a trop de fautes. Tout est à (re)faire.

**Comment by Salem2612** [comment]
C'est voulu qu'ils aient pris à leur charge tous les gros meetings et grosses vidéos de JLM ? (meeting de Lyon, Brest, Strasbourg, émission France 2). ça pourrait faire croire à du sabotage. Celle ci traîne depuis 1 mois et c'est quand même la plus importante !

**Comment by Goutte** [comment]
C'est le truc avec l'anarchie ; n'importe qui peut participer. Tout le monde lui dit qu'il devrait arrêter, qu'il fait plus de mal que de bien, mais... L'enfer est pavé de bonnes intentions, comme on dit !

**Comment by quidam34** [comment]
Est ce que je vous ai demander de corriger ! Un sujet on le garde jusqu'àu bout Merci !

**Comment by quidam34** [comment]
Et non le calage n'est pas finit !  Et votre mauvaise foi deviens grotesque !

**Comment by quidam34** [comment]
Bonsoir, Aller donc travailler sur l'issu #156 il est du 19 Janvier A mon avis ils ont besoin d'un coup de main ! Et vous venez me parler de lenteur alors que vous êtes sous-titreur de puis plus longtemps que nous ... Balayez sur le pas de votre porte ! Ok Et si l'idée c'est que je pète un boulon c'est raté lol ... je suis jamais grossier ni insultant  malheureusement  hein !   Je vous souhaite la bonne soirée a tous ! Que la nuit vous porte conseil !    ps : par contre vous l'êtes d'une certaine manière !

**Comment by quidam34** [comment]
@LucileDT pourriez vous rappeler au utilisateur d'ici qu'on ne touche pas a cette vidéo même si elle je la met dans la colonne a corriger,  meme si au demeurant elle est aussi avancé qu'une de vos vidéos dans cette colonne, mais d'une autre manière !  ! 

c'est pour cela que je l'ai remis là sans changer le label. Merci

**Comment by quidam34** [comment]
Petit rappelle de notre méthode de travail : pour que vous ne vous anormal de ne rien voir depuis quatre jours, rappel de notre méthode de travail.

1) Mise sur papier de tout le texte de la vidéo.
2 ) Mise en format .txt en vocal, ou au clavier (selon la personne qui le fait) de tout le texte.
3 ) Première correction automatique de toutes les fautes (Scriben entre autres, service payant )
    https://www.scribens.fr/
4) Deuxièmement correction humaine.
5) Envois sur Youtube de tout le texte, youtube ce charge de la création des champs et du réglage de la synchronisation.
À noter, il peut donc se passer bien des jours avant que rien apparaisse sur la vidéo. Évidemment ! 
6) Deux personnes en simultané s'occupent du réglage, humain cette fois, de la synchronisation, mais aussi du contenu de la cellule dont le découpage n'est pas forcements bien fait. ) Il était donc inutile de crier au loup, si, arrivé dans la colonne correction, la synchronisation n'est pas terminé .
7) Le travail est fini !

Donc quelque soit la colonne ou est mis ce sujet ne vous en occupez pas !

**Comment by Salem2612** [comment]
OK, vas pour la dictature. Je ne vais pas me battre pour du bénévolat. J'ai assez de personnes de votre sorte au travail.

Votre méthode est peut être efficace, je ne m'en rends pas compte, dans tous les cas elle est techniquement incompatible avec YouTube qui permet à n'importe qui, extérieur à toute communauté, de relire et modifier les sous titres.

**Comment by quidam34** [comment]
Est-ce que vous en faite partit des gens extérieurs à la communauté ? Pourquoi vous en inquiétez alors ? Et puis vous en voyez beaucoup passer vous ? Vraiment ? Alors pourquoi appuyer vos arguments là-dessus ? Juste envie de râler ? Vous ne trouvez pas cela démocratique ? Croyez-moi sur le forum, c'est démocratique... Et encore plus que dans votre manière de travailler, même si la vôtre, ok, épouse le principe YouTube ! Mais YouTube vous laisse-t-il le choix ? Vous laisse t'il le choix de faire le travail pour lequel vous avez le plus de goût ! Sur le forum, tout le monde y trouve son compte ! Certain préfère écrire les textes sur papier, d'autres corrigés, chacun faisant la tache pour laquelle il a le plus de goût ! Et comme dirait notre correctrice, comment peut-on faire une correction en n'ayant sous le nez des bouts de phrases alors qu'il faut voir un texte dans son ensemble pour corriger ! Vous avez déjà vu un grand patron faire un coup, le patron, un coup, la secrétaire et l'autre le manutentionnaire ! Mais dite, moi.... Où est-ce que c'est marqué qu'on devait obligatoirement travailler comme vous ? Pourquoi Youtube propose aussi la solution que j'utilise ? Bon voilà, vous êtes enfermé dans la logique qui vous arrange, tant dis que moi, je peux comprendre votre manière de travailler. Même si je ne l'approuve pas car plus lente ! Et ne me dites pas "telle vidéo, vous l'avez depuis... " La dernière méthode ne vient de commencer à 100 % sur la vidéo que l'on travaille. Avant, j'ai aussi dû chercher un correcteur motivé ! Bref plein de choses qui nous ont ralentis et fait perdre du temps. La rapidité, on en reparle à l'avenir ok ? Voilà ! J'espère ne plus avoir à revenir sur le sujet. Et puis le mot leitmotive des insoumis reste : La consigne, c'est qu'il n'y a pas de consigne non ?  ;-)

**Comment by Salem2612** [comment]
Si vous cherchez un correcteur ou un relecteur, je serais ravi de vous aider. Le problème est que je doive m'inscrire et participer sur un forum qui fait doublon avec github. Github me semble la meilleure option puisqu'il offre
- Le coté forum
- Le système des colonnes pour une représentation visuelle des taches en cours
- La possibilité de travailler et de s'échanger des fichiers txt sans risque de perte ou d'écrasement, avec suivi de modifications...

**Comment by quidam34** [comment]
Bonjour,
Cela ne me dérange pas de vous donner les textes ici en pièce jointe.
Concernant les colonnes, c'est inutile sur le forum, puisque nos "attributs" (vos labels) sont encore plus "pointu"
En voici un aperçu : En voici un aperçu :

http://www.sous-titreur.forum-insoumis.fr/viewforum.php?f=3
Ainsi, sans même devoir entrer dans un sujet, on sait qui est en train de faire quoi à l'instant précis.

On indique aussi en éditant le sujet, à la fin de la cession, jusqu'où on a travaillé. On indique aussi en éditant le sujet, à la fin de la cession, jusqu'où on a travaillé.

On peut aussi mettre des pièces jointes.

Le forum n'a rien à envier a github, au contraire.

-Nom de domaine facilement identifiable. Des "github" il y en a des milliers. Sans compter qu'un truc qui appartient à Google et Youtube, moi, je me méfie ! Et Jean-luc des américians aussi d'ailleurs !  :-) D'ailleur le choix de Youtube mais bon.. pas vraiment le choix je pense. Surtout après l'avoir vu dans une vidéo, Jlm visiter Dailymotion !

- "sous-titreur.forum-insoumis.fr"  étant en relations avec le forum : forum-insoumis.fr. C'est d'ailleurs un sous-domaine. Même si de ce coté tout est à refaire et c'est prévu de tout recommencer ! Le forum à beaucoup marché en 2012 ! Je pense tout reprendre à zéro bientôt.
Le forum est tout en français et si demain, nous voulons le réorganiser on fait ce qu'on veut, on est chez nous !
Les sujets, vos issues, ne sont pas mélanger ... Un sous-forum pour se présenter, un sous-forum pour parler, et l'autre pour le travail. 'Ici obligé de faire un tri pour cela ! " Notre guide des sous-titres n'est pas une " issue" mais un lien unique bien visible en dessous de la bannière. Il est loin d'être parfait, mais on avance doucement ! 
Pour terminer github (que j'ai besoin de regarder à chaque fois comment cela s'écrit) est d'abord une plate forum utilisé par les développeurs... Ce n'est pas tout adapté pour le grand public. J'en veux toujours pour preuve la personne qui m'a introduit ici qui était bien en peine de m'expliquer clairement ce qu'était une issue, etc. Et même pire, de me donner une adresse précise, puisque vous n'avez pas, à proprement parlé, de page d'accueil qui vous soit propre.
Nous avons aussi un tchat que personne n'utilise. lol  Pas, besoin de courir ailleurs !

C'est bien pour cela que personnellement, j'ai vite couru créer un forum en français.C'est bien pour cela que personnellement, j'ai vite couru créer un forum en français. Logiciel sur le mac etc... Par exemple, mon épouse qui met sur papier les textes utilise un logiciel très pratique sur son Androïd, qui lui permet, à chaque fois qu'elle remet en écoute la vidéo, de revenir X (choisi dans les préférences)  secondes en arrière. Permettant ainsi de ne pas tâtonner sur la réécoute de ce qui a été dit avant ! Vous voyez, on ne laisse rien au hasard.

Alors que l'on se demande si je ne suis pas un troll, ce n'est pas très sympa !

voilà  !

**Comment by Salem2612** [comment]
Je dois avoir une incontinence au phpBB parce que je ne vois pas les tags dont vous me parlez.
 - github est un hub entre des dépôts git, donc github.
 - La page d'accueil est disponible en page d'accueil : https://github.com/jlm2017/jlm-video-subtitles
 - Les issues sont l'équivalent d'un sujet sur un forum.

Mon idée n'est pas de se repasser les fichiers en pièce jointe, mais bien de les versionner grace à git.

**Comment by Goutte** [comment]
> Et puis vous en voyez beaucoup passer vous ? Vraiment ?

**Oui.** En fait, la communauté anonyme contribue **plus que vous**. Regardez les commits de sauvegarde, on voit bien qu'il y a beaucoup de contributions qui n'ont été référencées ni ici ni sur votre forum.

> Vous laisse t'il le choix de faire le travail pour lequel vous avez le plus de goût !

Evidemment !

---

_L'anti-intellectualisme a été un fil conducteur qui serpente à travers notre vie politique et culturelle, nourrie par la fausse idée que la démocratie signifie que "mon ignorance vaut autant que vos connaissances"._ -- Isaac Asimov

Votre ignorance est parfois tellement incroyable, que couplée à votre irrespect pour le travail des autres (hein, @Albapringe) il est impossible de ne pas se demander sérieusement si vous n'êtes pas un saboteur.

De plus, vous avez clairement des déficiences en orthographe ; pourquoi vouloir à tout prix contribuer à la cause sur ce que vous faites le plus mal ? Je veux dire, vous avez certainement plein de charisme en personne, pourquoi ne pas passer votre temps à militer dans la rue de vive voix plutôt que d'empoisonner les bénévoles sur internet ?

**Comment by quidam34** [comment]
@Salem2612   Un incontinence vous êtes certain ? ;-)   Une page d'accueil avec des fichiers "bin" et "config" . Moi j’appelle cela un répertoire, un mix entre un répertoire et une page d'acceuil quoi !  !  
" Les issues sont l'équivalent d'un sujet sur un forum."  oui j'avais bien compris ;-)

"mais bien de les versionner grace à git."  va falloir m'expliquer là ? 

Pas des tags des attributs : C'est tout ce qui est marqué en couleur devant le titre ... Ils sont personnalisés . Chaque personne a des tags personnalisés dont il dispose, suivant le boulot qu'il effectue a l'instant donné. Il existe donc Un attributs " valérie rectification s-titre" mais aussi " trucmuche rectification s-titre" etc... Chaque utilisateur n'accède évidemment qu'aux attributs qu'il le concerne uniquement et toujours avec leur nom devant... Par exemple ceux qui rectifient les sous-titres et qui ne corrigent jamais n'ont pas cet attribut inutile pour eux.

Vous croyez que je suis un petit plaisantin, que je ne réfléchis pas à tout ? Mais ça évolue tous les jours ce n'est pas statique ! Je suis très perfectionniste soit je fais tout ou soit je fais rien ! 

![attribut exemple](https://cloud.githubusercontent.com/assets/25107399/23514436/9f2a3746-ff67-11e6-99da-1c8d0bd1c3ae.jpg)

**Comment by Goutte** [comment]
> "mais bien de les versionner grace à git." va falloir m'expliquer là ?

https://www.christopheducamp.com/2013/12/15/github-pour-nuls-partie-1/

En gros, l'échange de fichiers par pièce jointe, c'est [un sujet de rigolade](http://www.webagencyfail.com/).

**Comment by quidam34** [comment]
J'avoue j'ai pas été lire ! un peu long..  l'idée c'est de partager un document sur le net et de travailler dessus en commun. Comme google doc le propose ?  @Goutte

**Comment by quidam34** [comment]
Bon, j'ai survolé votre lien, cela m'avance a quoi ?  "Créer Votre Repository Local"  "Créer Votre Repo En Ligne"  "git branch" etc... et cela m'avance a quoi ?

**Comment by Goutte** [comment]
> cela m'avance a quoi ?

Bonne question. [Internet a la réponse](https://www.google.fr/search?q=intérêt+systeme+versionning).
