### ISSUE TITLE
#RDLS17 : THÉO, MAYOTTE, HOLOGRAMME, YOUTUBE, ROUMANIE, CORRUPTION, FRANCE INSOUMISE

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#184]
# Video title
#RDLS17 : THÉO, MAYOTTE, HOLOGRAMME, YOUTUBE, ROUMANIE, CORRUPTION, FRANCE INSOUMISE

# URL
https://www.youtube.com/watch?v=579gZ1fsLVY

# Youtube subtitles language
Français

# Duration
28:55

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&v=579gZ1fsLVY&ui=hd&action_mde_edit_form=1&ref=player&tab=captions&lang=fr&captions-r=1

**Comment by Albapringe** [comment]
Comme d'hab, je suis preneur d'un texte à incorporer qui s'étalerait de la minute 15:00 à la fin pour accélérer le tout.

**Comment by desintoxiquezvous** [comment]
salut, 
bon j'essaie de commencer la reco a partir de 15 , je te tiens au courant de l'avancement

**Comment by desintoxiquezvous** [comment]
@Albapringe  voila, je viens de faire de 15 a 21:08
suis obligé de m'arreter pour l'instant
j'essaierai un peu plus tard si besoin pour la suite 
[RDLS17de15_00à21_08.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/758708/RDLS17de15_00a21_08.pdf)

**Comment by desintoxiquezvous** [comment]
@Albapringe je viens de reprendre de 21 à la fin ça sera prêt dans 30mn

**Comment by desintoxiquezvous** [comment]
@Albapringe C'est terminé, voilà la suite et fin du texte
[RDLS17 21_08à28_55.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/759012/RDLS17.21_08a28_55.pdf)
Bon courage

**Comment by Bentham** [comment]
Ca va très vite avec cette technique les chatons ! Bravo desintoxiquezvous !

**Comment by Albapringe** [comment]
Parfait. Moi, j'approche très vite de la minute 15:00 :) J'incorporerai ça d'ici 1 heure.

**Comment by Vlavv** [comment]
Bonsoir,
À 24:15, je crois bien qu'il ne dit pas « Le premier, c'est le _discours_ d'Insoumis » mais « le _Discord_ Insoumis ». Ça m'a un peu surpris, d'ailleurs, parce que je connaissais pas l'existence de ce serveur Discord à ce moment-là, et c'est cette phrase qui m'a permis de le découvrir.
Bonne soirée et bravo à tous pour tout ce travail.

**Comment by desintoxiquezvous** [comment]
merci Vlavv pour cette relecture anticipée sur le pdf , ça permet d'avancer encore plus vite ...
je viens de découvrir le mot  "Discord" ; faut dire que je suis un vieil insoumis ... retraité ;-)

**Comment by Albapringe** [comment]
Terminé et prêt pour première relecture.

**Comment by Bentham** [comment]
Allez je me lance !

**Comment by Bentham** [comment]
Et bim c'est fait.

**Comment by Albapringe** [comment]
On clôt @Bentham ? Oui, allez, on peut te faire confiance et on clôt, les ST sont publiés ^^ New speed record !

**Comment by Bentham** [comment]
Les sous-titres sont en ligne ! Je crois qu'on n'a jamais été aussi rapides !!

**Comment by Bentham** [comment]
J'ai eu juste une hésitation sur le nom "Le Seuil" entre guillemets. Intuitivement je n'en aurais pas mis, mais j'ai laissé comme ça.

**Comment by Albapringe** [comment]
Oui, enfin, on peut corriger ça rapidos, si tu veux. Tu les enlèves, et je valide, comme ça, c'est expédié ^^

**Comment by Bentham** [comment]
Qu'est-ce que tu en dis toi ? Tu avais laissé les guillemets, est-ce que ça se justifie de ton point de vue ?

**Comment by Albapringe** [comment]
A priori, tu as raison, les guillemets n'ont pas lieu d'être avec les maisons d'édition. Donc, j'ai corrigé. Je te laisse confirmer ^^

**Comment by Bentham** [comment]
Bon, je peux pas valider apparemment. Pas très grave, c'est vraiment un point de détail. Y'aura bien quelqu'un qui passera validera tes modifs :)

Allez bonne nuit à tous !

**Comment by Bentham** [comment]
Ah ben si c'est bon en fait, j'ai dit n'importe quoi. \o/
