### ISSUE TITLE
[subtitles] [en] #RDLS17 : THÉO, MAYOTTE, HOLOGRAMME, YOUTUBE, ROUMANIE, CORRUPTION, FRANCE INSOUMISE 

### ISSUE THREAD

**Issue by Blange1** [jlm2017/jlm-video-subtitles#185]
# Video title

#RDLS17 : THÉO, MAYOTTE, HOLOGRAMME, YOUTUBE, ROUMANIE, CORRUPTION, FRANCE INSOUMISE

# URL

https://www.youtube.com/watch?v=579gZ1fsLVY&feature=youtu.be

# Youtube subtitles language

Anglais

# Duration

28:55

# Subtitles URL

https://www.youtube.com/timedtext_editor?lang=en&ui=se&action_mde_edit_form=1&bl=csp&ref=hub&tab=captions&v=579gZ1fsLVY

**Comment by Blange1** [comment]
6'33

**Comment by Flupignon** [comment]
Quelqu'un a terminé la vidéo. Je fais la première correction.

**Comment by Flupignon** [comment]
3:58

**Comment by Blange1** [comment]
Elle n'est pas terminée, en tout cas pas quand je clique dessus! J'ai pas eu beaucoup de temps ces derniers jours malheureusement
11'56

**Comment by Blange1** [comment]
17'02

**Comment by EgnaroRueluoc** [comment]
Les sous-titres anglais ont été validés et sont affichés.

**Comment by Irish39** [comment]
Toujours besoin d'un "2nd review" ou pas?

**Comment by Irish39** [comment]
J'ai commencé le 2ème relecture. Je compte terminer plus tard ce weekend.

**Comment by Irish39** [comment]
Still working on the 2nd review! Phew it's long!!!! There's a lot of rephrasing to work on. 😜

**Comment by Irish39** [comment]
J'ai vérifié et validé jusqu'au 11,57.
