### ISSUE TITLE
[subtitles] [fr] «Nous sommes tes fils, Révolution !» - Mélenchon citant Hugo en meeting

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#187]
# Video title
«Nous sommes tes fils, Révolution !» - Mélenchon citant Hugo en meeting

# URL
https://www.youtube.com/watch?v=B8xROYog8KE

# Youtube subtitles language
French

# Duration
2:28

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=B8xROYog8KE&action_mde_edit_form=1&ui=hd&ref=player&bl=vmp&lang=fr

**Comment by houlenn** [comment]
Sous-titres terminés !

**Comment by LucileDT** [comment]
@MasterSlip Bien penser à mettre le label rouge "Someone is working..." pour éviter les conflits de rédaction ;)

Sinon à part ça, merci beaucoup !

**Comment by houlenn** [comment]
Oui d'accord, j'avais juste fait celle-là avant de recevoir les droits, elle était déjà prête, c'est pour ça que j'avais pas eu besoin du label ! :)

Content de pouvoir être utile ;)

**Comment by desintoxiquezvous** [comment]
je commence 1ere relecture

**Comment by desintoxiquezvous** [comment]
fin de 1ère relecture
quelques retouches pour coller au texte original (ponctuations, majuscules, mises à la ligne)
remplacé "penser" par "panser" à 1:32 
prêt pour 2 eme relecture
