### ISSUE TITLE
[subtitles] [fr] « La France est le pays européen qui utilise le plus de pesticides »

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#188]
# Video title
« La France est le pays européen qui utilise le plus de pesticides »

# URL
https://www.youtube.com/watch?v=Ju3vITxmjQs&t=4s

# Youtube subtitles language
French

# Duration
1:09

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&lang=fr&ref=player&action_mde_edit_form=1&ui=hd&v=Ju3vITxmjQs&tab=captions

**Comment by houlenn** [comment]
Transcription terminée !

**Comment by Vimogo** [comment]
Je corrige.

**Comment by Vimogo** [comment]
Par contre il ne faut pas oublier de cliquer sur "envoyer pour examen", je crois que tu ne l'as pas fait.

**Comment by houlenn** [comment]
Ha effectivement, désolé !

**Comment by quidam34** [comment]
Une question pourquoi l'apparition soudaine de 4 vidéos (dont celle ci)  dans la même colonne , toute ouverte par @MasterSlip  ?

**Comment by LucileDT** [comment]
Toutes les personnes ici peuvent créer des issues quand ça leur semble important, en l'occurence @MasterSlip a créé les issues pour travailler dessus, il y en a déjà 3 sur les 4 qui ont été sous-titrées :)

**Comment by desintoxiquezvous** [comment]
1ere relecture ok

**Comment by quidam34** [comment]
oui luciledt mais n'est-on pas censé les inscrire ici avant de commencer ?

**Comment by LucileDT** [comment]
Vous voulez dire, que la personne qui crée les issues devrait être inscrite sur le Github ?
