### ISSUE TITLE
[subtitles] [fr] « Il faut sortir du nucléaire » - Jean-Luc Mélenchon

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#189]
# Video title
« Il faut sortir du nucléaire » - Jean-Luc Mélenchon

# URL
https://www.youtube.com/watch?v=TYmeiHryrCE

# Youtube subtitles language
French

# Duration
1:56

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&lang=fr&v=TYmeiHryrCE&tab=captions&action_mde_edit_form=1&bl=vmp&ui=hd

**Comment by houlenn** [comment]
Sous-titres terminés !

**Comment by desintoxiquezvous** [comment]
en relecture

**Comment by desintoxiquezvous** [comment]
@MasterSlip 1ere relecture terminée juste 1 ou 2 mots retouchés c'est ok

**Comment by Vimogo** [comment]
Je relis.

**Comment by Vimogo** [comment]
Sous-titres publiés, je clos.
