### ISSUE TITLE
[organisation] FAQ Github

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#19]
---
---

## Je ne comprends pas comment fonctionne Github T_T
Vous pouvez consulter le [manuel qui a été rédigé pour vous](https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-01.-Comment-utiliser-Github) !

---
---

## Quelle est la procédure à suivre pour s'impliquer dans le Github ?
Vous pouvez consulter [cette page](https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-02.-Comment-participer), qui détaille les étapes du processus qu'on essaye de mettre en place.

---
---

## Est-ce qu'il y a une page dédiée aux présentations des membres ?
Oui, c'est là #17 

---
---

## Et quid du groupe facebook, où trouver la page ?
Idem, c'est là-dedans :) #17 
Ou le lien direct : https://www.facebook.com/groups/1850626858504963

---
---

## Y a-t-il un endroit où on puisse communiquer en privé autre que Facebook ?
Oui, ici : https://chat.coders.jlm2017.fr
- Inscrivez-vous
- Envoyez un message privé à `luciledt`ou à `albapringe`
=> on vous ajoutera au groupe de discussion privé des sous-titreurs.

---
---

## Comment on fait dans Gmail pour filtrer les notifications de Github?
-  Dans la barre de recherche dans Gmail, entrez : notifications@github.com
-  Cliquez sur la petite flèche grise tout à droite dans la barre de recherche,
-  Dans le menu qui s'ouvre, tout en bas, cliquez sur "Créer un filtre à partir de cette recherche"
-  Dans le menu qui s'ouvre, si vous choisissez d'appliquer un libellé pour les mails et de les archiver, ils n'apparaîtront pas dans la boite de réception, mais uniquement dans le dossier du libellé :)

---
---

## Et d'ailleurs, comment on active les notifications de Github?
- Connectez-vous à Github
- Cliquez sur votre avatar et sélectionnez Settings
- Dans la colonne de gauche, cliquez sur Notifications
- Dans le cadre "How you receive notifications", activez les cases :
  - Automatically watch repositories
  - Participating Web
  - Watching Web

Vous pouvez activer ou désactiver les notifications par mail à votre convenance (pour ma part, je les garde active et j'applique un filtre dans ma boîte mail pour les mettre directement dans un dossier).

Quand vous actualiserez la page, vous verrez apparaître une petite cloche en haut à droite : ![capture du 2016-12-03 10 41 51](https://cloud.githubusercontent.com/assets/23707217/20858425/34fe478a-b945-11e6-8c02-856afdd743c7.png)

Il y aura une petite pastille bleue dessus si vous avez des notifications (par exemple, nouveau commentaire sur une issue que vous surveillez, ou création d'une issue, ou quelqu'un qui vous assigne à une issue...) : ![capture du 2016-12-03 10 41 23](https://cloud.githubusercontent.com/assets/23707217/20858426/3720dbb8-b945-11e6-8fbd-b77393cabb07.png)

---
---

## Pourquoi utiliser Github plutôt que de faire directement le travail à partir de la chaîne YouTube de JLM ?
Récemment, Github a mis en place l'onglet "Projet", qui permet de gérer des tâches. Plutôt que de créer un tableau Trello (ça ressemble exactement à ça, des colonnes avec des taches à faire), Github paraissait être une meilleure solution (et un peu moins "payez pour avoir plus" que Trello) pour offrir de la visibilité à l'avancée du processus de sous-titrage.

De plus, le fait d'avoir des tâches listées ailleurs que sur YouTube, ça permet d'éviter les doublons par exemple, car on a facilement une vue d'ensemble.

Enfin, les notifications Github permettent facilement de se tenir au courant de l'activité.

---
---

## Comment ajouter un label à une issue ?
Pour ajouter (ou enlever) un label à une issue, il faut cliquer sur Labels, à droite de l'issue, puis sélectionner dans la liste le ou les label.s à ajouter :
![Aperçu du bouton pour ajouter des labels](http://img11.hostingpics.net/pics/501568Capturedcran20161202015936.png)
### /!\ Il est possible que vous n'ayez pas accès à cette option : il faut être contributeur pour cela.
N'hésitez pas à rajouter un commentaire sur l'issue pour signaler que vous avez besoin de ce droit, les personnes qui ont les droits d'administration se chargeront de vous ajouter à la liste !

---
---

## Comment ajouter une issue à un des tableaux de gestion ?
Pour ajouter une nouvelle issue à un tableau, il faut cliquer sur Add card, en haut à droite du-dit tableau.
![Aperçu du truc sur lequel il faut cliquer](http://img15.hostingpics.net/pics/125279Capturedcran20170109221602.png)
Une liste contenant les issues s'ouvre, vous n'avez plus qu'à glisser-déposer l'issue dans la colonne du tableau que vous voulez.
### /!\ Il est possible que vous n'ayez pas accès à cette option : il faut être contributeur pour cela.
N'hésitez pas à rajouter un commentaire sur l'issue pour signaler que vous avez besoin de ce droit, les personnes qui ont les droits d'administration se chargeront de vous ajouter à la liste !

---
---

## Je sous-titre lentement, n'y a-t-il pas des solutions pour aller vite ?
Et bien oui, et @Bentham nous a fait l'honneur de réaliser une vidéo pour détailler un grand nombre d'astuces qui accélèrent le sous-titrage !
C'est par ici : https://github.com/jlm2017/jlm-video-subtitles/issues/129

---
---

**Comment by LucileDT** [comment]
@Ricyeam si tu veux mettre le lien vers le groupe facebook ici, pas de soucis ! 
(faudrait peut-être aussi désigner d'autres administrateurs pour éviter de refaire la même qu'avec @Flupignon)

**Comment by Ricyeam** [comment]
Added How to filter Github notifications mails in Gmail

**Comment by Ricyeam** [comment]
Added How to activate Github notifications

**Comment by LucileDT** [comment]
Added "Why Github"

**Comment by LucileDT** [comment]
Added "how to add a label to an issue"

**Comment by LucileDT** [comment]
Rajouté : astuces de @Bentham pour sous-titrer plus rapidement.

**Comment by LucileDT** [comment]
Rajouté : on ne peut pas mettre de label si on n'est pas contributeur.

**Comment by LucileDT** [comment]
Rajouté : comment ajouter une issue à un tableau de gestion

**Comment by LucileDT** [comment]
Rajouté : tchat extérieur.

**Comment by LucileDT** [comment]
Ici, des questions : https://github.com/jlm2017/jlm-video-subtitles/issues/166

**Comment by Goutte** [comment]
Dans l'idée, on ne devrait utiliser les issues que pour les discussions qui sont vouées à être closes un jour.
Pour tout le contenu explicatif, on pourrait/devrait utiliser le wiki, non ?

J'ai créé, pour vous montrer, une page du wiki avec le contenu da la FAQ écrite par @LucileDT : https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-FAQ

---

Vous en pensez quoi ? On fait comme ça ?

**Comment by LucileDT** [comment]
@Goutte jusqu'à présent, je rédigeais la doc dans le dépôt de code, donc le wiki ferait doublon. Soit on passe sur wiki tout le contenu, soit on passe tout en fichiers .md, mais les deux à la fois me semble compliqué.

De plus, j'en avais fait une issue pour que les gens puissent poser leurs questions ici.

Cependant, je suis tout à fait d'accord avec le fait que la FAQ n'a rien à faire dans une issue.

**Comment by Goutte** [comment]
Excellente remarque !

Je suis partisan du wiki (il sert à ça, est un peu plus facile à éditer, et génère un sommaire) ; bien sûr, dans ce cas, il faut garder un README à la racine du site, qui servira de portail vers la documentation.

**Comment by LucileDT** [comment]
Est-ce que le wiki supporte le Markdown ?

**Comment by Goutte** [comment]
Oui ! Il supporte tous les formats (mais je recommande markdown).

Je peux me charger de la migration, si tu as autre chose à faire ! :grin:

**Comment by LucileDT** [comment]
Would be really nice <3

**Comment by Goutte** [comment]
En plus, le wiki est un dépôt git lui aussi, donc facile à exporter !

**Comment by LucileDT** [comment]
gitception

**Comment by Efalconnet** [comment]
Bonjour, 

J'essaie d'accéder aux liens en haut de page (manuel et page), mais ils sont "morts".... ont-il été déplacés ?

Merci

Etienne

**Comment by Bentham** [comment]
C'est une bonne question. Peut-être que nos experts informaticiens @LucileDT et @Goutte ont une explication ?

**Comment by Goutte** [comment]
@Efalconnet @Bentham Oui, [tout est sur le wiki maintenant](https://github.com/jlm2017/jlm-video-subtitles/wiki).

N'hésitez pas à clarifier la documentation, si vous vous en sentez le courage !
