### ISSUE TITLE
[subtitles] [fr] «Le modèle de l'agricuture productiviste va s'effondrer» - Mélenchon

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#190]
# Video title
«Le modèle de l'agricuture productiviste va s'effondrer» - Mélenchon

# URL
https://www.youtube.com/watch?v=dml3hEbsL0c

# Youtube subtitles language
French

# Duration
2:16

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&bl=vmp&v=dml3hEbsL0c&tab=captions&ui=hd&lang=fr

**Comment by desintoxiquezvous** [comment]
je fais la 1ere relecture

**Comment by desintoxiquezvous** [comment]
@MasterSlip juste quelques négations rajoutées , ok pour 2eme relecture

**Comment by Vimogo** [comment]
Sous-titres publiés, je clos.
