### ISSUE TITLE
[subtitles] [fr] Hollande, Valls et les ministres : les 40 personnes qui bloquent le pays

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#191]
# Video title
Hollande, Valls et les ministres : les 40 personnes qui bloquent le pays

# URL
https://www.youtube.com/watch?v=LE6g4G-vGG4

# Youtube subtitles language
French

# Duration
19:43

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&bl=vmp&tab=captions&ref=player&action_mde_edit_form=1&ui=hd&v=LE6g4G-vGG4

**Comment by houlenn** [comment]
Sous-titres terminés !

**Comment by Vimogo** [comment]
Je fais la première relecture.

**Comment by Vimogo** [comment]
Fini.

**Comment by desintoxiquezvous** [comment]
Je commence la 2ème relecture

**Comment by desintoxiquezvous** [comment]
@Vimogo @MasterSlip il y a un problème dans les containers a partir de la mn 1:  (décalages)
quand j'essaie de modifier dans mon brouillon,ll se produit des bugs dans les containers suivants, donc je n'ai pas envoyé mes modifications sur Youtube, et donc j’arrête la relecture et je remets au stade précédent, voir si tu peux @Vimogo modifier a partir de ton propre brouillon, sinon je ne sais pas trop quoi faire , une autre personne peut être ?

**Comment by LucileDT** [comment]
@desintoxiquezvous il est possible de supprimer son brouillon : 
![capture du 2017-02-14 16 04 13](https://cloud.githubusercontent.com/assets/23707217/22934456/50e00a92-f2cf-11e6-9e6c-9d0e8e0f73e9.png)

Si jamais tu veux réessayer.

**Comment by obilya** [comment]
Fini la 2e relecture, je pense avoir résolu le problème dont vous parlez. Quand j'ai fait "envoyer", YouTube m'a dit qu'il y aurait encore un contrôle, est-ce qu'on déplace quand même cette vidéo dans les terminées ?

**Comment by LucileDT** [comment]
@obilya 
- si les sous-titres ne sont pas visibles en ligne, il faut laisser l'issue ici et signaler qu'il manque encore une révision.
- si les sous-titres sont en ligne, on peu déplacer l'issue et la passer en `Approved` :)

**Comment by obilya** [comment]
@LucileDT d'accord, merci.

Donc je confirme : il faut encore une révision.

**Comment by desintoxiquezvous** [comment]
bonjours à tous, désolé mais je ne peux pas me recoller à la 2ème relecture avant après demain , si personne ne l'a fait d'ici la, je le ferais

**Comment by DominDamid** [comment]
Je commence la 2ème relecture

**Comment by DominDamid** [comment]
Fini !
