### ISSUE TITLE
|subtitles] [fr] Manifestation du 23 juin contre la loi El Khomri : « Hollande doit rétropédaler » - Mélenchon

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#192]
# Video title
Manifestation du 23 juin contre la loi El Khomri : « Hollande doit rétropédaler » - Mélenchon

# URL
https://www.youtube.com/watch?v=SEaI67zXEAI

# Youtube subtitles language
French

# Duration
1:55

# Subtitles URL
https://www.youtube.com/timedtext_editor?lang=fr&bl=vmp&ui=hd&v=SEaI67zXEAI&tab=captions&ref=player&action_mde_edit_form=1

**Comment by houlenn** [comment]
Sous-titrage terminé !

**Comment by LucileDT** [comment]
En fait, tu es une vraie machine de guerre ! D:

**Comment by houlenn** [comment]
Je suis en vacances, ça passe agréablement le temps, alors je me rends utile :p

**Comment by desintoxiquezvous** [comment]
je relis

**Comment by desintoxiquezvous** [comment]
@MasterSlip parfait bon boulot ! 
prêt pour 2eme relecture
