### ISSUE TITLE
Pas vu à la télé (4) Panama papers et Société Générale

### ISSUE THREAD

**Issue by desintoxiquezvous** [jlm2017/jlm-video-subtitles#193]
# Video title
Pas vu à la télé (4) Panama papers et Société Générale

# URL
https://www.youtube.com/watch?v=5exxOVSOBps

# Youtube subtitles language
French

# Duration
56:36

# Subtitles URL
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&ref=player&lang=fr&v=5exxOVSOBps&tab=captions&bl=vmp

**Comment by desintoxiquezvous** [comment]
bonjour a tous
je viens d'effectuer en local l'ensemble du sous titrage
je n'ai pas fait du sous titrage tout a fait mot à mot (suite a des remarques de malentendants de ma famille qui n'avaient pas le temps de tout lire), j'ai donc fait quelques ellipses, enlevé les redites, les interjections, etc.. bien évidemment, le texte n'a pas été du tout interprété et est resté fidèle aux propos des intervenants... 
dans la mesure du possible j'ai effectué le sous titrage sur 2 lignes pour éviter que le sous titre soit tronqué lors de la lecture sur tablette

**Comment by JihedC** [comment]
Bonsoir,
je me lance dans la relecture, je vais essayer de faire au mieux vu que c'est la premiere fois que je touche a des sous-titres sur Youtube.

**Comment by JihedC** [comment]
Rebonsoir, 
je me suis penche sur les sous-titre de la video. Ils sont tres bien fait, je n'ai trouve que des modifications mineures a faire. 
Le gros soucis c'est que les sous-titres s'arretent a partir de la 43 eme minute.
J'ai commence a en ajouter un peu, mais j'avance assez lentement et surtout j'ai un clavier QWERTY ce qui rend les choses pas facile. 
Si quelqu'un veut bien m'aider la dessus...

**Comment by LucileDT** [comment]
@desintoxiquezvous Est-ce normal qu'il manque la fin des sous-titres ?

@JihedC je te conseille de passer à une autre vidéo, il y a un soucis avec celle-ci :/

**Comment by desintoxiquezvous** [comment]
@LucileDT @JihedC bonsoir, il y a un problème car j'avais envoyé l'ensemble du film , pas la peine de retaper la suite , je l'ai complet sous forme de pdf ,il y a du y avoir un bug 
bon: le pb c'est que je ne suis pas sur l'ordi sur lequel est le pdf , je n'y aurais  accès que demain dans  la matinée, 
je te propose de te poser le texte  ici demain et que tu remontes la partie manquante suivant ma méthode (sauf si tu préfère faire autrement)
https://youtu.be/JcU7XDS-BSM
je referais bien le boulot directement , mais apparemment quand on a passé la main pour relecture on ne peux plus y retoucher sans faire bugger 
je te recontacte demain

**Comment by LucileDT** [comment]
@desintoxiquezvous merci, super :+1:

**Comment by JihedC** [comment]
Pas de soucis merci!

**Comment by desintoxiquezvous** [comment]
@LucileDT @JihedC et voili-voila le pdf complet de pasvualatele4 !
[pasvualatele panamas papers.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/782675/pasvualatele.panamas.papers.pdf)
bon courage , et... on lâche rien !

**Comment by JihedC** [comment]
Merci

**Comment by JihedC** [comment]
@desintoxiquezvous C'est enorme le boulot que t'as fait pour le sous-titrage de cette video! J'ai comble le probleme de la fin et fait une premiere relecture. La video est prete pour une seconde relecture!

**Comment by desintoxiquezvous** [comment]
je fais toujours comme ça , reconnaissance d'une grande partie du texte, corrigée dans word avant la mise en containers (une dizaine de mn ou plus ) , ça va beaucoup plus vite pour la suite .
c'est ce qu'on a fait ici sur d'autres vidéos à plusieurs , pendant qu'un monte le début, on fait une reconnaissance vocale sur une autre partie du texte plus loin ( en accord avec, ou à la demande de celui qui monte) puis on pose ici un pdf partiel qui permet au 1er monteur de ne pas taper le texte dans les containers,  mais de le monter directement 
Avec un texte propre au départ la relecture est beaucoup plus rapide ;-)

**Comment by JihedC** [comment]
En effet ca a l'air bien plus efficace.  Tu tapes le texte en meme temps que tu ecoutes la video dans un fichier word que tu corriges et copies sur youtube ensuite, c'est bien ca? 
Quelle methode utilises tu pour mettre en containers aussi rapidement (la dizaine de minute), ca m'a pris 1-2 h pour les 13 min manquantes :P ? Il y a un secret?

**Comment by desintoxiquezvous** [comment]
regarde ma méthode ici issue  #171 

dans un premier temps reconnaissance vocale selon la méthode de @bentham ,(je tape trop lentement pour écrire directement)
https://youtu.be/q68KAKVCOP4
pour la reco vocale je me sers comme @bentham de google doc dans Chrome

moi, je procède comme suit:
- j'écoute sur mon ipad ou mac book ,au casque, le discours, phrase par phrase, je mets en pause entre chaque , et je répète la phrase dans google doc sur mon imac avec un micro externe (meilleure reconnaissance que le micro de la webcam incorporée ), j'en fait une dizaine de mn (ce peut être une phrase longue ou une partie de phrase sachant que la reco tient compte du contexte de la phrase pour une meilleure transcription)
- ensuite retouche du texte dans word avec dictionnaire pour retoucher un max de fautes (le tout me prends environ 1h pour 5 a 10 mn de texte )
- ensuite copie de l'ensemble du texte corrigé dans le 1er container puis création dynamique des containers par coupe chronologique 
voir ci dessous 
https://youtu.be/JcU7XDS-BSM

ça marche super bien c'est presque du temps réel si on a pris soin de corriger le maximum de fautes avant
comme je t'ai dis si tu commence un sous titrage tu peux faire un appel au peuple pour que quelqu'un t'avance en t'envoyant un pdf d'une partie du texte un peu plus loin (attention ne pas travailler SUR le sous titrage dans youtube en même temps qu'un autre ça met des bugs ....)
essaie et tiens moi au courant ;-)

**Comment by desintoxiquezvous** [comment]
juste une précision: il faut avoir un compte gmail et Chrome comme navigateur, tu va dans ton googledoc tu crée un nouveau document vierge , et tu fais la reconnaissance vocale DANS googledoc à l'aide de l'outil reconnaissance vocale fourni, ensuite copier collé du texte dans word ou autre traitement de texte qui possède un correcteur orthographique..

**Comment by Milsabor** [comment]
Hello ! J'attaque la seconde relecture :) Il me faudrait également les droits pour les labels SVP ^^
Je me permets d'ajouter les sous-titres des slogans sur les clips de la Société Générale, car leurs chants ont un côté sarcastique et servent, à mon avis, le propos du zapping.

**Comment by Milsabor** [comment]
Interruption de la correction à 30:50.3, je reprends demain avant ou après le chiffrage ^^

**Comment by JihedC** [comment]
ok merci pour l'info je vais tenter de faire pareil

**Comment by LucileDT** [comment]
@Milsabor je t'ai ajouté.e aux collaborateurs, vérifie tes mails :D

**Comment by Salem2612** [comment]
J'ai terminé la 2eme relecture depuis l'endoit où s'était arrêté @Milsabor jusqu'à la fin. N'ayant pas les droits pour changer les labels, je vous laisse le faire ou me donner des droits :) Youtube n'a pourtant pas encore mis les sous titres publiques. Je ne sais pas ce qui le bloque.

**Comment by Salem2612** [comment]
Je ne comprends pourquoi Youtube ne publie pas ces sous titres. La 2eme relecture a été faite. A moins que ce ne soit pas automatique ?

**Comment by Milsabor** [comment]
Bonsoir ! Désolé pour la pause et merci pour l'ajout, @LucileDT ! Merci également à toi, @Salem2612 , d'avoir fini le taf.
Pour les sous-titres, en effet, ils n'apparaissent dans la vidéo qu'une fois qu'ils ont été validés ^^ Par contre, est-ce que le seul fait de mettre le label [6] les met en ligne, ou bien ça passe par le CM?

**Comment by LucileDT** [comment]
@Milsabor C'est la seconde vérification qui met en ligne les sous-titres, donc s'ils ne sont pas visibles, ils n'ont pas à avoir le tag `Process: [6] Approved`.

**Comment by Milsabor** [comment]
Oups ! Désolé d'avoir mis le label avant que ce ne soit validé sur Youtube, j'ai changé ça. Par contre, je ne suis pas sûr que les modifications de @Salem2612 aient été enregistrées puisqu'il n'y a pas de validation (et que les sous-titres ont l'air d'être "dans le même état" que quand je les avais laissés l'autre fois).
A moins que @Salem2612 tu ne te manifestes, je peux reprendre là où j'en étais resté pour progresser le Schmilblick.

**Comment by Salem2612** [comment]
Je pense que mes modifications ont été enregistrées parce que je les vois quand je souhaite les modifier. Par contre YouTube ne donne aucune indication sur le nombre de relectures effectuées et ce qu'il reste à faire jusqu'à leur publication.

**Comment by desintoxiquezvous** [comment]
tes modifications ne sont réellement enregistrées que si tu a cliqué sur le bouton  "envoyer" à Youtube sinon tu ne vois que ton propre brouillon qui est enregistré en local sur ton ordinateur

**Comment by Milsabor** [comment]
Bon, finalement, il suffisait que je relance la machine en approuvant moi-même, désolé du manque de maîtrise de l'outil YouTube.
C'est en ligne, @Salem2612 peux-tu vérifier que ta partie a bien été prise en compte, s'il-te-plaît ?

**Comment by Salem2612** [comment]
C'est bon ma partie a été prise en compte.
