### ISSUE TITLE
[subtitles] [fr] Attentats : bobards médiatiques autour des propos de Jean-Luc Mélenchon​

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#194]
# Video title
Attentats : bobards médiatiques autour des propos de Jean-Luc Mélenchon​

# URL
https://www.youtube.com/watch?v=UjP4RCur4Hk

# Youtube subtitles language
French

# Duration
2:25

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&ref=player&lang=fr&v=UjP4RCur4Hk&action_mde_edit_form=1&ui=hd&bl=vmp

**Comment by houlenn** [comment]
Pause : 1:06

**Comment by houlenn** [comment]
Terminé !

**Comment by desintoxiquezvous** [comment]
1ère relecture faite.
Remplacé Ali Baddou par Ali Badou.

**Comment by obilya** [comment]
Bonsoir tout le monde, j'ai fait la 2e relecture de cette vidéo et l'ai approuvée sur YouTube mais comme je ne suis pas encore contributeur (et novice) je vous en préviens ici car je ne peux pas faire glisser-déposer vers la catégorie "vidéo mise en ligne" dans le tableau général.

**Comment by LucileDT** [comment]
@obilya tu es ajoutée aux contributeurices :D Vérifie tes mails :)
