### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - THÉO, 6E RÉPUBLIQUE, SYRIE, INDÉPENDANCE DE LA FRANCE, OTAN, NUCLÉAIRE, TERRORISME

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#195]
# Video titre
MÉLENCHON - THÉO, 6E RÉPUBLIQUE, SYRIE, INDÉPENDANCE DE LA FRANCE, OTAN, NUCLÉAIRE, TERRORISME

# Video date de mise en ligne 👍 
13/02/2017

# URL
https://youtu.be/Se7QDwql_-s

# Youtube sous titre langue
Sous titre language : Français

# Durée : 
1h15

# Sous titre URL
https://www.youtube.com/timedtext_editor?ref=wt&v=Se7QDwql_-s&ui=hd&lang=fr&action_mde_edit_form=1&bl=watch&tab=captions

**Comment by quidam34** [comment]
On s'en occupe !

**Comment by PetiteKorat** [comment]
Est-ce qu'il serait possible de travailler à plusieurs sur ce projet ?

**Comment by Bentham** [comment]
quidam34 a ouvert son propre forum et travaille là-dessus avec quelques autres. Pour des raisons techniques, nous ne pouvons pas intervenir sur les vidéos dont ils s'occupent. Tu peux faire une demande d'inscription sur http://www.sous-titreur.forum-insoumis.fr/

**Comment by PetiteKorat** [comment]
Oh bah mince.... Comment réussir à se mettre tous d'accord si on s'étale un peu partout ?

**Comment by Bentham** [comment]
Nous avons essayé de discuter avec quidam34 pour que tout le monde se mette aux mêmes outils, mais sans succès.

**Comment by PetiteKorat** [comment]
Bah mince alors... C'est fortement dommage. Du coup, j'en déduis qu'à chaque fois que Quidam dit se charger d'un projet, il ne sert à rien d'intervenir dessus. C'est exact ?

**Comment by Bentham** [comment]
C'est cela. Du coup il plante son drapeau ici dès qu'une vidéo l'intéresse, et nous avons juste à attendre.

**Comment by LucileDT** [comment]
Après, il est possible de travailler avec eux via leur forum :)

**Comment by Bentham** [comment]
En ce qui me concerne, il a refusé de m'inscrire, mais vous pouvez essayer de votre côté :)

**Comment by quidam34** [comment]
Bonjour, oui, il est toujours possible de venir s'inscrire sur le forum, si l'idée n'est pas de venir débaucher de quelque manière que ce soit ! Pour l'instant les sous-titreurs de mon forum viennent exclusivement de mes contacts Facebook de mes 2900 "amis" presque tous Mélenchoniste. Mais, cela va, cela vient... On n'est pas compatible dans notre manière de travailler. J'essaie, encore toutes les méthodes possibles pour gagner du temps. Par exemple, l'un fournit le fichier texte, le corrige au correcteur automatique (j'ai même pris un abonnement pour cela sur un site par exemple) Je considère que c'est une première correction... Ensuite, une personne forte en orthographe fait une lecture, un troisième fait la mise en place sur la vidéo. De plus, pour essayer d'être plus réactif sur une vidéo, nous avons la possibilité de travailler a deux sur une vidéo... Comment ça marche ? Tout simplement, je mets en ligne la copie conforme d'une vidéo de jml sur mon compte perso Youtube.  Je crée ensuite sur le forum deux sujets pour la même vidéo, partie 1 et partie 2 . Voilà, vous savez tout, mais ce qui reste le plus rare, c'est la main d'œuvre ! Qui veut venir s'inscrire, s'inscrit sans problème !

**Comment by quidam34** [comment]
Bonjour, oui, il est toujours possible de venir s'inscrire sur le forum, si l'idée n'est pas de venir débaucher de quelque manière que ce soit ! Pour l'instant les sous-titreurs de mon forum viennent exclusivement de mes contacts Facebook de mes 2900 "amis" presque tous Mélenchoniste. Mais, cela va, cela vient... On n'est pas compatible dans notre manière de travailler. J'essaie, encore toutes les méthodes possibles pour gagner du temps. Par exemple, l'un fournit le fichier texte, le corrige au correcteur automatique (j'ai même pris un abonnement pour cela sur un site par exemple) Je considère que c'est une première correction... Ensuite, une personne forte en orthographe fait une lecture, un troisième fait la mise en place sur la vidéo. De plus, pour essayer d'être plus réactif sur une vidéo, nous avons la possibilité de travailler a deux sur une vidéo... Comment ça marche ? Tout simplement, je mets en ligne la copie conforme d'une vidéo de jml sur mon compte perso Youtube.  Je crée ensuite sur le forum deux sujets pour la même vidéo, partie 1 et partie 2 . Voilà, vous savez tout, mais ce qui reste le plus rare, c'est la main d'œuvre ! Qui veut venir s'inscrire, s'inscrit sans problème !

**Comment by Goutte** [comment]
@quidam34 _Mélenchoniste_ :man_facepalming:  --> **Insoumis** ! Ne suivez pas l'homme, mais l'idée ! Ça a l'air de rien, je sais, mais c'est _essentiel_ !

@PetiteKorat Désolé, mais c'est fort compliqué d'unifier les méthodes de travail de tout le monde. Dans l'idée, tu devrais pouvoir contribuer sans rien demander à personne, mais @quidam34 refuse catégoriquement de fonctionner de cette manière et va écraser brutalement ta contribution.

---

Quelques notes :

- Quel est le nom complet de JBB ?
- Revenir à la ligne quand le locuteur change me semble plus lisible.

**Comment by quidam34** [comment]
Putain il y a quelqu'un qui a continué ici le sous titrage ou pas  ? ou pas ? je rappelle qu'il ne faut pas toucher a cette vidéo sur ce site c'est le forum qui s'en occupe.

**Comment by Goutte** [comment]
> Putain il y a quelqu'un qui a continué ici le sous titrage ou pas ? ou pas ? je rappelle qu'il ne faut pas toucher a cette vidéo sur ce site c'est le forum qui s'en occupe.

@quidam34 Merci de rester civil. Et de vous relire, aussi.

**Comment by quidam34** [comment]
ca répond pas a ma question ....désolé

**Comment by Goutte** [comment]
Non, car personne ne peut répondre à votre question. N'importe qui peut éditer les sous-titres, sans rien demander à personne ; ni ici, ni sur votre forum privé. Il est _évident_ que quelqu'un peut continuer les sous-titres sans rien nous demander, ni à nous ni à vous. C'est pourquoi votre méthode brutale de travail est une très mauvaise méthode de travail. Vous n'aviez toujours pas compris ça ?

**Comment by quidam34** [comment]
Peut-être mais l'immobilisme et faire comme ca parce qu'on a toujours fait comme ca , je cherche l’efficacité et je l'ai trouvé.  Pour ma part 1 personne (pas tout le forum ) 1 personne met tout le texte sur un fichier texte, l'autre fait la correction et la troisième met cela en place sur le forum. On gagne beaucoup de temps ! bon pas grave je mets un champs qui indique de pas travailler sur nos vidéo dans youtube.  bonne soirée

**Comment by LucileDT** [comment]
@quidam34 un grand nombre de personnes sous-titre sans être rattaché au Github, vous allez faire assez souvent face au problème des sous-titres rajoutés par des bonnes volontés extérieures.

**Comment by quidam34** [comment]
Petit nouvelle de notre travail  : nous en sommes au trois quart meme si ce n'est pas visible sur la la vidéo.

**Comment by quidam34** [comment]
Nous avons mis tout le texte sur un fichier texte , il a été corrigé par 'scribens' mais nous somme en manque d'une correction manuelle. Je vais fais faire une demande ici pour voir...

**Comment by LucileDT** [comment]
@quidam34 de quoi avez-vous besoin exactement ?

**Comment by quidam34** [comment]
Bientôt finit dans la journée je pense

**Comment by quidam34** [comment]
merci @LucileDT nous avions besoin d'un correcteur du texte complet .. Merci quand même. Nous avons trouvé une très bonne correctrice maintenant.

**Comment by quidam34** [comment]
@LucileDT pourriez vous rappeler au utilisateur d'ici qu'on ne touche pas a cette vidéo même si elle je la met dans la colonne a corriger,  meme si au demeurant elle est aussi avancé qu'une de vos vidéos dans cette colonne, mais d'une autre manière !  ! 

c'est pour cela que je l'ai remis là sans changer le label. Merci

**Comment by quidam34** [comment]
Petit rappelle de notre méthode de travail : pour que vous ne vous anormal de ne rien voir depuis quatre jours, rappel de notre méthode de travail.

    Mise sur papier de tout le texte de la vidéo.
    2 ) Mise en format .txt en vocal, ou au clavier (selon la personne qui le fait) de tout le texte.
    3 ) Première correction automatique de toutes les fautes (Scriben entre autres, service payant )
    https://www.scribens.fr/
    Deuxièmement correction humaine.
    Envois sur Youtube de tout le texte, youtube ce charge de la création des champs et du réglage de la synchronisation.
    À noter, il peut donc se passer bien des jours avant que rien apparaisse sur la vidéo. Évidemment ! A noter que pour cette vidéo, il ne reste plus que dix minutes à mettre en écrit et que la mise en fichier .txt est déjà bien avancé.
    Deux personnes en simultané s'occupent du réglage, humain cette fois, de la synchronisation, mais aussi du contenu de la cellule dont le découpage n'est pas forcements bien fait. (c'est là qu'en était la vidéo du double meeting) Il était donc inutile de crier au loup.
    Le travail est fini !

Donc, si j'ai met le fichier dans la collone Deuxième correction, c'est parce que c'est là qu'on en est, en équivalence de travail. De plus nous nous occupons de tout de a à Z . Donc cela ne veut pas dir pour autant qu'il faut que vous en occupiez !

**Comment by quidam34** [comment]
Sera mis en ligne ce soir
