### ISSUE TITLE
[subtitles] [de] Les 10 premières mesures de Mélenchon à l'Elysée

### ISSUE THREAD

**Issue by obilya** [jlm2017/jlm-video-subtitles#197]
# Video title
Les 10 premières mesures de Mélenchon à l'Elysée

# URL
https://www.youtube.com/watch?v=brJu7qMJdVc

# Youtube subtitles language
German

# Duration
6:48

# Subtitles URL
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&ui=hd&bl=vmp&lang=de&v=brJu7qMJdVc&ref=player&tab=captions

**Comment by obilya** [comment]
Je ne trouve pas le label "Language: German", comment peut-on le créer ? (je pose aussi ma question dans #37 )

**Comment by obilya** [comment]
Et voilà ma première traduction en allemand, germanistes à vous de jouer ! ;)

**Comment by Flupignon** [comment]
Nice job ;)

**Comment by Bentham** [comment]
Bravo @obilya ! Merci pour ta participation !

**Comment by Oxil-2** [comment]
Je suis en train de relire et de faire 2/3 modifs. Tu plaisantais quand tu disais que tu n'avais "qu'un niveau licence" ? ;-)

**Comment by obilya** [comment]
@Oxil-2  c'est trop gentil :) je manque surtout de vocabulaire (je cherche 1 mot sur 3 dans le dico) mais je crois que pour la grammaire ça va, je n'ai pas trop perdu la main (enfin la langue haha)

**Comment by Oxil-2** [comment]
Voilà, relecture faite, surtout des corrections de détail en fait :) beau boulot !

Par contre, je trouve un peu étrange d'avoir les sous-titres français incrustés dans la vidéo et les sous-titres allemands par dessus. On peut pas faire autrement ?

**Comment by LucileDT** [comment]
@Oxil-2 non, on ne peut pas faire autrement, désolée :(

**Comment by Oxil-2** [comment]
Il nous faudrait un troisième relecteur par contre, non ? pour valider la traduction ?

**Comment by obilya** [comment]
Oui exactement ! J'avais ouvert une issue pour recruter des germanophones mais je ne sais pas si elle a été très remarquée.

**Comment by Oxil-2** [comment]
Je vais commenter sur le groupe FB pour attirer des valeureux ;-)

**Comment by Galeon07** [comment]
Bonsoir / bonjour 

J'ai fait une relecture des sous-titres de la vidéo. J'ai juste fait quelques corrections à la partie sur l'énergie :
- J'ai remplacé la traduction de quelques concepts par des façons de dire plus répandues en allemand (par exemple Kernenergie en Atomkraft, ou "Windparks aufs See" en Offshore-Windparks)
- et j'ai simplifié quelques phrases ou changé la structure parfois pour avoir quelque chose qui sonne un peu plus allemand (mais c'était vraiment très en surface) :)

Le reste était très bien. :)
Du coup, j'ai validé, mais je sais pas si ça a marché, ça me met que j'ai "envoyé" ma contribution, est-ce que c'est bon quand même ? (désolé si j'ai fait une erreur, je suis nouveau dans le sous-titrage de vidéos Youtube).. pour l'instant les sous-titres sont pas publiés sur la vidéo. :/

**Comment by Galeon07** [comment]
Bon en tout cas, les sous-titres ne sont pas publiés donc j'ai du faire une connerie. J'avais cliqué sur le lien en haut de l'issue, mais c'était peut-être pas là que je devais cliquer pour la validation ? Si c'est le cas, mes plus plates excuses, j'espère qu'à cause de moi le processus ne va pas recommencer à zéro...

**Comment by Goutte** [comment]
Oui, s'il te dit que tu as "Envoyé", c'est que tu as bien tout bon. Youtube va attendre que quelqu'un vienne pour cliquer sur "Looks Good". J'ai fourni la première validation, il en faut une deuxième.

En fait, si je comprends bien, pour Youtube, si tu corriges des choses, ça ne compte pas comme une validation, mais une contribution :wink:

**Comment by Galeon07** [comment]
Ca semble logique en effet ^^
Bon bah désolé d'avoir fait un peu de zèle...

**Comment by LucileDT** [comment]
@Galeon07 au contraire, on a besoin de gens pour corriger, c'est le but <3

**Comment by Galeon07** [comment]
Du coup je relance ça, car au final les sous-titres ont toujours pas été publiés :/ y a-t-il des gens qui peuvent les valider ?

**Comment by Goutte** [comment]
Closed by 7837acbb0c6d90a997bc60acd27b6fd82e0019b5
