### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - JE PROPOSE UN DÉBAT À FRANÇOIS FILLON 

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#20]
# Video Title
MÉLENCHON - JE PROPOSE UN DÉBAT À FRANÇOIS FILLON 

# URL
https://www.youtube.com/watch?v=M7Ke8LwzQAk

# Duration
5:42

# Youtube subtitles language
Français

# Subtitles URL
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&tab=captions&ui=hd&bl=vmp&ref=player&forceedit=timedtext&v=M7Ke8LwzQAk&lang=fr

**Comment by Ricyeam** [comment]
Dario par mail à Ricyeam
"Salut je sui en train de faire les sous titres de Mélenchon-je propose un débat à francois fillon"

**Comment by Ricyeam** [comment]
Dario à Ricyeam, par mail

"salut, j'ai fini de transcrire Mélenchon-je propose un débat à Francois Fillon, qui attend pour vérification"

**Comment by Bentham** [comment]
Corrigé et approuvé. A valider de votre côté !

**Comment by dalipokim** [comment]
Qu'est ce qu'il reste a faire ?

**Comment by bayasahra** [comment]
Corrigé et approuvé également !!

**Comment by dalipokim** [comment]
Salut tout le monde ! J'aimerais savoir, que reste t-il a transcrire en
Français ?

2016-11-29 10:46 GMT+01:00 Ricyeam <notifications@github.com>:

**Comment by bayasahra** [comment]
pour l'instant @dalipokim y'a deux issues en cours pour le sous titrage français moi même et champi sommes en train de les faire... donc quand elles seront prêtes tu pourras vérifier et valider.. ou tu peux également aller sur le site de mélenchon choisir la vidéo que tu veux sous titrer et te créer une issue ^^... si tu ne sais pas encore comment créer d'issue je pourrais éventuellement te la créer :)

**Comment by dalipokim** [comment]
Ok merci ! Il y a bien celle avec Mamère , j'en ai fait 10 mn déjà, mais
c'est un pavé ! Créer une issue ? que veux tu dire ?

**Comment by bayasahra** [comment]
@dalipokim je vais te la créer... tu as regardé un peu comment fonctionne le gith ou pas ? :) 
tu l'utilises comment ?

**Comment by dalipokim** [comment]
non, a vrai dire ca me gonfle un peu...J'utilise au minimum ! je vois qu'il
y a des vidéos a transcrire ou a corriger, les contributeurs ca ne va pas
plus loin !

2016-11-29 17:58 GMT+01:00 Baya <notifications@github.com>:

**Comment by bayasahra** [comment]
@dalipokim je viens de créer la vidéo ( l'issue) pour toi :) au lieu d'écrire tes messages ici tu vas les écrire sous la vidéo de mamère ... tu la vois ? et quand tu arrêtes ton travail tu laisses un message dessous pour nous signaler à quel timing tu t'es arrêté :) je t'aurais bien assigné dessus mais ton nom n'apparaît pas ....

**Comment by dalipokim** [comment]
cool merci c'est plus clair ! Donc il y a deux url, celle de la vidéo
originale et celle en cours de travail. Excellent je retrouve mon travail
déjà fait ! Ca me rassure ! Au boulot et merci encore !

**Comment by bayasahra** [comment]
@dalipokim exactement ... tu as les 2 URL ;) mais de rien
