### ISSUE TITLE
[subtitles] [eng] MÉLENCHON : «LE CETA AGGRAVERA LA CRISE ÉCOLOGIQUE ET SOCIALE»

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#201]
# Video title

MÉLENCHON : «LE CETA AGGRAVERA LA CRISE ÉCOLOGIQUE ET SOCIALE»

# URL

https://www.youtube.com/watch?v=khlMSRZmDAE

# Youtube subtitles language

Anglais

# Duration

01:20

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&lang=en&ui=hd&v=khlMSRZmDAE&ref=player&tab=captions

**Comment by fkevv** [comment]
genrations -> generations Sinon je n'ai pas trouvé d'erreurs :)

**Comment by fkevv** [comment]
Les sous-titres sont déjà publié apparemment.
