### ISSUE TITLE
[subtitles] [en] NOUVEAU TRAITÉ EUROPÉEN : LA FINANCE AVANT LE PEUPLE !

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#202]
# Video title

NOUVEAU TRAITÉ EUROPÉEN : LA FINANCE AVANT LE PEUPLE !

# URL

https://www.youtube.com/watch?v=YlBapm_yXRI

# Youtube subtitles language

Anglais

# Duration

01:04

# Subtitles URL

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&tab=captions&lang=en&v=YlBapm_yXRI&bl=vmp&ui=hd&ref=player

**Comment by Goutte** [comment]
Beau travail !

J'ai mis `people` au singulier, ça me fait bizarre de le voir au pluriel, je ne sais pas si ça se fait.

Je valide :+1:

**Comment by Flupignon** [comment]
Peoples = peuples (pas gens), ça me fait bizarre aussi mais ça se dit ;)

**Comment by Goutte** [comment]
Oups, j'ai peut-être été un peu vite en besogne, alors. Je ne l'ai jamais vu auparavant ! Je demanderai conseil à mon amie américaine tout à l'heure, en contexte, et je corrigerai en conséquence.

---

Edit: j'ai remis comme c'était !
