### ISSUE TITLE
[subtitles] [fr] Les Français en ont par-dessus la tête des querelles religieuses - Mélenchon

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#204]
# Video title
Les Français en ont par-dessus la tête des querelles religieuses - Mélenchon

# URL
https://www.youtube.com/watch?v=kozDd85bN_M

# Youtube subtitles language
French

# Duration
7:55

# Subtitles URL
https://www.youtube.com/timedtext_editor?ui=hd&bl=vmp&action_mde_edit_form=1&lang=fr&ref=player&tab=captions&v=kozDd85bN_M

**Comment by houlenn** [comment]
Arrêté à 5:25

**Comment by houlenn** [comment]
Terminé ! (désolé j'avais oublié le Someone is working :( )

**Comment by LucileDT** [comment]
Pas de soucis @MasterSlip ;)

**Comment by desintoxiquezvous** [comment]
Je commence la 1ère relecture

**Comment by desintoxiquezvous** [comment]
1ère relecture terminée. Modifs mineures (négations) remplacé à 5:22 "????" par C'est Tahar, vous venez".
Bon pour 2ème relecture

**Comment by Salem2612** [comment]
Bonjour, je veux bien faire la 2eme relecture, mais je n'ai pas encore les droits.

**Comment by Salem2612** [comment]
2eme relecture faite, c'était pas très long 7 minutes. Il y avait 2 ou 3 mauvais mots : "de" à la place de "que"...

**Comment by houlenn** [comment]
Sous-titres en ligne, je clos.

**Comment by Goutte** [comment]
@MasterSlip Je confirme, ils sont là : https://github.com/jlm2017/jlm-video-subtitles/blob/7a304a706b9053b64ee8c740d2e18027171a6639/subtitles/2016/2016-08-25.les-francais-en-ont-par-dessus-la-tete-des-querelles-religieuses-melenchon.fr.SZ0tP13GRTG7QvJldyDdjBaHQEiHV8k4.vtt

Beau travail à tous !
