### ISSUE TITLE
[subtitles] [fr] #RDLS18 - CETA, OTAN, EUROPE, SECOURS CATHOLIQUE À CALAIS

### ISSUE THREAD

**Issue by houlenn** [jlm2017/jlm-video-subtitles#205]
# Video title
#RDLS18 - CETA, OTAN, EUROPE, SECOURS CATHOLIQUE À CALAIS

# URL
https://www.youtube.com/watch?v=qhJVmuEtII8

# Youtube subtitles language
French

# Duration
30:34

# Subtitles URL
https://www.youtube.com/timedtext_editor?ui=hd&action_mde_edit_form=1&bl=vmp&ref=player&v=qhJVmuEtII8&tab=captions&lang=fr

**Comment by Shadokiller** [comment]
Pardon, je me suis planté de label! Merci MasterSlip! ;)

**Comment by Albapringe** [comment]
Où en est-on, sur cette issue ? Je ne vois rien d'effectué quand je vais sur le sous-titrage.

**Comment by Ctorres01** [comment]
Tu as bien mis "français"?

**Comment by Ctorres01** [comment]
Perso je vois jusqu'à un peu plus de 11min avec la fin à arranger apparemment. Je continuerais demain.

**Comment by Albapringe** [comment]
Ouaip, c'est bon :)

**Comment by jbtromain** [comment]
j'avais fait de 11min à 16min env, jusqu'a la fin du CETA en fait. Vous ne le voyez pas ? :/

**Comment by houlenn** [comment]
Non @jbtromain, les sous-titres s'arrêtent à 11 minutes. Tu les as bien envoyés ? :/

**Comment by desintoxiquezvous** [comment]
@MasterSlip @jbtromain je les vois jusqu'a 14:02

**Comment by Ctorres01** [comment]
Idem... Je vais continuer un peu aujourd'hui

**Comment by desintoxiquezvous** [comment]
@Shadokiller @jbtromain attention , ne travaillez pas en même temps sur les sous titres DANS Youtube: risque de bug et disparitions de sous titres, ça nous est déjà arrivé... utilisez les labels pour savoir qui est dessus. l'un APRÈS l'autre.....

**Comment by Ctorres01** [comment]
Oui t'inquiètes pas pour ça

**Comment by jbtromain** [comment]
ok, en fait je n'avais pas osé appuyer sur "envoyer" car je n'étais pas sur de ce que ça faisait ^^ Du coup, ça s'enregistrait comme brouillon,et je pensais que ce brouillon était commun

**Comment by LucileDT** [comment]
@jbtromain et non, malheureusement... Vivement que les sous-titres fonctionnent comme les fichiers Google Drive !

**Comment by desintoxiquezvous** [comment]
@jbtromain, @Shadokiller  Avez vous besoin d'un coup de main pour continuer ? un fichier texte par exemple ?

**Comment by desintoxiquezvous** [comment]
@jbtromain @Shadokiller si besoin, voilà le texte de 19:00 à la fin.
[RDLS18 de 19min à la fin.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/799138/RDLS18.de.19min.a.la.fin.pdf)

**Comment by Bentham** [comment]
En ce moment j'ai trop de travail pour m'y mettre, mais je suis très étonné de voir que cette RDLS n'est toujours pas bouclée. Avec Albapringe et desintoxiquezvous on avait fait la 17 en entier le jour même de sa publication...

**Comment by desintoxiquezvous** [comment]
@Bentham je viens de poser  le texte de 19:00 à la fin pour avancer ,mais pas de nouvelles ....

**Comment by desintoxiquezvous** [comment]
bon, @Bentham @jbtromain @Shadokiller ça fait déjà plus d'une semaine que ça traine, comme personne n'a l'air de bosser dessus, je m'y colle avant que la RDLS suivante n'arrive....
je devrais avoir fini ce soir , merci de ne rien envoyer avant pour ne pas mettre le buzz
je vous tiens au courant de l'avancement

**Comment by desintoxiquezvous** [comment]
bon, c'est terminé , je met en 1ere relecture

**Comment by Salem2612** [comment]
Je fais la 1ere relecture.

**Comment by Salem2612** [comment]
1ere relecture terminée et envoyée.

**Comment by Goutte** [comment]
Deuxième relecture faite !

**Comment by Salem2612** [comment]
Youtube n'a pas encore publié. Qu'est ce qu'il se passe encore ? De mon coté c'est noté comme "Envoyé" en vert et je n'ai pas d'autres boutons que "Quitter" et "Modifier".

**Comment by Goutte** [comment]
C'est probablement normal, j'ai fait quelques changements de ponctuation. Il faut que d'autres personnes valident ; ou il faut juste un peu de temps ?

**Comment by Albapringe** [comment]
Comme il y a eu 2 relectures, je pars du principe que tout est correct, j'ai validé pour que les sous-titres soient publiés. Je clos l'issue.

**Comment by LucileDT** [comment]
@Albapringe Du coup les sous-titres sont visibles en ligne ?

**Comment by Salem2612** [comment]
@LucileDT : Oui @Albapringe a forcé leur mise en ligne.
