### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «2017 EST UNE ÉLECTION COUP DE BALAI»

### ISSUE THREAD

**Issue by Galeon07** [jlm2017/jlm-video-subtitles#209]
# Video title
MÉLENCHON : «2017 EST UNE ÉLECTION COUP DE BALAI»

# URL
https://www.youtube.com/watch?v=7am2L_ur41E

# Youtube subtitles language
French

# Duration
23:05

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=watch&bl=vmp&action_mde_edit_form=1&lang=fr&v=7am2L_ur41E&tab=captions

**Comment by Galeon07** [comment]
J'ai fini de sous-titrer la vidéo. 
C'est la première fois que je sous-titre une vidéo sur Youtube, donc si vous avez des conseils ou des remarques pour m'améliorer, c'est super ! :)

**Comment by LucileDT** [comment]
Félicitation @Galeon07 !

**Comment by JihedC** [comment]
Salut!
Je me charge de la relecture, j'essaie de faire ca dans la semaine :)

**Comment by JihedC** [comment]
Est ce que tu as ecris les sous-titre dans un fichier word/pdf ou bien c'est uniquement sur youtube?

**Comment by Galeon07** [comment]
Merci @LucileDT  :)

Merci @JihedC ! Malheureusement non, j'ai fait la transcription directement sur Youtube

**Comment by DominDamid** [comment]
Comme j'ai du temps à consacrer et que les autres vidéos sont déjà prises en charge, je m'occupe de la relecture de celle-ci. J'espère ne pas te couper l'herbe sous le pied @JihedC  ;)

**Comment by DominDamid** [comment]
À 12:59 je lis dans le sous-titre, et c'est ce que j'entends aussi : "Mes comptes sont à Staoueli et à Oran."
J'avoue que je ne comprends pas ce que cela signifie... des idées ??

**Comment by DominDamid** [comment]
À 13:43, "un million de pieds-noirs, parmi lesquels il y avait les miens, qui ont laissé leur tombe." J'ai rajouté le mot "tombe" qui n'y était pas, je ne suis pas sûre du tout là encore.

**Comment by DominDamid** [comment]
Première relecture terminée.

**Comment by Salem2612** [comment]
Je fais la 2eme relecture.

**Comment by Salem2612** [comment]
2ème relecture terminée. Tout était impeccable. Les sous titres sont publiés sur Youtube, j'ai vérifié.

**Comment by JihedC** [comment]
Nice!

**Comment by Galeon07** [comment]
Merci ! :D

Par contre, en effet, en ce concerne les deux phrases que tu as soulignées, @DominDamid , c'est ce que Mélenchon dit, mais j'ai absolument aucune idée du sens ^^

**Comment by DominDamid** [comment]
@Galeon07 Ok !
