### ISSUE TITLE
[subtitles] [fr] Discours en hommage à Fidel

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#21]
# Video title
MÉLENCHON - HOMMAGE À FIDEL CASTRO 

# URL
https://www.youtube.com/watch?v=O6Q48L6JMtA

# Youtube subtitles language
Français

# Duration
11:52

# URL subtitles
https://www.youtube.com/timedtext_editor?lang=fr&bl=vmp&action_mde_edit_form=1&ui=hd&ref=psf&v=O6Q48L6JMtA&tab=captions

**Comment by LucileDT** [comment]
Les sous-titres ont été rédigés en français, il faut les valider.

**Comment by Ricyeam** [comment]
Ok je corrige et fais ca ce soir

**Comment by Ricyeam** [comment]
Corrigé et validé.
