### ISSUE TITLE
[subtitles] [fr] FAIRE LA RÉVOLUTION FISCALE - #EDCC15

### ISSUE THREAD

**Issue by desintoxiquezvous** [jlm2017/jlm-video-subtitles#212]
# Video title
FAIRE LA RÉVOLUTION FISCALE - #EDCC15 JEAN-LUC MÉLENCHON

# URL
https://www.youtube.com/watch?v=8fF40FiZ36c

# Youtube subtitles language
French

# Duration
19:30

# Subtitles URL
https://www.youtube.com/timedtext_video?ref=player&v=8fF40FiZ36c

**Comment by desintoxiquezvous** [comment]
j'me lance !

**Comment by Goutte** [comment]
Je bidouille le titre de cette issue, c'est pour faire un test, voir si mon script détecte bien qu'une issue est déjà présente. Si j'ai viré le suffixe JLM, c'est pas parce que je l'aime pas, s'entend. :wine_glass:

**Comment by desintoxiquezvous** [comment]
Sous titrage terminé. Bon pour 1ère relecture

**Comment by desintoxiquezvous** [comment]
@Goutte @LucileDT bonsoir je ne vois pas cette issue dans le ADD cart du project ST french c'est le serveur qui met du temps dans la mise a jour, ou bien?
du coup je ne peux pas la placer dans la colonne prêt pour correction 1
si quelqu'un a besoin du fichier texte de cette vidéo je peux le poser ici

**Comment by Goutte** [comment]
Je la vois, moi. C'est la 4e dans la liste ! Normalement, Github n'a pas de délai.

**Comment by desintoxiquezvous** [comment]
tu la vois dans la colonne project? moi pas, comment c'est possible? je ne vois pas non plus la #215 qui est la dernière des issues 
quand je regarde  subtitle french dans la colonne de choix des projets je vois dessous "updated one day ago" effectivement, ce n'est pas étonnant si je ne vois pas les dernières issues postées depuis hier 
je suis le seul a avoir ce bug?

**Comment by Goutte** [comment]
1) Va sur https://github.com/jlm2017/jlm-video-subtitles/projects/2
2) Clique sur `Add cards`.
3) ???

**Comment by desintoxiquezvous** [comment]
Merci pour tes conseils. 
La situation vient de se débloquer. Certainement un bug.
Bonne journée 

Envoyé de mon iPad

**Comment by Goutte** [comment]
Si le bug n'était pas entre la chaise et le clavier, il était peut-être dû à ton navigateur. Parfois, ça aide de vider son cache. `CTRL + MAJ + SUPPR`. Après, sur iPad, je ne sais pas...

**Comment by desintoxiquezvous** [comment]
j'avais vidé le cache... j'ai testé sur imac et mac book (firefox) et sur tablette (safari) c'était pareil , rien n'apparaissait dans ADDcart, 
ça a fini par se débloquer après avoir  tapé assignee:@desintoxiquezvous dans la fenêtre de recherche ce que je n'avais jamais été obligé de faire auparavant
snif snif ! le serveur y m'aime pas ...

**Comment by Milsabor** [comment]
Salut ! Je m'attaque à la relecture :)

**Comment by Milsabor** [comment]
Relecture opérée, je passe le relais !

**Comment by Salem2612** [comment]
Je fais la 2ème relecture.

**Comment by Salem2612** [comment]
Relecture terminée, envoyée et publiée sur Youtube.
- J'ai rajouté un "point" pour les grosses sommes (ex : 400.000€, 32.000€...) parce que 400000€ ce n'est pas évident à lire quand ça va vite.
- J'ai laissé les tirets en début de phrase (ex : "JML : - Blablabla"). J'imagine qu'ils étaient là pour que l'analyseur vocale ajoute des majuscules au début des phrases, ce qu'il ne fait pas avec des ":". Je ne sais pas s'il fallait enlever ces tirets.

**Comment by Goutte** [comment]
Bravo @desintoxiquezvous @Milsabor @Salem2612, beau travail !
