### ISSUE TITLE
Proposition pour corrections.

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#213]
Bonjour,

Vous savez que je teste sans cesse de nouvelles méthodes de travail qui permettrait d'être plus rapide et réactif. Actuellement sur notre forum, je propose de livrer les textes d'une vidéo sur un fichier texte. Le texte est écrit par mes soins et corriger avec "Scriben" en ligne ou je me suis abonné pour trois mois. .
Ainsi j'estime qu'une première correction à été faite , il reste une deuxième correction humaine à faire.  Je pense qu'il est bien plus rapide de faire comme cela, plutôt que chacun mette en champs les paroles de la vidéo, et de devoir attendre que deux correcteur passe derrière.  Ici dans mon cas, un fois corrigé humainement , il ne reste plus qu'a trouvé quelqu'un qui fait la mise en place sur la vidéo et c'est finit !    Actuellement ,il me manque juste une chose ... un correcteur, donc si, ici, il y a une personne qui serait intéressé par cette spécificité qu'il me contact ici !  :-)   

bonne journée a tous

**Comment by quidam34** [comment]
ps : voici un peit exemple des texte que nous créons mon épouse et moi même : 

21:23

J A: Alors justement là, je voudrais juste vous interrompre un moment, mais ça va tout à fait dans votre logique, lorsque vous prenez comme exemple, vous dites les bruits des bottes aux marches, aux frontière orientale de l'Europe, en gros, c'est l'Ukraine, n'est-ce pas. Vous estimez que ce sont les Américains qui sont responsables de tout cela, tout de même, c'est quand même la Russie de Vladimir Poutine qui a annexé la Crimée.

J-L M : J'attends votre point de vue, mais admettez qu'il en existe un autre ?

J A: Ce n'est pas un point de vue, ce sont des faits.

J-L M : Non madame, car les faits, vous avez commencé par effacer tous l'épisode précédents, l'épisode précédent, c'est l'interdiction de parler russe pour toutes les populations minoritaires et notamment celles de Crimée, la suppression du russe comme langue officielle dans un pays où 90 % des gens parlent russe, c'était quand même un problème.


J A : Ah, donc la Russie était dans une position défensive, lorsqu'elle à annexer la Crimée ?

J-L M : Si vous me permettez de vous répondre, mais j’admets votre logique, je la comprends, mais on a le droit d'être pour l'OTAN et les Américains ce n'est pas une honte

J A: Je n'ai pas dit ça

J-L M : Pour moi si c'en est une, mais on a le droit, je le comprends, je l'entends. Les Noirs américains se livrent à des provocations, se livraient, car c'était à l'époque leur stratégie d'alliance, c'est-à-dire renversant l'ordre du monde, un encerclement permanent de la Russie. Maintenant monsieur Trump arrive et il change de ligne politique, il dit nous allons nous allier avec les Russes contre les Chinois. Autrefois, c'était les Chinois contre les Russes maintenant, c'est les Russes contre les Chinois. Moi, dans chacune de ces positions, c'est vous qui allez avoir le tournis, parce que tous les dirigeants européens ne savent plus à quel sein se vouer, ils ont été toujours pour l'OTAN et l'Amérique, et maintenant, on leur apprend qu'il faut faire la paix avec les Russes. Moi, j'ai toujours la même position, je suis un indépendantiste français, la France à ses propres intérêts. Madame, écoutez-moi sur un chiffre puisque vous aimez les faits, le budget militaire des Nord-américains et de 600 milliards de dollars, 80 % des dépenses militaires du monde sont faites par les États-Unis d'Amérique et leurs alliés. Les Russes ont un budget militaire de 60 milliards, 10 fois moins, inférieur à celui de l'Arabie Saoudite. Alors, cette comédie, pardon madame, ça suffit, je ne parle pas de vous, ces provocations sans cesse venant de pays qui ont des comptes à régler avec la Russie, ce que je comprends parfaitement, mais nous ne sommes pas obligés de leur donner raison et d'accepter n'importe quelle provocation.


J B : Est-ce que de ce point de vue la finalement Donald Trump et vous n'êtes pas proches sur ce point de l'indépendance, finalement aujourd'hui Donald Trump dit “moi la Russie”
mais qui nous dit que demain ça ne sera pas non la Russie s’il n'y va pas intérêt pour les États-Unis

J-L M : Je sais que la tradition veut qu'on m'affuble du dernier tyran qui apparaît.

J B : Non, je ne vous affuble de rien, je dis sur ce point de vue précis, il n'y a-t-il pas un point commun, vous pouvez me répondre non !

J-L m : Bien c'est ce que je fais, je réponds non, parce que le point de vue de Monsieur Trump n'est pas un point de vue pro russe d'ailleurs, je ne suis pas pro russe, c'est un point de vue anti-chinois, je ne suis pas anti-chinois. Je suis contre la guerre, je suis pour la paix, je suis contre la guerre, je suis pour la paix. Excusez-moi, mais ça n'a pas l'air de vous préoccuper, car, supposons que l'on donne raison, je ne sais pas par exemple aux pays baltes, c'est quoi la suite ? La suite, c'est la guerre. On veut faire la guerre en Ukraine, c'est absurde il y a dans ce pays, non seulement la guerre est absurde, mais nous avons 7 centrales nucléaires et le cadavre de Tchernobyl qui est là-bas, tout ça est absurde donc la France doit limiter en permanence pour la paix. Elle doit être une puissance pacifique, donc pour ça, elle se retire de l'OTAN, parce qu'elle ne participe plus aux guerres de l'OTAN, dont aucune n'a donné un résultat quelconque, autre que des désastres, rappelez-vous la guerre d'Irak, rappelez-vous la guerre d'Afghanistan, rappelez-vous la guerre de Libye, chaque fois que c'est l’OTAN ça se termine dans une destruction massive et le désordre.
24:57

**Comment by Goutte** [comment]
> Les Noirs américains

C'est un algorithme, qui écrit ces textes, ou c'est un lapsus ?

---

Quant aux deux correcteurs, c'est une limitation imposée par Youtube.

En tout cas, bravo pour votre engagement ; aller jusqu'à embaucher des gens, respect.

**Comment by quidam34** [comment]
embaucher ? je comprend pas.     non c'est pas un algorithme lol c'est mon épouse, elle sait maintenant ,  j'avais déjà corrigé plusieurs fois lol . Celui là est passé au travers des mails du filet !  lol 
Vous avez que la limite imposer pour youtube de deux correcteurs et toute relative ! Suffit que deux personnes différente aillent sur la vidéo et qu'ils valident pour que cela passe (deux ip différentes j'imagine ) Donc la réponse n'est pas adapté.

**Comment by quidam34** [comment]
et si non il y a des fautes ? vous en avez vu ?

**Comment by Goutte** [comment]
> embaucher

Je parlais de Scriben !

---

Dans le texte que vous avez mis ci-dessus, oui.

> J'attends

> par effacer tous

> lorsqu'elle à annexer

etc.

**Comment by quidam34** [comment]
trouvé ici :   http://www.dicoz.fr/jattend-ou-jattends/      :   Exemple : ‘’J'attends son retour avant d'acheter les billets.’’    "Attendre" est un verbe du troisième groupe. On ajoute donc un "s" aux première et deuxième personnes du radical "attend".     Pour le reste ok . et donc votre avis sur j'attends ?

(je cherche a comprendre) Scriben a été trompé par le " à" qu'il n'a pas considéré comme un verbe d’où l'erreur   do'u la demande de relecture humaine !  ....   pour scribens, je l'ai pas vraiment embauché, je dirais pas ça comme ça !  :-) Quand je m'implique c'est toujours au max !

**Comment by Goutte** [comment]
Il dit "J'entends". C'est un truc de malentendant, on utilise un peu trop le vocabulaire auditif, souvent.

**Comment by Bentham** [comment]
Tous les "J A:" à changer en "J A :"
aux frontièreS orientalES
n'est-ce pas ? (pas un point)
mais admettez qu'il en existe un autre ! (pas un point d'interrogation)
 tous l'épisode précédent (et non précédents)
lorsqu'elle à annexé
ce n'est pas une honte. (point final)
Je n'ai pas dit ça ! (ponctuation)
Les Nord-américains 
la France a ses propres intérêts
des Nord-américains est de
Est-ce que de ce point de vue là
**" Est-ce que de ce point de vue la finalement Donald Trump et vous n'êtes pas proches sur ce point de l'indépendance, finalement aujourd'hui Donald Trump dit “moi la Russie” mais qui nous dit que demain ça ne sera pas non la Russie s’il n'y va pas intérêt pour les États-Unis"** : incompréhensible
n'y a-t-il pas un point commun (pas de "il" au début)
point de vue prorusse
antichinois
"**c'est absurde il y a dans ce pays, non seulement la guerre est absurde**" : incompréhensible
donc la France doit militer 


J'ajoute que le problème principal c'est la ponctuation, qui rend souvent le propos tout à fait incompréhensible.

**Comment by quidam34** [comment]
Benthman il fallait pas te donner la peine c'est un extrait de six page maintenant si tu me propose de faire des corections le forum ne refuse pas ton aide  :-)

**Comment by Bentham** [comment]
C'est gentil mais non, je préfère le fonctionnement démocratique de github.

**Comment by quidam34** [comment]
lol en quoi le forum n'est pas démocratique ? @Bentham

**Comment by quidam34** [comment]
@Bentham ?

**Comment by quidam34** [comment]
Reprise des corrections @Bentham 
"tous l'épisode précédent (et non précédents)"    Non ! tou**t** l'épisode précédent.
"lorsqu'elle à annexé"     ==> lorsqu'elle **a** annexé

**Comment by LucileDT** [comment]
Nous pouvons corriger bien plus facilement avec YouTube en relisant le texte en même temps que la vidéo passe.

De plus, comme déjà dit, les deux validations sont nécessaires (deux comptes Google). Autant en profiter pour corriger à ce moment-là.

@quidam34 vous ne sortez pas de sous-titres particulièrement rapidement, et souvent on y retrouve des fautes, pour l'instant votre méthode est loin d'avoir fait ses preuves.

**Comment by quidam34** [comment]
Parfois quand je vous parle Lucile, j'ai l'impression de parler a une personne âgé ! (vous l'êtes peut-être ?) qui a toujours travailler comme cela a qui va pas changer ses habitudes juste parce que que "c'est comme cela" je vous ai répondu sur l'autre sujet. Et puis pas grave si du coup les vidéos finissent par être sous titrés 1 mois après leur production hein !

**Comment by Goutte** [comment]
@quidam34 Où en êtes-vous des issues #183, #195 et #217 ? Si vous continuez les insultes _ad hominem_ (qui ne sont un argument que pour les esprits fallacieux), je vais être obligé de vous sanctionner.

**Comment by quidam34** [comment]
Je ne vois pas d'insulte mais un constat de rejet **sans même y réfléchir** de toutes pratiques autres que celle de ce site qui obligerais de revoir toute votre manière de travailler et donc toute votre organisation. J'ai répondu pour chaque issue a vos questions...  A force de voir cette mauvaise foi manifeste, je me pose des questions c'est tout  !

**Comment by Goutte** [comment]
Votre façon de travailler n'est pas compatible _avec les contributions anonymes_ ; si quelqu'un effaçait sans cesse votre travail, comme vous le faites sans vergogne pour le travail des autres, ça vous plairait ?

**Comment by quidam34** [comment]
Je ne fais rien sans vergogne comme vous dite ! Je préviens ici . Pour les gens extérieur, j'essaie de laissé un message dans le sous titrage lui même (mais bon les gens qui le font en externe  sont plutôt rare. Comme la solution que je propose est plus rapide , rendez donc votre travail compatible avec le mien ! Perso je pense que 8 jours est déjà un délais trop long pour la rendre accessible... il me semble que plus le temps passe et moins la vidéo devient attrayante .... donc un travail sous quelques jours est bien plus intéressant pour nos amis sourds. Pour l'instant, j'étais en recherche d'une bonne correctrice qui me rend son travail en a peine 8 heure ! Je l'ai .... elle corrige aussi les virgules ! ;-) nous allons donc prendre notre vitesse de croisière car pour l'instant nous cherchions encore la méthode idéale et de mettre en place notre organisation.  J'ajoute que sur le forum on a aussi des Labels en français qui son carrément personnalisé pour chaque utilisateur. J'suis désolé mais a chaque fois je dois aller traduire les vôtres ! Sans compter les issues qui sont mélangés et ou l'on doit utiliser un tri pour s'y retrouver.... quand a cette pagehttps://github.com/jlm2017/jlm-video-subtitles/projects/2   elle est complétement inutile puis qu'incluse dans nos "attributs" le mot français pour vos labels !

**Comment by Goutte** [comment]
Vous n'avez pas répondu à ma question ; si quelqu'un effaçait votre travail, comme vous le faites pour le travail des autres, ça vous plairait ?

**Comment by quidam34** [comment]
Pourquoi devrais-je répondre à cette question, nous avons cafouillé au début parce que des gens ici n'avait pas compris que notre manière de travailler n'était pas compatible ... Maintenant que tout le monde a compris, il n'y aura pas de problème sauf si quelqu'un attaque un travail pendant que nous travaillons dessus, parce qu'il ne sera pas venu voir dans le sujet que j'avais marqué que la vidéo était exclusivement réservée au forum et que notre méthode progressive de travail n'est pas compatible. Chose qui ne pourrait arriver sur le forum ! Il suffirait d'avoir une catégorie supplémentaire "sous titrage à l'ancienne" en plus d'actuellement. Ainsi, chacun pourrait travailler sans jamais risquer une bourde comme cela. Les deux méthodes auraient donc deux endroits bien distincts, sur les forums les issues ne sont mélanger ! On ne mélange pas les sujets pour se présenter, avec les vidéos a travailler en français, celle en anglais, sans compter l'LSF qui a d'ailleurs déserté ce site ! Que je sache ! Erreur d'autant pas possible que nous attributs (vos labels) précise carrément qui travaille à l'instant même, sur une vidéo. (sans devoir ouvrir le sujet) De plus, chacun travaille, non pas sur une vidéo, mais sur une mission. L'un retranscrit les textes, l'autre corrige, ensuite vient la mise en place automatique sur la vidéo et enfin les rectifications des timescodes et des césures parfois mal faite. Et franchement vu le temps gagné et la prise de tête aussi, il y a fort à parier que l'ancienne méthode serait vite abandonnée par tous ! Tien, je vais vous répondre quand même ... Si mon boulot était effacé, je me dirais que j'ai merdé si je ne suis pas venu voir avant dans le sujet (a pardon l'issue !!! ) bonne soirée a vous !   Ps : les invités peuvent maintenant visualiser le contenu du forum même s'il ne peuvent entrer dans les sujets . http://www.sous-titreur.forum-insoumis.fr

**Comment by Bentham** [comment]
Vous est-il venu à l'idée que nos avons pu réfléchir _puis_ désapprouver votre méthode, ou est-ce qu'il vous semble impossible de désapprouver votre méthode après avoir réfléchi ?

**Comment by Goutte** [comment]
Je vous l'ai déjà dit : les contributeurs anonymes ne viennent ni sur github ni sur votre forum, avant de contribuer ; **c'est leur travail que vous effacez avec votre technique brutale.**

---

Votre réponse _"c'est de ma faute car je ne suis pas venu voir"_ n'est pas sans rappeler celle des [Vogons](https://fr.wikipedia.org/wiki/Vogon) lorsqu'ils détruisent la planète Terre...

**Comment by quidam34** [comment]
@Goutte    Dans la mesure où on l'indique dans un champ dans les sous-titres d'une vidéo en production, c'est leur problème ! Et puis ils ne doivent pas être si nombreux 3035 insoumis me suivent ... Quand je fais une demande, c'est le désert ou bien : moi ! moi! moi ! et on les voit jamais ! @Bentham       Si si @Bentham , mais il semble que vous aillez mal réfléchi ou bien il faut m'expliquer  ! Vous savez cela s'appelle une discutions.. des échanges d'idées...  
Par contre j'attends toujours une explication sur ceci :

> C'est gentil mais non, je préfère le fonctionnement démocratique de github.

**Comment by Salem2612** [comment]
Avoir un forum et un github en parallèle c'est contreproductif. La page https://github.com/jlm2017/jlm-video-subtitles/projects/2 est très bien faite et utile puisqu'elle permet de voir facilement quelles vidéos sont à traiter, celles déjà prises en charge... Mais avec un autre forum en parallèle qui fait doublon, c'est certain que c'est compliqué de ne pas se marcher dessus. Je ne comprends pas pourquoi vous continuez de faire vivre votre forum alors qu'une seule plateforme suffit, et peut supporter vos 2 méthodes de travail. ça permettrait de réunir les 2 communautés.

**Comment by LucileDT** [comment]
Comme précisé dans l'issue #216, nous allons faire en sorte que @quidam34 ne participe plus à la rédaction des sous-titres, car cette personne fournit un travail contre productif.

**Comment by Goutte** [comment]
@Salem2612 Excellente remarque ! @quidam34, qu'avez-vous à répondre à ça ? Montrez-nous à nouveau à quel point votre orgueil vous aveugle !
