### ISSUE TITLE
[subtitles] [fr] EMISSION SPÉCIALE CHIFFRAGE : LES QUESTIONS DES JOURNALISTES - #EDCC16

### ISSUE THREAD

**Issue by Goutte** [jlm2017/jlm-video-subtitles#215]
Titre | EMISSION SPÉCIALE CHIFFRAGE : LES QUESTIONS DES JOURNALISTES - #EDCC16
----- | -----
Durée | 1:09:28
Langue | Français
Liens | [VIDÉO](https://www.youtube.com/watch?v=oDFyiX49MaU) - [ÉDITEUR](https://www.youtube.com/timedtext_editor?v=oDFyiX49MaU&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by desintoxiquezvous** [comment]
en cours de reconnaissance vocale

**Comment by desintoxiquezvous** [comment]
je commence les 12 premières minutes

**Comment by desintoxiquezvous** [comment]
je m’arrête a 11:55 reprendrais peut etre demain si personne d'autre

**Comment by desintoxiquezvous** [comment]
@Goutte bonjour, est tu toujours dessus ?, as tu besoin d'une partie de texte sur la suite et à quel moment de la vidéo, je suis dispo pour en faire un peu ou à t'envoyer du texte ....

**Comment by Goutte** [comment]
Je ne travaille plus sur cette vidéo. Je ferai une relecture finale, tu peux y aller !

**Comment by desintoxiquezvous** [comment]
Ok, je m'y colle

**Comment by desintoxiquezvous** [comment]
@Goutte donc je viens de faire de 11:52 à 16:45    et de 25:03 à 29:11 avec un manque entre les 2 (dû au fait que, ne sachant pas si tu était dessus, j'avais commencé d'abord a 25:03 pour te laisser une marge, puis après ton message, j'ai repris a partir de 11:52 
je reprendrais demain le trou manquant à partir de 16:45

**Comment by desintoxiquezvous** [comment]
@Goutte je viens de finir le trou manquant donc c'est fait de 00 à 29:11
j’arrête maintenant et reprendrais demain

**Comment by desintoxiquezvous** [comment]
@Goutte arrêté à 45:07 je reprends ASAP

**Comment by desintoxiquezvous** [comment]
@RobotInsoumis êtes vous toujours dessus ?

**Comment by Goutte** [comment]
@desintoxiquezvous, @RobotInsoumis a juste ajouté le label automatiquement, car il était erroné. Il ne travaille pas sur les vidéos, cf. #229. Je vous laisse continuer !

**Comment by desintoxiquezvous** [comment]
Je continue

**Comment by desintoxiquezvous** [comment]
@Goutte  Ca y est ,fini a l'instant, ça a été un peu laborieux mais il n'y a pas grand chose à reprendre je crois...
il y a pas mal d'interruptions de la part des journalistes ce qui provoque du brouhaha que j'ai estimé inutile de traduire (questions ou réponses avortées qui ne mènent nulle part etc)
de même j'ai rajouté les négations qui manquent souvent dans une discussion, ça rend plus compréhensible et "propre" le texte , enlevé les "donc" et autres...
Bon courage pour la relecture

**Comment by Goutte** [comment]
Je me lance !

**Comment by Goutte** [comment]
`⅔` :heart:

---

Voilà qui est fait ; ça n'a pas été sans mal, je n'ose même pas imaginer l'effort pour tout écrire. C'est parfois la foire d'empoigne, je n'avais pas fait attention en écoutant le live !

Surtout des corrections cosmétiques (majuscules, espaces, retours à la ligne, etc.).

Il faut maintenant deux validations.

**Comment by Goutte** [comment]
Il semblerait que les sous-titres aient été publiés directement suite à ma contribution. Soit vous avez été super-réactifs, soit Youtube me considère comme quelqu'un d'honorable. Ou alors il y a des mécaniques à l'œuvre dont j'ignore tout. Ou encore un mélange de tout ça, ou encore un _quartum quid_.

Bref, c'est en ligne, et cette issue est mon issue _témoin_. **Merci de ne pas la fermer, ni toucher à ses labels ou à sa carte dans le tableau !** On va laisser faire @RobotInsoumis et voir si il fait le boulot comme il faut, un peu avant minuit.

**Comment by Goutte** [comment]
↑
Émotion. :joy:

**Comment by LucileDT** [comment]
Bravo @Goutte !
