### ISSUE TITLE
[subtitles] [fr] #RDLS19 - SPIRULINE, CONSTRUIRE EN TERRE, ÉMISSION POLITIQUE, NUCLÉAIRE AMÉRICAIN

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#218]
# Video title
#RDLS19 - SPIRULINE, CONSTRUIRE EN TERRE, ÉMISSION POLITIQUE, NUCLÉAIRE AMÉRICAIN

# URL
https://www.youtube.com/watch?v=fyrAg_pReTY

# Youtube subtitles language
French

# Duration
21:37

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&ref=player&lang=fr&action_mde_edit_form=1&tab=captions&v=fyrAg_pReTY&ui=hd&captions-r=1

**Comment by Albapringe** [comment]
J'attaque pour cette nouvelle RDLS

**Comment by Bentham** [comment]
Ouah rapide ! Je mettrai peut-être un coup dedans ce soir en rentrant de répète :)

**Comment by Goutte** [comment]
Quelle rapidité ! Vous me faites douter de la pertinence de @RobotInsoumis !
Il n'est pas encore en lice, mais... Il ignorera les issues existantes s'il en trouve, mais il faudra respecter scrupuleusement la sémantique du titre. On verra bien !

**Comment by Albapringe** [comment]
Non, non, laisse-le. :) Si je vais si vite quand je vois une nouvelle vidéo, c'est pour mettre immédiatement le message à l'intention des sous-titreurs indépendants. Merci pour le rappel sur la syntaxe.

Pour info, aux volontaires, je suis preneur d'un texte partant d'environ 15:00 à la fin que j'introduirai moi-même.

**Comment by Bentham** [comment]
Bon, trop fatigué ce soir, je ferai ça demain plutôt...

**Comment by Albapringe** [comment]
Pas de souci. Comme j'ai avancé, ce sera plutôt de la minute 18:00 à la fin.

**Comment by quidam34** [comment]
Je suis désolé quelqu'un a pris l'initiative chez moi d'attaquer cette vidéo . Elle a fait tout le texte. vous le voulez ?    Vous dite j'attaque mais je n'ai rien vu sur la vidéo ?

**Comment by quidam34** [comment]
Le texte est en place et dans les champs. La correction n°1 est faite , jeter un oeil c'est presque tout bon !

**Comment by LucileDT** [comment]
@quidam34 si vous pouviez sous-titrer des vidéos moins récentes, ça nous arrangerait, merci : on éviterait de se marcher sur les pieds.

**Comment by quidam34** [comment]
Désolé , ma nouvelle correctrice a pris cette initiative et j'ai découvert le texte ce matin tout fait ! J'ai donc utilisé la méthode automatique de mise en place dans les champs et corrigé les erreurs dans la foulé ! voilà je l'ai mis au courant de ne plus prendre d'initiative comme celle là .  Mais bon le travail et fait le vous laisse les dernières retouches à faire.

**Comment by Bentham** [comment]
Eh ben mon pauvre @Albapringe, tu as bossé pour rien...

**Comment by Albapringe** [comment]
Je vois... Eh bien, dans ce cas, tant qu'une organisation satisfaisante ne sera pas trouvée, je ne contribuerai plus à la rédaction des sous-titres. Il faut dire que j'avais déjà nettement réduit ma participation à cause de cette méthode de fonctionnement parallèle et rendant l'ensemble brouillon et peu efficace. Cette mauvaise blague est celle de trop pour moi.

Je croyais @quidam34 qu'il était suffisamment clair qu'il fallait créer une issue ici dès que vous commencez un sous-titrage. Il est anormal que ton équipe ne sache pas qu'elle ne doit pas démarrer de sous-titrage tant qu'une issue n'a pas été créée ici et qu'une indication comme quoi vous prenez en charge la vidéo associée ait été faite, et ça, c'est de ton entière responsabilité. Je persiste à penser que deux organisations en parallèles ne se complètent pas, mais s'affaiblissent l'une l'autre, surtout quand l'une d'elle semble aussi mal gérée. On a déjà dit en particulier qu'il était souhaitable que vous ne fassiez pas de revue de la semaine. Alors, s'il te plait, soit tu mets de l'ordre dans le fonctionnement et l'organisation de ton forum en clarifiant les règles de sorte à ce que les deux systèmes fonctionnent ensemble, soit tu vas finir par dégoûter tout le monde ici ! Tu voudrais que ce soit bel et bien le cas que tu n'y arriverais pas mieux autrement. Sois heureux que je sois d'un naturel calme et donc relativement modéré dans mon propos, car tu m'as bien énervé ! Tu fais désormais partie des 2 ou 3 personnes dans ma vie qui ont réussi à m'énerver. Chapeau, l'artiste !

**Comment by LucileDT** [comment]
@quidam34 si encore une erreur de ce genre arrive, je peux vous assurer que nous nous passerons définitivement de votre "aide".

**Comment by desintoxiquezvous** [comment]
@Albapringe @Bentham @LucileDT 
le mépris de @quidam34 pour les personnes ayant travaillé avant lui sur une issue, sans tenir aucun compte du travail effectué par d'autres est insupportable. Sa prétention à se rendre indispensable indispose l'ensemble du groupe.
Quant à moi je refuse dorénavant de participer à la relecture ou validation de toute issue qu'il aura créée dans les mêmes conditions.
Travailler dans le respect de chacun et s'entraider d'une façon solidaire est la seule façon de travailler

**Comment by quidam34** [comment]
lol @LucileDT c'est vrai c'est très malin cette réponse ! Je choisirez les vidéos sans venir ici et vous verrez votre travail disparaitre !  Alors excusez moi mais vous devriez voir les choses sous un angle un peu moi aggressif   @desintoxiquezvous  Il y a que ceux qui ne font rien qui ne font pas d'erreur. Vous devriez vous poser la question de savoir "comment a t'il pu aller aussi vite ?" Ca c'est la bonne réaction. Si vous ne voulez pas finir on peut sans occuper ! Il reste a tout casser 30 mn de travail !

**Comment by quidam34** [comment]
@Albapringe  je vais pas m'étendre sur le sujet, c'est une nouvelle d'avant hier dans l'équipe qui ne connaissait pas les accords que l'on a . Maintenant c'est fait ! Milles excuses !

**Comment by LucileDT** [comment]
@quidam34 vous auriez pu ne pas mettre en ligne votre fichier mais vous l'avez fait. Vos procédures ne sont pas claires, et vous ne formez pas votre équipe.

Vous faites vos essais depuis bien assez longtemps pour qu'une erreur de cette ampleur ne vous soit pas pardonnée. Vous tapez sur les nerfs de tout le monde, ne faites aucun effort d'expression ni de politesse, arrivez ici pour vous plaindre sans vous être penché sur nos méthodes... Trop, c'est trop ! L'argument "un con qui marche va plus loin qu'un intellectuel assis" ne s'applique pas ici, car nous avançons, nous aussi, et c'est vous et votre ""travail"" qui nous fait reculer !

Vous êtes prévenus.

**Comment by Goutte** [comment]
Je vais regarder si on peut automatiser la sauvegarde des brouillons (pour l'instant, j'ai pas réussi), et l'upload via @RobotInsoumis. Ça nous permettrait d'utiliser git pour les sous-titres, et donc potentiellement de résoudre ces conflits. Je ne suis pas certain, donc pas de promesses !

---

_Toutes mes condoléances, ami⋅e⋅s insoumi⋅e⋅s._ J'en suis sérieusement à me demander si @quidam34 n'est pas un troll à la solde d'un concurrent politique aussi peu scrupuleux que lui...

**Comment by Bentham** [comment]
Je ne pense pas que ce soit un troll. C'est juste une personnalité narcissique et autoritaire qui nous fait porter le poids de ses névroses.

**Comment by quidam34** [comment]
Vous pouvez y aller , lol, j'ai le dos large ! Excusez mais j'ai du travail .

**Comment by Salem2612** [comment]
J'ai fait une relecture (la première officiellement d'après Youtube). Il en faut donc une 2eme pour que la vidéo soit publiée.

**Comment by Goutte** [comment]
J'ai relu et corrigé ; c'est truffé d'espaces mal placés, redondants, ou parfois absents.
Les phrases sont coupées un peu n'importe comment.
Exemple :
```
c'est un problème. Béh non, tout coûte,
tout absolument tout coûte ! Le problème
```

Et je ne parle pas des coquilles ! :man_facepalming: 

---

C'est quand même curieux que les vidéos sur lesquelles vous travaillez depuis plus de 20 jours ne soient pas terminées, mais que vous vous soyez empressé d'écraser le travail d'@Albapringe avec cette contribution médiocre au mieux ? C'est sûr qu'il faut de sacrées épaules pour porter le poids d'une telle culpabilité !

**Comment by quidam34** [comment]
lol @Goutte  ! Antoine, je crois  que j'ai aller déterrer votre travail passé pour voir un peu...(du site)  Il fallait bien trouver quelque chose à redire hein ! Pas terminé les autres vidéos ? Regardez mieux ! Si vous étiez au courant des techniques les plus modernes et rapides,vous sauriez qu'il est normal de ne pas voir le texte le temps de sa retranscription complète et que d'un seul coup d'un seul, le voir apparaitre et ceci même sur une vidéo d'une heure et demi. Est-ce que je critique votre travail moi ? ! OK ? De plus est-ce que j'ai dit que c’était finit ? 

> Le texte est en place et dans les champs. La correction n°1 est faite , jeter un oeil c'est presque tout bon !

ps pour ce que vous signalez , nous n'estimons que ce n'est pas un problème. A savoir, du moment que c'est un début de phrase ce n'est pas grave, pas contre si cela avait été ainsi : 

>Le problème c'est de savoir à quoi sert 
l'argent que vous dépensez, et surtout d'où vous

> le tirez, et combien ensuite à la sortie, ça va ramener

Dans le cas ci-dessus , oui là, nous aurions remis "le tirez" dans le champ précédent, mais là ...
Parce que la virgule suivante n'est qu'à deux mots ....

Dans le cas que vous citez : 

> c'est un problème. Béh non, tout coûte,
tout absolument tout coûte ! Le problème

>c'est de savoir à quoi sert l'argent que
vous dépensez, et surtout d'où vous le tirez,

La virgule est dix mots plus loin ! De plus vous n'avez rien corriger ??? Pourquoi ?
Vous allez me dire que "le problème" lui n'est qu'a deux mots du champs suivant, dans ce sens là nous estimons que ce n'est pas un problème. Voulez-vous tout régenter ?

Quant aux coquilles, vous n'en citez aucune. 
C'est la dernière fois que je perds mon temps à répondre à la mauvaise foi !

**Comment by LucileDT** [comment]
@quidam34 je pense que nous sommes tous ici d'accord pour dire que vos contributions sont médiocres, mal écrites et qu'il faut passer énormément de temps à les corriger.
Je pense que nous allons devoir nous passer de vos "services".

**Comment by Salem2612** [comment]
Il faut la relire cette vidéo ou alors on a des chances de se faire écraser notre travail ? Je ne comprends pas bien. Le problème c'est que ça retarde la mise en ligne de sous titres...

@Goutte a raison, tout est découpé au milieu des phrases, du coup il faut reprendre tous les timecodes... La flemme...

**Comment by Goutte** [comment]
@Salem2612 Et encore, j'ai corrigé des dizaines de fautes en tout genre, de l'accent au faux-sens !
'protéines' écrit de trois façons différentes... C'est quand même pas si compliqué d'ouvrir un dictionnaire !

> Antoine, je crois que j'ai aller déterrer votre travail passé pour voir un peu...(du site)

Outre le non-sens de cette phrase (expliquez?), je ne vous autorise pas à m'appeler par mon prénom, M. Paroche. Je sais que la vie est dure pour les clowns ventriloques qui abusent du `lol`, mais on a pas élevé les vaches ensemble.

> Est-ce que je critique votre travail moi ? ! OK ?

**Vous faites pire : vous l'écrasez** sans vergogne. J'apprécie toujours une bonne critique ; à vous lire, il semble que ce n'est pas votre cas ! Grandissez, un peu ! À 56 ans, vous devriez être capable de reçevoir des critiques, surtout quand elles sont méritées.

> Quant aux coquilles, vous n'en citez aucune.

Je les ai corrigées, c'est mieux. Mauvaise foi ! Téléchargez le nouveau fichier, et comparez-le au vôtre.

> De plus vous n'avez rien corriger ??? Pourquoi ?

Parce que le travail sur les timecodes aurait du être niquel dès le départ ! C'est plus de travail de corriger des timecodes ratés que de les faire bien dès le début. Un peu comme votre éducation...

> C'est la dernière fois que je perds mon temps à répondre à la mauvaise foi !

Laissez-moi rire ! Vous êtes un cas d'école de mauvaise foi, et vous nous faites perdre notre temps à tous avec vos "contributions" et votre toxicité générale.

> "le problème" lui n'est qu'a deux mots du champs suivant

Pourquoi ne pas l'avoir passé dans le champ suivant ? Vous estimez que ce n'est pas un problème ? Moi si.

**Comment by DominDamid** [comment]
Bon... deuxième relecture ??

**Comment by DominDamid** [comment]
Pouf ! Je m'arrête à 12:57... effectivement beaucoup de coupures doivent être modifiées. C'est long ! À mon avis une relecture supplémentaire à la fin ne serait pas superflue car ça fait beaucoup de choses à corriger en même temps, il me paraît inévitable que certaines erreurs passent à la trappe.

**Comment by Vimogo** [comment]
Je reprends le travail ici.

**Comment by Vimogo** [comment]
Oki, la vidéo est en ligne. Je clos.
