### ISSUE TITLE
[subtitles] [fr] #RDLS19 - SPIRULINE, CONSTRUIRE EN TERRE, ÉMISSION POLITIQUE, NUCLÉAIRE AMÉRICAIN 

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#219]
Video title
#RDLS19 - SPIRULINE, CONSTRUIRE EN TERRE, ÉMISSION POLITIQUE, NUCLÉAIRE AMÉRICAIN 

# URL
https://youtu.be/fyrAg_pReTY

# Youtube subtitles language
France

# Duration
21:37

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=wt&lang=fr&bl=watch&ui=hd&v=fyrAg_pReTY&action_mde_edit_form=1&tab=captions

**Comment by quidam34** [comment]
Je n'ai pas vu comment supprimer le sujet mis en double par erreur !

**Comment by LucileDT** [comment]
Doublon avec la #218
