### ISSUE TITLE
[organisation] Avancement RDLS

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#22]
Bon, on est pas au goulag hein, donc ya pas d'impératifs, mais je me suis dit que ca pourrait être sympa de savoir en combien de temps on mets en ligne les sous titres pour les revues de la semaine (vidéos dont tout le monde semble apprécier l'importance).

J'updaterai ce post toutes les semaines, pour nous donner une idée.

## Revue de la semaine n°8 #
 - Publiée par JLM le 25/11/16
 - Sous-titres en Français publiés le 27/11/16 [Ici: #12]  - **2 jours**
 - Sous-titres en Anglais publiés le 29/11/16 [Ici: #7] - **4 jours**

**Comment by Bentham** [comment]
Je pense qu'il est important d'ajouter les sous-titres le plus vite possible à la sortie des vidéos, pour accompagner l'effet "buzz". Pour ma part je compte m'atteler aux Revues immédiatement à leur sortie.

**Comment by Flupignon** [comment]
Oui tout à fait. En anglais ça dépend un peu de la dispo, en français on devrait pouvoir se relayer selon les dispos des uns et des autres.

**Comment by Ricyeam** [comment]
En Anglais aussi on devrait pouvoir se relayer, juste que quand c'est pas @Flupignon qui écrit les sous-titres il y aura certainement un peu plus de corrections necessaires. And corriger est plus rapide que écrire from scratch.

**Comment by LucileDT** [comment]
@Ricyeam, est-ce que tu penses que je peux fermer cette issue ?

**Comment by Flupignon** [comment]
En tout cas y a deux FDLS en anglais qui cherchent un relecteur ou une relectrice...

**Comment by Mattouk** [comment]
@Flupignon 
Je ne savais pas où poster, mais juste pour dire, je suis chaud pour commencer la RDLS 16 en anglais.

**Comment by Flupignon** [comment]
Et bah fais-toi plèz ;)

**Comment by Goutte** [comment]
Je ferme, la liste n'est plus maintenue. On peut toujours la ré-ouvrir si @Ricyeam revient ;)
