### ISSUE TITLE
[subtitles] [fr] L'AVENIR EN COMMUN : COMBIEN ÇA COÛTE ? - #EDCC1

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#224]
## L'AVENIR EN COMMUN : COMBIEN ÇA COÛTE ? - #EDCC1

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mardi 21 février 2017
**Durée**       | 0:01:43 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=aNw579fuoXM)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=aNw579fuoXM&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Goutte** [comment]
À revoir scrupuleusement, je ne suis pas certain de tout, et j'ai même une incertitude caractérisée à 1:08 :

```
On nous fait croire que tout ce qu'elle a fait sur 60 ans, Jean-Luc Mélenchon lui ???.
```

Offre ? Ôte ? ... What ?

**Comment by Vimogo** [comment]
Je revois

**Comment by Goutte** [comment]
Les sous-titres sont publiés ; merci @Vimogo pour la relecture et les corrections ma foi fort pertinentes !
