### ISSUE TITLE
[subtitles] [en] L'AVENIR EN COMMUN : COMBIEN ÇA COÛTE ? - #EDCC1

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#225]
## L'AVENIR EN COMMUN : COMBIEN ÇA COÛTE ? - #EDCC1

&nbsp;        | Info
------------- | -------------
**Date**      | Tuesday, 21 February 2017
**Duration**  | 0:01:43 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=aNw579fuoXM)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=aNw579fuoXM&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by Goutte** [comment]
A revoir.

**Comment by Goutte** [comment]
@LucileDT @Vimogo @Albapringe @Flupignon Quelqu'un peut-il revoir et valider cette vidéo avant minuit ? Je veux tester si @RobotInsoumis clot l'issue automatiquement une fois les sous-titres publiés !
Elle est très courte, ça prendra pas longtemps, promis !

WTF !? Ma contribution a été supprimée ?

**Comment by Goutte** [comment]
> WTF !? Ma contribution a été supprimée ?

J'ai rien dit, j'avais un autre brouillon avec du contenu foireux par dessus ma première contribution. Je l'ai supprimé, et tout va bien, vous devriez pouvoir valider.

**Comment by Goutte** [comment]
Ok, j'ai pu valider moi-même, et Youtube m'indique que les sous-titres sont maintenant publiés ! Merci, les gens ! :heart:
