### ISSUE TITLE
[subtitles] [fr] 6E RÉPUBLIQUE - RDV LE 18 MARS À 14H PLACE DE LA BASTILLE À PARIS - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#226]
## 6E RÉPUBLIQUE - RDV LE 18 MARS À 14H PLACE DE LA BASTILLE À PARIS - #18mars2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 02 mars 2017
**Durée**       | 0:02:33 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=w-cAW65pY9U)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=w-cAW65pY9U&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by desintoxiquezvous** [comment]
@Goutte une question : je m'aperçois que les sous titres ont un corps plus grand que d'habitude et que du coup certaines césures se font mal, d'autre part les sous titres n'apparaissent pas dans les containers, comme si ils étaient déjà incrustés dans la vidéo ???? que peut t-on vérifier ou modifier ?
le texte est ok a part les césures , que faut t'il faire...

**Comment by Goutte** [comment]
Bien vu !

On laisse tomber cette vidéo (au moins le français), car ils ont hardcodé les sous-titres. _Grmbl._ :angry:
