### ISSUE TITLE
[subtitles] [en] 6E RÉPUBLIQUE - RDV LE 18 MARS À 14H PLACE DE LA BASTILLE À PARIS - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#227]
## 6E RÉPUBLIQUE - RDV LE 18 MARS À 14H PLACE DE LA BASTILLE À PARIS - #18mars2017

&nbsp;        | Info
------------- | -------------
**Date**      | Thursday, 02 March 2017
**Duration**  | 0:02:33 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=w-cAW65pY9U)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=w-cAW65pY9U&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by A000045** [comment]
Effectué jusqu'à 0:56. Navré mais j'ai une réunion avec les insoumis de mon quartiers ^^
J'y retourne "dès que"...

**Comment by LucileDT** [comment]
Salut @A000045 ! Tu as été ajouté aux collaborateurs, est-ce que tu peux aller ici : https://github.com/jlm2017/jlm-video-subtitles/invitations et accepter l'invitation ?
Une fois fait, tu pourras modifier les labels :)

**Comment by A000045** [comment]
Bon voilà, du coup j'ai changé le label pour "First review" : je croyais que ça suffirait à le faire changer de colonne (mais peut-être que ça prend le temps de l'update ?) en tout cas il est prêt à la relecture. Salut insoumis ^^

**Comment by Goutte** [comment]
@A000045 Le robot fonctionne dans l'autre sens : changer la colonne fait changer les labels. Je m'occupe de la première relecture !

**Comment by MenvussaG** [comment]
Pouah, j'ai fait 10 minutes mais cette présentatrice fait vraiment vomir, je dois faire une pause
putain d'émissions de télé,
 Jocelyn
