### ISSUE TITLE
Qualité des sous-titres

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#23]
Chers tous,

Il faut vraiment faire attention à la ponctuation et aux capitales, ça fait perdre beaucoup de temps pendant les corrections ! Aussi, il faut veiller à ce que les "blocs de sous-titres" soient cohérents, il ne faut pas qu'on ait 3 lignes sur un bloc et le dernier mot de la phrase dans un bloc différent. Je viens de dfaire une correction avec pleins de blocs désorganisés et c'est très fastidieux à reprendre.

Merci

# Règles pour bien rédiger vos sous-titres
## Ponctuation :
  - En français, on met un espace entre le mot précédent et les caractères ```?```, ```!```, ```:```. **Exemple :** "Je vais manger !"
  - En anglais, on ne met pas d'espace entre le mot précédent et les caractères ```?```, ```!```, ```:```. **Exemple :** "I go eat!"
## Capitales :
  - Pensez à en mettre en début de phrase.
  - Elles ne sont pas obligatoire après des points de suspension ```...```. **Exemple :** "Je me disais... tu serais pas allé manger ?"
## Blocs de sous-titres :
  - Tentez de les rendre cohérents : évitez par exemple de rédiger pour la même phrase trois lignes dans un bloc, puis deux mots dans le bloc suivant.
  - Vous pouvez coller les blocs les uns aux autres, surtout si l'espace entre deux d'entre eux est petit.
  - Vous pouvez ajouter un saut de ligne dans un bloc en faisant ```shift``` + ```entrée```.
## Notes de traducteur ou d'auteur :
  - Si vous avez à en placer, mettez les entre crochets : [ et ].
  - Précisez à la fin de votre note : NDA pour Note De l'Auteur ou NDT pour Note Du Traducteur.

**Comment by Flupignon** [comment]
Il faut aussi bien caler les blocs sur le son, ça se fait facilement en regardant les "barres de son" visibles sous la vidéo.

**Comment by LucileDT** [comment]
Est-ce que tu peux donner un lien vers des vidéos qui pourraient servir d'exemple ? :)

**Comment by Flupignon** [comment]
Bah en fait je fais ça au feeling, mais je vais essayer de trouver ça.

**Comment by Flupignon** [comment]
Je trouve pas... Mais c'est vraiment une question de pas y aller comme un bourrin, d'envisager les phrases dans leur globalité et de se mettre à la place du lecteur en fait. Faut pas qu'il ya ait une phrase découpée comme ça par exemple : 

 "Cette raison c'est que toute" / "une série des" / "grands services qui font la dignité de l'État" /  "républicain"

Faut essayer d'harmoniser les propositions de la phrases et bien se caler sur la bande son qui défile en bas de la vidéo.

**Comment by LucileDT** [comment]
Pour ma part, j'ai tendance à faire de gros pavés, pour garder des phrases compréhensibles, je recompterai le nombre de mots que je mets.

**Comment by Flupignon** [comment]
Oui c'est ça l'idée

**Comment by Flupignon** [comment]
Il faut pas que tout soit haché.

**Comment by bayasahra** [comment]
hummm je sais pas c 'est du ressenti et on a tous un ressenti différent ^^ faut que les autres viennent lire pour voir si ça leur convient... moi perso si je le fais comme ça c'est que ça me convient pour la dynamique du discours... je me mets à la place du malentendant parce que bien évidemment avant de valider j'enlève le son et fait une relecture vidéo qu'avec les sous titres... et je trouve que ça lui donne un indice sur le rythme, le tempo et que ça fait donc partie de la personnalité de celui qui parle et je n'ai pas de problème particulier à tout lire ... à débattre bien sur

**Comment by LucileDT** [comment]
Faudrait qu'on trouve une association / un collectif qui pourrait nous aider.

**Comment by bayasahra** [comment]
@Flupignon 
Et en ce qui concerne ta ponctuation, j' ai laissé les virgules que tu mets juste avant les césures puisque tu as l' air d'y tenir et que c' est finalement du détail. Mais lorsque tu corrigeras mes textes j' aimerais bien que tu ne rajoutes pas les virgules après le dernier mot visible, car chez moi c' est délibéré : je pense que la césure sert de virgule.

**Comment by LucileDT** [comment]
@Flupignon j'ai mis à jour ton post en listant les pratiques pour rédiger des sous-titres. Tu me diras ce que tu en penses !

**Comment by Goutte** [comment]
@Flupignon @LucileDT On met ça dans le wiki ?

**Comment by LucileDT** [comment]
CF mon commentaire vis à vis du wiki dans l'issue #19

**Comment by Goutte** [comment]
https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-R%C3%A8gles-pour-bien-r%C3%A9diger-les-sous-titres
