### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «LE 18 MARS, MARCHONS POUR LA 6E RÉPUBLIQUE»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#230]
## MÉLENCHON : «LE 18 MARS, MARCHONS POUR LA 6E RÉPUBLIQUE»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 05 mars 2017
**Durée**       | 0:28:27 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=lOP70Zytja0)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=lOP70Zytja0&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by quidam34** [comment]
On prend, nous n'avons plus de travail pour la retranscription du texte.

**Comment by quidam34** [comment]
Plus de la moité du texte est écrit et surrement les trois quart demain matin !  Bonne nuit a tous !

**Comment by quidam34** [comment]
Ecriture du texte finit ! correction final en cours.

**Comment by quidam34** [comment]
Voir mon nouvelle issue et les question que je pose.

**Comment by Milsabor** [comment]
Bonsoir ! Je m'en occupe.

**Comment by Bentham** [comment]
Super @Milsabor ! Quand tu arrêteras de travailler, n'oublie pas d'enlever le label "Someone is working on this issue" :)

**Comment by Milsabor** [comment]
Ouaip, je me suis douté que les labels avaient été réorganisés ^^ Quand j'ai fini, j'envoie les sous-titres et je change tous les labels.

**Comment by Milsabor** [comment]
C'est terminé. J'aurais toutefois besoin d'une validation supplémentaire sur l'outil YouTube, car il semblerait que le premier envoi n'ait pas été effectif (d'où le tag Help Wanted et le fait que je ne l'ai pas encore basculé dans la colonne "validés et en ligne", à corriger dès que c'est OK)

**Comment by Goutte** [comment]
@Milsabor C'est fait, merci !
