### ISSUE TITLE
[subtitles] [fr] EN DIRECT - MÉLENCHON : Conférence de presse sur l'Europe - #JLMEurope

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#233]
## EN DIRECT - MÉLENCHON : Conférence de presse sur l'Europe - #JLMEurope

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 06 mars 2017
**Durée**       | 0:00:00 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=Yau84m-XpJg)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=Yau84m-XpJg&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Goutte** [comment]
Intéressant. C'est un stream live, donc c'est pourquoi la durée est nulle.
@LucileDT : je vais voir ce que je peux faire à ce sujet, mais je pense qu'un comportement raisonnable pour l'instant est d'ignorer les vidéos à durée nulle. Avis ?

---

Edit : je sais quoi faire.
