### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : Conférence de presse sur l'Europe - #JLMEurope

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#235]
## MÉLENCHON : Conférence de presse sur l'Europe - #JLMEurope

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 06 mars 2017
**Durée**       | 0:41:44 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=Yau84m-XpJg)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=Yau84m-XpJg&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by quidam34** [comment]
Bonjour, j'ai proposé a Maxime de m'envoyez sur le forum le fichier qu'il propose. On attend donc.

**Comment by quidam34** [comment]
Je viens de voir sur Youtube : @Goutte   qu'est-ce que l'on fait  ? cela m'a l'air bien .... vous voulez (le site) vous en occuper ou bien souhaitez vous qu'on le fasse ? Il me semble que quelques petites rectification semble nécessaire . Pour la correction c'est à mes correcteurs qu'il faut demander ! Vous me confirmer que c'est bien Maxime qui a mis son fichier en place et que rien n'a été corrigé depuis ?  Merci de votre réponse.

**Comment by Goutte** [comment]
Il reste des fautes à corriger, comme vous avez constaté. Je ne sais pas plus que vous qui a contribué.
Si vous souhaitez vous charger de la première relecture et des corrections, allez-y. Je ferai la validation.
