### ISSUE TITLE
[subtitles] [fr] On ne gère pas un hôpital comme une entreprise - #ManifSanté

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#237]
## On ne gère pas un hôpital comme une entreprise - #ManifSanté

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mercredi 08 mars 2017
**Durée**       | 0:01:58 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=HpGKAEManvU)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=HpGKAEManvU&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by desintoxiquezvous** [comment]
@RobotInsoumis 
bonjour HAL ! les sous titres sont déjà fait et en ligne , apparemment .... ;-D

**Comment by Goutte** [comment]
Oh !?

On va voir si il ferme l'issue tout seul ce soir à minuit.

**Comment by Goutte** [comment]
Ah non, car le titre a changé depuis sa création. Bon, C'est là : 5c562c45b0e90525cbe43fe5a10a71081a8ea8fa
