### ISSUE TITLE
[subtitles] [en] On ne gère pas un hôpital comme une entreprise - #ManifSanté

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#238]
## On ne gère pas un hôpital comme une entreprise - #ManifSanté

&nbsp;        | Info
------------- | -------------
**Date**      | Wednesday, 08 March 2017
**Duration**  | 0:01:58 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=HpGKAEManvU)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=HpGKAEManvU&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by Goutte** [comment]
Publié dans 5cd0027536d0fc0b49b6626188da1312ae3bcb54

J'ignore pourquoi @RobotInsoumis n'a pas fermé l'issue... Je vais enquêter.

**Comment by Goutte** [comment]
Oh, je sais. Le titre a changé entre l'ouverture de l'issue et la publication des sous-titres.

Je vais voir comment je peux faire pour rendre @RobotInsoumis moins dépendant du titre.
