### ISSUE TITLE
 [subtitles] [FR] MÉLENCHON - UN AN APRÈS LE 13 NOVEMBRE 2015 : MA RÉPONSE FACE AU «TERRORISME»

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#24]
# Video title

MÉLENCHON - UN AN APRÈS LE 13 NOVEMBRE 2015 : MA RÉPONSE FACE AU «TERRORISME»

# URL 

https://www.youtube.com/watch?v=osk854gGWLA

# Youtube subtitles language

Français

# Duration
 
52:10

# URL subtitles
 
https://www.youtube.com/timedtext_editor?tab=captions&v=osk854gGWLA&ui=hd&lang=fr&action_mde_edit_form=1&forceedit=timedtext&bl=vmp&ref=player

**Comment by Flupignon** [comment]
@Ricyeam @bayasahra  Dernière question avant de tout comprendre, comment je mets un nouveau projet dans les colonnes "projects" ?

**Comment by Ricyeam** [comment]
'+ add cards' somewhere en haut à droite des colonnes.

Aussi pour la mise en page des issues, c'est tres bien !

Petite modification, au lieu de mettre en gras les titres (titre, url… etc), mets un # devant la ligne. Ca mettra en forme tout seul ! (tu peux essayer en modifiant ton post si tu veux)

Je pourrai le faire moi-même bien sûr, mais comme ça tout le monde apprend!

**Comment by Flupignon** [comment]
ok merci

**Comment by dalipokim** [comment]
Salut tout le monde, je suis en train de transcrire celle avec Noël Mamère, ça le fait ?

**Comment by Flupignon** [comment]
Transcription jusqu'à 7:25 pour l'instant. Si quelqu'un veut prendre le relais... Je reprends ce soir.

**Comment by Flupignon** [comment]
Transcription jusqu'à 30:05

**Comment by Flupignon** [comment]
Transcrit jusqu'à 45:05, il reste 7 minutes de vidéo.

**Comment by bayasahra** [comment]
je suis dessus , je fais la première correction .

**Comment by bayasahra** [comment]
Corrigé et validé.
Pour celui qui va faire la seconde correction, je me suis consacrée à l' orthographe, je pense que là c' est bon, il faudrait regarder le timing .
@Flupignon            précisemment > précisément  et évènement > événement . tu les avais écrit plusieurs fois comme ça donc je suppose que c' est pas de l' inattention.
Et en ce qui concerne ta ponctuation, j' ai laissé les virgules que tu mets juste avant les césures puisque tu as l' air d'y tenir et que c' est finalement du détail. Mais lorsque tu corrigeras mes textes j' aimerais bien que tu ne rajoutes pas les virgules après le dernier mot visible, car chez moi c' est délibéré : je pense que la césure sert de virgule.
Bon courage pour celui qui prend la suite ;)

**Comment by dalipokim** [comment]
Je me lance sur une correction à 17h 30

**Comment by Flupignon** [comment]
@bayasahra je vais essayer promis, après quand je suis dans le jus je fais ça automatiquement...

**Comment by LucileDT** [comment]
@Flupignon tu peux mettre ton correcteur d'orthographe en français quand tu transcris n français (si tu veux, je peux t'expliquer comment on fait)  :)

**Comment by dalipokim** [comment]
Ok j'ai approuvé avec quelques modifs mineures sur la forme.
