### ISSUE TITLE
[subtitles] [fr] #RDLS20 : MACRON-RETRAITES, EUROPE, CORÉE, 18 MARS, 6E RÉPUBLIQUE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#241]
## #RDLS20 : MACRON-RETRAITES, EUROPE, CORÉE, 18 MARS, 6E RÉPUBLIQUE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 09 mars 2017
**Durée**       | 0:20:46 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=0RjL1w62IGI)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=0RjL1w62IGI&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by JihedC** [comment]
Bonjour,

je me lance la dessus tout de suite.

**Comment by JihedC** [comment]
[RDLS 20 sous titre.docx](https://github.com/jlm2017/jlm-video-subtitles/files/834559/RDLS.20.sous.titre.docx)
ci joint les sous titres de la 1ere partie de la video, si quelqu'un les lit svp ne faite pas attention aux fautes d'orthographe, je corrigerais tout (j'espere avant de les ajouter sur youtube)

**Comment by JihedC** [comment]
[RDLS 20 sous titre.docx](https://github.com/jlm2017/jlm-video-subtitles/files/836151/RDLS.20.sous.titre.docx)

voila les sous-titre de la video entiere, je precise que j'utilise un clavier qwerty, il peut dont y avoir des fautes d'accent :(

**Comment by JihedC** [comment]
Bon, j'ai incorpore les sous titres jusqu'a la 5:53

**Comment by desintoxiquezvous** [comment]
@JihedC bonjour, je ne vois les sous titres que jusqu'a 1:23
 tu a bien envoyé la suite?

**Comment by JihedC** [comment]
Il me semble oui, je suis au boulot la je ne peux pas verifier. Est ce que l'enregistrement des sous titres soumis se fait de facon automatique? je ne les ai pas enregistres de peur de les confirmer sans relecture.

**Comment by desintoxiquezvous** [comment]
bonjour j’étais absent je ne te  répond que maintenant @JihedC 
on ne voit que jusqu’à 3:22 
il faut que tu fasse "envoyer la contribution" et cocher ensuite "laisser d'autre continuer" si tu n'as pas été jusqu’à la fin , sinon ça reste en brouillon en local sur ton ordi et rien n'apparait)
et de toute façon la relecture par 2 autres sous titreurs est nécessaire pour valider le tout ,rien a craindre 
si tu ne la connais pas , voici une petite vidéo de ma méthode pour créer rapidement les containers texte quand on dispose d'un texte complet (ou assez long) ce qui est le cas ici 
https://www.youtube.com/watch?v=JcU7XDS-BSM&t=8s

**Comment by JihedC** [comment]
ok! Merci pour les precisions, je ferai ca apres le boulot du coup. J'ai egalement ete assez pris et n'ai pas eu le temps de me plonger dessus. 
Merci pour la video!

**Comment by JihedC** [comment]
Est ce que c'est bon maintenant?

**Comment by Goutte** [comment]
Je vois les sous-titres jusqu'à 5:50.

**Comment by DominDamid** [comment]
Est-ce qu'une nouvelle procédure a été mise en place ? Il me semble que plusieurs vidéos, dont celle-ci, gardent le label "someone is working..." pendant plusieurs jours sans interruption...

**Comment by Goutte** [comment]
Bien vu, @DominDamid.
En théorie, le label rouge ne devrait pas rester sur les vidéos pendant plusieurs jours.

@JihedC : allez-vous continuer ?

**Comment by JihedC** [comment]
@Goutte Desole j'avais bastille hier :D 
je finis le sous titrage ce soir :)

**Comment by JihedC** [comment]
Desole urgence de derniere minute au travail, je n'ai pas eu le temps de m'en occuper.

Si quelqu'un veut incorporer les sous-titres du doc, feel free.

**Comment by desintoxiquezvous** [comment]
je m'y colle

**Comment by desintoxiquezvous** [comment]
@JihedC @Goutte terminé prêt pour 1ere relecture

**Comment by Goutte** [comment]
J'ai fait une relecture de la deuxième moitié, à valider.

**Comment by DominDamid** [comment]
@Goutte Est-ce que du coup la première relecture est terminée ? J'ai un peu du mal avec les nouveaux labels.
Quoi qu'il en soit je me mets à une relecture intégrale.

**Comment by DominDamid** [comment]
Bon, j'ai fini. Je mets dans la colonne suivante pour que la deuxième relecture soit faite.

**Comment by Goutte** [comment]
@DominDamid Non, je n'avais fait que la moitié de la première relecture, ça ne comptait pas.

Bravo pour la relecture intégrale !
