### ISSUE TITLE
[subtitles] [en] #RDLS20 : MACRON-RETRAITES, EUROPE, CORÉE, 18 MARS, 6E RÉPUBLIQUE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#242]
## #RDLS20 : MACRON-RETRAITES, EUROPE, CORÉE, 18 MARS, 6E RÉPUBLIQUE

&nbsp;        | Info
------------- | -------------
**Date**      | Thursday, 09 March 2017
**Duration**  | 0:20:46 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=0RjL1w62IGI)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=0RjL1w62IGI&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by JihedC** [comment]
J'ai ecrit les sous titre de la version francaise. 
si quelqu'un veut se servir de ce fichier comme base de traduction :)
[RDLS 20 sous titre.docx](https://github.com/jlm2017/jlm-video-subtitles/files/836153/RDLS.20.sous.titre.docx) je pense me lancer dans la traduction une fois que j'aurai fini d'incorporer les francais sur youtube.
