### ISSUE TITLE
[subtitles] [fr] EN DIRECT - MÉLENCHON : Esprit de Campagne spécial 18 mars - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#243]
## EN DIRECT - MÉLENCHON : Esprit de Campagne spécial 18 mars - #18mars2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 12 mars 2017
**Durée**       | 0:00:00 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=C1gERgeC0eo)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=C1gERgeC0eo&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
pour info, émission déjà sous-titrée dans sa version non direct, projet #253
