### ISSUE TITLE
[subtitles] [fr] MÉLENCHON À ON N'EST PAS COUCHÉ LE 11 MARS 2017 - #ONPC

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#245]
## MÉLENCHON À ON N'EST PAS COUCHÉ LE 11 MARS 2017 - #ONPC

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 12 mars 2017
**Durée**       | 0:28:23 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=oBk63rLd7kE)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=oBk63rLd7kE&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by quidam34** [comment]
Bonjour , je profite d'une vidéo courte pour tester mon idée que j'ai appelé "zéro obstacle" Je serais peut-être déçu , on verra !

**Comment by Goutte** [comment]
```
Danyvape nounou le pauvre c'est quand le quotidien
des Francesca le programme de janvier de Lorient
```

Aille. La reconnaissance vocale n'est pas encore au point ! C'est même de moindre qualité que l'ASR fourni par youtube.

Je reconnais bien là le genre de cochonneries qui ont été **publiées** sur le RDLS 21, et qui sabotent la crédibilité du mouvement des insoumis.

@quidam34 continuez-vous à travailler sur cette vidéo ? Le label rouge n'est pas censé rester des jours durant.

**Comment by Milsabor** [comment]
Bonsoir ! Je m'y attaque.

**Comment by Fromtware** [comment]
J'ai fais presque trois minutes. Je continuerais demain.

**Comment by Milsabor** [comment]
J'ai terminé le sous-titrage, passage en première correction !
@Fromtware : bonsoir ! En général, il est mieux d'attendre que chaque phase soit terminée pour commencer la suite, afin d'éviter de s'embrouiller ^^ Mais merci pour ton aide ! Je t'invite à te proposer comme premier.e relecteur.trice :)

**Comment by desintoxiquezvous** [comment]
1ère relecture faite. OK
