### ISSUE TITLE
Emission complète du chiffrage.

### ISSUE THREAD

**Issue by quidam34** [jlm2017/jlm-video-subtitles#247]
Bonjour , maxime propose sur le forum de fournir le fichier de l'émission complète du chiffrage. Or je ne la voit pas ici . Comment fait-on ?  

https://youtu.be/T7b67QCjibc

**Comment by Goutte** [comment]
Vous faites bien de demander ! :+1: 
J'ai demandé à @RobotInsoumis d'ouvrir une issue ici : #252

**Comment by maximerinna** [comment]
Comment on change de statut ?  je suis novice sur github ?
