### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : Esprit de Campagne spécial 18 mars (Version non complète) - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#248]
## MÉLENCHON : Esprit de Campagne spécial 18 mars (Version non complète) - #18mars2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 12 mars 2017
**Durée**       | 0:00:00 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=h1I6cBQk5e4)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=h1I6cBQk5e4&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
pour info, j'ai déjà sous-titré cette vidéo en version complète
