### ISSUE TITLE
Outil de communication type tchat

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#25]
Bonjour à tous ! 

La personne qui s'occupe des projets de développement pour JLM m'a proposé de créer sur leur tchat un channel pour notre groupe.

J'aimerais savoir si ça vous intéresse, déjà dans un premier temps, de discuter via tchat. 

Ensuite, si ça vous botte, voici plus de détails : 
- leur système s'appelle Mattermost, c'est un logiciel open source, installé sur un des serveurs de JLM, 
- pour vous inscrire, vous aurez besoin d'une adresse mail, 
- il existe une application mobile pour Mattermost, qui est plutôt pratique si vous avez un smartphone,
- pour l'instant, ce sont principalement des développeurs qui sont inscrits dessus. 

Si vous êtes toujours chaud, je vous donnerai le lien et on se fabriquera un channel pour discuter entre nous :) 

# Lien vers le tchat
https://chat.coders.jlm2017.fr

## Procédure
- Inscrivez-vous
- Envoyez un message privé à `luciledt`ou à `albapringe`
=> on vous ajoutera au groupe de discussion privé.

**Comment by Ricyeam** [comment]
Ca me parait vraiment bien comme idée !

**Comment by bayasahra** [comment]
génial ça !!! :)

**Comment by Bentham** [comment]
Nice ! Je plussoie, je poussoie !

**Comment by bayasahra** [comment]
@Bentham va vite me plussoiyer et me poussoiyer la revue 7 oueeeeeeeeee !!!! lol :p

**Comment by Bentham** [comment]
Aaaaaaah !! Pas si vite jeune fille, je reviens tout juste du boulot, alors la clope, un peu de guitare, et ce soir j'avance le projet au chaud 👍

**Comment by Flupignon** [comment]
Bonne idée ! Bon moi j'ai pas de smartphone par contre; je suis encore à l'âge de pierre :p

**Comment by LucileDT** [comment]
Pas de soucis, @Flupignon, c'est absolument pas obligatoire, juste plus pratique (par exemple, j'ai un smartphone avec une vieille version d'Android, je ne peux pas non plus utiliser l'application, à chacun son silex !).

**Comment by Ricyeam** [comment]
ah oui moi aussi vieille version, du coup pas dit que je puisse utiliser l'app…mais c'est pas grave ! ca a l'air d'etre une bonne idée quand même ^^

**Comment by LucileDT** [comment]
Allez, je up avec une mise à jour de l'issues, contenant le lien, et la procédure, pour rejoindre un tchat privé (hébergé sur les serveurs de jlm !) suite à la demande faite sur #121 :D

**Comment by NoelleM** [comment]
Tout à fait ce que j'espérais pour éviter les déperditions d'énergie... Les copiés/collés depuis FB ou autres s'avérant particulièrement fastidieux quand il concerne un nombre croissant de personnes aux idées lumineuses.... :)

**Comment by quidam34** [comment]
Bon ! en mêm temps si on ne s'y retrouve pas tous en même temps pour échnager c'est comme ici quoi ? non ? sauf qu'on peut joindre d'autres personne d'autres groupe , mais même là a qui sert "le chat" ce sera pas souvent des échanges en direct sauf rendez vous !

**Comment by NoelleM** [comment]
Je m'en sers de boîte postale : je dépose et la levée se fait au rythme de
chacun 😁 !
Perso, le tchat me convient vraiment bien mais n'hésitez pas à me dire,
amis de l'issue #45 ou #121, si cela ne vous va pas... Je m'adapterai au au
plus pratique !

**Comment by Goutte** [comment]
https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-Outils-de-communication-%C3%A0-votre-disposition
