### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : Esprit de Campagne spécial 18 mars (Version non complète) - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#250]
## MÉLENCHON : Esprit de Campagne spécial 18 mars (Version non complète) - #18mars2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 12 mars 2017
**Durée**       | 0:09:36 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=C1gERgeC0eo)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=C1gERgeC0eo&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by maximerinna** [comment]
Intégration brut des sous titres par la moulinette CC : le titre a supprimer svp : **C1gERgeC0eo**
"Moulinette CC de www.scribovox.ovh : Merci de corriger ce texte généré automatiquement par et pour les 10% de personnes sourdes et malentendantes."

**Comment by maximerinna** [comment]
Comment on change de statut ?  je suis novice sur github ?

**Comment by maximerinna** [comment]
Bon , je suis perdu dans ce github, je n'arrive a rien trop de fonctions. 

Il me manque des neurones,  es ce que  l'ont peu faire un truc simple svp .

Les correcteurs qui le souhaites me poste sur ce canal unique suivant : 
http://cc-scribovox.strikingly.com/#poster-un-lien-cc-youtube

 le lien de la vidéo Youtube a mouliné .   Actuellement j'ai posé 4 secondes de décalage pour que la synchronisations soit ok , me dire si cela suffit? 

Une fois fais, je l 'intègre dans la vidéo Youtube avec la Phase systématique suivante: 

"Moulinette CC de www.scribovox.ovh : merci de corriger ce texte généré automatiquement par et pour les 10% de sourdes et malentendantes."   

Après vous géré comme vous le souhaité le reste , je ne peu pas faire plus que cela. 

Avantage : C'est simple pour moi et je vais automatisé le flux des demandes pour ne rien avoir a faire .

Dite moi si c'est ok ?  je me répète, mais il n y a pas de contre partie, c'est ma contribution.

Pour le % de mot juste , je suis sur du 85 à 90% de mot juste , avec perte systématique du dernier mot de chaque phrase , la synchronisation doit être ok , me dire si ce n'est pas le cas.

**Comment by Goutte** [comment]
Hello !

> Il me manque des neurones, es ce que l'ont peu faire un truc simple svp .

Tu n'as normalement rien à faire de spécial sur github, à part vérifier que quelqu'un ne travaille pas déjà sur la vidéo "à la main". Que souhaites-tu faire sur github ?

> Actuellement j'ai posé 4 secondes de décalage pour que la synchronisations soit ok , me dire si cela suffit?

4 secondes, c'est un peu trop, les sous-titres sont en retard de 1.5s sur cette vidéo.

> je suis sur du 85 à 90% de mot juste

Effectivement, sur cette vidéo, c'est beaucoup mieux, je dirais 75-80% de mots justes pour ce que j'ai lu.

> Dite moi si c'est ok ?

Tant que tu mentionnes que les sous-titres ont été générés automatiquement, et que tu n'écrases pas les sous-titres ou brouillons faits par les autres contributeurs, je pense que tout le monde sera content ! :+1: 

---

As-tu pu comparer tes résultats à l'ASR de YouTube ?
