### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - Esprit de campagne spécial 18 mars (version complète) - #18mars2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#253]
## MÉLENCHON - Esprit de campagne spécial 18 mars (version complète) - #18mars2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 13 mars 2017
**Durée**       | 2:01:30 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=KFi2kVCEbww)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=KFi2kVCEbww&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by maximerinna** [comment]
en cours , comment on change de statut ?  je suis novice sur github ?

**Comment by Goutte** [comment]
Sur https://github.com/jlm2017/jlm-video-subtitles/projects/2 tu peux changer la carte de colonne !

**Comment by sentinelle2017** [comment]
je relis

**Comment by sentinelle2017** [comment]
désolée, je n'avais pas vu que c'était écrit par la moulinette, donc en fait j'ai remis un statut "writing in progress" parce qu'il y pas mal de taf... soyez indulgent, j'ai pas l'habitude, deuxième contrib seulement ;)
@MasterSlip

**Comment by sentinelle2017** [comment]
j'en suis à la 19eme minutes, si qq veut avancer un peu...

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 41'25 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 44'44 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 57'15 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
@RobotInsoumis : salut ! peux tu m'aider stp, ce doc a le statut "closed" et je n'arrive pas à le remettre en mode normal. en fait je suis toujours en train de bosser dessus

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 1'06'11 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 1'18'11 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
sous-titres fait jusqu'à 1'48'30 seulement, après c'est encore les sous-titres générés automatiquement
donc ne PAS PASSER LE DOC EN FINITION

**Comment by sentinelle2017** [comment]
a ceux qui vont relire : j'ai vraiment galérer sur cette vidéo, tout à reprendre, sous titres mal calés, beaucoup de paroles qui se croisent... Bref, j'ai fait de mon mieux, mais au bout d'une dizaine d'heures, je pense que je ne suis plus très objective, alors n'hésitez pas à bien corriger, et à recaler les sous-titres ci besoin :) merci

**Comment by SarahBu** [comment]
Sous-titrage parfaits pour moi.

**Comment by sentinelle2017** [comment]
Merci d avoir pris le temps 😊 je ferais les tiens si j y arrive



Le 18 avr. 2017 à 21:22, SarahBu <notifications@github.com<mailto:notifications@github.com>> a écrit :


Sous-titrage parfaits pour moi.

**Comment by SarahBu** [comment]
Pourquoi c'est repassé en Second Review ? @RobotInsoumis

**Comment by sentinelle2017** [comment]
parce que tu as fait la first review, mais pas la second review, il faut deux relecteurs différents pour passer "approved", c'est pour ça qu'on le fait ensemble sur l'autre doc @SarahBu 

mais @RobotInsoumis c'est vrai que sur ce coup c'est dommage car il n'y a que 9 mn à relire et le reste est vélotypie

**Comment by Goutte** [comment]
@RobotInsoumis est un peu ... zélé. Je réfléchis à une solution. Idées ?

**Comment by sentinelle2017** [comment]
@Goutte : pour les cas de vélotypie ? pourrait-on créer peut-être créer un statut "approved spécial vélotypie" ? de ce que j'ai compris, il n'y a pas eu de décision collective de savoir s'il fallait retranscrire les vélotypie ou pas, c'est ça... pour ma part, je trouve que ce serait assez inutile et pas forcément évident à lire à l'écran, d'autant qu'on manque de temps pour tout faire... j'ai l'impression qu'on est pas beaucoup sur ce job, en ce moment en tout cas, j'ai vu que le discord avait fait énormément de choses à côté, c'est sûrement pour ça. mais si on veut rattraper le retard avant le 2eme tour... enfin voilà ;) bonne journée !

**Comment by sentinelle2017** [comment]
@Goutte j'ai dit une connerie, sur cette carte il n'y a pas que 9 mn à relire, je l'ai écrit en entier, le problème se pose sur la carte #310 
désolée, je fatigue...

**Comment by SarahBu** [comment]
Question con... c'est quoi vélotypie ?

Cordialement,

Sarah Bultez 
(Envoyé de mon IPhone )

**Comment by sentinelle2017** [comment]
y'a pas de question con @SarahBu ;) vélotypie c'est le système qui écrit directement les sous titres en direct pendant les meeting, donc c'est les textes qui sont déjà incrustés sur les vidéos. mais tout n'est pas sous-titrés : par exemple, les clips diffusés ou les émissions ne le sont pas

**Comment by SarahBu** [comment]
Ah ok. Du coup il faut les checker quand même ^^
Reçu 5/5

Cordialement,

Sarah Bultez 
(Envoyé de mon IPhone )

**Comment by sentinelle2017** [comment]
oui on fait un rapide check pour voir s'il faut ajouter des ST sur certaines choses [😊]


bonne journée :)


________________________________
De : SarahBu <notifications@github.com>
Envoyé : vendredi 21 avril 2017 13:11
À : jlm2017/jlm-video-subtitles
Cc : Sentinelle2017; State change
Objet : Re: [jlm2017/jlm-video-subtitles] [subtitles] [fr] MÉLENCHON - Esprit de campagne spécial 18 mars (version complète) - #18mars2017 (#253)

Ah ok. Du coup il faut les checker quand même ^^
Reçu 5/5

Cordialement,

Sarah Bultez
(Envoyé de mon IPhone )
