### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «LA CONSTITUTION DE LA 5E RÉPUBLIQUE EST DANGEREUSE»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#255]
## MÉLENCHON : «LA CONSTITUTION DE LA 5E RÉPUBLIQUE EST DANGEREUSE»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 13 mars 2017
**Durée**       | 0:50:25 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=pFlHwR-OYLk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=pFlHwR-OYLk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by MenvussaG** [comment]
Je m'y mets sur celle là, quelqu'un a commencé mais c'est bien pourri...

**Comment by MenvussaG** [comment]
Rhaaaaaaa quelle galère ces sous titrages automatiques, franchement il y a pas un moyen d'effacer tout ? (bon j'ai quand même bien rit quand il a traduit El Khomeri par El connerie) !!
j'ai fini le texte, reste le timing encore...

**Comment by Goutte** [comment]
C'est probablement le sabotage de @quidam34, comme pour les autres vidéos.

**Comment by MenvussaG** [comment]
ouf, ça y est sur celle-là, à relire parce que j'ai été à la serpe sur la fin
