### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «LE PLAN B, C'EST LE PLAN DE LA PAIX»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#258]
## MÉLENCHON : «LE PLAN B, C'EST LE PLAN DE LA PAIX»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mardi 14 mars 2017
**Durée**       | 0:22:00 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=sektMcC_PAk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=sektMcC_PAk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by MenvussaG** [comment]
Bon j'ai fait la moitié de celle ci pour tester, 
je sais pas comment changer les labels (si j'ai compris c que j'ai pas les droits)
a demain
dodo.

**Comment by MenvussaG** [comment]
Ok c'est fini de mon côté, si quelqu'un passe par là, à mettre en relecture,
merci

**Comment by MenvussaG** [comment]
non, vraiment ? personne ne passe par ici ?
"#jycomprendsrien
