### ISSUE TITLE
[subtitles] [FR] JUPPÉ, FILLON - SUPPRIMER L'ISF : LA POLITIQUE DES RICHES

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#26]
# Video title

 JUPPÉ, FILLON - SUPPRIMER L'ISF : LA POLITIQUE DES RICHES

# URL

https://www.youtube.com/watch?v=uSUGLX7DtkI

# Youtube subtitles language

Français

# Duration

2:21

# URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&tab=captions&forceedit=timedtext&lang=fr&ref=watch&v=uSUGLX7DtkI&ui=hd&action_mde_edit_form=1

**Comment by bayasahra** [comment]
alors je dois mal entrer les liens ça fonctionne pas ... quelqu'un pour me dire où est mon erreur ? ^^

**Comment by bayasahra** [comment]
sous titrage + timing + ortho
travail fini
bon pour vérification et validation
une petite chose: à 2:12 un mot me manque j' ai mis 3 points d'interrogation pour celui qui trouve
==> " ceux qui ??? l' ISF
( me suis régalée... extrait super bien choisi !!! bravo au staff youtube de mélenchon :) )

**Comment by dalipokim** [comment]
Salut, pour le mot manquant je dirais ( ceux qui ont l'i isf) qu'il bute sur le mot, tout simplement. Je passerais voir pour la validation plus tard.

**Comment by Flupignon** [comment]
Comme @dalipokim je dirais qu'il a bégayé oui.
Par contre tu mets pas de ponctuation / majuscules ?
Et comme je disais dans #23 je pense pas qu'il faille autant hacher les sous-titres dés qu'il y a une petite pause, il faudrait peut-être mieux regrouper les sous-titres pour que ça défile moins vite. Qu'est-ce qu'en pensent les autres ?

**Comment by bayasahra** [comment]
@dalipokim merciiiiiii :)
@Flupignon  hummm je sais pas c 'est du ressenti et on a tous un ressenti différent ^^ faut que les autres viennent lire pour voir si ça leur convient... moi perso si je le fais comme ça c'est que ça me convient pour la dynamique du discours... je me mets à la place du malentendant parce que bien évidemment avant de valider j'enlève le son et fait une relecture vidéo qu'avec les sous titres... et je trouve que ça lui donne un indice sur le rythme, le tempo et que ça fait donc partie de la personnalité de celui qui parle et je n'ai pas de problème particulier à tout lire ...  à débattre bien sur

**Comment by bayasahra** [comment]
tiens temps qu' on y est :) elle est courte elle ^^

**Comment by Bentham** [comment]
Je suis dessus !

**Comment by Bentham** [comment]
Fait ! Quelques corrections de mise en forme, des petits contresens, rien de très grave. A valider de votre côté

**Comment by dalipokim** [comment]
Salut, j'ai corrigé la ponctuation et bougé quelques containers. Rien de méchant mais ça fluidifie la lecture.
Un truc bizarre : J'ai refermé la page ensuite je la ré ouvre et mon taf a disparu !!!

**Comment by Bentham** [comment]
oups, j'espère que nos corrections ne se sont pas marché dessus...

**Comment by dalipokim** [comment]
Au pire c'est pas grave ! J'y ai passé 5 mn ! Ca m’embêterais que mon taf sur Mamère soit perdu !! Il y en déjà pour plus de 8 h !

**Comment by Bentham** [comment]
Alors faut faire attention, apparemment les corrections ont été faites en même temps... Ce qui fait que je vois mes corrections à moi, mais que Baya voit les corrections de Dalipokim...
Donc je propose de faire attention ! Perso quand je commence une transcription, je l'annonce ici sur la page appropriée, et je mets un autre message quand j'arrête de bosser. Ce serait peut-être mieux qu'on s'abstienne de toucher aux sous-titres quand quelqu'un est déjà en train de les modifier...

Qu'en pensez-vous ?

**Comment by dalipokim** [comment]
Désolé je n'avais pas vu ! Où se situe l'indication que quelqu'un bosse ? Est-ce en temps réel?

**Comment by Bentham** [comment]
Pas de pb, c'est pas du gros gros boulot non plus ! J'ai publié ici il y a une demie-heure "Je suis dessus !"

**Comment by dalipokim** [comment]
Je confirme ! J'avais survolé ! Je ferais gaffe maintenant ! Bon courage.

**Comment by Bentham** [comment]
Sous-titres affichés sur youtube ! Encore une victoire de canard.
