### ISSUE TITLE
[subtitles] [en] MÉLENCHON : «JE VOTE CONTRE L'EUROPE DE LA GUERRE»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#268]
## MÉLENCHON : «JE VOTE CONTRE L'EUROPE DE LA GUERRE»

&nbsp;        | Info
------------- | -------------
**Date**      | Thursday, 16 March 2017
**Duration**  | 0:00:59 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=XjhASOwTqBg)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=XjhASOwTqBg&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by Flupignon** [comment]
Hello tout le monde, je suis pas venu depuis un moment alors je reprends petit à petit avec cette courte vidéo.

**Comment by Goutte** [comment]
Ah, j'avais commencé en screud'...

Tiens, ce que j'ai fait :

```
0:00:00.000,0:00:05.080
I'm voting against this text because its objective is to evade the obligation

0:00:05.220,0:00:08.640
to submit a treaty to all europeans

0:00:08.800,0:00:12.780
before entering this absurd Europe of war that you're brewing.

0:00:13.060,0:00:17.840
I am concerned with the binary vision this text holds,
opposing, for unknown reasons,

0:00:18.140,0:00:21.800
a zone called "asiatic" to a zone called "euro-atlantic".

0:00:22.100,0:00:26.100
I'm worried to see that you already
established a military Staff

0:00:26.520,0:00:31.900
and further worried that the text is supposed to prepare us to high intensity conflicts

0:00:32.000,0:00:34.400
which is to say, war - no more, no less.

0:00:34.740,0:00:38.240
In the same way it calls for reinforcement of the networks of OTAN.
```

**Comment by Goutte** [comment]
Je crois que c'est le sous-titrage le plus rapide que @RobotInsoumis ait jamais vu : 2 heures entre l'ouverture et la fermeture !
