### ISSUE TITLE
[subtitles] [FR] NOËL MAMÈRE - JEAN-LUC MÉLENCHON : REGARDS CROISÉS

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#27]
# Video title

NOËL MAMÈRE - JEAN-LUC MÉLENCHON : REGARDS CROISÉS

# URL

https://www.youtube.com/watch?v=X3bHtC2CKs8

# Youtube subtitles language

Français

# Duration

59:02

# URL subtitles

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=X3bHtC2CKs8&ui=hd&ref=watch&lang=fr&tab=captions&bl=vmp&forceedit=timedtext

**Comment by bayasahra** [comment]
@dalipokim ici dali :)

**Comment by dalipokim** [comment]
de 10:08 à 10:15, les gars parlent ensemble, je transcrit celui qui parle le plus fort !!! Si quelqu'un veut compléter...

**Comment by dalipokim** [comment]
je ne comprend pas les mots  10:44 (j'ignorais ?)    11:09 (pas?)

**Comment by bayasahra** [comment]
@dalipokim 
10:44 ==>  " je dirais il y a un troisième élément"
11:09 ==>  " nos pas"

**Comment by dalipokim** [comment]
merci ! Je risque de repasser par ici, ma petite hi fi faisant ce qu'elle peut ! !!!

**Comment by dalipokim** [comment]
Avis a la popoulationne ! Je ne fais plus les parties ou les voix se superposent, je perd mon temps donc je signalerais les passages, les bonnes âmes, soit me diront quoi mettre soit rempliront d'elles mêmes, merci.

**Comment by dalipokim** [comment]
J'ai une idée de méthode de travail, parce que c'est chronophage de tout faire ! Une personne fait la prise "sténo" en .txt, la transmet à un correcteur, qui transmet a un monteur/ ajusteur. Chacun un tiers du boulot, au moins sur les longues vidéos ! Qu'est-ce que vous en pensez ?

**Comment by bayasahra** [comment]
@dalipokim dali faut avancer petit à petit, t'es pas un esclave sous le fouet !! lol ... tu peux faire 3 minutes de vidéo par jours ça aide quand même tout le monde sans te saturer .... on est une équipe ... c est l'avantage ;)

**Comment by dalipokim** [comment]
3mn par jours ça ne sera jamais prêt pour l'élection !!! J'ai du temps libre, alors allons y !

la liste des corrections, les trucs où je n'ai pas compris et j'ai besoin d'un coup de main ! 

12:06----12:12 ?
15:11 (pas compris JLM)
19:58 ?
20:10 éclairant ?
20:40 ?
21:47 Marc Thiessen ?? prix Nobel (connais pas !)
22:22 à voir si on met Mélenchon ou le journaliste
22:40 ?
23:45 pas compris Noël
25:04 grobordel !
27;05-----27:09 ?
29:52 ?
32:57 vérifier les noms
33:17 ?
34:19----34:25 
34:33 ?
38:22 vérifier noms
42:32 ?
44:32 vocable ?
44:51 beau chantier ?
45:40 ?
45:47 ?
46:02 ?
46:13 ?
46:26 ?   
A+

**Comment by dalipokim** [comment]
17h25 je commence a tafer

**Comment by dalipokim** [comment]
je reprend plus tard dans la soirée, là il y a une réunion des Insoumis ! Pour rappel !

**Comment by Bentham** [comment]
Oublie pas d'envoyer régulièrement pour examen avec le bouton en haut à droite, même si tu précises ensuite que c'est pas fini. Pour l'instant je ne vois pas tes sous-titres apparaître, j'espère que ça a été validé !

**Comment by dalipokim** [comment]
et merde je ne l'ai pas fait ! Est-ce que tu es dessus car j'ai l'intention
de m'y remettre.

2016-11-30 19:16 GMT+01:00 Bentham <notifications@github.com>:

**Comment by dalipokim** [comment]
Est-ce que quelqu'un bosse en ce moment sur la vidéo NOËL MAMÈRE - JEAN-LUC MÉLENCHON : REGARDS CROISÉS ?

**Comment by Bentham** [comment]
no pas moi en tout cas

**Comment by dalipokim** [comment]
ok donc j'y vais ! 22h 25

**Comment by bayasahra** [comment]
@dalipokim ça va tu t'en sors ?? tu tiens le coup ???  lol :)

**Comment by dalipokim** [comment]
a donf c'est copieux mais ca va ! tu fais quoi ?

2016-12-01 0:12 GMT+01:00 Baya <notifications@github.com>:

**Comment by dalipokim** [comment]
Coucou les gens, j'ai fini pour ce soir, j'ai envoyé pour examen(non fini) et j'ai fini aux alentours de 43:30. Bonne nuit !

**Comment by dalipokim** [comment]
Salut tout le monde quelqu'un bosse sur NOËL MAMÈRE - JEAN-LUC MÉLENCHON : REGARDS CROISÉS ?

**Comment by Flupignon** [comment]
Slt, non je suis sur la FAQ. Enfin quand mon fils me laissera du temps -_-

**Comment by dalipokim** [comment]
Ok je la fait alors. Sinon j'ai dom dom qui a l'air intéressée pour participer, comment je la met en relation et avec qui ?

**Comment by Flupignon** [comment]
Y'a déjà quelqu'un sur la FAQ en ce moment, donc si il y est encore ce soir, je me remettrai sur JLM-Mamère. Pour ta pote, jpense qu'il faut qu'elle s'inscrive sur github et tu lui donne l'adresse de notre projet.
Pour les questions la mieux placée c'est @LucileDT je pense (désolé Lucile...).

**Comment by dalipokim** [comment]
c'est quelqu'un avec un pseudo sur YT, pote pas encore !!! La problème est que je suis déjà sur NOËL MAMÈRE - JEAN-LUC MÉLENCHON...du coup je ne sais pas si c'est bon d'être a plusieurs dessus ?

**Comment by Flupignon** [comment]
Non mais je peux pas maintenant, tout à l'heure si t'y es plus jveux dire.

**Comment by dalipokim** [comment]
yep je suis parti pour finir le gros du boulot ! Il me reste 10 mn à transcrire (càd +-2 heures de taf) mais il y pas mal de trous ou je ne capte pas trop ce qui est dit, donc il en restera à faire !

**Comment by LucileDT** [comment]
Pour ce qui est des contacts qui cherchent à nous rejoindre, vous pouvez déjà lire cette issue : #13

Je pense que l'idéal est de leur donner le lien vers l'issue https://github.com/jlm2017/jlm-video-subtitles/issues/19
Pour l'instant, on a pas mieux. Je ferai une boîte mail ce soir, et je vous donnerai l'adresse, comme ça, on évitera de donner nos adresses personnelles dans des commentaires publics :)

**Comment by dalipokim** [comment]
CA Y EST J'AI FINI !!! J'en peux plus ! Donc je finis de lister les trous que j'ai laissé et je vous laisse finir ! Je ne pensais pas en voir le bout !

**Comment by Flupignon** [comment]
23:07 > "caucus"

**Comment by Flupignon** [comment]
Bon j'ai juste comblé les trous mais j'ai pas le temps de tout relire.
Juste deux trois remarques : 
1) Oublie pas le tiret à Jean-Luc.
2) Pas de 's' à la première personne de l'impératif du premier groupe (ex : Écoute !)

**Comment by dalipokim** [comment]
ok, j'utilise la correction automatique pour compléter !!!

2016-12-02 8:50 GMT+01:00 Flupignon <notifications@github.com>:

**Comment by dalipokim** [comment]
Salut j'ai quelqu'un de youtube qui est intéressée de tafer ici, quel lien
je donne ?

**Comment by LucileDT** [comment]
Tu peux donner le lien Facebook ou l'adresse mail suivante : traducteurs.insoumis@gmail.com

**Comment by dalipokim** [comment]
Ok merci je le fait de ce pas !!!

2016-12-02 19:01 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by LucileDT** [comment]
Merci à toi :)

**Comment by Bentham** [comment]
Je m'y mets

**Comment by Bentham** [comment]
Correction terminée et validation

**Comment by dalipokim** [comment]
IL y a quelque chose qui m'intrigue ! QUi a fait :si c'est pas quelqu'un
d'ici ça ne pourrait pas être "dom dom sur YT ? (qui voulait participer
mais j'ai plus de nouvelles
Europe : « Il faut rompre avec ce monde pourri » - Mélenchon
si c'est pas quelqu'un d'ici ça ne pourrait pas être "dom dom sur YT ? (qui
voulait participer mais j'ai plus de nouvelles)

2016-12-04 11:04 GMT+01:00 Bentham <notifications@github.com>:

**Comment by Ricyeam** [comment]
@dalipokim est-ce que tu pourrais essayer de choisir la bonne issue quand tu postes ? J'ai vu que tu as créé une issue pour la vidéo que tu mentionnes et c'est très bien, mais ça risque de vite devenir problématique si tout le monde poste où bon lui semble sans suivre la classification. Merci !

**Comment by LucileDT** [comment]
Plus exactement : 
- quand tu penses à un problème qui concerne notre manière de faire, est-ce que tu peux poster dans l'issue #10 ? 
- quand tu penses à un problème de com avec les autres sous-titreurs, est-ce que tu peux poster dans l'issue #13 ?

Quitte à, dans chacune de ces issues, mettre un #numéro_de_l_issue qui t'a fait penser au problème :) Comme ça, on peut retrouver facilement tous les messages qui concernent une problématique dans la même issue.

**Comment by bayasahra** [comment]
je commence la deuxième validation !

**Comment by bayasahra** [comment]
corrigé et validé ( avec pause au milieu désolé ^^le sous titrage n' est pas encore validé par youtube donc je ne "close" pas l' issue.

**Comment by Bentham** [comment]
Je viens de valider de mon côté, tout est en place sur youtube ! Je ferme l'issue !

Yes !
