### ISSUE TITLE
[subtitles] [zh] NOUVEAU TRAITÉ EUROPÉEN : LA FINANCE AVANT LE PEUPLE !

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#270]
## NOUVEAU TRAITÉ EUROPÉEN : LA FINANCE AVANT LE PEUPLE !

&nbsp;        | Info
------------- | -------------
**Date**      | Friday, 17 February 2017
**Duration**  | 0:01:05 :clock7:
**Language**  | 中国 :cn:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=YlBapm_yXRI)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=YlBapm_yXRI&tab=captions&bl=vmp&action_mde_edit_form=1&lang=zh&ui=hd)

**Comment by Goutte** [comment]
Yes ! Bien joué !

**Comment by Goutte** [comment]
Il manque les deux dernières lignes, pour que je puisse valider !

**Comment by miranda17** [comment]
Et là c'est bon ? J'ai fait copier-coller parce que comme certaines choses ne se traduisent pas mot à mot, ce n''est pas en phase. Aussi tu peux valider les deux autres vidéos, à part si y'a d'autre sinophones qui veulent repasser (mais je sais pas si y'en a).

**Comment by Goutte** [comment]
C'est bon, j'ai validé ! (même si je n'y comprends rien)
