### ISSUE TITLE
[subtitles] [fr] #RDLS21 : 666 PARRAINAGES, 18 MARS, CAC 40, BNP, LAFARGE, RÉCHAUFFEMENT CLIMATIQUE, KENYA, AUSTRALIE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#272]
## #RDLS21 : 666 PARRAINAGES, 18 MARS, CAC 40, BNP, LAFARGE, RÉCHAUFFEMENT CLIMATIQUE, KENYA, AUSTRALIE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 17 mars 2017
**Durée**       | 0:24:23 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=wBmP_9Gwry0)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=wBmP_9Gwry0&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by DominDamid** [comment]
Bon, je vois sur YouTube que des sous-titres sont déjà présents, bien que très aléatoires. Je déplace donc dans la deuxième colonne et arrange un peu tout cela.

**Comment by DominDamid** [comment]
J'ai repris en main le texte, ajusté les blocs de sous-titres jusqu'à 7:32.

**Comment by Goutte** [comment]
Ah, oui, effectivement, ce sont des sous-titres de faible qualité, générés automatiquement.

Il y a des boulettes énormes, comme :

`Blanche saumon -> Et bien ce sont`

J'ai continué la "relecture" jusqu'à 8 minutes.

...

Les timings sont ratés, ni faits ni à faire. Ca prendrait moins de temps de tout refaire de zéro. On dirait que quelqu'un sabote volontairement les sous-titres...

@DominDamid Méfie-toi, on dirait le travail de quidam34, qui a aussi tendance à écraser les contributions des autres.

**Comment by Goutte** [comment]
Le pire, c'est que certains ont validé les sous-titres foireux, et que maintenant ils sont publiés.

@LucileDT peut-être que si Antoine voit cette vidéo en ligne avec ces sous-titres foireux, ça le motivera à nous donner les accès pour qu'on puisse modérer ?

**Comment by Goutte** [comment]
Je ré-ouvre, car ce n'est pas fini.

**Comment by Goutte** [comment]
J'ai continué jusqu'à 12:02.

C'est ennuyeux car c'est plus de travail que si il n'y avait rien.

**Comment by Goutte** [comment]
À relire en entier, il y a encore de quoi corriger.

C'est urgent, car les sous-titres foireux (courtoisie de @quidam34) sont déjà publiés.
