### ISSUE TITLE
[subtitles] [en] MÉLENCHON : Défilé pour la 6e République - #18mars2017

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#277]
MÉLENCHON : Défilé pour la 6e République - #18mars2017

Date	Samedi 18 mars 2017
Durée	1:07:18 🕖
Langue	anglais :gb: 
Vidéo	https://www.youtube.com/watch?v=b5atq_VZd2M
Sous-titres	https://www.youtube.com/timedtext_editor?ref=player&bl=vmp&ui=hd&v=b5atq_VZd2M&lang=en&tab=captions&action_mde_edit_form=1&new=yes&edit_id=YOUTUBE_CAPTIONS3icnXILYExCQpaF_7BsYUw8qSHPviGZ6

**Comment by Flupignon** [comment]
J'ai traduit les 10 premières minutes pour un premier extrait sur la chaîne en anglais. Je ne sais pas si j'aurai le temps de finir le discours par contre... Désolé pour la mise en forme, je ne sais pas trop comment la reproduire (je suis un illettré du numérique je vous rappelle !).

**Comment by Bastien-Toronto** [comment]
Salut. Merci d'avoir commencer ce gros boulot.
Sur le lien Youtube sous-titre, il y a a la fois la transcription temps reel et le sous-titrage en anglais. C'est un peu le bazar, non? Y a t'il moyen d'avoir la meme video sans la transcription en temps reel ?
Merci

**Comment by Goutte** [comment]
Hello @Flupignon !

Pour ouvrir une nouvelle issue sur une vieille vidéo, il vous suffit de visiter l'URL suivante :

   `https://bot.insoumis.online/captions/create/<LANGUAGE>/<VIDEO_ID>`
   - `<LANGUAGE>` peut être `fr`, `en`, `de` (allemand) ou `zh` (chinois).
   - `<VIDEO_ID>` est l'identifiant youtube de la vidéo.

De la sorte, elle sera formatée parfaitement, la carte sera créée dans le tableau approprié, etc.
Et le bot pourra la fermer automatiquement une fois les sous-titres publiés !

Je te laisse essayer avec cette vidéo `b5atq_VZd2M`, puis fermer cette issue ;)

**Comment by Goutte** [comment]
@Bastien-Toronto Nous adorerions avoir la vidéo sans la vélotypie, mais l'équipe officielle ne veut pas, pour la raison (à ce qu'on m'a dit) que ça requiert de leur part de téléverser une nouvelle vidéo, et donc de perdre le nombre de vues (la notoriété générale) de la première. Pour ma part je pense que ce n'est pas un argument suffisant, mais c'est eux qu'il faut convaincre.

**Comment by Bastien-Toronto** [comment]
Merci @Goutte

**Comment by Heneark** [comment]
Pfiou, c'était un gros morceau, mais j'ai enfin fini!
Pour la citation de Victor Hugo, j'ai directement pris une version traduite du texte [https://archive.org/details/williamshakespea00hugouoft], donc il y a effectivement quelques mots probablement inconnus des non-natifs.
