### ISSUE TITLE
[subtitles] [fr] #RDLS22 - MORTS DE LA RUE, CLIMAT, NICOLAS HULOT, 18 MARS, GRAND DÉBAT TF1, PROCURATIONS

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#279]
## #RDLS22 - MORTS DE LA RUE, CLIMAT, NICOLAS HULOT, 18 MARS, GRAND DÉBAT TF1, PROCURATIONS

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 23 mars 2017
**Durée**       | 0:33:09 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=rRLUDT7ueoE)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=rRLUDT7ueoE&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by MenvussaG** [comment]
Bonjour,
je commence

**Comment by MenvussaG** [comment]
entretemps la vidéo s'est fait hacké à nouveau...fait ch...
j'efface tout, je recommence et surtout j'enregistre ce que je fais :)

**Comment by desintoxiquezvous** [comment]
@MenvussaG 
pour info si tu pense que ça peut te servir ....
regarde ma méthode de sous titrage ici issue #171
dans un premier temps reconnaissance vocale selon la méthode de @bentham ,(je tape trop lentement pour écrire directement)
https://youtu.be/q68KAKVCOP4
pour la reco vocale je me sers comme @bentham de google doc dans Chrome
moi, je procède comme suit:
j'écoute sur mon ipad ou mac book ,au casque, le discours, phrase par phrase, je mets en pause entre chaque , et je répète la phrase dans google doc sur mon imac avec un micro externe (meilleure reconnaissance que le micro de la webcam incorporée ), j'en fait une dizaine de mn (ce peut être une phrase longue ou une partie de phrase sachant que la reco tient compte du contexte de la phrase pour une meilleure transcription)
ensuite retouche du texte dans word avec dictionnaire pour retoucher un max de fautes (le tout me prends environ 1h pour 5 a 10 mn de texte )
ensuite copie de l'ensemble du texte corrigé dans le 1er container puis création dynamique des containers par coupe chronologique
voir ci dessous
https://youtu.be/JcU7XDS-BSM
ça marche super bien c'est presque du temps réel si on a pris soin de corriger le maximum de fautes avant
comme j'ai déjà fait avec d'autres sous titreurs :  si tu commence un sous titrage tu peux faire un appel au peuple pour que quelqu'un t'avance en t'envoyant un pdf d'une partie du texte un peu plus loin (attention ne pas travailler SUR le sous titrage dans youtube en même temps qu'un autre ça met des bugs ....)

**Comment by MenvussaG** [comment]
@desintoxiquezvous
merci pour la méthode, j'ai pas encore de micro donc pas facile pour la reconnaissance vocale :)pour le sous titrage, c'est ce que j'utilise d'habitude !

      De : desintoxiquezvous <notifications@github.com>
 À : jlm2017/jlm-video-subtitles <jlm-video-subtitles@noreply.github.com> 
Cc : MenvussaG <petiot38@yahoo.Fr>; Mention <mention@noreply.github.com>
 Envoyé le : Samedi 25 mars 2017 22h40
 Objet : Re: [jlm2017/jlm-video-subtitles] [subtitles] [fr] #RDLS22 - MORTS DE LA RUE, CLIMAT, NICOLAS HULOT, 18 MARS, GRAND DÉBAT TF1, PROCURATIONS (#279)
   
@MenvussaG
pour info si tu pense que ça peut te servir ....
regarde ma méthode de sous titrage ici issue #171
dans un premier temps reconnaissance vocale selon la méthode de @bentham ,(je tape trop lentement pour écrire directement)
https://youtu.be/q68KAKVCOP4
pour la reco vocale je me sers comme @bentham de google doc dans Chrome
moi, je procède comme suit:
j'écoute sur mon ipad ou mac book ,au casque, le discours, phrase par phrase, je mets en pause entre chaque , et je répète la phrase dans google doc sur mon imac avec un micro externe (meilleure reconnaissance que le micro de la webcam incorporée ), j'en fait une dizaine de mn (ce peut être une phrase longue ou une partie de phrase sachant que la reco tient compte du contexte de la phrase pour une meilleure transcription)
ensuite retouche du texte dans word avec dictionnaire pour retoucher un max de fautes (le tout me prends environ 1h pour 5 a 10 mn de texte )
ensuite copie de l'ensemble du texte corrigé dans le 1er container puis création dynamique des containers par coupe chronologique
voir ci dessous
https://youtu.be/JcU7XDS-BSM
ça marche super bien c'est presque du temps réel si on a pris soin de corriger le maximum de fautes avant
comme j'ai déjà fait avec d'autres sous titreurs : si tu commence un sous titrage tu peux faire un appel au peuple pour que quelqu'un t'avance en t'envoyant un pdf d'une partie du texte un peu plus loin (attention ne pas travailler SUR le sous titrage dans youtube en même temps qu'un autre ça met des bugs ....)—

**Comment by MenvussaG** [comment]
Job done
a relire

**Comment by DominDamid** [comment]
J'ai relu (oublié de mettre le label pendant le travail mais il semble que ce soit bon...).
Les coupures ne sont pas top mais je n'y ai pas retouché pour qu'on puisse sortir les sous-titres au plus tôt.

**Comment by MenvussaG** [comment]
@goutte merci pour l'invit,
@DominDamidmerci, je vais essayer de m'appliquer,
j'ai changé le label de la #255 pour relecture, je pense que les coupures sont encore pire ! (tout le monde parle en meme temps dans cette emission a la con) Jocelyn

      De : DominDamid <notifications@github.com>
 À : jlm2017/jlm-video-subtitles <jlm-video-subtitles@noreply.github.com> 
Cc : MenvussaG <petiot38@yahoo.Fr>; Mention <mention@noreply.github.com>
 Envoyé le : Vendredi 31 mars 2017 1h37
 Objet : Re: [jlm2017/jlm-video-subtitles] [subtitles] [fr] #RDLS22 - MORTS DE LA RUE, CLIMAT, NICOLAS HULOT, 18 MARS, GRAND DÉBAT TF1, PROCURATIONS (#279)
   
J'ai relu (oublié de mettre le label pendant le travail mais il semble que ce soit bon...).
Les coupures ne sont pas top mais je n'y ai pas retouché pour qu'on puisse sortir les sous-titres au plus tôt.—
