### ISSUE TITLE
[subtitles] [eng] Mélenchon - FAQ 30/11/16

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#28]
# Video title
MÉLENCHON - FAQ - 6E RÉPUBLIQUE, CANNABIS, BIO, YOUTUBE, SNOWDEN, ASSANGE…

# URL
https://www.youtube.com/watch?v=GkPZ3sIhMPg

# Youtube subtitles language
Anglais

# Duration
48:34

# Subtitles URL
https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&ui=hd&v=GkPZ3sIhMPg&lang=en&ref=player&tab=captions

**Comment by Ricyeam** [comment]
Je n'ai pas commencé, juste fais l'intitulé de l'issue.

**Comment by ClaireEV** [comment]
Je vais commencer, je ne sais pas combien je ferai ! je vous tiens au courant dans la journée

**Comment by Ricyeam** [comment]
Je viens de vérifier, rien n'a été commencé en Anglais.

**Comment by Flupignon** [comment]
4:46

**Comment by Flupignon** [comment]
11:13

**Comment by Flupignon** [comment]
16:07

**Comment by Flupignon** [comment]
19:33

**Comment by Flupignon** [comment]
22:46

**Comment by Flupignon** [comment]
31:42

**Comment by Flupignon** [comment]
34:10

**Comment by Flupignon** [comment]
Je reprends... avec les conseils de @Bentham ! :)

**Comment by Flupignon** [comment]
Terminé, mais il faut que je relise et que je refasse le timing.

**Comment by Flupignon** [comment]
J'ai dû réimporter les sous-titres sur la chaîne en anglais parce que quand les sous-titres ont été validés en français, ce n'est plus possible de modifier le timing, et je les réimporterai une fois que ce sera fini avec le nouveau timing.

**Comment by Flupignon** [comment]
20:24

**Comment by Flupignon** [comment]
37:31

**Comment by Flupignon** [comment]
Fini ! C'était pas du gâteau cette FAQ... Il y a pas mal d'adaptations à cause de la dimension très orale. Bon courage @Ricyeam et @Blange1 !

**Comment by Blange1** [comment]
J'ai relu et fait juste quelques modifs, notamment des sauts de ligne pour faciliter la lecture. Joli travail @Flupignon !

**Comment by Blange1** [comment]
Désolée pour les bugs d'étiquettes, mon internet est pas au top. J'ai relu et fait une poignée de modifs, notamment quelques sauts de ligne pour faciliter la lecture. Beau travail @Flupignon !

**Comment by Flupignon** [comment]
Merci ;) Manque plus que la validation de @Ricyeam !

**Comment by Flupignon** [comment]
Je réouvre en attendant une dernière validation.

**Comment by obilya** [comment]
Je suis en train de relire, c'est top :) J'ai juste un doute sur "So just look for answers in the book when you need to... We have to prepare this, don't we ?" à 0.34.0, je crois que ce qu'il dit ce n'est pas que les gens doivent chercher les réponses dedans mais que lui et l'équipe ont cherché, non ?

**Comment by Flupignon** [comment]
Oui tu as tout à fait raison. Je te laisse faire la modification, comme ça je pourrai peut-être valider.

**Comment by obilya** [comment]
Ca marche !

**Comment by obilya** [comment]
C'est en ligne :D
