### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : « POURQUOI AUTANT DE MISÈRE DANS UN PAYS SI RICHE ? »

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#283]
## MÉLENCHON : « POURQUOI AUTANT DE MISÈRE DANS UN PAYS SI RICHE ? »

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mardi 28 mars 2017
**Durée**       | 0:17:28 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=P9RRsNgCxF4)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=P9RRsNgCxF4&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by SarahBu** [comment]
Process: [1] Writing in progress

**Comment by MadeINF** [comment]
j'ai fais la 2ème relecture c'est ok

**Comment by SarahBu** [comment]
Super !

Cordialement,

Sarah Bultez 
(Envoyé de mon IPhone )

**Comment by SarahBu** [comment]
Et du coup ce sera en ligne quand ?

**Comment by Goutte** [comment]
J'ai fait une relecture aussi, YouTube m'indique que c'est publié !

Je n'ai relu que le début, je vous fais confiance pour le reste ;)

**Comment by Salem2612** [comment]
Pour info, j'ai fais la première relecture. Le début (les 8 premières minutes) étaient complètement en vrac : chaque sous titre était présent 2 fois et les synchros étaient n'importe comment. Je ne blame pas du tout @SarahBu qui a du faire le sous titrage, je voulais juste savoir s'il n'y avait pas eu un bug ou un sabotage ? La fin était nickel.

Les sous titres ont été publiés sur Youtube. Tout est impeccable.

**Comment by Goutte** [comment]
@Salem2612 J'ai constaté le même genre de défaut.

**Comment by SarahBu** [comment]
Bonjour,
je regarde les sous-titres, c'est n'importe quoi et quand je l'édite, c'est nickel.Je pige pas là.....Y'a un bug apparemment.....
De plus, c'est écrit "en ligne" mais ce n'est pas en ligne.... du coup, que se passe-t-il ? Cordialement,
Sarah Bultez
 

    Le Lundi 3 avril 2017 13h46, Antoine Goutenoir <notifications@github.com> a écrit :
 

 @Salem2612 J'ai constaté le même genre de défaut.—

**Comment by SarahBu** [comment]
Bon bah là c'est bien. N'y aurait-il pas un soucis avec l'historique de navigation ?
Bon toujours est-il que ce n'est pas en ligne :) Cordialement,
Sarah Bultez
 

    Le Lundi 3 avril 2017 18h25, Sarah Bultez <sj.delaban@yahoo.fr> a écrit :
 

 Bonjour,
je regarde les sous-titres, c'est n'importe quoi et quand je l'édite, c'est nickel.Je pige pas là.....Y'a un bug apparemment.....
De plus, c'est écrit "en ligne" mais ce n'est pas en ligne.... du coup, que se passe-t-il ? Cordialement,
Sarah Bultez
 

    Le Lundi 3 avril 2017 13h46, Antoine Goutenoir <notifications@github.com> a écrit :
 

 @Salem2612 J'ai constaté le même genre de défaut.—

**Comment by SarahBu** [comment]
Il semble que c'est bon maintenant. En tout cas de mon côté les sous-titres apparaissent comme je les ai fait.... @MadeINF @Salem2612 @Goutte

**Comment by sentinelle2017** [comment]
y'avait un bug sur le premier sous-titre qui disparaissait trop vite car chevauché par le second. c'est débugué et tout apparait comme il faut en ligne @SarahBu
