### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : Une géopolitique et une défense au service de la paix - #JLMDéfense

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#286]
## MÉLENCHON : Une géopolitique et une défense au service de la paix - #JLMDéfense

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 31 mars 2017
**Durée**       | 1:06:08 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=vQ6VRi0smIo)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=vQ6VRi0smIo&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Bentham** [comment]
Corrigé jusqu'à 8:50. Je voudrais supprimer tout le reste de la transcription (version "moulinette" chaotique) mais le système d'upload réagit étrangement.

**Comment by DominDamid** [comment]
Je prends la suite.

**Comment by DominDamid** [comment]
Je m'arrête à 16:31.

**Comment by DominDamid** [comment]
Bonjour @SarahBu !
Je me posais la question de savoir si mes sous-titres étaient bien enregistrés pour les autres, car au moment où je les ai validés, YouTube m'a indiqué que mes sous-titres ne s'afficheraient pas tout de suite, car ils devaient être d'abord "validés par la communauté". Et ils n'apparaissent pas sur la version en ligne.
Est-ce que tu peux me dire si, sur ta version, les sous-titres entre 8:50 et 16:31 sont encore fantaisistes ou corrects ?

**Comment by SarahBu** [comment]
Bah c'est franchement un vrai bazard, il ne faut pas le mettre en relecture quand c'est comme ça, je m'attendais à un petit boulot de relecture et en réalité je dois tout refaire ><. Là je m'arrête à 16:00 et je reprends plus tard.

**Comment by SarahBu** [comment]
Je le repasse dans work in progress

**Comment by DominDamid** [comment]
Je reprends à 16:00.

**Comment by DominDamid** [comment]
Sous-titres complétés jusqu'à 28:16.

**Comment by DominDamid** [comment]
Je m'y remets.

**Comment by DominDamid** [comment]
Je m'arrête à à 33:38.

**Comment by SarahBu** [comment]
Arrêté à 37:17:2

**Comment by SarahBu** [comment]
Pfffff si quelqu'un peut m'aider à le finir celui-là, il me sort par les yeux....
JPP
