### ISSUE TITLE
[subtitles] [fr] DÉFILÉ POUR LA 6E RÉPUBLIQUE LE 18 MARS 2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#287]
## DÉFILÉ POUR LA 6E RÉPUBLIQUE LE 18 MARS 2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Samedi 01 avril 2017
**Durée**       | 0:03:41 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=JeXZwEIxMus)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=JeXZwEIxMus&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Bentham** [comment]
Je fais une relecture

**Comment by Bentham** [comment]
Correction faite. Attention en français on met une espace avant les points d'interrogation, exclamation, double point.

**Comment by Bentham** [comment]
Il faudrait que quelqu'un valide derrière d'ailleurs, parce que pour l'instant la version publiée commence avec une belle faute à "MélAnchon" :)

**Comment by Albapringe** [comment]
Allez, je m'y attelle. Puisque les sources de nos désagréments ne semblent plus devoir nous poser de problèmes, je suis prêt à reprendre du service plus activement :)

**Comment by Bentham** [comment]
Des coeurs dans ta face.

**Comment by Albapringe** [comment]
Terminé. Une simple validation est nécessaire, j'ai juste re-condensé en des containers moins éclatés.

**Comment by Bentham** [comment]
J'approuve ce contenu. Next !
