### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «LE SPORT EST MALADE DE L'ARGENT»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#289]
## MÉLENCHON : «LE SPORT EST MALADE DE L'ARGENT»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 03 avril 2017
**Durée**       | 0:28:49 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=UH_bcFxI8xk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=UH_bcFxI8xk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Albapringe** [comment]
Je prends cette vidéo.

**Comment by maximerinna** [comment]
Bonjour, 

j'ai réussi a corriger ma moulinette chaotique ;-)  et maintenant elle fonctionne correctement. 

La synchronisation est pile au bon endroit, et j'arrive a récupérer 80 % des mots juste ( j'ai comparé avec une video ok ) . 

Si quelqu’un souhaite vérifier svp, je ne peu pas le faire par moi même, je travail en aveugle. 

J'ai généré le fichier CC de la vidéo :   https://youtu.be/UH_bcFxI8xk
Sur un pad public  suivant   :   https://bimestriel.framapad.org/p/t5n98HpZVy

Copier/coller en format txt a plat et intégration sous youtube. 

Vous pouvez couper le fichier en morceau pour en intégré qu une petite partie . 

Pouvez vous me dire si la synchronisation est juste maintenant ? 

Maxime

**Comment by Albapringe** [comment]
Terminé pour le sous-titrage. Contrairement à mon habitude, je n'ai pas fait de relecture finale, des erreurs ont pu se glisser.

**Comment by Goutte** [comment]
@maximerinna Merci d'avoir essayé. Tu peux comparer toi-même avec les sous-titres créés par @Albapringe ; à première vue, la synchro n'est pas encore parfaite. La fin de la vidéo n'est même pas identique, c'est étrange.

@Albapringe Merci pour ces sous-titres ! J'ai validé, normalement c'est en ligne !

**Comment by Bentham** [comment]
Je fais une relecture après le débat :)

**Comment by Bentham** [comment]
Bon ça s'est fini trop tard, je vais dodo et j'essaie d'y penser demain !

**Comment by DominDamid** [comment]
L'issue s'est close sans qu'il y ait eu de 2ème relecture ?

**Comment by maximerinna** [comment]
Bonsoir, 

J'ai enfin compris le pourquoi du comment pour ma moulinette chaotique, par contre , je ne trouve pas de solution, si quelqu’un a une idées, 

Explications : 
Les décalages sont du au applaudissement ou autre bruits, dans le sens ou pour la reconnaissance vocale le temps fille , qu il y est ou pas de parole . 

Si dans une trame de 6 secondes, il a 3 secondes de parole et  3 secondes de bruit et bien décalage assurée. 

Etant donner que la rupture est déclencher sur un petit moment de silence (si, si il y en a ) 
La respiration de JLM fait 400 millis secondes , j'en profite pour y glisser un retour chariot ;-) 

Bref, je doit trouver une solution pour identifier la différence entre la parole et le bruit. 

Bon , j'ai don encore du pain sur la planche, mais rien est impossible, c'est juste que personne ne l'as fait avant. 

A très bientôt, si vous avec une idées d’algorithme ou de principe, je suis preneur. 

La seul solution qui resterais serais de couper net sans chercher a caler au silence ( respiration ) , du coût on perte les séquences inéligibles, bref la notion de phrase, ou proposition. 

C'est donc plus un problème linguistique que technique.

Du coût , cela limite ce type d'outils au vidéo très propre type revue de semaine qui passe bien mieux. puisque sans parasitage ( ou alors on interdit les applaudissements  ;-) 

Amicalement Maxime

**Comment by Bentham** [comment]
Allez je m'y mets

**Comment by Bentham** [comment]
Corrigé ! Pas beaucoup de modifications apportées.

Vraiment chouette cette interview d'ailleurs.
