### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - FAQ 30/11/16

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#29]
# Video title
MÉLENCHON - FAQ - 6E RÉPUBLIQUE, CANNABIS, BIO, YOUTUBE, SNOWDEN, ASSANGE…

# URL
https://www.youtube.com/watch?v=GkPZ3sIhMPg

# Youtube subtitles language
Français

# Duration
48:34

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&tab=captions&ui=hd&v=GkPZ3sIhMPg&lang=fr&ref=player

**Comment by Ricyeam** [comment]
Je n'ai pas commencé, juste rédigé l'intitulé de l'issue.

**Comment by Flupignon** [comment]
Quelqu'un a commencé (je ne sais pas qui) donc je change le label.

**Comment by Flupignon** [comment]
Je vais transcrire à partir de la 30e minute pour être sûr de ne pas chevaucher le travail de qq'un d'autre.

**Comment by Flupignon** [comment]
En fait non, ça peut perturber...

**Comment by Flupignon** [comment]
En pause, j'en suis à 9:00.

**Comment by Flupignon** [comment]
Je m'y remets. J'en suis à 13 min (une autre personne est dessus aussi).

**Comment by LucileDT** [comment]
Peut-être que tu pourrais laisser dans un sous-titre un lien vers le github :P

**Comment by Flupignon** [comment]
Ouais c'est vrai, mais juste un lien, les gens vont pas comprendre ce que c'est...
Enfin petite pause nocturne, j'en suis à 22:05. J'aurai pas beaucoup de temps demain (ou aujourd'hui plutôt).

**Comment by dalipokim** [comment]
Il y a du monde là ?

**Comment by LucileDT** [comment]
Je fais de la doc sur le Github, donc je suis là :)

**Comment by dalipokim** [comment]
sur la  FAQ ! Donc je bosse un peu dessus !

**Comment by dalipokim** [comment]
Est ce que tu pourrais écouter a 22:36 il a le nez bouché et je n'arrive pas à capter ce qu'il dit stp ?

**Comment by LucileDT** [comment]
J'ai écouté, pas moyen de comprendre.

On pense à une de ces options :
> Puis un battant

> Puis bon, maintenant

> Puis un matin

**Comment by dalipokim** [comment]
Merci, je met " Puis bon maintenant un peu dans le sérieux" avec réserves !

**Comment by dalipokim** [comment]
Donc 22:36 à voir si ça convient et fin a 28:18.

**Comment by dalipokim** [comment]
Salut j'ai fait vite fait une transcription

https://www.youtube.com/watch?v=Jkojd3SskSY
Jean-Luc Mélenchon dénonce l'évasion fiscale au Parlement européen

https://www.youtube.com/timedtext_editor?v=Jkojd3SskSY&tab=captions&bl=vmp&forceedit=timedtext&action_mde_edit_form=1&ref=player&lang=fr

mais comme je n'ai pas trouvé l'explication pour la placer pour validation,
je te le laisse comme ça, c'est cadeau !

2016-12-02 2:53 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by dalipokim** [comment]
Re  il y a un utilisateur youtube qui m'a parlé d'un site de transcription
vidéo qui s’appelle Amara. Est-ce que tu connais, si oui, est-ce que ça
pourrais nous servir, à ton avis ?

2016-12-02 2:53 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by Flupignon** [comment]
Hey ! Je viens de regarder une vidéo qui explique ce que c'est : les fonctionnalités sont les mêmes que sur YT donc je vois pas trop l'intérêt de se rajouter un outil (à moins qu'il y en ait d'autres mais je ne les ai pas vues).

**Comment by Flupignon** [comment]
Pause, j'en suis à 33min04.

**Comment by Bentham** [comment]
Je relis et fais quelques corrections avant de valider

**Comment by dalipokim** [comment]
Salut est-ce que tu as vu pour "Jean-Luc Mélenchon dénonce l'évasion
fiscale au Parlement européen" ?

2016-12-02 18:06 GMT+01:00 Bentham <notifications@github.com>:

**Comment by Bentham** [comment]
Relecture et correction terminées, prêt pour une seconde vérification.

@dalipokim Non, de quoi s'agit-il ? Je n'ai pas vu d'issue sur cette vidéo

**Comment by dalipokim** [comment]
le message est dans Mélénchon FAQ j'y ai posé les liens de la vidéo
(originale et corrigée ) Comme je n'ai pas trouvé l'explication pour créer
une issue...

**Comment by bayasahra** [comment]
je m'y mets à l' instant pour la relecture.

**Comment by dalipokim** [comment]
Salut baya aurais tu 5 mn m'accorder pour m'expliquer comment mettre une
vidéo ? Merci.

2016-12-02 19:48 GMT+01:00 Baya <notifications@github.com>:

**Comment by LucileDT** [comment]
@dalipokim je vais finir de rédiger la documentation pour ça dans la nuit, et si tu es disponible sur Facebook aux alentours de 23h,je peux t'expliquer :)

**Comment by bayasahra** [comment]
@dalipokim  je te laisse aux mains de lucile, elle se propose gentiment ;)

**Comment by dalipokim** [comment]
Désolé je n'ai pas de Facebook ! Ou plus ! J'avais droit à une "cougar" qui
me tombait dessus à la première minute de connexion ! Systématiquement ! Je
m'en tiens à la boîte mail maintenant ! Mais si tu veux envoie moi un
message avec le lien et ça ira. Bon courage.

2016-12-02 20:45 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by dalipokim** [comment]
ok merci.

2016-12-02 20:47 GMT+01:00 Baya <notifications@github.com>:

**Comment by Flupignon** [comment]
@Bentham Je me mets à la correction.

**Comment by bayasahra** [comment]
corrigé et validé...
le nom de l' entreprise j' ai mis KEM ONE ... il a parlé de PVC Ca correspondrait donc ....
Pour mes autres remarques je vais les faire dans la qualité du sous titrage, le texte n' est souvent pas fidèle mot pour mot aux paroles de Jean Luc Mélenchon sans pour autant en changer le sens... à savoir si c' est important.

**Comment by Flupignon** [comment]
@bayasahra  Tu étais dessus ? Moi aussi...

**Comment by bayasahra** [comment]
@Flupignon regarde plus haut je l' avais noté...

**Comment by Flupignon** [comment]
My bad, j'avais pas vu. Bon bah j'ai perdu un temps précieux :(
