### ISSUE TITLE
[subtitles] [pt] MELENCHON: Une géopolitique et une défense au service de la paix - #JLMDéfense

### ISSUE THREAD

**Issue by RomainZinho** [jlm2017/jlm-video-subtitles#291]
https://www.youtube.com/watch?v=vQ6VRi0smIo

**Comment by RomainZinho** [comment]
Ayéé, j'ai terminé de rédiger les ss-titres en portugais!

**Comment by RomainZinho** [comment]
Pour la révision, il faut bien attendre que qqn d'autre la corrige sur youtube, c'est ça? :)

**Comment by Enrok** [comment]
Mais il n'y a pas de sous titre sur YouTube... ?!

**Comment by Bentham** [comment]
C'est juste @Enrok, seule la transcription française est disponible. @RomainZinho tu es sûr d'avoir envoyé ta traduction ? Essaye de rentrer dans l'interface avec un autre compte et tu verras qu'il n'y a pas de sous-titres portugais disponibles.

**Comment by RomainZinho** [comment]
Ah zut, oui j'ai essayé avec un autre compte et les sous-titres n'apparaissent pas, mais à partir de mon compte, il est bien indiqué qu'ils étaient envoyés
[FireShot Screen Capture #047 - 'YouTube' - www_youtube_com_timedtext_cs_panel.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/900659/FireShot.Screen.Capture.047.-.YouTube.-.www_youtube_com_timedtext_cs_panel.pdf)

**Comment by RomainZinho** [comment]
Et les sous-titres sont bien dispos sur mon compte, qqn a une explication? Sinon, si vous voulez, je peux charger le ficher .txt qq part?

![fireshot screen capture 010 - youtube - www_youtube_com_timedtext_editor_ref hub v vq6vri0smio ui sub action_mde_edit_form 1 bl csps lang pt tab ca](https://cloud.githubusercontent.com/assets/26854811/24726164/c0377202-1a27-11e7-9da6-d89d44951462.png)

**Comment by Bentham** [comment]
C'est étrange... Tu as bien appuyé sur le bouton bleu en haut à droite ?

**Comment by Bentham** [comment]
Oh j'y suis. Je peux y accéder quand je vais dans les sous-titres portugais, mais ils n'apparaissent pas dans la liste. Je valide et on va voir.

**Comment by Bentham** [comment]
C'est peut-être parce que tu n'as pas fait de traduction du titre et/ou de la description ? Le menu apparait quand on clique sur le bouton bleu : 

![image](https://cloud.githubusercontent.com/assets/1228430/24727072/f2794a7e-1a54-11e7-9dfe-836f1bc356ab.png)

**Comment by RomainZinho** [comment]
Ok, je viens de traduire la description aussi en portugais! Pas mal de contacts brésiliens engagés veulent déjà voir cette vidéo!

**Comment by RomainZinho** [comment]
Hum, et malgré la traduction du titre et de la description, les sous-titres n'apparaissent toujours pas... :(

**Comment by Goutte** [comment]
Comme dit @Bentham, effectivement le Portugais n'apparait pas dans la liste, mais on peut y accéder directement en modifiant l'URL.

J'ai validé (même si je n'y comprends rien), et YouTube m'indique que ça a été publié !

**Comment by RomainZinho** [comment]
Ah super!

**Comment by Flupignon** [comment]
Bravo les gars !
J'en informe Christian Rodriguez des relations internationales de la FI qui m'a demandé de traduire le discours en anglais, et qui sera je pense très content de cette version en portugais !

**Comment by Flupignon** [comment]
Peut-être que l'un d'entre vous pourrait créer une chaîne JLM en portugais (avec titres et descriptions en portugais) pour augmenter la visibilité de JLM chez les lusophones ?

**Comment by RomainZinho** [comment]
Hehe, moi, je veux bien mais on s'y prendrait comment? Et il y aurait d'autres vidéos à traduire en priorité pour d'autres langues (dont les lusophones)?

**Comment by Goutte** [comment]
@RomainZinho  Si tu te lances dans la traduction en portugais, je peux bosser un peu pour te simplifier la création d'issues sur github, si tu veux.

**Comment by RomainZinho** [comment]
@Goutte ah oui, je veux bien, je vais commencer une autre vidéo en portugais, la dernière RDLS, je pense, je maîtrise pas trop l'outil des issues :D
