### ISSUE TITLE
[subtitles] [fr] JEAN-LUC MÉLENCHON AUX MARDIS DE L'ESSEC

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#292]
## JEAN-LUC MÉLENCHON AUX MARDIS DE L'ESSEC

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mardi 04 avril 2017
**Durée**       | 2:03:34 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=3zu317upAUA)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=3zu317upAUA&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by spi-soustitrage** [comment]
je voudrais collaborer au sous-titrage de cette vidéo. @pascale86
je suis inscrite sur le discord @spi et sur le github @spi-soustitrage

**Comment by Bentham** [comment]
Tu es maintenant inscrit comme contributeur. N'hésite pas à consulter notre Wiki pour comprendre nos processes : https://github.com/jlm2017/jlm-video-subtitles/wiki

**Comment by spi-soustitrage** [comment]
Merci! 
Les 2 premières entrées de 05.FAG (fonctionnement et implication dans github) donnent sur une erreur 404.

**Comment by Bentham** [comment]
C'est corrigé :)

**Comment by spi-soustitrage** [comment]
Ok, merci!
J'ai sous-titré 13 min sur en cliquant "éditer sur youtube".
Autre lien mort: sur la page https://github.com/jlm2017/jlm-video-subtitles/wiki/%5BFR%5D-02.-Comment-participer
sous le titre "comment vous impliquer", le lien "le guide pour bien débuter" est mort.
Je vais chercher des infos dans les conversations.
Amitiés insoumises

**Comment by spi-soustitrage** [comment]
petit pb de sauvegarde aujourd'hui.
Sous-titré jusqu'à 21.16
mais texte saisi jusqu'à 30.02

**Comment by spi-soustitrage** [comment]
sous-titré jusqu'à 1.14
Des consignes pour les termes techniques comme Zollverein ou interland? Rajouter des * ou pas?
