### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «IL EST TEMPS DE RIRE DE NOS MAÎTRES AVANT DE LES RENVERSER»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#293]
## MÉLENCHON : «IL EST TEMPS DE RIRE DE NOS MAÎTRES AVANT DE LES RENVERSER»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mardi 04 avril 2017
**Durée**       | 0:02:01 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=anqwf3Vng4c)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=anqwf3Vng4c&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Bentham** [comment]
Verrouillé.
