### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «COMMENÇONS LES JOURS HEUREUX»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#294]
## MÉLENCHON : «COMMENÇONS LES JOURS HEUREUX»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mercredi 05 avril 2017
**Durée**       | 0:01:45 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=1A6QIMF1Y3s)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=1A6QIMF1Y3s&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by Bentham** [comment]
Je fais ça rapidement, c'est prioritaire.

**Comment by Bentham** [comment]
Ah non, je vois que quelqu'un est en travail dessus... Je repasserai plus tard.

**Comment by Bentham** [comment]
Fais attention @Salem2612, pour l'instant vous êtes deux personnes à travailler sur la vidéo en même temps, ça veut dire que l'un de vous deux travaille pour rien.

**Comment by Salem2612** [comment]
J'ai pas eu le temps de m'y mettre en fait.

**Comment by DominDamid** [comment]
Effectivement, des sous-titres ont été mis. À première vue cela semble correct donc je change de colonne et je m'attelle à la première relecture.

**Comment by DominDamid** [comment]
Et voilà ! Plus qu'une deuxième relecture pour la forme ; normalement ça roule.

**Comment by Bentham** [comment]
Corrigé et validé.
