### ISSUE TITLE
[subtitles] [en] MÉLENCHON : Une géopolitique et une défense au service de la paix - #JLMDéfense

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#295]
# Video title

MÉLENCHON : Une géopolitique et une défense au service de la paix - #JLMDéfense

# URL

https://www.youtube.com/watch?v=vQ6VRi0smIo

# Youtube subtitles language

Anglais

# Duration

1:06:07

# Subtitles URL

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&forceedit=captions&lang=en&tab=captions&v=vQ6VRi0smIo&ref=player&ui=hd&bl=vmp

**Comment by Flupignon** [comment]
Hello! J'ai fait jusqu'à 5:44.

**Comment by Flupignon** [comment]
17:44

**Comment by Flupignon** [comment]
19:44

**Comment by Flupignon** [comment]
20:54

**Comment by Flupignon** [comment]
27:50

**Comment by Flupignon** [comment]
32:15

**Comment by Flupignon** [comment]
Je vais continuer le sous-titrage de cette vidéo sur la chaîne en anglais parce que je suis obligé de me caler sur le découpage de la version française (français automatique !!!), et le découpage des sous-titres est juste horrible.

**Comment by Flupignon** [comment]
Hello. La vidéo est prête pour relecture.

**Comment by RomainZinho** [comment]
Ok, je vais regarder ça!

**Comment by RomainZinho** [comment]
Super! J'ai validé, et j'ai aussi fait une traduction pour la description de la vidéo et son titre, qui doit encore être validée.
