### ISSUE TITLE
[subtitles] [fr] #RDLS24 : SYRIE, STX, SOLIDARITÉ INSOUMISE, CARAVANE, DISCORD, MÉLENPHONE, DÉBAT

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#296]
## #RDLS24 : SYRIE, STX, SOLIDARITÉ INSOUMISE, CARAVANE, DISCORD, MÉLENPHONE, DÉBAT

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 06 avril 2017
**Durée**       | 0:25:50 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=dLxbhHEIlrA)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=dLxbhHEIlrA&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by MathildeG9** [comment]
J'ai commencé, mais comme c'est ma première rédaction je ne suis pas très rapide, quelqu'un peut continuer s'il le souhaite, sinon je reprendrais demain

**Comment by sentinelle2017** [comment]
salut
c'est ma première contrib
je veux bien continuer

**Comment by sentinelle2017** [comment]
j'ai pas compris comme je dois faire pour mettre "writing in progress"... bref, j'ai avancé un peu, je reviens tout à l'heure ;)

**Comment by yopox** [comment]
J'ai corrigé jusqu'à 12 minutes :)

**Comment by sentinelle2017** [comment]
ça allait ?

**Comment by yopox** [comment]
Oui ça va :) il y avait `fusse` -> `fût-ce` mais à part ça c'est vraiment mineur

**Comment by sentinelle2017** [comment]
en fait, tu as du corriger mathilde, moi je suis arrivée après ;) et j'y retourne ;)

**Comment by yopox** [comment]
Ça marche, @ moi si tu souhaites une relecture finale !

**Comment by Bentham** [comment]
@sentinelle2017 Il faut que tu cliques dans la zone "labels" en haut à droite, et tu pourras ajouter ou supprimer les labels. Normalement tu as reçu une notification avec un lien à activer pour que tu sois considéré comme contributeur.

**Comment by sentinelle2017** [comment]
merci @Bentham ! j'ai un peu de mal avec l'interface ;) mais grâce à toi j'ai réussi ! bon allez je continue, je suis ravie de participer :)

**Comment by sentinelle2017** [comment]
@YoPox fini, je te laisse dessus, je vais chercher mon petit à l'école !! lol ! juste juste !

**Comment by DominDamid** [comment]
Salut @sentinelle2017 , précision concernant les labels : "Writing in progress" est utilisé lorsque les sous-titres sont en cours de rédaction, à ne pas confondre avec "someone is working on this issue" qui signifie que quelqu'un est en train d'écrire à ce moment-là. On met "awaiting subtitles" lorsque la rédaction des sous-titres n' pas encore été démarrée.
Je me permets de mettre les labels appropriés et de faire le changement de colonne dans le tableau de projet.

**Comment by yopox** [comment]
J'ai relu les sous-titres. 
@Bentham @DominDamid est-ce que je peux être contributeur ? Merci.

**Comment by Bentham** [comment]
C'est fait :) Il te suffit d'activer le lien reçu en notification

**Comment by sentinelle2017** [comment]
Oui ok. Désolée je suis nouvelle j ai pas encore tout bien saisi
