### ISSUE TITLE
[subtitles] [en] MÉLENCHON : «IL EST TEMPS DE RIRE DE NOS MAÎTRES AVANT DE LES RENVERSER»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#298]
## MÉLENCHON : «IL EST TEMPS DE RIRE DE NOS MAÎTRES AVANT DE LES RENVERSER»

&nbsp;        | Info
------------- | -------------
**Date**      | Tuesday, 04 April 2017
**Duration**  | 0:02:01 :clock7:
**Language**  | English :gb:
**Video**     | [See it on YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=anqwf3Vng4c)
**Subtitles** | [Edit them in YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=anqwf3Vng4c&tab=captions&bl=vmp&action_mde_edit_form=1&lang=en&ui=hd)

**Comment by RomainZinho** [comment]
J'ai validé! :)

**Comment by RomainZinho** [comment]
j'ai aussi traduit la description de la vidéo en anglais, si qqn peut la valider?
