### ISSUE TITLE
[subtitles] [FR] PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#30]

**Comment by Ricyeam** [comment]
?

**Comment by LucileDT** [comment]
Doublon il me semble :)

**Comment by bayasahra** [comment]
pardon ??? c est pas un doublon c'etait une erreur, j' avais mal créé l'issue ...mais je l avais close il me semble ??

**Comment by Ricyeam** [comment]
Elle est tjs close, mais j'avais pas vu le doublon. Sorry ! Merci pour l'explication.
