### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : « LA FRANCE DOIT ÊTRE INDÉPENDANTE »

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#300]
## MÉLENCHON : « LA FRANCE DOIT ÊTRE INDÉPENDANTE »

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 07 avril 2017
**Durée**       | 0:21:27 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=MwvuVvToLdQ)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=MwvuVvToLdQ&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by RomainZinho** [comment]
Je m'y mets! :)

**Comment by RomainZinho** [comment]
arrêt à 2:52, je passe la main et je vais passer prendre une bière.

**Comment by iNespresso** [comment]
Je peux reprendre!

**Comment by iNespresso** [comment]
Je me suis arrêtée à 7min, je laisse la main.

**Comment by houlenn** [comment]
Je sais pas si c'est juste chez moi, mais les blocs de sous-titres ne sont pas bien calés :/ Je corrige ça et j'entame la suite !

**Comment by houlenn** [comment]
Corrigé jusqu'à 3:33 seulement ... :(

**Comment by RomainZinho** [comment]
Je m'y remets!

**Comment by RomainZinho** [comment]
Ouf, j'ai terminé toute la vidéo, j'ai fait plus attention à ce que les sous-titres soient bien là où ils devraient être cette fois. :)

**Comment by DominDamid** [comment]
Je commence la relecture.

**Comment by DominDamid** [comment]
Je m'arrête à 7:11.

**Comment by MenvussaG** [comment]
ok j y suis
