### ISSUE TITLE
[subtitles] [fr] «MÉLENCHON, L'HOMME QUI AVANÇAIT À CONTRE-COURANT» - Documentaire de Gérard Miller

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#304]
## «MÉLENCHON, L'HOMME QUI AVANÇAIT À CONTRE-COURANT» - Documentaire de Gérard Miller

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 10 avril 2017
**Durée**       | 1:22:56 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=3RtMQQ3wdjk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=3RtMQQ3wdjk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by RomainZinho** [comment]
Ok, je me mets un peu dessus!

**Comment by RomainZinho** [comment]
Bon, j'ai pas eu trop le temps ajdh, j'ai arrêté à 3:00 :)

**Comment by RomainZinho** [comment]
Je m'y remets, apparemment qqn a bossé sur les sous-titres de cette vidéo pendant ce temps, c'est qqn de github?

**Comment by FairyDemon** [comment]
Je m'y mets aussi ! Étant donné qu'il dure 1h30 à peu près, je te propose que tu fasse les 40 premières minutes et moi le reste ? :)

**Comment by RomainZinho** [comment]
ça marche! ;)

**Comment by peupac** [comment]
salut romain j'ai commencé les ST y'a 2 jours...je vois que tu es dessus ...
Comment peut-on s'organiser ? On se donne des tranches de video à ST ?

**Comment by peupac** [comment]
Pourquoi sur YT je ne vois pas les ST que vous avez fait? (je débute...)
comme FairyDemon qui a commencé les 40 dernieres min... moi g rien dans YT

**Comment by peupac** [comment]
ok c'est bon j'ai pris la suite de Fairy Demon... demain je ferai à partir de 1h00

**Comment by RomainZinho** [comment]
Salut! Hehe t'inquiète pas, moi aussi j'y comprenais rien il y a une semaine ;) Les sous-titres vont apparaître quand on aura terminé l'integrale de la video et qu'on aura envoyé notre contribution pour validation. J'ai terminé les sous-titres jusqu'à 40mn.
Prévenez-moi dès que vous avez terminé, comme ça je pourrai valider votre contribution (et vous pourrez valider la mienne) et la vidéo pourra apparaître avec les sous-titres!

**Comment by RomainZinho** [comment]
Alors, vous avez pu avancer sur les sous-titres?

**Comment by RomainZinho** [comment]
Bon, et bah je vais m'y mettre

**Comment by maximerinna** [comment]
moulinette en cours

**Comment by RomainZinho** [comment]
Donc j'arrête de bosser sur la video?

**Comment by Bentham** [comment]
Non non, libre à toi !

**Comment by RomainZinho** [comment]
Ok, j'aurais terminé à la fin de la journée, heure brésilienne!

**Comment by maximerinna** [comment]
Bonjour, voila ma contribution en espérant que ce soit utile.

Livraison du flux 304  3RtMQQ3wdjk

Mode op , CTRL C CTRL V dans un éditeur, puis intégration direct dans Youtube ou bien dans le logiciel de gestion spécifique. 

format srt charset "utf-8"  en PJ le PDF 

Si vous avez besoin d'un format specifique, faite moi le savoir :

La ligne 1 est a supprimer SVP la synchro est plus juste, alec un glissement sur la fin des cases pour alonger le temps de lecture.

Etherpad Public :  https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/304-3rtmqq3wdjk-q9dv87k2
Format   PDF    :    
[JLM_304_PDF.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/926530/JLM_304_PDF.pdf)




Amicalement Maxime

Il y a trois façons d'utiliser ce fichier srt :

En mode assistance partielle : 
Le correcteur souhaite faire 10 minutes de correction de 0H12M00 a 0H22M00 .
dans le fichier srt copier coller des 10 minutes dans un fichier plat , puis dans youtube intégration de ce fichier partiel, la synchronisation étant ok la correction porte surtout sur le début et fin de ligne (j'ai encore des perte de mots )

En mode total : La vidéo est vierge de toutes correction .
Injection total du fichier et correction classique sur la période choisi

Le correcteur ne souhaite pas utiliser le fichier : et bien rien est changer sur le mode opératoire actuel.
il n'y a pas d'assistance.

Note : j'ai aussi la possibilité de diffuser en temps réel le sous-titrage pour correction en live.
C'est a dire que si plusieurs correcteurs écoute la vidéo, a la fin de la diffusion le sous-titrage est presque finalisé.

**Comment by RomainZinho** [comment]
Ok, c'est terminé, prêt pour validation!

**Comment by sentinelle2017** [comment]
@RomainZinho j'ai déplacé ton doc dans le tableau des issues pour qu'il trouve un relecteur

tu n'avais pas oté le label "someone is working" du coup je pense, que personne n'aura osé y toucher ;)

**Comment by SarahBu** [comment]
Il y a beaucoup de retouches à faire, je me suis arrêtée à 16:52:08

**Comment by sentinelle2017** [comment]
ok je m'assigne avec toi sur ce doc, je te propose de prendre la suite quand j'aurais un peu de temps @SarahBu et on communique par les messages pour dire chacune où on en est. quand l'une de nous bosse, elle met le label "someone is working" ;) ça te va

**Comment by SarahBu** [comment]
C'est parfait 👍🏼 

Cordialement,

Sarah Bultez 
(Envoyé de mon IPhone )

**Comment by sentinelle2017** [comment]
@SarahBu je prends à 16'52'08

**Comment by sentinelle2017** [comment]
@SarahBu : bilan : 
2eme relecture faite du début à 16'52 : pensez à mettre les initiales en début de changement de parole (JLM, GM) et les composantes sonores *applaudissements* *ovations de la foule*, car les sous titres sont faits pour les malentendants donc il faut qu'ils aient le contexte sonore ;)
1ère relecture faite de 16'52 à 42'49

donc au choix : tu peux faire la 2eme relecture de ce que je viens de faire de 16'52 à 42'49, comme ça tu devrais moins galérer et surtout on avance en même temps et le doc pourra passer directement "approved " après ; soit tu préfères avancer et tu peux prendre à 42'49.
comme tu veux :)

j'espère que ça te convient comme façon de travailler à deux, sinon, tu me dis :)
moi je fais une pause j'en peux plus...

**Comment by sentinelle2017** [comment]
ps autres contributeurs : on s'est organisé à deux sur ce doc, donc si ça vous va, je vous propose de nous le laisser finir, et de relire un autre doc ;) merci :)

**Comment by sentinelle2017** [comment]
je continue un peu, @SarahBu si tu arrives, fais moi signe je te laisserai la place ;)

**Comment by SarahBu** [comment]
Coucou,
je suis là ^^ Cordialement,
Sarah Bultez
 

    Le Mercredi 19 avril 2017 19h29, Sentinelle2017 <notifications@github.com> a écrit :
 

 je continue un peu, @SarahBu si tu arrives, fais moi signe je te laisserai la place ;)—

**Comment by sentinelle2017** [comment]
ah super, j'enregistre et je te passe :)

**Comment by sentinelle2017** [comment]
donc tout pareil que ce que je t'ai dis en com plus haut, mais jusqu'à 1''02'30
c'est bon j'ai libéré le doc :) bon courage

**Comment by sentinelle2017** [comment]
@SarahBu c'est bon, t'as pris ?

**Comment by sentinelle2017** [comment]
ben alors le @RobotInsoumis nous ferme les issues qu'on a pas fini ? il est crevé ;)

**Comment by sentinelle2017** [comment]
et il le passe en approved alors qu'on a pas fini... je comprends plus rien...
@SarahBu t'en es où du coup, t'as bossé dessus ou pas hier ?

**Comment by sentinelle2017** [comment]
@SarahBu , je sais pas si tu as avancé, je reprends à 1'02'30

**Comment by sentinelle2017** [comment]
PREMIERE relecture finie, il faut une deuxième relecture de 16'52 à la fin ! merci :) afin que ce magnifique document soit accessible à tous !

**Comment by SarahBu** [comment]
Deuxième relecture OK, vidéo publiée

**Comment by sentinelle2017** [comment]
super @SarahBu ! ravie d'avoir travailler en binôme !
