### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : « POUR LA SÉPARTION DE L'ÉTAT ET DE L'ARGENT» - #DemainPresident

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#307]
## MÉLENCHON : « POUR LA SÉPARTION DE L'ÉTAT ET DE L'ARGENT» - #DemainPresident

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 14 avril 2017
**Durée**       | 0:20:33 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=O6aRT3Z6hIM)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=O6aRT3Z6hIM&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by maximerinna** [comment]
`<iframe name="embed_readwrite" src="https://mypads.framapad.org/p/307-o6art3z6him-xi39eq7qi?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false" width=600 height=400></iframe>`

**Comment by maximerinna** [comment]
Bonjour, 307  https://youtu.be/O6aRT3Z6hIM 

Voila ma contrubution en espérant que ce soit utile . 

Mode op , CTRL C  CTRL V  dans un editeur puis intégration ditrect dans Youtube ou bien dans le logiciel de retouche spécifique.  format  srt   charset "utf-8"
Si vous avez besoin d'un format spécifique faite moi le savoir : 
 
La ligne  1 est a supprimer  SVP  malentendantes.  la synchro est plus juste car pas de bruit de fond 

https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/307-o6art3z6him-xi39eq7qi

Etherpad Public en lecture seul

**Comment by spi-soustitrage** [comment]
Relu jusqu'à 6'49

**Comment by spi-soustitrage** [comment]
Désolée, je me suis emmêlée dans les labels:
le sous-titrage est fait et relu jusqu'à 8'15.
Le sous-titrage reste à faire à partir de là.
