### ISSUE TITLE
Rage

### ISSUE THREAD

**Issue by Goutte** [jlm2017/jlm-video-subtitles#308]
Quelqu'un a supprimé une colonne entière dans le projet de sous-titrage français.

@RobotInsoumis n'a donc pas pu créer de nouvelles cartes pour les nouvelles issues, et nous avons perdu toutes les cartes qui étaient dans cette colonne.

Je vais appliquer [le rasoir d'Hanlon](https://fr.wikipedia.org/wiki/Rasoir_d%27Hanlon), et ne pas crier au sabotage. Cependant, si la personne incriminée lit ces lignes, je la supplie de faire preuve d'un peu plus de circonspection à l'avenir.

**Comment by sentinelle2017** [comment]
salut, du coup c'est normal qu'il n'y ait rien dans la première colonne du tableau @Goutte ? j'ai des issues dans l'onglet "issues " mais aps dans le tableau. je les aurais bien ajouter mais il faut me dire comment il faut faire si jamais ça peut aider

**Comment by sentinelle2017** [comment]
bon , j'ai remis des issues dans la colonne 1
