### ISSUE TITLE
[subtitles] [fr] #RDLS25 : MÉDIAS, ALLIANCE BOLIVARIENNE (ALBA), EAU MORTELLE, LILLE, HOLOGRAMMES

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#309]
## #RDLS25 : MÉDIAS, ALLIANCE BOLIVARIENNE (ALBA), EAU MORTELLE, LILLE, HOLOGRAMMES

&nbsp;          | Info
--------------- | ---------------
**Date**        | Samedi 15 avril 2017
**Durée**       | 0:28:09 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=hGQtZo2bqUM)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=hGQtZo2bqUM&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by desintoxiquezvous** [comment]
bonjour, je commence la reconnaissance vocale

**Comment by maximerinna** [comment]
Bonjour, voila ma contribution en espérant que ce soit utile.

Livraison du flux 309  https://youtu.be/13DUm8Y6n5o 

Mode op , CTRL C    CTRL V dans un éditeur,  puis intégration direct dans Youtube ou bien dans le logiciel de retouche spécifique. format srt charset "utf-8"

Si vous avez besoin d'un format spécifique faite moi le savoir :

La ligne 1 est a supprimer SVP  la synchro est plus juste car pas de bruit de fond
 

Etherpad Public en lecture seul

https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/309-13dum8y6n5o-vv3c0q7t1


Amicalement Maxime

Note : j'ai aussi la possibilité de diffuser en temps réel le sous-titrage pour correction en live.

C'est a dire que si plusieurs correcteurs écoute la vidéo , a la fin de la diffusion le sous-titrage est presque finalisé.

A+

**Comment by desintoxiquezvous** [comment]
@RoboInsoumis #RDLS25 la vidéo vient de passer en privée c'est normal ou pas ? 
je continue à la voir sur mon mac ou je travaille dessus mais plus sur ma tablette .... c'est pour éviter les doublons en sous titrage ou bien est elle en train d'être modifiée ?? j'aimerais bien savoir si je dois continuer (la reconnaissance vocale est presque terminée )

**Comment by desintoxiquezvous** [comment]
Je pose là le texte complet corrigé pour insertion quand les sous titres seront accessibles à l'insertion.
Remarqué une erreur : la Dominique n'est pas la République Dominicaine. C'est petite une île située entre la Martinique et la Guadeloupe.
[RDLS25.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/923551/RDLS25.pdf)

**Comment by desintoxiquezvous** [comment]
Toujours pas d'accès

**Comment by Goutte** [comment]
@desintoxiquezvous  Il semblerait que la vidéo d'origine ait eu un problème, et qu'ils l'aient téléversée à nouveau.

J'ai mis à jour les liens dans l'issue ci-dessus.

**Comment by desintoxiquezvous** [comment]
@Goutte  l'ensemble du texte (a jour) est saisi et je commence la mise en containers , je te tiens au courant , ça devrait être fini dans 1 ou 2 heures

**Comment by desintoxiquezvous** [comment]
bientot fini

**Comment by desintoxiquezvous** [comment]
@Goutte sous titres finis a l'instant, prêt pour premiere relecture

**Comment by desintoxiquezvous** [comment]
pou info ci joint le fichier caption crée (en pdf)
[RDLS25 caption.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/923761/RDLS25.caption.pdf)

**Comment by sentinelle2017** [comment]
Relecture faite, quasiment tout au top ! bravo à tous :)

**Comment by sentinelle2017** [comment]
du coup j'ai mis le label second review, mais si j'avais osé j'aurais mis "approved"
