### ISSUE TITLE
[subtitles] [FR] PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#31]
# Video title

PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE

# URL

https://www.youtube.com/watch?v=Uu-PtBsmSUc

# Youtube subtitles language

Français

# Duration

1:04:57

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=watch&lang=fr&action_mde_edit_form=1&ui=hd&v=Uu-PtBsmSUc&tab=captions&bl=vmp

**Comment by bayasahra** [comment]
je m'y mets !!!!!

**Comment by bayasahra** [comment]
arrêt à 7:20:5

**Comment by bayasahra** [comment]
je m'y remets !!!

**Comment by bayasahra** [comment]
en pause 12:16:5 ... m' y remets dans pas longtemps.

**Comment by bayasahra** [comment]
je suis dessus !!

**Comment by bayasahra** [comment]
15:33:0

**Comment by bayasahra** [comment]
je suis dessus !!

**Comment by bayasahra** [comment]
21:27:8

**Comment by bayasahra** [comment]
je suis sur l' affaire !!!

**Comment by bayasahra** [comment]
29:24:2

**Comment by LucileDT** [comment]
@bayasahra Est-ce que tu pourras mettre le label ```Process: Paused``` quand tu arrêteras la rédaction des sous-titres la prochaine fois ? (c'est un nouveau label, sinon @Flupignon et @Bentham se perdent et travaillent sur le même truc en même temps :P)

Il faut le mettre quand on arrête, et l'enlever quand on reprend la rédaction :)

Merci d'avance !

**Comment by bayasahra** [comment]
je suis dessus !

**Comment by bayasahra** [comment]
40:15.5

**Comment by bayasahra** [comment]
je suis dessus

**Comment by bayasahra** [comment]
Apparemment quelqu' un a fait de 40:15.5 jusqu' à 43:11.7 j' ai visionné et corrigé.

**Comment by bayasahra** [comment]
51:08.1

**Comment by bayasahra** [comment]
je suis dessus
il y a quelqu' un dessus !!!! c' est quelqu ' un de l' équipe ou quoi ???
Oué il y a quelqu ' un dessus !!! j' espère qu' il va pas revalider sur mon travail ....

**Comment by LucileDT** [comment]
Je pense pas que ce soit quelqu'un de l'équipe.

**Comment by LucileDT** [comment]
Je suis dessus !

**Comment by LucileDT** [comment]
J'aurai besoin d'aide pour 51:57, je n'arrive pas à comprendre ce qu'il dit.
J'ai mis : 
> Parce qu'on dirait que les dangers qui viennent de la mer unifient tous ceux qui ont à en connaître.

Mais possible que je me goure.

**Comment by LucileDT** [comment]
Fini !

**Comment by bayasahra** [comment]
ah ^^ j' aurais bien aimé le finir ... mais bon ... je suppose que c' est le travail d' équipe ^^

**Comment by Bentham** [comment]
Baya si tu veux je rajoute des fautes dans les 30 dernières secondes et tu corriges tout avec ton clavier magique !

Quand on peut aider...

**Comment by LucileDT** [comment]
Ah, désolée Baya :( je pensais que comme la vidéo était longue, tu pourrais en avoir assez :/

**Comment by bayasahra** [comment]
pas de soucis Lucile ^^.... simplement,  il restait que 13 minutes à faire, ça m' aurait pas tué :) c' est mon perfectionnisme qui parle j' aime bien terminer ce que je commence.

**Comment by bayasahra** [comment]
Lucile .... je voulais relire pour faire une première correction, mais comme la dernière fois,  tu n' as pas validé ton travail.... là les sous titrages sont fait jusqu'à 51.08 , où je les ai arrêté ..... peux-tu valider ton travail ?
merci

**Comment by LucileDT** [comment]
Ah, étrange, les miens sont validés :/

**Comment by LucileDT** [comment]
Youtube me les marque "Envoyé"

**Comment by bayasahra** [comment]
Non, moi perso je l' ai pas ....; je demanderai à Ben quand il sera dispo si il voit les sous titrages au-delà de 51 minutes.

**Comment by Bentham** [comment]
Oui je vois les sous-titres jusqu'à la fin !

**Comment by LucileDT** [comment]
Est-ce que tu peux les relire ?

**Comment by bayasahra** [comment]
Impressionnant ! 'tain ! je les vois pas ..... c' est la deuxième fois avec ce que valide lucile LOL .....

**Comment by LucileDT** [comment]
Il faut nous y faire : nous sommes incompatibles T_T

**Comment by Bentham** [comment]
Allez go !

**Comment by Bentham** [comment]
Fait ! A valider de votre côté !
