### ISSUE TITLE
[subtitles] [fr] EN DIRECT - MÉLENCHON : Meeting à Toulouse - #JLMToulouse

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#310]
## EN DIRECT - MÉLENCHON : Meeting à Toulouse - #JLMToulouse

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 16 avril 2017
**Durée**       | 1:42:21 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=TBgNycaFV1c)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=TBgNycaFV1c&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
Vélotypie à partir de 9'30
je sous-titre ce qui est avant

**Comment by sentinelle2017** [comment]
Sous-titres à relire de 1'56 à 9'04
Avant et après : vélotypie

Merci

**Comment by maximerinna** [comment]
Bonjour, voilà ma contribution en espérant que ce soit utile.

Flux 310 https://youtu.be/TBgNycaFV1c

Mode op , CTRL C CTRL V dans un éditeur, puis intégration direct dans Youtube ou bien dans le logiciel de gestion spécifique.  Le format charset "utf-8"   : Si vous avez besoin d'un format spécifique, faite moi le savoir :

Etherpad Public : https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/310-tbgnycafv1c-2b3xzq7wo

Format   PDF    : [JLM_310_PDF.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/924903/JLM_310_PDF.pdf)

Amicalement Maxime

Note : j'ai aussi la possibilité de diffuser en temps réel le sous-titrage pour correction en live.
C'est à dire que si plusieurs correcteurs écoutent et corrige la vidéo en temps réel, à la fin de la diffusion le sous-titrage avant vérification est finalisé. 
Exemple : le direct ce termine a 16H12 et bien a **16H13** le sous-titrage brut synchronisé est dispo.

**Comment by sentinelle2017** [comment]
Salut ! Merci beaucoup !
En fait il n y avait que quelques minutes à sous titres le reste était fait pendant le meeting.
J'ai vu tes messages sur d autres vidéos. J arrive pas trop à me servir de ces fichiers, suis pas au point ;)
Par contre si tu as du temps, est ce que ça t embêterait de relire mes sous titres de esprit de campagne sur la marche du 18mars ? Ils sont en first review ?

Merci à toi

Vic

Le 17 avr. 2017 à 05:50, RINNA <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour, voila ma contribution automatique si cela peu servir..

https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/310-tbgnycafv1c-2b3xzq7wo

JLM_310_PDF.pdf<https://github.com/jlm2017/jlm-video-subtitles/files/924903/JLM_310_PDF.pdf>

Amicalement Maxime

**Comment by maximerinna** [comment]
Bonjour, Sentinelle 2017 

Je suis malentendant, donc incapable de corriger par l'audio, la seul contribution que je peu faire, c'est le fichier srt brut pdf et etherpad avec synchronisation. 

Il y a trois façons d'utiliser ce fichier srt : 
1) En mode assistance  partiel: 

Le correcteur ( toi ) souhaite faire 10 minutes de correction de 0H12M00 a 0H22M00  .
dans le fichier srt copier coller des 10 minutes dans un fichier plat , puis dans youtube intégration de ce fichier partiel, la synchronisation étant ok la correction porte surtout sur le début et fin de ligne (j'ai encore des perte de mots ) 

2) En mode total : La vidéo est vierge de toutes correction . 
Injection total du fichier et correction classique sur la période choisi

3) Le correcteur ne souhaite pas utiliser le fichier : et bien rien est changer sur le mode opératoire actuel.
il n'y a pas d'assistance. 

Amicalement Maxime

**Comment by sentinelle2017** [comment]
@SarahBu : coucou Sarah ;) il n'y a que 8mn a relire ici, du coup je me permets de te solliciter à nouveau si tu peux ;) (je sais pas ce qui se passe, y'a personne en ce moment...)

**Comment by SarahBu** [comment]
Ok, je m'en occupe ce soir

Cordialement,

Sarah Bultez 
(Envoyé de mon IPhone )

**Comment by sentinelle2017** [comment]
@spi-soustitrage : comme tu as relu, faut que tu passes le doc en second review normalement, je l'ai fait du coup

**Comment by SarahBu** [comment]
J'ai fait des modifications, donc à relire et valider.
