### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «LIBERTÉ, ÉGALITÉ, FRATERNITÉ» - DISCOURS SUR LA PÉNICHE INSOUMISE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#311]
## MÉLENCHON : «LIBERTÉ, ÉGALITÉ, FRATERNITÉ» - DISCOURS SUR LA PÉNICHE INSOUMISE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Lundi 17 avril 2017
**Durée**       | 0:32:47 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=2mF62BsfIpA)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=2mF62BsfIpA&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
ST fait jusqu'à 13'47

**Comment by sentinelle2017** [comment]
ST fait jusqu'à 17'24

**Comment by sentinelle2017** [comment]
ST fait jusqu'à 22'04

**Comment by sentinelle2017** [comment]
je reprends

**Comment by sentinelle2017** [comment]
prêts pour relcture @SarahBu @spi-soustitrage

**Comment by EgnaroRueluoc** [comment]
Je relis

**Comment by EgnaroRueluoc** [comment]
Petite question, si on fait une petite modification, est ce que le processus de validation est à refaire intégralement ? Parce que je n'ai pas envie de chipoter pour une lettre si ça reste compréhensible

**Comment by EgnaroRueluoc** [comment]
C'est bon, j'ai relu. Les ST ont été validés.

**Comment by sentinelle2017** [comment]
quand tu relis il faut que tu changes le label de "first review" a second review
non, on recommence pas le processus à chaque petite correction ;)
merci pour la relecture
