### ISSUE TITLE
[subtitles] [fr] JEAN-LUC MÉLENCHON INVITÉ DE BOURDIN DIRECT - #BourdinDirect

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#316]
## JEAN-LUC MÉLENCHON INVITÉ DE BOURDIN DIRECT - #BourdinDirect

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:44:47 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=ZdK2aOnuWbo)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=ZdK2aOnuWbo&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
@spi-soustitrage : c'est relu jusqu'à 3'02'07
pour ton problème de changement de locuteur, je t'ai fait l'exemple du début à 3'02'07 de ce que j'ai pu observer de mieux dans le travail des autres contributeurs : initiales en début de prise de parole / changement
il faut penser que les personnes sourdes n'ont pas le repère de la voix, pour savoir qui parle

j'espère que cela t'aura aider.
je regarderais la suite plus tard

je laisse le com ici pour que tout le monde voit que le boulot est en cours et je te mets le label "someone is working" parce que comme on est déjà deux dessus, ça évitera de compliquer en multipliant les contributeurs je pense

**Comment by spi-soustitrage** [comment]
Merci de l'info, je vais utiliser ça.
Comme JJB et JLM sont, visuellement un peu encombrants, je propose de passer, après quelques minutes pour que les gens s'habituent, à quelque chose de plus court et visuellement différencié: M et B.
J'essaye ça, si ça ne convient pas, je les transformerai après.

**Comment by spi-soustitrage** [comment]
sous-titré jusqu'à 20 mn

**Comment by sentinelle2017** [comment]
ok @spi-soustitrage : reçu toutes infos, pas trop le temps, mais je regarderais un peu plus tard :)

**Comment by sentinelle2017** [comment]
@spi-soustitrage : comme promis je jette un œil

**Comment by sentinelle2017** [comment]
ok , me revoilà, j'ai pas relu du coup, parce que tu as laissé les tirets entre là ou j'ai fait et la minute 10 à peu près... j'ai vu qu'après tu as mis le système dont tu m'as parlé... franchement j'ai un doute, il faudrait demander son avis à qq de plus expérimenté que moi, mais je sais pas si c'est bien clair du coup...
pour ce soir, je ne fais rien de plus, je suis crevée ;)

**Comment by SarahBu** [comment]
Pourriez-vous enlever le "someone is working on this issue" quand vous ne travaillez pas dessus svp ?

**Comment by SarahBu** [comment]
Pas facile de travailler sur le découpage comme vous l'avez fait ⭕️

**Comment by Bentham** [comment]
Rien ne t'empêche de virer tous les découpages, si ça te simplifie la tâche :)

**Comment by SarahBu** [comment]
Là je fais une pause :D Cordialement,
Sarah Bultez
 

    Le Lundi 24 avril 2017 19h33, Bentham <notifications@github.com> a écrit :
 

 Rien ne t'empêche de virer tous les découpages, si ça te simplifie la tâche :)—

**Comment by sentinelle2017** [comment]
On l a laisse exprès sur celle la parce qu'on bosse à deux dessus

Vic

Le 24 avr. 2017 à 19:02, SarahBu <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pourriez-vous enlever le "someone is working on this issue" quand vous ne travaillez pas dessus svp ?

**Comment by spi-soustitrage** [comment]
J'ai sous-titré jusqu'à 32'. Je ne pourrai pas travailler dessus aujourd'hui ni demain. J'enlève le label.

**Comment by sentinelle2017** [comment]
Bien reçu. Beaucoup de boulot en retard moi aussi et besoin de couper un peu quelques jours j avoue

Vic

Le 26 avr. 2017 à 11:16, spi-soustitrage <notifications@github.com<mailto:notifications@github.com>> a écrit :


J'ai sous-titré jusqu'à 32'. Je ne pourrai pas travailler dessus aujourd'hui ni demain. J'enlève le label.

**Comment by sentinelle2017** [comment]
@spi-soustitrage le label "writing in progress" on ne l'enlève plus tant que les ST ne sont pas finis, c'est le label "someone is working" que l'on met et enlève lorsque l'on prend la main sur le document et qu'on la rend :) j'ai remis, c'est bon

**Comment by spi-soustitrage** [comment]
Ok merci de l'avoir remis. Excuse-moi, je l'ai fait en automatique, trop crevée d'écouter 4 fois de suite les voix de Bourdin et JLM qui se chevauchent. Mais je l'aurai. C'est d'ailleurs très intéressant de dépiauter un texte de cette façon, au plus prés du texte oral et de l'argumentation. Et aussi de remarquer les choix de montage image, les regards du journaliste à la caméra...

**Comment by sentinelle2017** [comment]
Oui c est vrai on remarques beaucoup de choses comme ça ! Si tu as besoin que je remise tu me dis

Vic

Le 26 avr. 2017 à 20:50, spi-soustitrage <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok merci de l'avoir remis. Excuse-moi, je l'ai fait en automatique, trop crevée d'écouter 4 fois de suite les voix de Bourdin et JLM qui se chevauchent. Mais je l'aurai. C'est d'ailleurs très intéressant de dépiauter un texte de cette façon, au plus prés du texte oral et de l'argumentation. Et aussi de remarquer les choix de montage image, les regards du journaliste à la caméra...

**Comment by spi-soustitrage** [comment]
@sentinelle2017 @SarahBu 
Si vous avez le temps de relire.

**Comment by SarahBu** [comment]
Là ça va être difficile, les législatives me prennent un temps fou...Je vais tenter mais je ne promets rien :) Cordialement,
Sarah Bultez
 

    Le Lundi 1 mai 2017 16h18, spi-soustitrage <notifications@github.com> a écrit :
 

 @sentinelle2017 @SarahBu
Si vous avez le temps de relire.—

**Comment by sentinelle2017** [comment]
J aurais pas dit mieux 😉 mais je vais tenter aussi 😉

Vic

Le 1 mai 2017 à 17:40, SarahBu <notifications@github.com<mailto:notifications@github.com>> a écrit :

Là ça va être difficile, les législatives me prennent un temps fou...Je vais tenter mais je ne promets rien :) Cordialement,
Sarah Bultez


Le Lundi 1 mai 2017 16h18, spi-soustitrage <notifications@github.com<mailto:notifications@github.com>> a écrit :


@sentinelle2017 @SarahBu
Si vous avez le temps de relire.—

**Comment by youpidou** [comment]
Relu jusqu'à 10:25.

**Comment by youpidou** [comment]
Entièrement relu

**Comment by sentinelle2017** [comment]
@youpidou : normalement si tu es le premier relecteur, tu passe au second, sachant que @spi-soustitrage tu aurais du mettre "first review" allez les copains, vous allez vous y faire ;)

**Comment by sentinelle2017** [comment]
je fais une 2e relecture rapide du coup

**Comment by sentinelle2017** [comment]
2eme relecture ok
