### ISSUE TITLE
[subtitles] [fr] LES SERVICES PUBLICS - UN AN APRÈS | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#318]
## LES SERVICES PUBLICS - UN AN APRÈS | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:01:46 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=dUvzxC6rTcU)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=dUvzxC6rTcU&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by EgnaroRueluoc** [comment]
Fait. Merci de valider les ST (normalement ils sont bons, je les ai repris d'une vidéo du meeting)

**Technique pour gagner du temps sur les vidéos de campagne :**
Je vais sur une vidéo d'un meeting avec les sous-titre (édition) je fais Ctrl + F et je tape un mot clé "Education" pour trouver le passage des ST du clip de campagne.
Je Ctrl + A (tout selectionner) puis Ctrl + C (copier) la première case
Je vais sur la vidéo de campagne (édition) et Ctrl + V (coller) puis Ctrl + Entrée (aller à la ligne)
Je recommence en laissant tout dans la première case.
Puis je lance la vidéo, et à chaque passage à la ligne synchronisée avec la vidéo, j'appuie sur Entrée.

/!\ Penser à "étirer" la grosse case de sous titres afin qu'elle puisse être "découpée" aux bons moments. Je vous conseille de faire une première grosse case, quand vous en avez marre, vous synchronisez.

Cela a pris approximativement 10 minutes, c'est un gain de temps énorme. Merci de valider svp.

**Comment by EgnaroRueluoc** [comment]
Serait-il possible d'avoir des droits pour mettre des labels svp ? Ce sera plus rapide que de mettre des commentaires à chaque fois. Merci.
