### ISSUE TITLE
[subtitles] [fr] LA RÉVOLUTION NUMÉRIQUE - UN AN APRÈS | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#322]
## LA RÉVOLUTION NUMÉRIQUE - UN AN APRÈS | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:01:31 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=PGg07mvYPP4)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=PGg07mvYPP4&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by EgnaroRueluoc** [comment]
Les ST sur cette vidéo sont bien affichés.
