### ISSUE TITLE
[subtitles] [fr] L'EMPLOI POUR TOUS - UN AN APRÈS | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#323]
## L'EMPLOI POUR TOUS - UN AN APRÈS | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:01:32 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=HMNc2gst13c)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=HMNc2gst13c&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
mettez les statuts à jour quand vous bossez !

**Comment by sentinelle2017** [comment]
Quand j'ai ouvert le doc il était déjà ST, donc j'ai fait le première relecture, voilà pourquoi il est passé en second review directement après moi

**Comment by EgnaroRueluoc** [comment]
Les ST sont bien affichés.

**Comment by sentinelle2017** [comment]
t'as relu ? si oui, tu passes en "approved" ;)
