### ISSUE TITLE
[subtitles] [fr] LES NOUVELLES FRONTIERES DE L'HUMANITÉ | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#324]
## LES NOUVELLES FRONTIERES DE L'HUMANITÉ | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:03:30 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=uGiy1WWRRXk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=uGiy1WWRRXk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
Quand j'ai ouvert le doc il était déjà ST, donc j'ai fait le première relecture, voilà pourquoi il est passé en second review directement après moi

**Comment by EgnaroRueluoc** [comment]
Les ST sont bien affichés dans la vidéo
