### ISSUE TITLE
[subtitles] [fr] L'URGENCE DEMOCRATIQUE | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#325]
## L'URGENCE DEMOCRATIQUE | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:03:20 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=qSExgt2W_Tk)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=qSExgt2W_Tk&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by youpidou** [comment]
Sous-titres ajoutés, prêt pour la relecture.

**Comment by sentinelle2017** [comment]
@youpidou : super ;) je vais relire
quand tu sous-titres et que tu as fini, tu dois changer le label "awaiting subtitles" en "first review" ;)
bonne soirée

**Comment by sentinelle2017** [comment]
@youpidou : sous titres parfaits, je passe en relecture 2

**Comment by youpidou** [comment]
@sentinelle2017 J'ai toujours pas trouvé comment on fait pour changer les labels :-(

**Comment by sentinelle2017** [comment]
@youpidou : pas de souci : regarde en haut à droite, tu as une colonne sous "edit / new issue"
dans cette colonne, tu as "assignees" , tu cliques sur la roulette et tu ajoutes ton peudo
en dessous tu as labels, avec la roulette, c'est la que tu changes

tu me dis si c'est bon
