### ISSUE TITLE
[subtitles] [fr] LA PAIX | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#326]
## LA PAIX | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:03:21 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=DLFy28BLWM8)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=DLFy28BLWM8&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by sentinelle2017** [comment]
Quand j'ai ouvert le doc il était déjà ST, donc j'ai fait le première relecture, voilà pourquoi il est passé en second review directement après moi

**Comment by EgnaroRueluoc** [comment]
Les ST sont bien affichés sur la vidéo.

**Comment by sentinelle2017** [comment]
je le sais ;)


il faut les relire une 2eme fois et les passer "approved" pour que le boulot soit bien fini ;)


mais bon maintenant ...

________________________________
De : EgnaroRueluoc <notifications@github.com>
Envoyé : dimanche 23 avril 2017 17:23
À : jlm2017/jlm-video-subtitles
Cc : Sentinelle2017; Assign
Objet : Re: [jlm2017/jlm-video-subtitles] [subtitles] [fr] LA PAIX | CLIP OFFICIEL JLM2017 (#326)


Les ST sont bien affichés sur la vidéo.
