### ISSUE TITLE
[subtitles] [fr] L'EUROPE | CLIP OFFICIEL JLM2017

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#327]
## L'EUROPE | CLIP OFFICIEL JLM2017

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:03:21 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=FI4QiI00Qj4)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=FI4QiI00Qj4&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by EgnaroRueluoc** [comment]
Je commence

**Comment by EgnaroRueluoc** [comment]
Fini. A relire, corriger et valider s'il vous plait. Merci !
