### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - 15 MINUTES POUR CONVAINCRE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#328]
## MÉLENCHON - 15 MINUTES POUR CONVAINCRE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Jeudi 20 avril 2017
**Durée**       | 0:19:20 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=hr_2aZ72oKY)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=hr_2aZ72oKY&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by EgnaroRueluoc** [comment]
J'ai commencé à faire 1/4 de la vidéo. J'espère finir demain !

**Comment by EgnaroRueluoc** [comment]
Fini ! Quelqu'un pourra relire, corriger et ajouter quelques passages que je n'arrivais pas à retranscrire ? Merci !

**Comment by desintoxiquezvous** [comment]
@EgnaroRueluoc bonjour je me colle a la relecture, merci d'avoir commencé 
22h 45
premiere relecture faite
pret pour la 2eme

**Comment by desintoxiquezvous** [comment]
pret pour 2eme lecture

**Comment by sentinelle2017** [comment]
2eme relecture en cours

**Comment by sentinelle2017** [comment]
2eme relecture faite
