### ISSUE TITLE
[subtitles] [FR] Intervention au 20 h de TF1 du 01/12/2016

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#33]
# Video title

MÉLENCHON - NOTRE PROGRAMME : L'AVENIR EN COMMUN

# URL

https://www.youtube.com/watch?v=96uH7RFbFTo

# Youtube subtitles language

Français

# Duration

7:47

# URL subtitles

https://www.youtube.com/timedtext_editor?v=96uH7RFbFTo&tab=captions&action_mde_edit_form=1&ui=hd&bl=vmp&ref=player&lang=fr

**Comment by Bentham** [comment]
Vidéo bloquée par TF1, impossible de la voir.
La vidéo est dispo sur facebook, mais il est évidemment impossible de sous-titrer.

https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FJLMelenchon%2Fvideos%2F10154820200498750%2F&show_text=0&width=560

Je ferme l'issue, j'en rouvrirai une si jamais ils trouvent une solution pour maintenir la vidéo sur youtube.

**Comment by LucileDT** [comment]
Merci pour l'information !

**Comment by Ricyeam** [comment]
Aucun problem pour la lire sur youtube depuis l'angleterre. Si tu utilises un proxy depuis la france ca marchera aussi. Je réouvre l'issue et fais les sous titres ce soir ou demain

**Comment by LucileDT** [comment]
GJ

**Comment by dalipokim** [comment]
Faites passer : Avec firefox, installer un vpn (un qui marche bien Hotspot shield) et lui mettre une localisation virtuelle hors de France.

**Comment by Bentham** [comment]
Je ne trouve pas qu'il soit utile de travailler à sous-titrer en français une vidéo qui n'est pas disponible en France. Je passe mon tour sur celle-là.

**Comment by LucileDT** [comment]
@Bentham Si on sous-titre en anglais, c'est notamment pour l'internationalisation :P

**Comment by Bentham** [comment]
Oui, en anglais ça fait sens ! Je parlais seulement de la transcription en français :)

**Comment by LucileDT** [comment]
Ah, autant pour moi :/ Mais il faut quand même penser aux belges, suisses, québécois sourds ou malentendants, non ?

**Comment by Bentham** [comment]
L'audience serait tellement limitée que je me demande si ça en vaut bien la peine... A débattre. Les autres vous en pensez quoi ?

**Comment by bayasahra** [comment]
c' est bien si c' est fait, mais pas en priorité... c' est pas comme si il y avait que cette vidéo à faire ;) voilà mon avis.

**Comment by dalipokim** [comment]
Salut, mon avis est qu'on pourrai le faire tout de même puisque j'ai vu en
commentaire que JLM allait faire une réclamation pour la récupérer. Et on
peut mettre une indication sous le titre comme quoi on ne peut la voir
qu'avec un VPN.

2016-12-03 13:23 GMT+01:00 Baya <notifications@github.com>:

**Comment by Ricyeam** [comment]
Je commence en Fr… quelqu'un a fait jusqu'à 2min 04 "trompés, trahis!"

**Comment by Ricyeam** [comment]
ca m'écorche les doigts d'écrire la question du journaliste vis a vis de la pseudo similarité du programme avec celui de MLP. :\

**Comment by Ricyeam** [comment]
Fait jusqu'à 4min, le bâtiment où je suis à la fac ferme, je dois partir… je finis ce soir.

**Comment by Ricyeam** [comment]
Je m'y remets à l'instant.

**Comment by Ricyeam** [comment]
Bon ça y est, j'ai dû m'arrêter au milieu, et revoir les temps de ce qui avait été fait déjà. C'est prêt pour vérification. Si quelqu'un peut utiliser un proxy pour le faire, et que ça soit publié? Merci !

**Comment by LucileDT** [comment]
Je suis désolée, je n'ai pas de proxy sous la main à l'heure actuelle...

**Comment by dalipokim** [comment]
Salut lucile, tu peux, sous firefox, installer un vpn (hotspot shield
fonctionne bien ) ce qui t’évite d'utiliser un proxi ! Il faut aller dans
les modules complémentaires, c'est super simple

2016-12-04 21:57 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by dalipokim** [comment]
La vidéo n'est plus censurée

**Comment by dalipokim** [comment]
validée avec quelques modifs mineures

**Comment by bayasahra** [comment]
j' attaque la deuxième correction.

**Comment by bayasahra** [comment]
corrigé et validé.
Je n' ai pas accès à la vidéo donc j' ai corrigé l' ortho.
Ben vu que t' es ici ^^ tu peux juste mater vite fait si t' as accès à la vidéo, et si oui si le sous titrage a été accepté qu' on puisse close l' issue ;)

**Comment by dalipokim** [comment]
Baya est-ce a dalipokim que tu parles ?

2016-12-05 22:34 GMT+01:00 Baya <notifications@github.com>:

**Comment by Bentham** [comment]
baya je peux pas voir la vidéo...

**Comment by bayasahra** [comment]
oue pareil que moi quoi .... ça doit être bon ... dali fermera l' issue .... il peut la voir lui apparemment ;)

**Comment by dalipokim** [comment]
Ok ca marche ! Sinon vous pouvez installer un vpn sur votre explorateur ça
prend 2 mn et c'est indolore :)

2016-12-05 23:20 GMT+01:00 Baya <notifications@github.com>:

**Comment by Bentham** [comment]
Je fais pas trop confiance aux VPN "gratuits"... :)
Si jamais je décide un jour de confier TOUTES mes données de navigation à un serveur, je pense que je choisirai une solution fiable, sérieuse et reconnue... Donc payante !

**Comment by dalipokim** [comment]
en attendant on est sur Gmail!!! :) Donné pour données !

2016-12-05 23:28 GMT+01:00 Bentham <notifications@github.com>:

**Comment by dalipokim** [comment]
Je m'y colle dans 5 mn mais ça marche si je l'ai déjà fait une fois ?

**Comment by dalipokim** [comment]
Il y a une petite coquille sur cette vidéo, à 7:02le CTE au lieu de l'OCDE
que fais-je ? je corrige ou je laisse tel quel et on valide ?

**Comment by dalipokim** [comment]
C'est bon Approuvé avec modification (1)

**Comment by Ricyeam** [comment]
(Désolé hors sujet) @Bentham l'important c'est que tu choisisses une compagnie qui ne garde pas les log des connexions de leurs abonnés. Comme ca même si une demande leur est faite par un Etat ou autre de voir les données de connexion de tel utilisateur, la compagnie du vpn sera dans l'impossibilité matérielle de le faire. Va voir du coté de TunnelBear par exemple (c'est celui que j'utilise).

**Comment by Ricyeam** [comment]
Bon j'y comprends plus rien, les sous-titres fr qu'on a fait ne sont pas publiés mais accessibles dans l'outil d'édition. J'ai validé, mais rien.

**Comment by Bentham** [comment]
Il faut plusieurs validations pour qu'ils soient publiés !
