### ISSUE TITLE
[subtitles] [eng] Europe : « Il faut rompre avec ce monde pourri » - Mélenchon 

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#34]
# Video title
Europe : « Il faut rompre avec ce monde pourri » - Mélenchon

# Url
https://www.youtube.com/watch?v=HMNwmW1BHRY

# Duration
17:20

# Language
English

# Subtitles URL

https://www.youtube.com/timedtext_editor?bl=vmp&forceedit=timedtext&v=HMNwmW1BHRY&action_mde_edit_form=1&ref=player&tab=captions&lang=en

**Comment by Ricyeam** [comment]
Vidéo super interessante de Melenchon sur l'Europe actuelle.

Je mets juste ca là pour partager avec vous, j'essaierai de faire un bout de sous-titres ce week end
(au moins au francais, probablement en anglais aussi mais @Flupignon il y aura besoin de correction!)

**Comment by Flupignon** [comment]
Oui bien vu ! Je voulais la faire mais il y avait de nouvelles vidéos... C'est vraiment le genre de vidéo prioritaire pour les traductions.

**Comment by Ricyeam** [comment]
La video a deja été sous-titrée en français, je ne sais pas par qui. Je voulais en faire un bout en anglais ce soir mais malheureusement l'app youtube sur iOS ne laisse pas cette possibilité...j'ai laissé  mon ordi a la fac donc je vais pas pouvoir avancer. Au mois je le saurai maintenant, que j'ai besoin de l'ordinateur et pas de l'ipad pour faire les sous-titres!

**Comment by Ricyeam** [comment]
Je m'y mets

**Comment by Ricyeam** [comment]
Bwa je galère à la traduction… J'ai fait les 2 - 3 premières minutes, @Flupignon tu pourrais jeter un oeil et me dire si ca vaut la peine de continuer, ou bien si tu dois tout changer? Peut être que je ferai mieux de m'employer à sous-titrer une autre vidéo, et corriger celle-ci si tu as le temps de la traduire.

**Comment by Flupignon** [comment]
J'allais m'y mettre hier, mais j'ai pas pu. J'essaye aujourd'hui !

**Comment by Flupignon** [comment]
4:04

**Comment by Flupignon** [comment]
J'ai presque terminé mais je dois arrêter, j'en suis à 15:12 et je termine ce soir.

**Comment by Ricyeam** [comment]
Ok ça marche, je relirai ensuite. Merci! Tu pourras me dire si les premières minutes etaient ok ou si tu as du changer beaucoup? Je devrai pouvoir faire la relecture ce soir ou demain selon quand tu termines.

**Comment by Flupignon** [comment]
Je crois que j'ai fait quelques modifs mais rien de bien méchant. Regarde l'issue #78  aussi ;)

**Comment by Flupignon** [comment]
Finalement j'ai pu finir, mais j'ai pas le temps de relire. C'était pas du gâteau avec toutes ces digressions et ces phrases inachevées...

**Comment by Ricyeam** [comment]
Oui je sais bien, c'était bien ma difficulté de départ également ! Je me mets à la relecture. Merci !

**Comment by Ricyeam** [comment]
Ok, j'ai modifié quelques petites choses, du détail surtout (des espaces en trop, un groupement pas top a cause du timing…). Révisé et approuvé.

Par contre tu as laissé des mots commes "germanophobes" ou "eurosceptics", ca se dit en Anglais?

**Comment by Ricyeam** [comment]
Pret pour revue 2 si quelqu'un est motivé (il reste @ClaireEV  et @LucileDT pour l'anglais il me semble?), mais les sous-titres sont déjà visibles sinon.
