### ISSUE TITLE
[subtitles] [fr] #RDLS26 : APRÈS LE PREMIER TOUR DE LA PRÉSIDENTIELLE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#342]
## #RDLS26 : APRÈS LE PREMIER TOUR DE LA PRÉSIDENTIELLE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 28 avril 2017
**Durée**       | 0:32:04 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=HcMV4Fa51Cs)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=HcMV4Fa51Cs&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by maximerinna** [comment]
Moulinette en cours

**Comment by maximerinna** [comment]
Le fichier sous etherpad : https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/342-hcmv4fa51cs-1t2cku7lf

Le fichier PDF :  
[JLM_342_PDF.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/965204/JLM_342_PDF.pdf)

Pas bien le morale ... sniff ..
