### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «UNE AUTRE MAJORITÉ EST POSSIBLE»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#345]
## MÉLENCHON : «UNE AUTRE MAJORITÉ EST POSSIBLE»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 07 mai 2017
**Durée**       | 0:02:59 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=BvVz9noRQEs)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=BvVz9noRQEs&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by youpidou** [comment]
J'ai relu une première fois, pour moi c'est ok ^^
