### ISSUE TITLE
[subtitles] [fr] LÉGISLATIVES : «NOUS SOMMES EN CAMPAGNE POUR GAGNER» - Mélenchon

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#347]
## LÉGISLATIVES : «NOUS SOMMES EN CAMPAGNE POUR GAGNER» - Mélenchon

&nbsp;          | Info
--------------- | ---------------
**Date**        | Mercredi 10 mai 2017
**Durée**       | 0:21:42 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=pZQfccTuVLo)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=pZQfccTuVLo&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by youpidou** [comment]
Avancé la retranscription jusqu'à 14mn (je ne me suis pas encore relue donc c'est surement très imparfait)

**Comment by youpidou** [comment]
Prêt pour la première relecture.

**Comment by Bentham** [comment]
Bonjour à tous,

Grande nouvelle, notre organisation se restructure ! Nous avons décidé de migrer vers Trello, un site beaucoup plus simple et intuitif que github.

Je vous invite à consulter tout d'abord la vidéo suivante : https://www.youtube.com/watch?v=LPQqW0LGvAA
Elle vous expliquera comment utiliser cette plate-forme.

Voici la liste du tableau pour la transcription des sous-titres en français : https://goo.gl/IkFE9S
Le github sera bientôt abandonné, donc je vous invite à vous initier dès que possible à ce nouveau fonctionnement. Comme vous le verrez, il est BEAUCOUP plus simple.

Je vous invite à rejoindre notre groupe facebook, sur lequel la communication est bien plus facile : https://www.facebook.com/groups/1850626858504963/

Par ailleurs, je vous rappelle les liens vers les vidéos expliquant comment transcrire plus efficacement :
- Comment transcrire efficacement les vidéos : https://www.youtube.com/watch?v=tg5NzbiRqI0
- Méthode plus efficace pour la transcription des vidéos (avec reconnaissance vocale) : https://www.youtube.com/watch?v=tg5NzbiRqI0

Je reste disponible pour répondre à vos questions, quelles qu'elles soient.

A bientôt !
