### ISSUE TITLE
[subtitles] [fr] #RDLS27 : LÉGISLATIVES, MARSEILLE, INDUSTRIE, GM&S, TECHNIP, ÉCOLOGIE, NUCLÉAIRE

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#349]
## #RDLS27 : LÉGISLATIVES, MARSEILLE, INDUSTRIE, GM&S, TECHNIP, ÉCOLOGIE, NUCLÉAIRE

&nbsp;          | Info
--------------- | ---------------
**Date**        | Vendredi 12 mai 2017
**Durée**       | 0:30:08 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=98bBzBt-Lc0)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=98bBzBt-Lc0&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by maximerinna** [comment]
Livraison du fichier brut : 
https://mypads.framapad.org/mypads/?/mypads/group/video-2017-vc4x7l1/pad/view/349-98bbzbt-lc0-8p24577au
et au format PDF : 
[JLM_349_PDF.pdf](https://github.com/jlm2017/jlm-video-subtitles/files/998615/JLM_349_PDF.pdf)
