### ISSUE TITLE
[subtitles] [FR] Revue de la semaine #9

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#35]
# Video title

RDLS # 9 - YOUTUBE, PROGRAMME, FILLON, ANIMAUX POLLINISATEURS EN DANGER

# URL

https://www.youtube.com/watch?v=ekBMfrb14xA

# Youtube subtitles language

Francais

# Duration

23:20

# Subtitles URL

https://www.youtube.com/timedtext_editor?lang=fr&tab=captions&v=ekBMfrb14xA&ui=hd&action_mde_edit_form=1&ref=player&bl=vmp

**Comment by Bentham** [comment]
Je m'y mets. Je vais sans doute faire la moitié maintenant, si quelqu'un voudra prendre la relève après ça...

**Comment by dalipokim** [comment]
Pas de problème, envoie moi un message quand tu as fini.

**Comment by LucileDT** [comment]
@dalipokim pour que les titres ressemblent à ceux des autres issues, il faut que tu mettes # et un espace avant :)

**Comment by dalipokim** [comment]
ha aha cool mais je n'en suis pas encore là ! J'ai essayé hier mais j'ai eu
l'impression que ça partait en sucette alors plutôt que faire une connerie,
j'ai laissé tombé. Je préfère attendre les explications !

2016-12-02 20:50 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by Bentham** [comment]
Allez c'est bon pour moi, j'ai arrêté à 12:44.

**Comment by dalipokim** [comment]
ok je reprends tout de suite, bonne soirée !

**Comment by Bentham** [comment]
merci, bon courage à toi :)

**Comment by LucileDT** [comment]
@dalipokim Si tu veux te rendre sur l'issue #37, j'y serai dans la soirée !

**Comment by Flupignon** [comment]
Je reprends, mais je pense pas finir ce soir...

**Comment by Bentham** [comment]
@Flupignon et @dalipokim , vous n'êtes pas en train de modifier en même temps par hasard ?

**Comment by Flupignon** [comment]
J'en ai bien peur...

**Comment by Flupignon** [comment]
J'ai pas encore encore commencé. @dalipokim  tu es sur la revue 9 ?

**Comment by LucileDT** [comment]
A priori oui, il l'a écrit il y a une heure ^_^

**Comment by dalipokim** [comment]
OUI desolé g pas vu les messages !

2016-12-02 23:46 GMT+01:00 Flupignon <notifications@github.com>:

**Comment by dalipokim** [comment]
J'ai fini la RVDLS"9, je l'envoie pour vérification. A+

**Comment by Bentham** [comment]
Merci pour le boulot @dalipokim ! T'as fait des heures sup' là :D

Je relis le tout et j'envoie

**Comment by Bentham** [comment]
Deux petites remarques en corrigeant, dis-moi si ça te saoule que je relève ce genre de choses.

- A plusieurs reprises tu écris : "Mr Fillon". En fait "Mr" est l'abréviation anglaise, elle est mise pour Mister. En français c'est "M.", tout simplement !

- Par ailleurs, je ne pense pas qu'il soit utile de mettre trois points d'exclamation à la suite, même quand l'exclamation est très vive. On comprend aussi bien avec un seul point d'exclamation, et ça simplifie la lecture... Qu'est-ce que tu en dis ?

En tout cas c'est bon, c'est validé !

**Comment by Bentham** [comment]
Les sous-titres sont publiés ! High five collectif !

Si quelqu'un veut passer pour une dernière relecture, c'est parfait (par exemple, pour les containers). Mais ça devrait être bon tel quel.

**Comment by dalipokim** [comment]
En fait c'est l'habitude, on va faire comme tu dis !
