### ISSUE TITLE
[subtitles] [fr] «NOUS SOMMES LA FRANCE DE LA LIBERTÉ, DE L'ÉGALITÉ ET DE LA FRATERNITÉ.» - Mélenchon

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#357]
## «NOUS SOMMES LA FRANCE DE LA LIBERTÉ, DE L'ÉGALITÉ ET DE LA FRATERNITÉ.» - Mélenchon

&nbsp;          | Info
--------------- | ---------------
**Date**        | Samedi 20 mai 2017
**Durée**       | 0:11:06 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=Hgf91mAaRUc)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=Hgf91mAaRUc&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by houlenn** [comment]
Sous-titres retranscrits jusqu'à 6:44 et mis en place jusqu'à 3 minutes à peu près, je m'arrête là pour le moment.

**Comment by Bentham** [comment]
Bonjour @MasterSlip , tu as vu qu'on a tous migré sur Trello ?
