### ISSUE TITLE
[subtitles] [eng] Revue de la semaine 9

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#36]
# Video title

RDLS #9 - YOUTUBE, PROGRAMME, FILLON, ANIMAUX POLLINISATEURS EN DANGER

# URL

https://www.youtube.com/watch?v=ekBMfrb14xA

# Youtube subtitles language

Anglais

# Duration

23:20

# Subtitles URL

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&lang=en&ref=player&v=ekBMfrb14xA&tab=captions&ui=hd&bl=vmp

**Comment by Flupignon** [comment]
7:33

**Comment by Flupignon** [comment]
Back to work.

**Comment by Flupignon** [comment]
J'en suis à 13:38.

**Comment by Flupignon** [comment]
Pause 15:09

**Comment by Flupignon** [comment]
Quelqu'un a fini la trad, il ou elle a géré grave ! Je relis le tout et je valide, sauf si vous voulez relire avant @Ricyeam ou @ClaireEV

**Comment by Flupignon** [comment]
En fait y'a quand même de la trad automatique à la fin. Pause à 20;41.

**Comment by Flupignon** [comment]
Bon pour vérif n°2 ! @LucileDT @Ricyeam @ClaireEV  ?

**Comment by LucileDT** [comment]
J'arriiiiiive !

**Comment by LucileDT** [comment]
Fait !
