### ISSUE TITLE
i would control my form on website odoo 10

### ISSUE THREAD

**Issue by ikrape** [jlm2017/jlm-video-subtitles#360]
hi every body ,
actually i work on website odoo and ihave two problems  :+1:  i want to control my form on website i have tried many fonction that validate my form on logs only not on the site (printed erreur)
and my next problem : i want to upload a file on website 
im a beginner on odoo10 and that's my first experience and i really need a help afterr then 2 weeks searching and no result and no answer 
i wish that you to help me
and thanks :)

**Comment by Enrok** [comment]
ahah really ? I think you posted on the wrong thread

**Comment by ikrape** [comment]
@Enrok  hello i think me too :D
