### ISSUE TITLE
Help for implementation of an algo on Python

### ISSUE THREAD

**Issue by SalmaAitlhaj** [jlm2017/jlm-video-subtitles#363]
Hi all, 

Please can someone help me implement the algorithm 1 page 6 on this paper : http://yuba.stanford.edu/~nickm/papers/sigcomm2014-video.pdf

This algorithm !! Pleeeaaase :

![image](https://user-images.githubusercontent.com/24361018/47783841-14995180-dd04-11e8-9d6c-0ffe30a8d20f.png)

**Comment by Goutte** [comment]
Hello ! Looks straighforward ; where's your code ? What do you need ?
How come you're asking for help here ?

**Comment by SalmaAitlhaj** [comment]
I don't know how to write it on python, if you can help please, i'm not good at it

**Comment by Goutte** [comment]
This is not the right place for this ; do send me an email (**redacted**)
Also, I can help, but I'm not going to write it for you from scratch ;)
