### ISSUE TITLE
Documentation - Guide d'usage de Github

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#38]
Hello à tous !

J'ai commencé à rédiger la documentation pour que les personnes qui ont du mal avec Github puisse plus facilement s'en sortir.

**Page d'accueil :** https://github.com/jlm2017/jlm-video-subtitles
**Mode d'emploi de Github :** https://github.com/jlm2017/jlm-video-subtitles/blob/master/french-ressources/comment-utiliser-github.md
**Procédure qu'on utilise :** https://github.com/jlm2017/jlm-video-subtitles/blob/master/french-ressources/comment-participer.md

Dites-moi si ça vous va ou s'il manque des trucs !

**Comment by Ricyeam** [comment]
Merci pour ce taf @LucileDT :)

**Comment by LucileDT** [comment]
Vu que ces liens sont listés dans la FAQ, je clos l'issue :)
