### ISSUE TITLE
docplex-interpolation

### ISSUE THREAD

**Issue by Kamel97458** [jlm2017/jlm-video-subtitles#385]
Hello :)   I would like to solve a mathematical model with python docplex. one of its constraints contains a mathematical interpolation (cubic spline) taking advantage of the cubic spline function which exists in the scipy library. But I still have the error  "' dict' object has no attribute 'astype' "

TFR the dictionnary of decision variables
network is my data frame which contains the data

s=0
for i in network.index.unique():
    b=network.iloc[1, 2:15].values
    from scipy.interpolate import interp1d
    cub=interp1d(x_int, y_int, kind="cubic")
    s=s+network.loc[i]["WAMF"]*cub(TFR[i])
mdl.add_constraint(s<=0.985)

**Comment by jillro** [comment]
not the right place
