### ISSUE TITLE
[subtitles] [fr] [TEASER] PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE 

### ISSUE THREAD

**Issue by dalipokim** [jlm2017/jlm-video-subtitles#39]
# Video title
[TEASER] PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE 

# URL
https://www.youtube.com/watch?v=kUdVpA5W6t8

# Youtube subtitles language
Français

# Duration
5:10

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&bl=vmp&action_mde_edit_form=1&lang=fr&v=kUdVpA5W6t8&tab=captions&ui=hd

**Comment by dalipokim** [comment]
je l'ai finie mais j'ai un problème à 3:40 avec des "éponges ""écarives ?"" qui composent le Zovirax. j'ai rien trouvé la dessus ! Sinon a part ça c'est prêt.

**Comment by LucileDT** [comment]
@dalipokim Super pour la création de l'issue + les labels + la bonne colonne dans le Project :+1: !

**Comment by dalipokim** [comment]
Salut je n'ai ni twitter ni Facebook, quelqu'un pourrait-il contacter JM Biette (il est sur les deux) histoire de savoir de quelles éponges il parle svp ? Je sais je suis chiant mais je ne trouve rien là dessus !

**Comment by bayasahra** [comment]
@dalipokim contacté JMb lol rien que ça dali !! :) t' arrêtes tes bêtises oué ^^ donne moi le timing

**Comment by dalipokim** [comment]
à 3:40 sur le teaser. Mais si tu lui parles des éponges qui composent le
zovirax il devrait comprendre.

2016-12-03 17:22 GMT+01:00 Baya <notifications@github.com>:

**Comment by Bentham** [comment]
DES EPONGES DES CARAÏBES !! hahaha

J'ai gagné le blind test ?

**Comment by bayasahra** [comment]
j' allais le mettre lol j' ai corrigé mais pas validé vu que t es dessus :) l' éponge dont provient la molécule Dali vient des Caraïbes ^^

**Comment by Bentham** [comment]
vas-y vas-y, je touche à rien. c'était juste pour le jeu

**Comment by bayasahra** [comment]
pas toi ben dali est dessus toi je savais même pas que t étais là <3 lol

**Comment by dalipokim** [comment]
tu es sûr DES EPONGES DES CARAÏBES , Si oui je met ça et c'est bon comme ça
!

2016-12-03 17:32 GMT+01:00 Bentham <notifications@github.com>:

**Comment by bayasahra** [comment]
mdr Dali ^^ je te propose d' appeler JMB pour confirmation lol <3 ... mais oui c' est ça tu peux le rajouter ;)

**Comment by Bentham** [comment]
Oui sûr de chez sûr dali !

**Comment by dalipokim** [comment]
Ok je corrigerais donc comme ça, merci

2016-12-03 17:41 GMT+01:00 Bentham <notifications@github.com>:

**Comment by LucileDT** [comment]
Si vous voulez que je contacte l'équipe, c'est possible : le CM de JLM me suit sur Twitter, du coup je peux lui envoyer des messages privés. Le délai de réponse est d'environ deux jours.

**Comment by dalipokim** [comment]
Merci lucile mais ce que m'a répondu Bentham me paraît cohérent, je
corrigerais comme ça après, pour l'instant je vérifie : 1 an après le 13
novembre 2015

**Comment by dalipokim** [comment]
Ok c'est corrigé, j'ai envoyé pour vérification. Merci pour le chambrage !

**Comment by dalipokim** [comment]
Lucile, une suggestion pour plus de clarté sur l'onglet projects, si la
colonne "prêt pour correction (2) " se nommait "prêt pour validation", ce
serait t'y pas mieux ?

**Comment by LucileDT** [comment]
Bonne idée ! Je suis d'accord. Les autres ?

**Comment by bayasahra** [comment]
j' ai encore un peu de temps je me colle à la première correction

**Comment by dalipokim** [comment]
On est samedi soir tout le monde est parti au Macumba !!!

2016-12-03 20:10 GMT+01:00 LucileDT <notifications@github.com>:

**Comment by bayasahra** [comment]
Validé et corrigé.
Je pensais avoir le temps de tout faire en même temps pour une vidéo de 5 minutes, mais j' ai plus de temps, je dois y aller.  j' ai commencé à regarder les timings mais je peux pas vraiment m' y pencher dessus et j' en ai vu à changer. Donc celui qui fait la correction 2,  l' othographe c' est bon mais pas les timings. 
à++

**Comment by Flupignon** [comment]
Approuvé :)
