### ISSUE TITLE
[communication] News about the team?

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#4]
# Date
24 novembre 2016

# Type
Internal

# Media used
Mail

# Purpose
Take news about people working on the project.

# Content
**Avancée, organisation, groupe facebook - Sous titrage anglais JLM**
>Salut !
>Quelques questions pour toi :
>- Est-ce que tu as des nouvelles des gens ?
>- J'ai créé un projet GitHub pour gérer le sous-titrage, jette un oeil ici : https://github.com/LucileDT/jlm-english-subtitles et ici : https://github.com/LucileDT/jlm-english-subtitles/projects/1
Si tu veux, je peux commencer indépendamment de vous à travailler avec, par contre s'il y a moyen que vous listiez les vidéos pour lesquelles vous avez commencé à travailler, ce serait cool !
>- Pas de nouvelles vis à vis du groupe facebook, je suis toujours en attente de validation...

# Answer
> Salut,
désolé pour les non reponses de cette semaine !
As tu reussi à rejoindre ce groupe facebook? ```groupe facebook```
Comme je disais l'admin a eu son compte supprimé juste quand on commencait à s'organiser, du coup ca a pris du retard.
Tiens moi au courant si tu peux rejoindre le groupe ou non, c'est possible que je doive en créé un autre!
Merci

--

> Ah, ok, super le github.
Je viens de t'envoyer un message pour le groupe, mais je n'avais pas lu celui ci, mes excuses.
Je vais certainement créer un nouveau groupe, vu que apparemment seul l'admin peut ajouter des membres a celui ci… mais le groupe n'a pas d'admin, donc ca devient compliqué.
En attendant peux tu m'ajouter? ``` utilisateur facebook```

**Comment by Ricyeam** [comment]
Super, merci beaucoup !! Effectivement je ne connaissais Github que de nom, mais cet outil a l'air assez puissant pour les travaux collaboratifs. Bonne idée !

**Comment by LucileDT** [comment]
Du coup, après les réponses de Ricyeam + la discussion de cet après-midi, je clos le topic !

**Comment by Ricyeam** [comment]
Naaaann attends, il faudrait qu'on arrive à faire participer au github celui derriere le jml in english channel. Ou bien autre issue?

**Comment by LucileDT** [comment]
Une autre issue serait pas mal. Je la crée et je t'assigne dessus ?

**Comment by Ricyeam** [comment]
ok

**Comment by Bentham** [comment]
Bonjour à tous, je viens de m'inscrire au github pour participer aux sous-titres. Est-ce qu'il y a une page dédiée aux présentations des membres ? Et quid du groupe facebook, où trouver la page ? Merci !

**Comment by LucileDT** [comment]
Salut !
RDV ici : #19 pour la réponse à tes questions :D
