### ISSUE TITLE
[subtitles] [fr] LA CASTE, LES PRIMAIRES ET LA SOUVERAINETÉ DU PEUPLE 

### ISSUE THREAD

**Issue by dalipokim** [jlm2017/jlm-video-subtitles#40]
# Video title
MÉLENCHON - LA CASTE, LES PRIMAIRES ET LA SOUVERAINETÉ DU PEUPLE 

# URL
https://www.youtube.com/watch?v=Y_V0k4fDnuw

# Youtube subtitles language
Français

# Duration
27:33

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=Y_V0k4fDnuw&tab=captions&ui=hd&action_mde_edit_form=1&ref=player&lang=fr&bl=vmp

**Comment by dalipokim** [comment]
je commence a tafer d'sus Il faudra au final, et je laisse ça aux yeux en bon état, changer le fond (ou la couleur) du sous titrages car ça passe mal visuellement.

**Comment by Bentham** [comment]
Qu'est-ce que tu veux dire ? En fait, c'est l'utilisateur lui-même qui choisit la façon dont ses sous-titres apparaissent...

**Comment by dalipokim** [comment]
Fini de rédiger. Prêt pour première vérification sachant qu'il y a quelques trous et quelques incompréhensions !
0:08 dynastie "diton" ?
7:56 j'ai un doute sur la fin
21:53 ?
24:28 ?
26:07 ?

**Comment by Bentham** [comment]
Voilà ce que j'entends :

0:08 : " de la dynastie, dit-on, "
7:56 "pour faire passer mon candidat plutôt qu'un autre"
21:53 "la clé de l'affaire, c'est : est-ce qu'on quitte le Serpent monétaire européen ou pas ?"
24:28 "j'appelle ça l'éco-humanisme, ou ce que vous voulez- mais la France tourne."
26:07 "Le peuple français dit une chose, ils en ont rien à foutre. Eux-mêmes, eux-mêmes proposent des chose. Puis après ils arrivent : "Madame, nous aussi ! Nous aussi !" "

**Comment by dalipokim** [comment]
merci je fonce pour corriger ça

**Comment by dalipokim** [comment]
Merci bentham j'ai corrigé et envoyé pour vérification.

**Comment by bayasahra** [comment]
je me lance dans la première correction.

**Comment by bayasahra** [comment]
Corrigé et validé le timing et la fidélité de la retranscription.
Dali, quand il y a un dialogue, c' est quand même plus claire de faire apparaître les initiales des deux personnalités en présence à chaque prise de parole. Là,  je m' en suis occupée.
Pour la deuxième vérification, il reste l' orthographe et la ponctuation. 
Bon courage.

**Comment by Flupignon** [comment]
D'accord avec @bayasahra pour les initiales.

**Comment by Flupignon** [comment]
Je m'en charge, j'essaye de tenir compte de ce que tu m'a dit la dernière fois.

**Comment by bayasahra** [comment]
bah là je me suis pas occupée de la ponctuation , donc tu fais comme tu le sens lol ;) bon courage.

**Comment by Flupignon** [comment]
T'aimes pas trop les virgules en fin de "bloc de sous-titre" c'est ça ?

**Comment by bayasahra** [comment]
^^ ouep... c' est pas que j' aime pas , c' est que la césure fait office de virgule. donc c' est inutile, je le ressens comme ça :) mais si toi tu mets des virgules j' irais pas te les enlever... je respecte totalement ton inclination lol !!! :) ... je file ... bonne nuit à toi :)

**Comment by Flupignon** [comment]
Bah moi aussi  alors je vais essayer de pas le faire sur ta vidéo. :)

**Comment by bayasahra** [comment]
lol flupi :)
