### ISSUE TITLE
[subtitles] [fr] Europe : « Il faut rompre avec ce monde pourri » - Mélenchon 

### ISSUE THREAD

**Issue by dalipokim** [jlm2017/jlm-video-subtitles#41]
# Video title
Europe : « Il faut rompre avec ce monde pourri » - Mélenchon 

# URL
https://www.youtube.com/watch?v=HMNwmW1BHRY

# Youtube subtitles language
Français

# Duration
17:20

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=HMNwmW1BHRY&lang=fr&tab=captions&action_mde_edit_form=1&bl=vmp

**Comment by dalipokim** [comment]
Je tiens à préciser que j'ai trouvé ce truc tout fait sur YT. Alors qui ? Peut être "dom dom" qui m'a contacté, a qui j'ai donné l'adresse mail du groupe et depuis ?

**Comment by LucileDT** [comment]
Merci @dalipokim de m'avoir fait penser à vérifier la boîte mail :)

**Comment by dalipokim** [comment]
C'est retapé ! Je l'envoie pour vérification

**Comment by Bentham** [comment]
Je regarde ça.

**Comment by Bentham** [comment]
Corrigé et validé.

**Comment by bayasahra** [comment]
le sous titrage est déjà actif ;) j' ai revisionné la vidéo une fois quand même, c' est nickel ! bon travail :)

**Comment by dalipokim** [comment]
c'est toi qui l'avait fait ce sous titrage ?

2016-12-04 15:12 GMT+01:00 Baya <notifications@github.com>:

**Comment by bayasahra** [comment]
non dali :)
