### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «FRANÇOIS FILLON VEUT DÉTRUIRE L'ÉTAT»

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#43]
# Video title
MÉLENCHON : «FRANÇOIS FILLON VEUT DÉTRUIRE L'ÉTAT»

# URL
https://www.youtube.com/watch?v=kv7EdO6GdP4

# Youtube subtitles language
Français

# Duration
27:18

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=kv7EdO6GdP4&ref=player&action_mde_edit_form=1&bl=vmp&lang=fr&ui=hd

**Comment by Bentham** [comment]
Les sous-titres sont déjà en ligne, est-ce le fait de l'un d'entre nous ?

**Comment by bayasahra** [comment]
pas de moi en tout cas

**Comment by Bentham** [comment]
Je vérifie la chose, mais ça a l'air propre

**Comment by Bentham** [comment]
Ok quelques retouches mineures, surtout des containers. Il suffit de valider de votre côté et c'est bon
(quelques redécoupages pourraient être faits, mais ça fonctionne suffisamment bien tel quel)

**Comment by Bentham** [comment]
J'ai revalidé moi-même, apparemment ça marche... Tout est en ligne, travail terminé !
