### ISSUE TITLE
[subtitles] [fr] MÉLENCHON - LÉGALISATION DU CANNABIS : POUR OU CONTRE ?

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#44]
# Video title
MÉLENCHON - LÉGALISATION DU CANNABIS : POUR OU CONTRE ?

# URL
https://www.youtube.com/watch?v=dAlp7hic4Gw

# Youtube subtitles language
Français

# Duration
3:58

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&bl=vmp&v=dAlp7hic4Gw&ref=player&action_mde_edit_form=1&lang=fr&ui=hd

**Comment by dalipokim** [comment]
C'est bon ! Prêt pour la vérification.

**Comment by LucileDT** [comment]
Je vérifie !

**Comment by LucileDT** [comment]
Corrections de ponctuations, et de quelques fautes d'orthographe.

@dalipokim j'ai également "collé" les boîtes de sous-titres lorsqu'elles avaient un tout petit espace entre elles :)

Besoin d'une deuxième relecture !

**Comment by Bentham** [comment]
je m'y colle !

**Comment by Bentham** [comment]
Fait ! Par contre c'est étrange, j'ai trouvé plein de petites fautes qui avaient été corrigées dans la FAQ. Dans un cas comme celui-là, où il est publié un extrait d'une vidéo déjà sous-titrée, le plus logique est de faire un copier-coller des sous-titres qu'on a déjà transcrits...
