### ISSUE TITLE
[communication] Confirmation des vidéos sous-titrées

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#46]
# Introduction

Une petite issue pour noter les envois de confirmation de sous-titre à Antoine.

**/!\ Vous aurez peut-être remarqué qu'il existe un nouveau label : ```Process: [7] Confirmation sent to Antoine```.** Il doit être appliqué sur les issues uniquement quand un mail a été envoyé à Antoine pour lui dire que les sous-titres sont sortis. 

Si vous pouvez me laisser close les issues (donc me les laisser ouvertes à partir du label n°6) ça serait super ! Comme ça, je le ferai à chaque fois que j'enverrai un mail à Antoine.

# Modèle
```markdown
## Date
Date d'envoi du mail

## Contenu
> Contenu du mail

## Vidéos concernées
- numéro d'une issue, 
- numéro d'une issue,
...
- numéro d'une issue.
```

**Comment by Ricyeam** [comment]
Oui j'allais juste te demander ça, si tu voulais qu'on te laisse close les issues comme ca tu envoies la confirmation en meme temps. Je viens d'en fermer quelques-unes désolé, ça n'arrivera plus !

**Comment by LucileDT** [comment]
## Date
Mardi 6 décembre 2016

## Contenu
> Les vidéos listées ci-dessous possèdent des sous-titres :
> 
> **Français**
> 
> - REVUE DE LA SEMAINE # 7 - PAUVRETÉ, iTÉLÉ, MÉDIAS, PRIVATISATION DES BARRAGES : https://www.youtube.com/watch?v=oWTHYsVUSPM
> 
> - MÉLENCHON - ÉLECTIONS AMÉRICAINES - VICTOIRE DE TRUMP : https://youtu.be/Kq5iJsBbBes
> 
> - REVUE DE LA SEMAINE # 5 - FICHAGE GÉNÉRALISÉ, ÉLECTIONS, ÉGALITÉ FEMMES-HOMMES, GRÈVE DANS LA SANTÉ : https://www.youtube.com/watch?v=kt9V0BXujyI
> 
> - MÉLENCHON - JE PROPOSE UN DÉBAT À FRANÇOIS FILLON : https://www.youtube.com/watch?v=M7Ke8LwzQAk
> 
> - MÉLENCHON - HOMMAGE À FIDEL CASTRO : https://www.youtube.com/watch?v=O6Q48L6JMtA
> 
> - RDLS # 8 : FILLON, NUCLÉAIRE, PRISON FERME POUR UN VOLEUR AFFAMÉ : RDLS # 8 : https://www.youtube.com/watch?v=4zZ0rOIMOPs
> 
> - JUPPÉ, FILLON - SUPPRIMER L'ISF : LA POLITIQUE DES RICHES : https://www.youtube.com/watch?v=uSUGLX7DtkI&t=28s
> 
> - MÉLENCHON - FAQ - 6E RÉPUBLIQUE, CANNABIS, BIO, YOUTUBE, SNOWDEN, ASSANGE… : https://www.youtube.com/watch?v=GkPZ3sIhMPg
> 
> - RDLS # 9 - YOUTUBE, PROGRAMME, FILLON, ANIMAUX POLLINISATEURS EN DANGER : https://www.youtube.com/watch?v=ekBMfrb14xA
> 
> - [TEASER] PAS VU À LA TÉLÉ 7 - L'ÉCONOMIE DE LA MER - JEAN-MARIE BIETTE : https://www.youtube.com/watch?v=kUdVpA5W6t8
> 
> - MÉLENCHON - UN AN APRÈS LE 13 NOVEMBRE 2015 : MA RÉPONSE FACE AU «TERRORISME» : https://www.youtube.com/watch?v=osk854gGWLA&t=443s
> 
> - Europe : « Il faut rompre avec ce monde pourri » - Mélenchon : https://www.youtube.com/watch?v=HMNwmW1BHRY
> 
> - MÉLENCHON - LA CASTE, LES PRIMAIRES ET LA SOUVERAINETÉ DU PEUPLE : https://www.youtube.com/watch?v=Y_V0k4fDnuw
> 
> - NOËL MAMÈRE - JEAN-LUC MÉLENCHON : REGARDS CROISÉS : https://www.youtube.com/watch?v=X3bHtC2CKs8
> 
> - MÉLENCHON - LÉGALISATION DU CANNABIS : POUR OU CONTRE ? : https://www.youtube.com/watch?v=dAlp7hic4Gw
> 
> Soit 15 vidéos.
> 
> 
> **Anglais**
> 
> - MÉLENCHON - HOMMAGE À FIDEL CASTRO : https://www.youtube.com/watch?v=O6Q48L6JMtA
> 
> - RDLS # 8 : FILLON, NUCLÉAIRE, PRISON FERME POUR UN VOLEUR AFFAMÉ : https://youtu.be/4zZ0rOIMOPs
> 
> - REVUE DE LA SEMAINE # 7 - PAUVRETÉ, iTÉLÉ, MÉDIAS, PRIVATISATION DES BARRAGES : https://www.youtube.com/watch?v=oWTHYsVUSPM
> 
> - REVUE DE LA SEMAINE # 6 - SPÉCIAL ÉLECTIONS AMÉRICAINES : https://www.youtube.com/watch?v=REVN_ozRpnE
> 
> - RDLS # 9 - YOUTUBE, PROGRAMME, FILLON, ANIMAUX POLLINISATEURS EN DANGER : https://www.youtube.com/watch?v=ekBMfrb14xA
> 
> Soit 5 vidéos.

## Vidéos concernées
**Français**
- #8  
- #14 
- #16 
- #20 
- #21 
- #12 
- #26 
- #29 
- #35 
- #39 
- #24 
- #41 
- #40 
- #27 
- #44 

**Anglais**
- #18 
- #7 
- #3 
- #2 
- #36

**Comment by LucileDT** [comment]
@Ricyeam pas de soucis :P

**Comment by Ricyeam** [comment]
il y a aussi #33

**Comment by LucileDT** [comment]
Je n'ai pas listé cette vidéo pour l'instant, je pense envoyer les mails le soir. Ça me permettra de lister dans un mail les vidéos, plutôt que d'envoyer plein de mails les uns après les autres.

De plus, cette issue n'est pas dans la colonne ```validée```, donc je ne sais pas, d'autant plus que je ne peux pas la voir.

**Comment by bayasahra** [comment]
Salut Lucile
Moi je pense qu'on devrait close l' issue nous même pour un effet immédiat ... pour plus de lisibilité de la page d' issue, c' est déjà chargé, et les enlever dès qu' il n' y a plus de travail à faire dessus c' est pas mal.
Tu pourrais aller valider dans la dernière colonne projects , c' est pas infaisable... et on te les déplacerait en haut ... ou on peut même te les laisser dans la colonne de projects 3 si c' est plus lisible pour toi. Qu' en pense les autres ?

**Comment by Flupignon** [comment]
On peut rajouter une colonne 'project:sent to antoine' sinon ?

**Comment by Bentham** [comment]
Ce serait peut-être plus clair en effet !

**Comment by Ricyeam** [comment]
Je pense que l'issue devrait etre close seulement quand tout a été fait, y compris l'envoyer à Antoine. Rajouter un label (et une colonne?) 'to send to Antoine' nous apporterait une conclusion à tous (au lieu de close l'issue), et améliorerait la visibilité aussi

**Comment by bayasahra** [comment]
@Ricyeam  Quand on sous titre une vidéo, qu' on l' arrête et qu' on navigue à partir de la page d' issue pour corriger deux autres vidéos en cours, la lisibilité n' est pas de refus. On jongle quand même pas mal entre les vidéos dans la même journée, donc plus le nombre d' issues est petit plus c' est agréable.. Lucile, ça ne lui change pas grand chose de valider depuis une colonne de projects. Après la colonne antoine est une très bonne idée mais en plus pour plus de visibilité finale.

**Comment by Flupignon** [comment]
HORS-SUJET : Quelqu'un qui a la chaîne "TheAppologies" a contribué à la trad de la revue 9, je lui ai envoyé un message privé.

**Comment by LucileDT** [comment]
@Flupignon thx!

@bayasahra je comprends tout à fait le fait que c'est le merdier dans la liste des issues. Je suis en train de réfléchir à vous fournir un moyen plus simple de voir toutes les issues qui ont besoin de quelqu'un pour bosser dessus, en plus de la page des projets. Pour l'instant, si vous préférez, vous pouvez clore, et on verra ensuite comment améliorer ça :) Car comme dit @Ricyeam, effectivement, clore l'issue uniquement quand tout est fait serait plus logique.

@Flupignon pour la colonne supplémentaire, oui, ça serait pas mal en effet :D

**Comment by bayasahra** [comment]
je comprends lucile :) mais clore l' issue est le seul moyen de désengorger cette même liste d' issues donc ....

**Comment by LucileDT** [comment]
@bayasahra peux-tu regarder l'issue #47 et me dire ce que tu en penses ?

**Comment by Ricyeam** [comment]
ah, en lisant ca je pensais justement à faire une liste de liens pointant sur une recherche des issues en fonction des labels… GJ @LucileDT , comme d'hab!

**Comment by Ricyeam** [comment]
Je pense que si, à la place d'aller chercher les issues dans l'onglet attribué, on prend l'habitude de passer par la page 'projects', la visualisation est beaucoup plus facile. Par contre, ca suppose que les issues soient bien dans les bonnes colonnes en fonction des labels. Si vous voulez je peux m'occuper de vérifier ca régulièrement.

**Comment by bayasahra** [comment]
C' est une issue que l' on doit modifier à chaque vidéo créée, à chaque changement de labels ? ça devient donc un autre suivi à mettre en place... Si vous trouvez que cette issue est un gain de temps à coté d' un simple coup d' oeil sur l' ensemble des issues qui ne nous demande pas de travail ajouté et sans dépendre d' un quelconque suivi... je ne vois pas la logique, mais soit.

**Comment by LucileDT** [comment]
L'issue n'a pas à être modifiée, les liens fonctionneront toujours :) Ils permettent de filtrer les issues qui concernent uniquement les vidéos, par exemple.

**Comment by LucileDT** [comment]
## Date
12 décembre 2016

## Contenu
> Bonjour,
> 
> Les vidéos listées ci-dessous possèdent des sous-titres :
> 
> **Français :**
> 
>    - MÉLENCHON : «FRANÇOIS FILLON VEUT DÉTRUIRE L'ÉTAT» : https://www.youtube.com/watch?v=kv7EdO6GdP4
>    - ORGANISONS 1000 POINTS DE DIFFUSION DU PROGRAMME ! : https://www.youtube.com/watch?v=L1fa4Uh9_Xs
>    - REVUE DE LA SEMAINE # 6 - SPÉCIAL ÉLECTIONS AMÉRICAINES : https://www.youtube.com/watch?v=REVN_ozRpnE
>    - Affaires étrangères : deux poids deux mesures au Parlement européen : https://www.youtube.com/watch?v=32mjOWZvm2Q
>    - MÉLENCHON - POURQUOI LE CODE DU TRAVAIL EST GROS ? : https://www.youtube.com/watch?v=jnqujbuCNsM
> 
> Soit 5 vidéos
> 
> **Anglais :**
> Aucune.

## Vidéos concernées
- #43 
- #48 
- #54 
- #50 
- #77

**Comment by Flupignon** [comment]
Si il y a des sous-titres pour la REVUE DE LA SEMAINE # 6 - SPÉCIAL ÉLECTIONS AMÉRICAINES (deux versions même !)

**Comment by LucileDT** [comment]
Ah, pas vu :x

**Comment by Goutte** [comment]
Ooops, j'avais pas vu ce message, j'ai fermé plein d'issues... Pardon ! :face_with_head_bandage:
... 'le ferai plus !

**Comment by LucileDT** [comment]
@Goutte pas de soucis, j'ai laissé tomber l'idée : si ceux d'en haut ne font pas l'effort de communiquer avec nous, je ne vois pas pourquoi je me taperais ce boulot.
