### ISSUE TITLE
[subtitles] [fr] ORGANISONS 1000 POINTS DE DIFFUSION DU PROGRAMME !

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#48]
# Video title
ORGANISONS 1000 POINTS DE DIFFUSION DU PROGRAMME !

# URL
https://www.youtube.com/watch?v=L1fa4Uh9_Xs

# Youtube subtitles language
Français

# Duration
1:37

# Subtitles URL
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&bl=vmp&tab=captions&v=L1fa4Uh9_Xs&ui=hd&ref=player&lang=fr

**Comment by Bentham** [comment]
Transcription déjà réalisée par un anonyme. Correction et validation de ma part, les sous-titres sont en ligne.

**Comment by bayasahra** [comment]
lol ben ^^ c' est pas un anonyme, cette courte vidéo est un extrait de la revue 9 dont on c' était occupé du sous titrage ;) ... Antoine ou celui qui a mis en ligne la vidéo c' est resservi du sous titrage déjà fait.

**Comment by Bentham** [comment]
Aha... Pour moi anonyme ça voulait juste dire "quelqu'un qui n'a pas communiqué son nom" !
