### ISSUE TITLE
[subtitles] [fr] PAS VU À LA TÉLÉ #6 - L'AUTISME - Invitée : OLIVIA CATTAN

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#49]
# Video title
PAS VU À LA TÉLÉ # 6 - L'AUTISME - Invitée : OLIVIA CATTAN

# URL
https://www.youtube.com/watch?v=Xo1W8mnVyb8

# Youtube subtitles language
Français

# Duration
1:00:25

# Subtitles URL
https://www.youtube.com/timedtext_editor?ui=hd&v=Xo1W8mnVyb8&action_mde_edit_form=1&lang=fr&ref=player&bl=vmp&tab=captions

**Comment by Bentham** [comment]
J'aimerais beaucoup sous-titrer cette vidéo, ça me semble important. Ca risque de prendre du temps mais j'essaierai de m'y mettre cette semaine

**Comment by bayasahra** [comment]
lol !! :) oue je confirme ça prend du temps ( cf revue 7 que j' ai pas encore fini !! ) déjà c' est long en soi, mais en plus on corrige et valide à coté ^^ donc avec tout ces arrêts ^^" ... mais bon l' essentiel c' est qu' au final ça soit fait ;)

**Comment by Bentham** [comment]
Allez j'avance un peu !

**Comment by Bentham** [comment]
Fait jusqu'à 10:05

**Comment by Bentham** [comment]
J'y retourne

**Comment by Bentham** [comment]
Fait jusqu'à 20:05

**Comment by Bentham** [comment]
On y retourne...

**Comment by Bentham** [comment]
Bon je me suis un peu endormi en le faisant, mais c'est fait jusqu'à 30:02 !

**Comment by Bentham** [comment]
Allez au boulot !

**Comment by Bentham** [comment]
Fait jusqu'à 40:10

**Comment by Bentham** [comment]
En avant !

**Comment by Bentham** [comment]
Les petits chats, qu'est-ce que vous entendez à 41:42 ?

Olivia Cattan : 'Parce que bon, je suis pas non plus dupe, ils le prenaient parce que je parlais de discrimination, XXXXXXXXX, voilà, c'était la menace !"

EDIT : ça y est j'ai compris : "de maître Dupont-Moretti qui était derrière nous" :)

**Comment by Bentham** [comment]
Allez c'est bon, la délivrance est proche ! Fait jusqu'à 50:00

**Comment by bayasahra** [comment]
c' est pas la peine que je regarde à 41:42 alors :p

**Comment by Bentham** [comment]
Non ! Mais ça vaut le coup de regarder toute la vidéo.

Et ça tombe bien pour toi, y'aura la deuxième révision à faire ! MUHAHAHAHA (rire diabolique)

**Comment by bayasahra** [comment]
MDRRRR :) avec plaisir ;) (Toi y'a plusieurs relectures à faire qui attendent depuis une semaine <3)

**Comment by Bentham** [comment]
Hésite pas à m'assigner ! Je vais faire l'économie de la mer quand j'aurai terminé celle-ci

**Comment by Bentham** [comment]
et goooooooo

**Comment by Bentham** [comment]
et c'est fait !!! pfiou, quel boulot !!!

**Comment by bayasahra** [comment]
je fais la première correction.

**Comment by bayasahra** [comment]
j'ai corrigé surtout l'ortho pour cette première correction... j'ai yeuté un peu le timing et je pense qu'il y a des changements à faire d'où une seconde correction orientée timing.
Si personne ne se colle à la seconde vérif, je la ferais plus tard dans la nuit ou demain ;)
@Bentham mon ti Ben, faire attention de veiller à toujours mettre les initiales de la personne qui parle lors des émissions à échange comme celle-ci, ça a été pas mal oublié ;)

**Comment by Bentham** [comment]
Pardon madame, j'le f'rai plus, promis juré !

**Comment by Bentham** [comment]
Je viens de valider et les sous-titres sont en ligne !
