### ISSUE TITLE
[communication] Tweet about this project

### ISSUE THREAD

**Issue by DarckCrystale** [jlm2017/jlm-video-subtitles#5]
# Date
25 novembre 2016

# Type
Public

# Media used
Twitter

# Purpose
Expose the project to maybe get more contributors

# Content
> Pour ceux que ça intéresse : projet de sous-titrage des vidéos de PlaceAuPeuple : https://github.com/LucileDT/jlm-english-subtitles/projects/1 … (@JLMelenchon @jlm_2017)

# Answer
- @jlm_2017 like it

**Comment by Flupignon** [comment]
Au fait les gens c'est quoi vos compte Twitter ? Moi c'est "Flupignon Grolin", follow me !
