### ISSUE TITLE
[subtitles] [FR] Affaires étrangères : deux poids deux mesures au Parlement européen

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#50]
# Video title

Affaires étrangères : deux poids deux mesures au Parlement européen

# URL

https://www.youtube.com/watch?v=32mjOWZvm2Q

# Youtube subtitles language

Français

# Duration

1:15

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=fr&ui=hd&v=32mjOWZvm2Q&ref=watch&action_mde_edit_form=1&tab=captions&bl=vmp

**Comment by bayasahra** [comment]
je suis dessus.

**Comment by bayasahra** [comment]
fini. prêt pour vérification.
Ralalalaala JLM ! quel homme <3

**Comment by LucileDT** [comment]
Je relis

**Comment by LucileDT** [comment]
C'est bon, il faut une seconde relecture.

**Comment by Bentham** [comment]
Je checke la chose.

**Comment by Bentham** [comment]
Validé. Quel tribun notre Méluche !!
