### ISSUE TITLE
[subtitles] [FR] Le libre-échange détruit la sidérurgie française - Invervention au Parlement européen

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#51]
# Video title

Le libre-échange détruit la sidérurgie française - Intervention au Parlement européen

# URL

https://www.youtube.com/watch?v=hwveRPW9Doc

# Youtube subtitles language

Français

# Duration

1:05

# URL subtitles

https://www.youtube.com/timedtext_editor?v=hwveRPW9Doc&ui=hd&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ref=watch

**Comment by bayasahra** [comment]
je suis dessus

**Comment by bayasahra** [comment]
Fini, prêt pour vérification.

**Comment by Bentham** [comment]
go

**Comment by Bentham** [comment]
faiiiiiit
