### ISSUE TITLE
Modèle d'issue de suivi multilingue

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#52]
# Modèle
## Titre de l'issue
```[subtitles-management] Titre de la vidéo```

## Corps de l'issue
```markdown
# Video title
TITRE DE LA VIDEO

# URL
http://www.url-de-la-video.fr

# Corresponding issues
## Français
#numéro_de_issue

## Anglais
#numéro_de_issue
```

# Exemple
## Titre de l'issue
```todo```

## Corps de l'issue
```markdown
todo
```

*Tout ce qui est préfixé par # sera affiché en gros, en gras et en souligné, comme un titre de niveau 1.*

**Comment by Goutte** [comment]
Toujours dans l'optique de "faire du ménage" dans les issues, est-ce que les `[subtitles-management]` sont toujours d'actualité ? Il me semble que c'est beaucoup de travail de maintenance, et on a la recherche qui remplit cette fonctionnalité.

**Comment by LucileDT** [comment]
Tu peux supprimer, c'st bon :)
