### ISSUE TITLE
[subtitles] [fr] REVUE DE LA SEMAINE # 6 - SPÉCIAL ÉLECTIONS AMÉRICAINES

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#54]
# Video title
REVUE DE LA SEMAINE # 6 - SPÉCIAL ÉLECTIONS AMÉRICAINES

# URL
https://www.youtube.com/watch?v=REVN_ozRpnE

# Youtube subtitles language
Français

# Duration
16:24

# Subtitles URL

**Comment by bayasahra** [comment]
hummmmm le sous titrage est déjà en ligne ...
