### ISSUE TITLE
[communication] Gomette asks to pin this repo on JLM 2017 GitHub

### ISSUE THREAD

**Issue by DarckCrystale** [jlm2017/jlm-video-subtitles#6]
# Date
27 novembre 2016

# Type
Public

# Media used
Twitter

# Purpose
Regroup repositories for JLM campaign.

# Content
**From Gomette (@Guilrobis)**
> @DarckCrystale @JLMelenchon @jlm_2017 Salut ! C'est trop cool :) Le copain qui s'occupe de Youtube m'a envoyé ton dépôt ce matin.
> (Je suis dans l'équipe de campagne.)
> On en a parlé et on s'est dit que si t'étais ok, on pourrait ptet basculer le dépôt sous https://github.com/jlm2017
> pour donner plus de visibilité (en te laissant admin bien sûr)
> en tout cas bravo, très bon boulot :)

# Answer
**From DarckCrystale (@DarckCrystale)**
> Pas de soucis !
Par contre, je ne sais pas du tout ce que ça va changer niveau administration du truc, je n'ai jamais travaillé avec des projets regroupés comme ça :/
J'ai vu que vous avez un Mattermost, si ça vous tente, je veux bien que vous m'invitiez dessus (je ne garantis cependant pas une présence particulièrement active).

**Comment by LucileDT** [comment]
### Procédure de transfert
* désigner @guilro comme responsable du dépôt Github
* @guilro s'occupe du reste en une étape

Dernières nouvelles : @guilro n'a pas reçu ma demande à temps (elle n'est valable que 24h) pour s'approprier le dépôt Github. La demande a été relancée ce soir, donc ça devrait être transféré demain !

**Comment by LucileDT** [comment]
Transfert effectué hier avec succès !
