### ISSUE TITLE
[subtitles] [eng] Revue de la semaine n°8

### ISSUE THREAD

**Issue by Ricyeam** [jlm2017/jlm-video-subtitles#7]
# Video title
 RDLS # 8 : FILLON, NUCLÉAIRE, PRISON FERME POUR UN VOLEUR AFFAMÉ 

# URL

https://youtu.be/4zZ0rOIMOPs

# Youtube subtitles language

Anglais

# Duration

17:13

# Subtitles URL

https://www.youtube.com/timedtext_editor?v=4zZ0rOIMOPs&tab=captions&action_mde_edit_form=1&ui=hd&forceedit=timedtext&bl=vmp&ref=player&lang=en

**Comment by Ricyeam** [comment]
- Subtitles being created by an unknown member at the moment, done until 10:21.3 so far. I think the person behind the JML In English youtube channel is doing it.

**Comment by Flupignon** [comment]
Work in progress, je devrais avoir terminé d'ici quelques heures.

**Comment by Flupignon** [comment]
Revue #8 prête pour vérification. Certaines parties très orales peuvent être améliorées je pense.

**Comment by LucileDT** [comment]
Je relirai ça cet après-midi :)

**Comment by Bentham** [comment]
FLupignon, comme on m'a dit que tu n'étais pas sur facebook je recopie le message que j'y ai posté :

"Je viens de jeter un œil à la traduction en anglais (de la revue 8 je crois), c'est du super boulot, bravo les lapins !"

Je vais relire rapidement le tout, mais le travail me paraît vraiment sérieux et je ne suis pas sûr d'y trouver à redire. Encore bravo pour la qualité de la trad.

**Comment by Flupignon** [comment]
Salut Bentham, enchanté !
Merci beaucoup ça fait plaisir. Je vais me recréer un FB très vite (anonyme je suis plutôt anti-facebook).

**Comment by LucileDT** [comment]
Coucou @Flupignon ! Je suis en train de relire, là. 

Je corrige les ponctuations, et il y a un truc que je voulais te demander : tu écris "rightwing", mais google trad et mon dictionnaire anglais Firefox me disent que ça s'écrit plutôt "right wing" (et "left wing"), avec un espace. Tu le savais ? Est-ce une erreur ?

**Comment by LucileDT** [comment]
Et on a aussi "dishonest", avec un seul 'n' :)

**Comment by Ricyeam** [comment]
J'aurais écrit avec un espace également, mais peut-être que c'est une forme acceptée que je ne connais pas?

**Comment by Flupignon** [comment]
C'est "right wing" pour un nom (la droite) et "right-wing" pour un adjectif (right-wing people).
J'ai pas vérifié j'étais certain pour l'adjectif...
Et même pour "right-wing people" on peut dire "right-winger" ( et left évidemment), ce sera plus court et moins redondant que de dire "people" tout le temps. Et "dishonest" oui ;)

>http://www.macmillandictionary.com/thesaurus-category/british/right-wing-politics-and-conservatism
>http://www.merriam-webster.com/dictionary/right%20wing

**Comment by Flupignon** [comment]
Et aussi en général je mets des formes US plutôt que British, mais ça c'est un choix perso...

**Comment by Flupignon** [comment]
Quelques procédés de traduction à connaître pour ceux qui n'ont pas l'habitude de traduire. C'est qu'une page wiki mais c'est déjà bien :

https://fr.wikibooks.org/wiki/Proc%C3%A9d%C3%A9s_de_traduction_de_l'anglais_en_fran%C3%A7ais

**Comment by LucileDT** [comment]
@Flupignon j'ai relu, corrigé (typos, ponctuations, et quelques fautes), et mis en ligne la correction.

**Comment by Flupignon** [comment]
Super ! Je suis en train de remanier l'hommage à Fidel.

**Comment by Flupignon** [comment]
Au fait @LucileDT , comment tu fais pour configurer la boite mail pour diriger certains mails vers un dossier ? (Si tu as Gmail)

**Comment by LucileDT** [comment]
@Flupignon 
- dans la barre de recherche, tu entres : notifications@github.com
- tu cliques sur la petite flèche grise tout à droite dans la barre de recherche, 
- dans le menu qui s'ouvre, tout en bas, tu cliques sur "Créer un filtre à partir de cette recherche" 
- dans le menu qui s'ouvre, si tu choisis d'appliquer un libellé pour les mails et de les archiver, ils n'apparaîtront pas dans la boite de réception, mais uniquement dans le dossier du libellé :)

**Comment by Flupignon** [comment]
Muchas gracias ! J'ai presque terminé la trad de l'hommage à Fidel.

**Comment by Ricyeam** [comment]
Hey les gens, ca serait bien d'essayer d'utiliser les issues correspondantes pour questions etc, et de laisser chaque issue dédiée à son sujet (ou sa vidéo). Pour l'instant c'est pas trop grave, mais quand on aura 100 vidéos et 160 issues on va se perdre! :)

J'ai ajouté la question des filtres dans gmail à la FAQ.
