### ISSUE TITLE
[subtitles] [FR] MÉLENCHON - POURQUOI LE CODE DU TRAVAIL EST GROS ?

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#77]
# Video title

MÉLENCHON - POURQUOI LE CODE DU TRAVAIL EST GROS ?

# URL

 https://www.youtube.com/watch?v=jnqujbuCNsM

# Duration

1:58

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=fr&ui=hd&action_mde_edit_form=1&bl=vmp&v=jnqujbuCNsM&tab=captions&ref=watch

**Comment by bayasahra** [comment]
je suis dessus

**Comment by bayasahra** [comment]
fini. A vérifier.

**Comment by Bentham** [comment]
Je m'en occupe !

**Comment by Bentham** [comment]
Ayéééééé

**Comment by LucileDT** [comment]
Je fais la seconde correction :)

**Comment by LucileDT** [comment]
Validay !

**Comment by Bentham** [comment]
Quelle équipe de choc.

**Comment by Ricyeam** [comment]
Awesome :)
