### ISSUE TITLE
[subtitles] [eng] Revue de la semaine n°10

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#79]
# Video title

RDLS10 - MATTEO RENZI, EUROPE, PAUVRETÉ, ZONES MORTES DANS LES OCÉANS, SNOWDEN

# URL

https://www.youtube.com/watch?v=DwvM9oV3v3I

# Youtube subtitle language

English

# Duration

25:16

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=player&action_mde_edit_form=1&ui=hd&v=DwvM9oV3v3I&tab=captions&bl=vmp&lang=en

**Comment by Flupignon** [comment]
Je commence ce soir.

**Comment by Flupignon** [comment]
6:21

**Comment by Flupignon** [comment]
9:06

**Comment by Flupignon** [comment]
20:03 Je devrais avoir fini demain soir.

**Comment by Flupignon** [comment]
Il reste que 30 sec de vidéo mais je dois me lever tôt demain. Je finirai dans la journée @Ricyeam

**Comment by LucileDT** [comment]
Pas de soucis @Flupignon ! On n'est pas aux pièces :D

**Comment by Flupignon** [comment]
Terminé ! J'ai pas relu le tout, mais je relis souvent les séquences que je viens d'écrire, donc ça devrait aller. Pour "insoumis" je l'ai laissé en français, mais j'ai traduit par "unsubdued, rebel" entre parenthèses. Qu'en pensez-vous ? ça s'applique plus dans un contexte guerriers ("unsubdued tribes" par exemple) mais je l'ai aussi vu plus rarement dans d'autres contextes. Il faudrait s'accorder pour la traduction d'Insoumis !

**Comment by LucileDT** [comment]
Pour la traduction d'Insoumis, je ne sais pas, désolée :/

**Comment by Ricyeam** [comment]
On peut pas laisser "Insoumis" ? Ca représente quelque chose de bien particulier, qui est propre au contexte français.

**Comment by Flupignon** [comment]
Je l'ai laissé en français mais j'ai mis "unsubdued/rebel" entre parenthèses je crois, je te laisse relire.

**Comment by Flupignon** [comment]
Guys, could someone check the video...? La RDLS #11 est déjà sortie...

**Comment by Ricyeam** [comment]
Yep sorry, je fais ca de suite

**Comment by Ricyeam** [comment]
done

**Comment by Flupignon** [comment]
Sweet! Tu as eu des modifs à faire ?

**Comment by Flupignon** [comment]
J'ai aussi fait deux petites vidéo de 1 min. C'est pas urgent, quand t'auras le temps. Et je devrais avoir fait la moitié de la RDLS 11 ce soir.

**Comment by Ricyeam** [comment]
oui j'ai fait quelques modif, des fautes de frappes principalement (j'ai bien kiffé les "private and pubic meetings" ^^). Aussi au début tu avais mis les 100 000 followers en lettres, je les ai remis en chiffres. Ca correspond a la suite la vidéo, et aussi c'est plus simple à lire je pense.

**Comment by Flupignon** [comment]
Oui tu as bien fait !

**Comment by Ricyeam** [comment]
je viens de le faire, mais j'ai pas l'impression que ca ait fait quoique ce soit… je suppose qu'une troisième personne doit valider. @LucileDT ? @ClaireEV ?
