### ISSUE TITLE
[subtitles] [fr] Revue de la semaine n°7

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#8]
# Video title
REVUE DE LA SEMAINE # 7 - PAUVRETÉ, iTÉLÉ, MÉDIAS, PRIVATISATION DES BARRAGES

# URL
https://www.youtube.com/watch?v=oWTHYsVUSPM

# Youtube subtitles language
Français

# Duration
22:48

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&v=oWTHYsVUSPM&ui=hd&action_mde_edit_form=1&ref=watch&lang=fr&forceedit=timedtext&bl=vmp

**Comment by bayasahra** [comment]
sous titrage+ timings de 00:00:00 à 5:18:9
travail toujours en cours...

**Comment by LucileDT** [comment]
@bayasahra J'avais commencé les sous-titres en français pour cette vidéo, j'ai des sous-titres jusqu'à 9:27.

**Comment by bayasahra** [comment]
@LucileDT ton travail n'est pas existant lucile as tu validé ???? quand on clique sur le lien il y a que ce que j'ai fait hier soir qui apparaît à savoir jusqu'à 5:18:9

**Comment by LucileDT** [comment]
Je ne les avais pas validés vu qu'ils n'étaient pas finis :( 
Désolée, je n'avais pas fait attention hier au fait que tu rédigeais ceux-là D:

Du coup, je ne sais pas ce qui va se passer si je les valide :/

**Comment by bayasahra** [comment]
ne valide pas je suis dessus ... il faudra juste une personne qui vérifie quand j'aurai fini.... là j'en suis à plus de 10 minutes maintenant donc ça serait un doublon inutile

**Comment by LucileDT** [comment]
Ok !

**Comment by bayasahra** [comment]
suite et fin==> sous titrage+ timing  de 5:18:9 à 22:47:6
vérification ortho faite.
envoyé pour examen au staff JLM.
Travail fini.

**Comment by LucileDT** [comment]
Super ! On peut relire nous aussi :)

**Comment by bayasahra** [comment]
salut Ben ^^ 
Je t'assigne pour vite clôturer la revue 7 fr que j'ai fini hier...
si tu pouvais juste relire et valider ça serait super
ça devrait aller vite j'ai vraiment tout revérifié donc il ne devrait pas y avoir de retouche à faire...
Comme j'adore ce discours là de Mélenchon particulièrement ça serait domage qu'il ne soit pas validé rapidement ^^
bisous à toi et bonne journée ;)

**Comment by Bentham** [comment]
Ah, Ben c'est moi... Haha ! Pas habitué à ce diminutif ! Je relis ça rapidement et je valide :)

**Comment by Ricyeam** [comment]
@bayasahra Tres bonne initiative! Aussi quand tu as fais une premiere revision, pourrais-tu déplacer l'issue dans la bonne colonne dans la page du projet? glisser-déposer, facile ! :) Merci beaucoup !

**Comment by Bentham** [comment]
J'ai commencé, mais ça va me prendre trop de temps. Je bouclerai ça ce soir ou demain !

**Comment by Ricyeam** [comment]
@Bentham peux -tu nous dire jusqu'à où tu as vérifié? Comme ca si quelque'un peut s'en occuper il ou elle pourra reprendre à partir de là. Merci !

**Comment by Bentham** [comment]
Jusqu'à 3:07 "ils se renseignent eux-mêmes, ils comparent,".

**Comment by Bentham** [comment]
Arrêté à 10:40. C'est tout pour ce soir, la suite demain !

**Comment by Ricyeam** [comment]
Je continue. Une faute que j'ai vue dans plusieurs vidéos.
"On est bien montés". Le participe passé de "monter" s'accorde avec le sujet (pronom "On") à cause de l'auxiliaire "être". On est d'accord.
Par contre "on" c'est 3e personne du **singulier**, donc pas de "s" à "monté". 

"On est bien monté."
Je sais c'est bizarre car tout le monde comprends 'nous', mais 'on' est un pronom de la 3e personne du singulier (la preuve, on dit "on est monté" et non pas "on sommes montés").

**Comment by Bentham** [comment]
Hello Ricyeam, je ne suis pas tout à fait d'accord avec toi. A ce qu'il me semble, le "on", évidemment, entraîne une conjugaison du verbe à la troisième personne du singulier ; mais ça n'implique aucune nécessité quant à l'accord du participe passé.

Je te cite l'exemple développé par http://ameliorersonfrancais.com/grammaire/verbes/accord-avec-le-pronom-on/ :

"Paul et moi, on est mariés depuis déjà un an."

Il serait visiblement incorrect de dire  "Paul et moi, on est marié depuis déjà un an" ! Quand le "on" se référe non à n'importe qui en général, mais à un sujet bien identifié, on accorde le participe passé avec le sujet implicite.

Qu'est-ce que tu en dis ?

**Comment by Ricyeam** [comment]
Hmmm ok… oui ça a du sens, et c'est vrai que "on est mariés" ne me choque pas. Donc j'ai dû me tromper! Quatre ans en Angleterre et je perds mon Français :p Désolé ! 

Vous en dites quoi les autres?

**Comment by bayasahra** [comment]
hummm je ne sais pas vraiment ..... moi je l' écris toujours "on est bien monté " quoiqu 'il arrive lol :) donc je pense que c 'est quelque chose que bentham avait rectifié en "on est bien montés" ?
@Ricyeam il faudrait mettre le timing de la faute pour qu'on puisse voir la phrase qui l'inclue... et d'autre part faut-il citer chaque chose qu'on corrige sur les différentes vidéos ? je te vois le faire pour chaque... mais quand on en corrige 15, 20 voir plus ( comme c'est le cas souvent ) les lister reviendrait à une grosse perte de temps non ? ne peux-tu pas mettre "corrigé puis validé" si c est le cas ? ne le prend pas mal simple question...

**Comment by Ricyeam** [comment]
Bon j'ai fini de corriger cette vidéo. Pfiuu c'était long! PAr contre Youtube demande une autre vérification, donc si en même temps la personne qui le fait pouvait modifier le "on est montés" que j'ai changé en "on est monté"… Je n'ai pas noté le timing par contre désolé.

Et @bayasahra Oui c'est mieux de bien noter, mais franchement c'est déjà assez fastidieux comme ça ! Si tu es motivée pour tout noter vas-y fais toi plaisir :p ;)

**Comment by bayasahra** [comment]
@Ricyeam non justement je ne l'ai pas fait et ne le ferai pas lol !!!! t imagines si j' avais listé ça ... le bordel quoi !!! et j'en vois pas l'intérêt je corrige et écris juste " corrigé et validé" ;)
c'est fastidieux à relire alors je te laisse imaginer pour celui qui passe sa journée à la faire seconde après seconde ;)

**Comment by Bentham** [comment]
Et bim, relu, corrigé, validé. Bon j'ai pas mis en forme de façon parfaite (jusqu'à la minute 10 c'est tip top, et après plus relâché), mais je pense pas que ça soit grave si la ponctuation ou les majuscules sont parfois légèrement incorrectes. Ça me fait gagner énormément de temps comme ça.

**Comment by LucileDT** [comment]
Concernant le "on", personne n'a un Bescherelle ?

**Comment by Ricyeam** [comment]
Nope pas ici, mais en effet je ferai plus (+++) confiance à un Bescherelle !

**Comment by Bentham** [comment]
La règle me semble claire, mais n'hésitez pas à vérifier de votre côté si vous avez un doute :)
