### ISSUE TITLE
[subtitles] [FR] #RDLS10 - MATTEO RENZI, EUROPE, PAUVRETÉ, ZONES MORTES DANS LES OCÉANS, SNOWDEN

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#80]
# Video title

#RDLS10 - MATTEO RENZI, EUROPE, PAUVRETÉ, ZONES MORTES DANS LES OCÉANS, SNOWDEN

# URL

https://www.youtube.com/watch?v=DwvM9oV3v3I&t=3s

# Youtube subtitles language

Français

# Duration

25:16

# URL subtitles

https://www.youtube.com/timedtext_editor?tab=captions&ui=hd&v=DwvM9oV3v3I&ref=watch&action_mde_edit_form=1&lang=fr&bl=vmp

**Comment by bayasahra** [comment]
Alors je viens de voir qu' apparemment un anonyme a fait le sous titrage français.... je mets donc l' issue en correction.
merci à l' anonyme !!!! :)

**Comment by bayasahra** [comment]
je me colle à la première correction !

**Comment by bayasahra** [comment]
Validé. J' ai corrigé l' orthographe.
pour la deuxième correction il faudrait regarder le timing et la retranscription ;)

**Comment by Bentham** [comment]
2ème correction incoming !!

**Comment by Bentham** [comment]
good

**Comment by Bentham** [comment]
sous-titres publiés sur le Tube !
