### ISSUE TITLE
[subtitles] [FR] AU FIL DE LA FRANCE - 1000 POINTS DE DIFFUSION DU PROGAMME : MERCI !

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#81]
# Video title

AU FIL DE LA FRANCE - 1000 POINTS DE DIFFUSION DU PROGAMME : MERCI !

# URL

https://www.youtube.com/watch?v=l6xhk9ltlCE

# Youtube subtitles language

Français

# Duration

2:36

# URL subtitles

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&ref=watch&lang=fr&v=l6xhk9ltlCE&tab=captions&bl=vmp&ui=hd

**Comment by bayasahra** [comment]
je suis dessus !

**Comment by bayasahra** [comment]
Fini. Validé
Prêt pour correction.

**Comment by Bentham** [comment]
je regarde ça rapidos

**Comment by Bentham** [comment]
Fait et validé !

Chère Bayou, à l'avenir oublie pas qu'on ne met pas d'espace après une apostrophe ! Donc au lieu de "Donc ça, c' est l' événement,", faut avoir "Donc ça, c'est l'événement," :)
C'est pas grand chose mais ça enlève un peu de boulot au second correcteur !

(pas d'espace entre des guillemets et ce qu'elles encadrent, non plus !)

**Comment by bayasahra** [comment]
LOl :) rien d' autre à signaler Monsieur ?? ça sera tout ??? c' est noté ;)

**Comment by Bentham** [comment]
C'est tout ! Pour le reste ta plume est habile et fiable telle un cheval de trait.

**Comment by bayasahra** [comment]
hahahaha <3 :)

**Comment by bayasahra** [comment]
je clos... l' issue est en ligne
