### ISSUE TITLE
[subtitles] [fr] Mélenchon - Il y a un intérêt général humain

### ISSUE THREAD

**Issue by NoelleM** [jlm2017/jlm-video-subtitles#82]
# Video title
Mélenchon - Il y a un intérêt général humain

# URL
https://youtu.be/jj1_Ow5jrlo

# Youtube subtitles language
Français

# Duration
01:23:13

# Subtitles URL
https://www.youtube.com/timedtext_editor?tab=captions&action_mde_edit_form=1&bl=vmp&ui=hd&v=jj1_Ow5jrlo&lang=fr&ref=player

**Comment by Bentham** [comment]
Une heure et demie ça me semble énorme... Il serait plus logique de se concentrer sur les extraits courts mis en ligne.

**Comment by NoelleM** [comment]
C'est mon baptême du feu ! Gare aux éclats...
Je laisse la place. Je digère les explications de Ricyeam ...

**Comment by Ricyeam** [comment]
Oui @Bentham tu as raison, j'ai juste pris une vidéo dont personne ne se serait occupé en meme temps pour expliquer à @NoelleM comment créer une issue etc. 

En meme temps certains extraits courts seront tirés de cette vidéo.

**Comment by Bentham** [comment]
ok vu ! J'avais pas compris :)

**Comment by Kingluther** [comment]
Je profite du "tutoriel" pour poser ma question : si par exemple j'avais le temps de me consacrer à cette retranscription (pas aujourd'hui, mais pourquoi pas à un autre moment), que ce soit sur youtube ou dailymotion, pour pouvoir ajouter les sous-titres, il me faut pouvoir accéder à la vidéo comme si j'en étais l'auteur. Donc comment faire ? (j'ai pas (encore ?) trouvé ça dans le petit tuto mis en ligne)

**Comment by LucileDT** [comment]
@Kingluther pour pouvoir rajouter des sous-titres à une vidéo, il n'y a pas besoin d'en être l'auteur : la chaîne PlaceAuPeuple a activé la rédaction des sous-titres par des tiers.

Pour pouvoir y accéder, tu dois avoir un compte Gmail. Connecté avec celui-ci, tu n'as qu'à cliquer sur l'url **Subtitles URL** présente dans l'issue, et tu seras envoyé vers l'outil de rédaction des sous-titres de la chaîne :)

Si tu as un problème, n'hésite pas à poser tes questions ici : #32

**Comment by Flupignon** [comment]
Sur Youtube, tu lis la vidéo en mode spectateur
-> tu cliques dans paramètre (écrou) en bas à droite   
   -> tu cliques sur 'sous-titres' puis 'ajouter de sous-titres'
      -> un autre onglet s'ouvre
         -> tu cliques sur 'sélectionner une langue' puis 'français'
            -> la page d'édition de sous-titres s'ouvre et tu commences !

**Comment by Kingluther** [comment]
J'ai fait les 8 premières minutes. Je vais tenter de comprendre comment le faire basculer dans la case "sous-titrages" commencés.

**Comment by Kingluther** [comment]
@LucileDT  "Quand vous commencez à écrire des sous-titres, déplacez la carte de la première colonne (sous-titres requis) à la seconde (sous-titres en cours de rédaction)." Euh, oui, mais comment ? Glisser déposer n'a pas l'air de fonctionner, si je clique sur le label ça fonctionne pas non plus

**Comment by Ricyeam** [comment]
sous firefox le glisser deposer fonctionne?

**Comment by LucileDT** [comment]
C'est que @Kingluther n'est pas ajouté aux contributeurs du projet, je viens de le faire, il faut qu'il le confirme (normalement, un mail a été envoyé).

**Comment by LucileDT** [comment]
D'ailleurs @Ricyeam j'en ai profité pour te donner les droits d'admin, tu pourras rajouter des gens désormais :)

**Comment by Kingluther** [comment]
Parfait ! J'ai pu déplacer et changer l'étiquette... il reste 90% du boulot à faire, mais je pourrais pas y retoucher personnellement avant janvier.

**Comment by LucileDT** [comment]
Pas de soucis, IRL avant tout ! Au moins, tu as pu toucher un peu au système et voir comment ça marche :3

**Comment by Albapringe** [comment]
Cette vidéo, visionnée près de 100.000 fois, vient de faire à son tour l'objet de demandes de droits par Radio France. Je m'abstiens de tout commentaire pour rester sage.

**Comment by NoelleM** [comment]
Peux-tu préciser de quelle vidéo il s'agit ? Et me confirmer que je
comprends bien en disant que Radio France veut "nous" demander de l'argent
pour sa diffusion ?

**Comment by Albapringe** [comment]
C'est l'idée, oui. Ou, du moins, demander une autorisation de diffusion. Tu peux suivre le lien mort en haut de cette issue pour le vérifier. Il s'agissait de l'interview de Mélenchon avec Nicolas Demorand dans l'émission Questions Politiques sur France Inter.

**Comment by NoelleM** [comment]
J'hallucine !!!!!!!!!!!!

**Comment by NoelleM** [comment]
Vu la montée en puissance de l'audience (et du visionnage) des vidéos de
JLM, on peut s'attendre à d'autres réclamations de ce genre...

**Comment by clement20** [comment]
Allez je m'y colle! Ma  première! Je commence a 8:37:3

**Comment by Bentham** [comment]
Haha tu vas voir comme c'est long ! Bon courage !

**Comment by clement20** [comment]
fini à 14:08:6 . Effectivement c'est long pour un rendu ... court!

**Comment by clement20** [comment]
Je reprends à 14:08:6

**Comment by Bentham** [comment]
Tu as regardé les vidéos qui montrent comment accélérer la transcription ?

**Comment by clement20** [comment]
Oui j'ai vu une vidéo, avec l'écriture au kilométre puis la segmentation. Mon navigateur Opera m'a joué quelques mauvais tours qui m'ont fait recommencer une bonne partie. Mais ça commence à venir!

**Comment by clement20** [comment]
fini à 22:35:5

**Comment by clement20** [comment]
Reprise à 22:35:5

**Comment by clement20** [comment]
Fini à 33:07:8

**Comment by clement20** [comment]
Reprise à 33:07:8

**Comment by clement20** [comment]
Fini à 45:49:4

**Comment by quidam34** [comment]
Mon équipe peut-elle prendre la relève ?

**Comment by clement20** [comment]
Euh ça dépend pour quoi faire. Il reste encore du sous titrage à produire, donc trop tôt pour la correction.

**Comment by LucileDT** [comment]
@clement20 a été ajouté aux contributeurs !

**Comment by clement20** [comment]
Help, je suis pas trop loin de la fin mais j'ai un problème. Depuis tout à l'heure, lorsque j'appuie sur Entrée pour mettre les ST au bon moment, normalement quand on appuie sur entrée, ça fait coïncider la fin du ST sur le curseur (barre rouge de la timeline) Or au lieu de faire ça, ça me le mets bien plus tard. Je comprends pas ce qui se passe, car jusqu'alors tout marchait à merveille. Quelqu'un pourrait me donner un coup de main? merci.

**Comment by quidam34** [comment]
arf il semble que l'on travaille sur le meme projet . Mon équipe en est sur 46.05 toute le journée merci !

**Comment by Bentham** [comment]
A l'avenir, il faudra vraiment bien se répartir les tâches ! Les anciennes vidéos dont je vous ai fourni la liste sont importantes et pour l'instant personne n'y a encore touché...

**Comment by quidam34** [comment]
ok allez lire mon issue sur la possibilité de travailler a deux sur la même  vidéo en même temps s'il le faut !

**Comment by clement20** [comment]
Pour ma part j'en suis à 1h16.24

**Comment by clement20** [comment]
Du coup on fait quoi? J'en suis presque a la fin, mais j'ai une grosse galere car a chaque fois que jappuie sur entrée pour valider mon ST, au lieu de faire coller la fin du ST a la barre rouge de la time line, il me le mets plus loin. Quelqu'un aurait une idée pour se  dépêtrer de tout cela?

**Comment by clement20** [comment]
Sinon si vous préférez repartir de 45:49.4 et que vous avez pas ce fichu bug, je peux vous fournir l'ensemble des textes, et yaura juste a les coller dans le temps.

**Comment by quidam34** [comment]
Je viens d'y aller voir et nous en somme a 1H15 .  Françoise de mon équipe s'occupe de finir ce jour (info : elle ne fait aucune faute ou presque c'est pratique ! )

**Comment by LucileDT** [comment]
@clement20 je ne sais pas pourquoi tu as ce bug, désolée, je ne peux pas t'aider. Tu as essayé de redémarrer ton navigateur ? Tes modifications sont enregistrées sous former de brouillon, elles restent même si tu recharges la page.

@quidam34 Je pense que nous tous ici apprécierions que vous fassiez attention aux vidéos sur lesquelles vous travailliez avec votre équipe et que vous nous en teniez informé. Nous avons un fonctionnement décrit, et bien que complexe au premier abord, il évite d'avoir des problèmes comme celui que nous rencontrons sur cette vidéo, c'est à dire que plusieurs personnes travaillent en même temps sur les mêmes vidéos, rendant le travail d'un des deux inutile.
Je crois que vous ne comprenez pas que nous n'avons pas moyen de modifier la plupart des outils sur lesquels nous sommes obligés de travailler.
De plus, si vous pouviez faire un effort dans votre expression pour que nous comprenions plus facilement ce que vous dites, ce serait super.
L'issue dont vous parlez est la suivante : #152, ce serait une bonne chose quand vous parlez d'une issue d'en donner le lien, ça facilite la lecture.

**Comment by clement20** [comment]
@LucileDT Oui j'ai changé et redémarré le navigateur, mais rien n'y fait.

**Comment by clement20** [comment]
Terminé.

**Comment by LucileDT** [comment]
@clement20 est-ce que tu as ce problème sur d'autres vidéos ? Et tu es sur quel navigateur/OS ?

**Comment by clement20** [comment]
J'ai pas encore testé sur d'autres vidéos. Mais je n'avais pas le bug au début. Je me demande si c'est pas du au fait d'avoir travaillé à plusieurs en meme temps.
J'ai Windows 7, et en navigateur j'ai testé sous firefox, opera et chrome ; dernières versions, avec le même problème.

**Comment by LucileDT** [comment]
Ah, super étrange... Si jamais ça apparaît sur d'autres vidéos, poke moi et je regarderai avec toi si on ne peut pas trouver une solution.

Clement20 : @LucileDT 
J'ai a nouveau le meme probleme sur une autre vidéo : voici une capture vidéo du probleme :
[bug.zip](https://github.com/jlm2017/jlm-video-subtitles/files/746481/bug.zip)
@

**Comment by desintoxiquezvous** [comment]
première relecture terminée, j'ai enlevé quelques sous titres très court (1 ou 2 sec) quand il y avait des apartés de St Cricq ou Leparmentier qu'on n' avait pas le temps de lire et qui polluaient la bonne compréhension du discours  
5 heures non stop pour relire quand même ... 
fatigué, je suis ....
à vous pour la 2ème relecture

**Comment by desintoxiquezvous** [comment]
juste un petit aparté pour dire que je viens de réaprouver une 2ème fois le travail que je viens de faire (dans youtube) car je n'y avait pas mis mon nom lors de l'envoi, je ne sais pas si ça a de l'importance pour la visibilité de l'administrateur mais bon....

**Comment by LucileDT** [comment]
Merci pour ton travail ! Et non, globalement, ça ne change pas grand chose, en tout cas pas à l'heure actuelle :)

**Comment by DominDamid** [comment]
Je me mets à la deuxième relecture.

**Comment by DominDamid** [comment]
J'ai arrêté à 28:14.

**Comment by quidam34** [comment]
Bonjour ! Mon équipe se propose de terminer cette correction qui traine ! Je télécharge de nouveau le fichier . Toute correction faite sur youtube directement sera effacé . Merci

**Comment by LucileDT** [comment]
@quidam34 Vous est-il possible de mettre le label rouge "Process: Someone is working on this issue" quand vous prenez une vidéo en charge ? Merci d'avance !

**Comment by quidam34** [comment]
je signale que ces sous titre on été déjà publié m'enfin on va faire comme si j'avais rien vu

**Comment by LucileDT** [comment]
@quidam34 Les sous-titres sont visibles en ligne ?

**Concernant ma remarque, je vais essayer d'être un peu plus explicite :**
Est-ce que vous pourriez mettre le label rouge sur l'issue quand vous la choisissez pour en rédiger les sous-titres ? Comme ça, personne ici ne travaillera dessus, et donc ça évitera que quelqu'un commence à travailler mais voit son travail écrasé par le vôtre. Merci d'avance :D

**Comment by houlenn** [comment]
Effectivement, y a des sous-titres en français sous la vidéo, mais ils auraient besoin d'une relecture je crois ...
