### ISSUE TITLE
[subtitles] [ENG] POUR LA LIBERTÉ DU NET ET LA SOUVERAINETÉ NUMÉRIQUE

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#83]
# Video title

POUR LA LIBERTÉ DU NET ET LA SOUVERAINETÉ NUMÉRIQUE

URL

https://www.youtube.com/watch?v=lx7kVw4Byrk

Youtube subtitle language

English

Duration

00:53

URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&action_mde_edit_form=1&lang=en&ui=hd&v=lx7kVw4Byrk&tab=captions&ref=player

**Comment by Ricyeam** [comment]
tu as mis "numerical sovereignty." Ca serait pas plutôt "digital" or "IT" ? numerical en anglais ca se réfere aux nombres plutôt, non?

**Comment by Ricyeam** [comment]
"Microsoft equip" => "Microsoft equips" ? pareil pour install la phrase d'après

**Comment by Ricyeam** [comment]
j'ai laissé numerical mais j'ai changé equip/install => equips installs. Je l'approuve mais on pourra toujours remodifier si necessaire.

**Comment by Flupignon** [comment]
Oui mets 'digital' je sais pas ce qu'il s'est passé dans ma tête :s

**Comment by Ricyeam** [comment]
c'est fait :)

**Comment by Flupignon** [comment]
Parcontre pour 'equip' et 'install' c'est exprès, c'est du "subjonctif", mais je ne suis pas toujours certain de son utilisation 
>>> http://www.educastream.com/imperatif-b2

**Comment by Ricyeam** [comment]
"Je ne suis pas d'accord pour que Microsoft equipe l'armée francaise". En fr c'est du subjonctif en effet.
"I disagree with the fact that MS equip the French army". Je ne connaissais pas cette forme du subjonctif, mais ok. Dans le doute, on peut pas mettre "I disagree for MS to equip the French army" à la place, ou "I disagree with MS equipping the French army"…

**Comment by Ricyeam** [comment]
SInon je te fais confiance et remet sans le s. Tu en penses quoi ?

**Comment by Flupignon** [comment]
Normalement, cette forme s'utilise quand on est pas sûr de l'accomplissement de l'action (possibilité de oui ou de non), et dans ce cas-là, le contrat est apparemment signé... Je sèche un peu, donc ok pour "I disagree with MS equipping the French army".

**Comment by Ricyeam** [comment]
Ok, je change.

**Comment by Ricyeam** [comment]
Done. Je te laisse close les issues qui sont approuvées et que tu as traduites (comme ca tu vois lesquelles ont ete faites aussi).

**Comment by Flupignon** [comment]
Thx
