### ISSUE TITLE
[subtitles] [FR] POUR LA LIBERTÉ DU NET ET LA SOUVERAINETÉ NUMÉRIQUE

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#84]
# Video title

POUR LA LIBERTÉ DU NET ET LA SOUVERAINETÉ NUMÉRIQUE

# URL

https://www.youtube.com/watch?v=lx7kVw4Byrk

# Youtube subtitles language

Français

# Duration

0:53

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=fr&ui=hd&v=lx7kVw4Byrk&ref=watch&action_mde_edit_form=1&tab=captions&bl=vmp

**Comment by bayasahra** [comment]
apparemment un anonyme a fait le premier jet... je vais corriger.
Il y a quelqu'un qui est en train de bosser sur le sous titrage Anglais.

**Comment by Flupignon** [comment]
Désolé @bayasahra  je me suis trompé d'issue !

**Comment by bayasahra** [comment]
validé prêt pour correction 2 
@Flupignon de quoi flupi ??, explique moi tout  ^^

**Comment by Flupignon** [comment]
Non c'est juste que j'ai changé les labels parce que je croyais que c'était l'issue en anglais, mais je les ai remis.

**Comment by Bentham** [comment]
go

**Comment by Bentham** [comment]
Validé ! Et en ligne !
