### ISSUE TITLE
[subtitles] [FR] A bas les paradis fiscaux ! J L Mélenchon au Parlement européen

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#85]
# Video title

A bas les paradis fiscaux ! J L Mélenchon au Parlement européen

# URL

https://www.youtube.com/watch?v=2TbjWeOxQNg&list=PLnAm9o_Xn_3DU-PS1cGkVoMthELDzFVRT&index=19

# Youtube subtitles language

Français

# Duration

1:07

# URL subtitles

https://www.youtube.com/timedtext_editor?ui=hd&action_mde_edit_form=1&bl=vmp&tab=captions&ref=watch&lang=fr&v=2TbjWeOxQNg

**Comment by bayasahra** [comment]
Terminé.
Prêt pour correction.

**Comment by Bentham** [comment]
gooooooo

**Comment by Bentham** [comment]
Done !

**Comment by bayasahra** [comment]
je clos l' issue ;)
