### ISSUE TITLE
[subtitles] [FR] « La cause du terrorisme est dans la guerre et l'argent » - Jean-Luc Mélenchon au Parlement européen

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#86]
# Video title

« La cause du terrorisme est dans la guerre et l'argent » - Jean-Luc Mélenchon au Parlement européen

# URL

https://www.youtube.com/watch?v=A3KM2oOi-Jc&index=15&list=PLnAm9o_Xn_3DU-PS1cGkVoMthELDzFVRT

# Youtube subtitles language

Français

# Duration

3:26

# URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&ref=watch&action_mde_edit_form=1&tab=captions&ui=hd&lang=fr&v=A3KM2oOi-Jc

**Comment by bayasahra** [comment]
Fini. <3 JLM ! 
Prêt pour correction, @Bentham  dans les dernières secondes je ne comprends pas le mot qu'il dit.
@Flupignon ... je sais qu'en anglais tu te débrouilles seul et qu'il y a beaucoup de travail... :'( mais cette vidéo serait super intéressante en sous titrage anglais. Je pense que des opinions comme celle-ci intéresse vraiment le reste du monde.

**Comment by Bentham** [comment]
let's go !

**Comment by Bentham** [comment]
Fait ! Merci Baya pour tes jolies apostrophes !

Le mot de la fin c'est PNR... Je te renvoie à ça : https://fr.wikipedia.org/wiki/Donn%C3%A9es_des_dossiers_passagers

**Comment by bayasahra** [comment]
ahahah t'as vu quand je veux hein :p 
ok je vais yeuter ça <3
