### ISSUE TITLE
[subtitles] [ENG] L'immigration est un exil forcé

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#87]
# Video title

L'immigration est un exil forcé

# URL

https://www.youtube.com/watch?v=79uwqnYPETs

# Youtube subtitle language

English

# Duration

00:37

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=en&ref=player&tab=captions&bl=vmp&forceedit=timedtext&ui=hd&v=79uwqnYPETs&action_mde_edit_form=1

**Comment by Ricyeam** [comment]
Approuvé
