### ISSUE TITLE
[subtitles] [fr] RDLS11 - ALEP, MOYEN-ORIENT, MÉTHANE, INSCRIPTION SUR LES LISTES ÉLECTORALES

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#88]
# Video title

RDLS11 - ALEP, MOYEN-ORIENT, MÉTHANE, INSCRIPTION SUR LES LISTES ÉLECTORALES

# URL

https://www.youtube.com/watch?v=cWbD66BNWc4

# Youtube subtitle language

Français

# Duration

21:33

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=player&bl=vmp&tab=captions&action_mde_edit_form=1&lang=fr&v=cWbD66BNWc4&ui=hd

**Comment by LucileDT** [comment]
Il y a un début de sous-titres déjà réalisés.

**Comment by Bentham** [comment]
Je m'y colle !

**Comment by Bentham** [comment]
Fait. Des sous-titres de grande qualité avaient déjà été ajoutés. J'ai validé, tout est sur Youtube, dossier bouclé !

**Comment by Flupignon** [comment]
Good job! ;)

**Comment by LucileDT** [comment]
Merci @Bentham !
