### ISSUE TITLE
[subtitles] [eng] #RDLS11 - ALEP, MOYEN-ORIENT, MÉTHANE, INSCRIPTION SUR LES LISTES ÉLECTORALES

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#89]
# Video title

RDLS11 - ALEP, MOYEN-ORIENT, MÉTHANE, INSCRIPTION SUR LES LISTES ÉLECTORALES

# URL

https://www.youtube.com/watch?v=cWbD66BNWc4&t=51s

# Youtube subtitle language

Anglais

# Duration

21:33

# URL subtitles

https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&ui=hd&v=cWbD66BNWc4&ref=player&lang=en&tab=captions&bl=vmp

**Comment by Bentham** [comment]
Hello @Flupignon, je vois que tu as laissé le label "Working", tu es encore dessus ?

**Comment by Flupignon** [comment]
7:17 je reprends ce soir. Il tourne plus vite que son ombre le Jean-Luc, c'est dur de suivre le rythme ! x)

**Comment by Flupignon** [comment]
13:13. Plus que 8 min. Au dodo !

**Comment by Flupignon** [comment]
15:32

**Comment by Flupignon** [comment]
18:14. Je devrais avoir terminé ce soir.

**Comment by Flupignon** [comment]
RDLS 11 prête pour vérif ! @Ricyeam @ClaireEV @LucileDT

**Comment by Ricyeam** [comment]
ahahahah j'avais pas relevé 'le swagg compte beaucoup dans cette histoire" :D

**Comment by Ricyeam** [comment]
Approuvée.

**Comment by Flupignon** [comment]
@Ricyeam les sous-titres ne sont plus dispos, tu pourrais essayer de reconfirmer ?

**Comment by LucileDT** [comment]
Sous-titres validés mais pas visibles en ligne :/

**Comment by Flupignon** [comment]
Bizarre...

**Comment by Ricyeam** [comment]
je viens de rererererevalider, et en effet ca n'apparait toujours pas!? Attendons quelques jours pour voir… mais c'est bizarre en effet

**Comment by Flupignon** [comment]
Toujours pas...

**Comment by LucileDT** [comment]
À ce niveau-là, il faudrait peut-être contacter le support YouTube, non ?

**Comment by Flupignon** [comment]
@LucileDT tu as essayé de valider ?

**Comment by LucileDT** [comment]
Ouip, avec deux comptes différents.

**Comment by Flupignon** [comment]
@Ricyeam @LucileDT Je me demandais, j'ai enregistré le fichier de sous-titres pour mettre la vidéo sur la chaîne en anglais. Peut-être que si je l'importe sur la vidéo originale, ça pourrait fonctionner ?

**Comment by LucileDT** [comment]
Essaye toujours. Au pire, si ça marche pas, j'essayerai de contacter le service technique YouTube

**Comment by Flupignon** [comment]
Ok. Je vais faire ça.
Au fait je pense qu'il serait bien d'enregistrer tous les fichiers de sous-titres quand ils sont terminés (je le fais pour les fichiers en anglais) au cas où le compte subirait une attaque de éfénistes dieudolâtres soraliens upéèristes qui n'auraient que ça à faire... Ça fait un peu parano, mais comme les sous-titres sont ouverts... Je pense que ce n'est pas impossible de leur part.

**Comment by Flupignon** [comment]
C'est bon, je vous laisse valider en croisant les doigts !

**Comment by LucileDT** [comment]
@Flupignon Tu as tout à fait raison... Je prendrai le temps de faire ça ce soir pour ceux en français.

**Comment by Flupignon** [comment]
Et tu as pu validé cette RDLS finalement? Il y a la RDLS12 aussi. J'imagine que c'est la période des examens pour vous, vous devez être bien pris...

**Comment by LucileDT** [comment]
Pour ma part, je suis en alternance, et là en période entreprise, donc j'ai moins de temps pour ça :/

Les sous-titres ne sont toujours pas en ligne, je vais contacter le support YouTube.

**Comment by LucileDT** [comment]
Support contacté.

**Comment by Flupignon** [comment]
@Blange1 on arrive pas à valider cette vidéo depuis un moment, tu pourrais essayer de le faire ? Et tu pourras t'occuper des RDLS 12 et 13 (issues #114 et #120) en prio quand tu auras le temps stp ? Merci d'avance

**Comment by Blange1** [comment]
@Flupignon yes pas de soucis pour les RDLS 12 et 13, je m'y colle ce soir ! En revanche j'ai déjà relu et validé cette vidéo hier, avant de me rendre compte qu'elle avait déjà le tag "validé". Donc ça devrait être bon non ?

**Comment by Flupignon** [comment]
C'est bon c'est en ligne ! On savait pas pourquoi mais ça marchait pas.
