### ISSUE TITLE
[communication] Contact with "JLM in English" channel + invitation to this project

### ISSUE THREAD

**Issue by LucileDT** [jlm2017/jlm-video-subtitles#9]
# Date
27 novembre 2016

# Type
Internal

# Media used
Youtube comment + Mail

# Purpose
Ask to the ```JLM in english``` guy to join us on this Github project

# Content
**Youtube comment by @Ricyeam:**
> [Ricyeam] Sorry I've just seen these messages. Join the github project, it helps keeping track and collaborating. We are three people on it, two of us had no clue about github before, so it's alright if you don't know it either. I sent you the link in pm. And the campaign team is aware of it, too !

# Answer
**From @Flupignon to @LucileDT and @Ricyeam:**
> Salut à vous (je fais un peu le mort en ce moment Ricyeam dsl),
> 
> Lucile je m'appelle Arthur Villers (Flupignon sur internet..), je traduis des vidéos de JLM sur sa chaîne Youtube et j'ai créé la chaîne "JLM in english unofficial" qui permet d'avoir les vidéos avec un titre et une image en anglais.
> 
> Je suis diplômé en traduction FR-ANG (niveau master) et actuellement au chômage, ce qui me donne du temps pour les trads (je dois tout de même m'occuper de mon fils et de ma famille...). Je te laisse visiter ma chaîne pour vérifier mon niveau en traduction.
> 
> Je viens de voir le mail de Ricyeam avec un peu de retard. C'est super que nous soyons plusieurs. Je viens de m'inscrire sur le Github, il faut juste que je me familiarise avec l'outil, qui n'a pas l'air très accessible au premier coup d'oeil.
> 
> Je suis en train de terminer la revue #8 et je vais ensuite passer au discours en hommage à Fidel Castro. Je pense que les vidéos à traduire en priorité sont les revues et les vidéos à dimension internationale (sujets comme l'écologie, terrorisme et Plan B)
> 
> Je vais bientôt me recréer un compte Facebook anonyme (mon ancien compte a été bloqué pour cause de prosélytisme...) et recréer un groupe, à moins que l'ancien groupe existe toujours. Ce sera plus simple peut-être pour se partager le travail et pour recruter d'autres bénévoles.
> 
> Arthur

See more details in comments.

**Comment by Ricyeam** [comment]
Comment added on a public discussion thread with the channel
 https://www.youtube.com/channel/UCmEylv0W0nuoueXsnZqeRUg/discussion

> "[Ricyeam] Sorry I've just seen these messages. Join the github project, it helps keeping track and collaborating. We are three people on it, two of us had no clue about github before, so it's alright if you don't know it either. I sent you the link in pm. And the campaign team is aware of it, too !﻿"

**Comment by Ricyeam** [comment]
Réponse par mail à Lucile et moi-même de l'interessé
> "Salut à vous (je fais un peu le mort en ce moment Ricyeam dsl),
> 
> Lucile je m'appelle Arthur Villers (Flupignon sur internet..), je traduis des vidéos de JLM sur sa chaîne Youtube et j'ai créé la chaîne "JLM in english unofficial" qui permet d'avoir les vidéos avec un titre et une image en anglais.
> 
> Je suis diplômé en traduction FR-ANG (niveau master) et actuellement au chômage, ce qui me donne du temps pour les trads (je dois tout de même m'occuper de mon fils et de ma famille...). Je te laisse visiter ma chaîne pour vérifier mon niveau en traduction.
> 
> Je viens de voir le mail de Ricyeam avec un peu de retard. C'est super que nous soyons plusieurs. Je viens de m'inscrire sur le Github, il faut juste que je me familiarise avec l'outil, qui n'a pas l'air très accessible au premier coup d'oeil.
> 
> Je suis en train de terminer la revue #8 et je vais ensuite passer au discours en hommage à Fidel Castro. Je pense que les vidéos à traduire en priorité sont les revues et les vidéos à dimension internationale (sujets comme l'écologie, terrorisme et Plan B)
> 
> Je vais bientôt me recréer un compte Facebook anonyme (mon ancien compte a été bloqué pour cause de prosélytisme...) et recréer un groupe, à moins que l'ancien groupe existe toujours. Ce sera plus simple peut-être pour se partager le travail et pour recruter d'autres bénévoles.
> 
> Arthur"

**Comment by Ricyeam** [comment]
Réponse à Arthur

> "Salut Arthur,
> 
> merci pour ta réponse. Fais nous savoir ton login sur guthub pour que lucile puisse t'ajouter au projet.
> 
> L'outil est au final assez simple à utiliser, ne t'inquiete pas. Par contre pour l'instant on s'est concentré sur les videos officielles, on etait tous les 3 d'accord que c'etait le plus important. On pourra en discuter et faire evoluer, toute perspective est la bienvenue !
> 
> Commence par lire le readme, et si tu as des questions j'ai recrée un autre groupe sur facebook, des que tu as un compte ajoute moi de nouveau (https://www.facebook.com/Ricyeam.Telmoec) et je t'ajouterai sur le groupe. Il m'etait impossible d'ajouter des personnes à l'ancien groupe, n'étant pas admin, donc j'en ai fait un autre.
> 
> C'est vraiment bien qu'on s'organise comme ca, tu verras Github va vraiment permettre de tenir informé tout le monde du progrès fait, et vu que l'equipe de campagne utilise l'outil aussi ils seront capables de voir notre avancement et de faire les validations plus rapidement.
> 
> Merci pour ton boulot, et à bientot.
> 
> Aymeric"

**Comment by Ricyeam** [comment]
Arthur => Ricyeam, par mail

> "Je l'ai lu, il faut juste un peu de pratique pour que ça rentre.
> 
> Je me suis enregistré en tant que Flupignon, et je vous 'follow' déjà ;)"

**Comment by Ricyeam** [comment]
Arthur => Ricyeam, par mail

> "Je me suis permis de faire des doublons parce je pense qu'un public non-francophone ne cliquera pas sur une vidéo dont le titre et l'image (la "miniature youtube") sont en français s'il ne sait pas qu'il y a des sous-titres.
En revanche je conçois que ça fasse moins monter les vues, c'est pour ça que sa chaîne est toujours promue dans les écrans de fin de chaque vidéo et dans les descriptions.
> 
> Enfin je ne vais pas me faire le compte FB ce soir, je vais juste un peu avancer sur la vidéo et me coucher. Je devrais avoir fini demain.
> 
> Je vous tiens au courant pour la suite. Tu pourrais peut-être me briefer demain ?
> 
> Bonne nuit"

**Comment by Ricyeam** [comment]
Ricyeam => Arthur, par mail

> "ok. Je comprends pour les doublons, pas de souci, on en avait déjà discuté ! Et je pense que ton argument est bon aussi :)"

**Comment by bayasahra** [comment]
En tout les cas sois le bienvenu Arthur :)
pour les non francophones, il faudrait peut être juste demander au staff de Mélenchon de mettre en avant sur la page d'accueil de la chaine officielle youtube un icone ou une phrase qui prévient qu'un sous titrage est disponible ( peut être aussi un petit icone pour les malentendants) ?

**Comment by LucileDT** [comment]
Pour le joindre, c'est @Flupignon !

Et ses réponses venaient du mail que j'avais envoyé hier : 
@LucileDT => @Flupignon, par mail : 
> Salut !
> 
> Enchantée :D Pas de soucis pour la famille, j'ai le même problème de mon côté (je suis en alternance et j'ai un gamin, je vois le genre).
> 
> J'avais vu ton commentaire et du coup j'étais au courant pour ta chaîne. Je pense qu'il faudrait éviter de créer des doublons aux vidéos de JLM, principalement parce que si on arrive à sous-titrer ses vidéos sur sa chaîne, ça lui fera des vues, ce dont il a besoin (encore trop de suggestions de vidéos Youtube pour Eric Zemmour et pas assez pour JLM à mon goût). Je ne sais pas si tu as vu, mais suite à mon contact, l'équipe de JLM a validé certains de tes sous-titres (que j'ai relu, il y avait quelques fautes de frappe). J'espère que ça te fait plaisir !
> 
> Niveau niveau d'anglais, justement, comme j'ai relu ce que tu avais fait, pas besoin de regarder ta chaîne ^_^ C'est vraiment bien ! (je suis plutôt nulle en expression en anglais, malheureusement, mais j'ai une bonne compréhension).
> 
> Pour le Github, si tu veux, je peux te refaire une intro rapide, comme avec Ricyeam et Baya sur Facebook ce soir, par mail ou autre (ce que tu préfères).
Je pense aussi que les revues sont ce qu'il y a de plus "urgent" à sous-titrer. Il faudrait aussi voir à le faire pour les extraits de revues quand ils sont mis en ligne.
> 
> Tiens-nous au courant pour Facebook, par contre j'ai bien peur que tu ne doives valider ton compte avec un numéro de téléphone, désormais.
