### ISSUE TITLE
[subtitles] [FR] PAS VU À LA TÉLÉ #8 : LA PAUVRETÉ - CHRISTOPHE ROBERT - FONDATION ABBÉ PIERRE

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#91]
# Video title

PAS VU À LA TÉLÉ #8 : LA PAUVRETÉ - CHRISTOPHE ROBERT - FONDATION ABBÉ PIERRE

# URL

https://www.youtube.com/watch?v=bdcMbUVfWRA&t=2s

# Youtube subtitles language

Français

# Duration

1:03:35

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=watch&action_mde_edit_form=1&bl=vmp&ui=hd&tab=captions&v=bdcMbUVfWRA&lang=fr

**Comment by bayasahra** [comment]
un anonyme a commencé le sous titrage jusqu'à 11:00.5

**Comment by LVAI** [comment]
Bonjour, je ne peux pas éditer cette issue. Je pense que c'est parce que je ne suis pas encore contributrice :)
Mais j'ajoute un commentaire pour indiquer que j'ai ajouté les sous-titres jusqu'à 12:58:03.
Je continuerai sans doute ce soir ou vendredi.
C'est ma première expérience, je ne connaissais pas du tout : fichtre que c'est long !
Je suis d'autant plus reconnaissante à tous ceux qui sous-titrent leur vidéos :)

**Comment by Bentham** [comment]
Hé oui c'est très long... S'il y a des gens intéressés je pourrais faire une petite vidéo pour montrer comment gagner en vitesse quand on écrit des sous-titres ! Y'a quelques petites astuces à comprendre :)

**Comment by Albapringe** [comment]
Ah, ben oui, je suis preneur. Parce que pour les vidéos très longues, le gain est susceptible d'être colossal. Sans parler du fait que ça peut aider tous les nouveaux arrivants à adopter une technique commune, donc tout bénéf.

**Comment by Bentham** [comment]
C'est par ici @Albapringe : #129

**Comment by LVAI** [comment]
J'ai ajouté et envoyé les sous-titres jusqu'à 15:11.3

**Comment by LucileDT** [comment]
@LVAI est désomais ajouté.e aux contributeurs du projet :D

**Comment by LVAI** [comment]
Ajout jusqu'à 19:25.2. Je continue demain (donc je laisse les tags).
Fiou ! Des heures de boulot et je n'ai sous-titré que 8 minutes de discours !
C'est un vrai métier dîtes-moi.

**Comment by Bentham** [comment]
Je suis dessus pour la vidéo de démonstration

**Comment by LVAI** [comment]
Haan c'est moche de piquer les vidéos des autres et de pas mettre le label XD
J'attends du coup. Dis-moi quand c'est bon stp.

**Comment by Bentham** [comment]
Haaa tu es dessus ? J'avais vu que le "Someone is working on this issue" avait été ajouté il y a treize heures, donc je pensais à une erreur. En fait on ne met ce label que quand quelqu'un est réellement en train de travailler dessus - quand une rédaction de sous-titres est en cours !

**Comment by Bentham** [comment]
Tu as fait des modifications entre temps ?

**Comment by LVAI** [comment]
Oui c'est bien comme ça que j'avais compris (ouf !). Hier du coup je l'ai mis puis enlevé. Je l'ai remis ce matin mais ça a pas enregistré apparemment. Bizarre...
J'ai fait des modifs sur les anciens sous-titres. Je sais pas s'il y aura conflit ou pas entre nos modifs du coup.
Pour l'instant j'ai rien soumis.

**Comment by Bentham** [comment]
Ok je libère la chose !

**Comment by LVAI** [comment]
Sous-titres jusqu'à 27:56.8

**Comment by Vimogo** [comment]
Bon allez je m'y mets.

**Comment by Bentham** [comment]
Tu es increvable !

**Comment by Vimogo** [comment]
Bah j'ai du temps de libre. C'est pas la terminale S qui va me voler ma vie. ^^

**Comment by Vimogo** [comment]
Bon allez, là je commence à faire une faute de frappe tous les trois mots à cause de la fatigue, il est temps pour moi de me ressourcer pour mieux reprendre notre lutte plus tard. J'ai avancé les sous-titres jusque 35:10.6

**Comment by Bentham** [comment]
Je m'y mets.

**Comment by Bentham** [comment]
Ah, mais je peux pas m'y mettre, @Vimogo il faut que tu envoies tes modifications (via le bouton du haut "envoyer pour examen"), sinon je ne peux pas les voir... Là pour moi c'est sous-titré jusqu'à 27:52

**Comment by LVAI** [comment]
J'allais m'y mettre aussi :)

**Comment by Vimogo** [comment]
Pardon, je mets ça en ligne dès que mon ordinateur est allumé.

**Comment by Vimogo** [comment]
C'est fait. Encore pardon.

**Comment by LVAI** [comment]
@Bentham, @Vimogo, vous n'êtes pas dessus, je peux m'y mettre ?

**Comment by Bentham** [comment]
Libre à toi !

**Comment by LVAI** [comment]
@Vimogo , tu as écrit (je crois que c'est toi cette nuit ^^) plusieurs points d'interrogation :
"Et alors on fera des économies sur la durée. Sur la question scolaire aussi, sur la question de santé (?) etc."
"Mais, le prix est... Si on faisait ce total à chaque fois, en euros (?) là ça coûte tant en retard scolaire, ..."
C'est parce que tu n'es pas sûr de ce qui est dit ? Ou tu ne trouves pas ça clair ?
Le 1er ça me parait bon (en cohérent avec les parties précédentes que j'ai sous-titrées). Le 2è j'ai corrigé "alors là".

Et sinon, j'ai vu que tu faisais des blocs de sous-titres assez longs. Je sais pas si vous avez des habitudes par rapports à ça comme je suis nouvelles. Est-ce que c'est voulu ? Ou plus simple ?
Pour ma part, les sous-titres courts me paraissent plus simples à lire. Un sous-titre long, tu sais pas trop combien de temps il va rester, tu as peur de ne pas avoir le temps de le lire alors tu te dépêches et du coup tu n'as pas forcément le temps de bien comprendre ce que tu lis. Ici ce serait dommage ^^. Je trouve que les sous-titres courts détendent le lecteur. Mais ce n'est qu'un point de vue...

Je me suis permise de reprendre ta partie du coup. J'ai découpé un peu les sous-titres et j'ai corrigé deux/trois fautes. Rien de bien grave, des fautes de fatigue que je fais moi-même souvent ^^

**Comment by Albapringe** [comment]
En fait, @LVAI, étant moi-même malentendant, je pense que c'est le contraire. Les blocs de sous-titres longs sont moins fatigants, car il y a toujours des moments de pause dans un discours, ce qui laisse plus de temps pour lire les sous-titres de la séquence en cours. Le sous-titrage court est très dynamique, et pour peu qu'il ne soit pas très bien calé, la succession rapide voire désynchronisation des paroles/sous-titres est perturbante. De même, l'omission d'un trop grand nombre de mots pour celui qui écoute et lit en même temps est gênante.

C'est pourquoi je veille à faire toujours des blocs aussi longs que possible, de trois lignes (maxi) de sous-titrage quand on les édite (ce qui donne un rendu de 2 lignes de sous-titre sur la vidéo à l'échelle réelle, ce qui est normalement le maximum toléré par convention)
Je veille aussi à être le plus fidèle possible au discours, quitte à utiliser force de ponctuation.
Enfin, l'ancrage des blocs doit commencer un peu avant le début du discours lui même, le temps que le sous-titre lu arrive jusqu'au cerveau en même temps que la parole ^^

**Comment by LVAI** [comment]
Merci @Albapringe !
Je suis très contente d'avoir cet autre point de vue que je ne connaissais pas !

Je vais faire attention à laisser des blocs relativement longs du coup. Mais pas plus de deux / trois lignes en édition (soit deux lignes sur la vidéo).

Je ne sais pas s'il y a une équipe de correcteurs qui est différente des contributeurs ou si tout le monde peut tout faire :) mais au moment de la correction, ce serait bien (si ce n'est déjà fait) de lister ces pratiques. Comme ça on pourra essayer de les anticiper autant que possible dès la rédaction :)

**Comment by Vimogo** [comment]
À priori toutle monde peut tout fait @LVAI. Les (?) que j'ai placé symbolisent bien une incertitude quand à la transcription. Étant également légèrement malentendant, j'ai l'habitude de regarder la vidéo avec les sous-titres mais à ne me soucier d'eux que si je n'arrive pas à comprendre certains mots. Dans ces cas-là je préfère en avoir de plutôt longs pour qu'ils ne soient pas terminés en prenant en compte mon temps de réaction avant de les regarder. Mais je reconnais avoir quelques difficultés à découper suffisamment les longues phrases pour l'instant, j'utilise personnellement autant que possible un standard de quatre lignes à l'éditeur.

**Comment by Albapringe** [comment]
@Vimogo 4 lignes en édition, c'est un peu long, en effet, car le rendu final est nécessairement de 3 lignes. Par convention, les sous-titres ne doivent pas s'étirer au final sur plus de deux lignes.
N'aie pas peur de couper les phrases après une virgule, (ou une micro-pause du discours) par exemple. Dès lors que le point de séparation des blocs juxtaposés correspond au bon moment du discours, ça passe très bien.

**Comment by LVAI** [comment]
J'ai sous-titré jusqu'à 38:24.4.

Si jamais vous remarquez des trucs bizarres avec mon sous-titrage, n'hésitez pas à me le dire pour que je m'améliore !!
Même sur un exemple précis "ce bloc est un peu court" ou "la lecture est plus agréable si tu coupes ici plutôt que là", etc.

Un petit doute à 36:16. JLM dit "les gens se retrouvent avec des frais d'entretien qu'ils n'arrivent plus à assumer et ils s'appauvrissent (?) de ce truc." Si vous arrivez à mieux comprendre que moi...
Pareil à 38:01, JLM dit "les taux de chômage n'étaient pas ce qu'ils sont aujourd'hui, (?) les perdus de vus sociaux"
Et juste après (38:07) "ils ne sont plus indemnisés pour le chômage (je rappelle (?) que 50% des gens ne sont pas indemnisés pour le chômage)".

Autre question, est-ce qu'il y a des habitudes concernant l'écriture des nombres en chiffres ou en lettres - et des unités en lettre ou en symbole - pour un meilleur confort de lecture ?
En ce qui me concerne, j'ai plutôt tendance à écrire les gros nombres en lettres (un million / ou 1 million), les petits chiffres en chiffres s'il représente vraiment une quantité (1 000 €, 10 ans) et en lettres lorsqu'ils sont intégré au discours (deux à trois fois). J'écris les unités en symboles parce que je trouve ça plus lisible (m², km, €). Mais encore une fois vos avis sont plus que bienvenus !

**Comment by LucileDT** [comment]
J'ai les mêmes standards que toi au niveau des chiffres, nombres et symboles :)

**Comment by Vimogo** [comment]
Je reprends !

**Comment by Vimogo** [comment]
Bon je suis fatigué, je vais me coucher. Les sous-titres en sont à 41:01.8

**Comment by LVAI** [comment]
Tu es trop rapide !

**Comment by Vimogo** [comment]
Bah je suis les conseils de Bentham, je laisse la vidéo en vidéo en vitesse 1.25 ou 1.5 lors de l'écriture, et en 2 lors d'une relecture, et je tape plutôt vite, voilà tout ^^ Je fais du 5-6 minutes par heure d'écriture en moyenne.

**Comment by Vimogo** [comment]
Par contre j'observe que le label [Process: Paused] a disparu. Est-ce volontaire ?

**Comment by Bentham** [comment]
Oui il faisait doublon avec le label "Someone is working on this issue". Le label "Process: Paused" était le premier label qu'on a utilisé, et puis on a vite décidé de l'abandonner parce qu'il était ambigu.

**Comment by Albapringe** [comment]
Oui, il a été supprimé. Le label "Someone is working" fait foi.

Edit : grillé ! Chacun son tour :)

**Comment by LVAI** [comment]
Sous-titres ajoutés jusqu'à 50:44.9.
Je me suis dit "je sous-titre jusqu'à 11h" puis au moment où je pensais arrêter je me suis dit "Aller ! Il reste que 10 minutes de vidéo !" (tout en me rappelant que 10 min de vidéo ça ne prend pas 10 minutes à sous-titrer, loin s'en faut !) et j'ai réalisé qu'il était déjà midi XD

**Comment by Bentham** [comment]
Je m'occupe de la fin !

**Comment by Bentham** [comment]
Enfin terminée !

**Comment by DominDamid** [comment]
Bonsoir !
  Je me mets à la correction des sous-titres... je ne peux pas changer le label car nouvelle, donc non contributrice ;)

**Comment by Bentham** [comment]
Tu viens d'être ajoutée ! Bienvenue ici, et n'hésite pas à te présenter sur la page idoine : https://github.com/jlm2017/jlm-video-subtitles/issues/17

**Comment by DominDamid** [comment]
Ok merci beaucoup !

**Comment by DominDamid** [comment]
Fini !
Alors par contre je ne sais pas si je dois "approuver" les sous-titres sur YouTube, je ne voudrais pas bloquer les modifications ultérieures, mais là je ne sais pas si mes modifications sont enregistrées...
Autre chose : je ne me suis pas permis de changer la façon de sous-titrer, donc j'ai laissé les "bah" et les "euh" qui avaient été écrits ; est-ce que j'aurais dû les enlever ?
Pareil en ce qui concerne la longueur des sous-titres ; certains s'étalent sur quatre lignes ; j'en ai coupé certains mais pas tous : est-ce que ce travail se fait à cette étape ou lors de la dernière relecture ?
Ce qui est complètement terminé en tout cas c'est les erreurs de transcription et d'orthographe (normalement !).

**Comment by Bentham** [comment]
Oui, quoi qu'il en soit il faut toujours que tu valides tes corrections avec le bouton bleu en haut ! ("envoyer pour examen" ou "approuver")
Si tu ne le fais pas, tes modifications ne seront enregistrées qu'en brouillon local et personne d'autre ne pourra les voir.
Pour les "euh" et les "bah", ils sont inutiles, mais ils ne dérangent pas non plus et ça donne une idée du ton à l'oral. C'est au libre choix du correcteur.
Pour ce qui est de la longueur des sous-titres, des sous-titres longs ne sont pas dérangeants, et en réalité il rendent la lecture plus simple pour les malentendants.

Bravo pour cette première correction !

**Comment by DominDamid** [comment]
Ok, merci pour tes réponses aussi rapides.
Pour la longueur des sous-titres cela me posait question du fait qu'ils cachent une partie importante de l'image, surtout lors des gros plans.
J'ai bien approuvé les sous-titres du coup. Par contre il me semble que je n'ai pas encore la main pour modifier les labels, ou peut-être que je n'ai pas bien compris la manœuvre.

**Comment by Bentham** [comment]
Normalement tu as reçu une notification. Si tu l'as perdue, tu peux te rendre sur :
https://github.com/jlm2017/jlm-video-subtitles/invitations

**Comment by DominDamid** [comment]
Merci, c'est bon maintenant.
Bonne nuit à toi !

**Comment by LucileDT** [comment]
@DominDamid Je te vénère car tu as lu la documentation <3 Bienvenue et merci !

**Comment by quidam34** [comment]
Pour notre équipe c'est bon maintenant !   sauf la longueur des sous titre pas plus de trois lignes à l'avenir non ?

**Comment by LVAI** [comment]
Moi je suis même partisane du 2 lignes max :smile: je dépasse parfois un peu quand ça conserve le sens de la phrase mais j'évite.
Mais ça n'engage que moi et je sais qu'on est en désaccord sur le sujet :smile:

**Comment by LucileDT** [comment]
@quidam34 nous laissons cette liberté au sous-titreur. Nous n'avons pas assez de retours sur la question pour juger de la bonne pratique à adopter (je pense que si une vingtaine de malentendants/Sourds nous donnaient leur avis, nous pourrions en choisir une, tant que ce n'est pas le cas, nous ne pouvons pas nous prononcer).

**Comment by quidam34** [comment]
Je disais cela car j'avais vu le message d'un sourd qui disait que c'était mieux surtrois ligne la dernière fois.  Mon équipe s'occupe des deux corrections .

**Comment by quidam34** [comment]
la vidéo ayant été corrigé ! qui pourrait la valider ?

**Comment by desintoxiquezvous** [comment]
bon, je commence la 2eme relecture

**Comment by Bentham** [comment]
La vidéo était propre, et je ne sais pas qui est venu foutre le bazar dans les containers... Bon...

**Comment by desintoxiquezvous** [comment]
bon , j'en suis presque à la fin (mn 58) , que doit je faire ensuite dans Youtube dois je envoyer "approuver"ou "non terminée" ?

**Comment by Bentham** [comment]
Approuver

**Comment by desintoxiquezvous** [comment]
ok 
est ce que par hasard tu aurais la fin du texte (le bon hein, dans l'ordre en mode texte) à partir de 58 ça me permettrais de faire du copier coller dans les containers  parce ce que sur la fin c'est vraiment la cata , sinon tant pis je continue à réécrire et donc j'approuve à la fin

**Comment by Bentham** [comment]
Tu peux me donner quelques exemples d'erreurs pour que je voie ce qui te pose problème ?

**Comment by desintoxiquezvous** [comment]
j'en suis à la mn 58 va voir vers 59  , sur un conteneur sur 3 ou 4 le texte n'est pas celui qui est dit mais un autre plus loin ou avant

**Comment by Bentham** [comment]
Oui ok. Je sais pas qui a fait ça. Je n'ai pas de fichier malheureusement, il faut tout rétablir à la main.

**Comment by desintoxiquezvous** [comment]
bon, j'en suis à 59 je finis bientôt ,je te préviens dès que j'approuve , pourra tu le remettre à la bonne place avec le bon statut ensuite pour une relecture appropriée ça m'évitera de le mettre au mauvais endroit comme c'est une procédure plutôt inhabituelle

**Comment by quidam34** [comment]
Eh ho les gens cette vidéo il y a déjà une journée j'ai dit que c'était finit relecture et tout ! 


je me site "la vidéo ayant été corrigé ! qui pourrait la valider ?"    et quand je dis cela c'est que cela a été fait deux fois !

**Comment by desintoxiquezvous** [comment]
oui et bien si tu l'avait revue tu aurais vu qu'a partir de mn 42 un conteneur sur 3 ou 4 n'est pas à sa place , le texte ne correspond pas à ce qui est dit ,c'est un vrai bordel,
j'etais parti pour une relecture finale et je me retrouve à retoucher tous les textes depuis 4 h , 
j'en suis à 1 h 00 , c'est presque fini et bon pour une nouvelle lecture .......

**Comment by Bentham** [comment]
@quidam34 Il ne fallait pas changer les labels. Vu l'état des sous-titres, une nouvelle correction va être nécessaire.

**Comment by desintoxiquezvous** [comment]
@Bentham  je viens de finir a l'instant et j'ai donc envoyé "approuver"
merci de remettre a la la bonne place......

**Comment by Bentham** [comment]
c'est bon, c'est en attente de l'ultime correction.

**Comment by quidam34** [comment]
cela consiste en quoi l'ultime correction ? 

@Bentham vous me marquer il y a douze heures "@quidam34 Il ne fallait pas changer les labels. Vu l'état des sous-titres, une nouvelle correction va être nécessaire." 

Nota : "désintoxiquezvous" vous répond il y a aussi douze heures "@Bentham je viens de finir a l'instant et j'ai donc envoyé "approuver"

Vu qu'il a fait cela aussi dans la douzième heure cela devait pas être si grave que cela non ?  ;-) 

Enfin l'essentiel soit que vous soyez arrivé au bout d'une chose qui était déjà terminé. ;-)

jean-michel le toxique...

**Comment by desintoxiquezvous** [comment]
@quidam34 @Bentham jusqu'a 42 mn  tout était. ok, à partir de la mn 42 ça m'a pris 5 h pour tout retaper , 1 container sur 3 n'était pas à sa place, décalé ou texte manquant ou en doublon sur plusieurs containers , je maintiens que personne n'a vraiment relu correctement cette partie , ce n'est pas possible et donc ce boulot n'était pas fini 
je ne suis peut être pas un rapide mais je vérifie consciencieusement ce que je fais

**Comment by LucileDT** [comment]
De plus, on relit toujours deux fois car YouTube nous y oblige, c'est la procédure.

**Comment by quidam34** [comment]
49.36 : corrigé chèreté par cherté
52.10 ; Rroms par Roms
53,31 pareils : Rroms (deux fois) 
54.38 encore : Rroms
54:44.4  toujours : Rrom. 
1:01:26  precision ==> précision     voilà bien que déjà publié j'ai fait les changements reste plus qu'a valider ...  mon équipe le fera je bouche se sujet dans les publier .

**Comment by quidam34** [comment]
c'est bon !

**Comment by LucileDT** [comment]
Impeccable :thumbsup:

**Comment by Flupignon** [comment]
"Rrom" est correct voire préférable... > http://www.cafebabel.fr/societe/article/rom-ou-rrom.html

**Comment by DominDamid** [comment]
Merci @Flupignon , tu m'évites de rechercher une source... J'étais à l'origine de cette correction de Rom en Rrom car j'avais eu la même info que toi d'une autre source, très sérieuse aussi.
