### ISSUE TITLE
[subtitles] [eng] A bas les paradis fiscaux ! J L Mélenchon au Parlement européen

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#92]
# Video title

A bas les paradis fiscaux ! J L Mélenchon au Parlement européen

# URL

https://www.youtube.com/watch?v=2TbjWeOxQNg&t=4s

# Youtube subtitle language

Anglais

# Duration

1:08

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=en&v=2TbjWeOxQNg&tab=captions&ref=player&action_mde_edit_form=1&ui=hd&bl=vmp

**Comment by Ricyeam** [comment]
Approved
