### ISSUE TITLE
[subtitles] [eng] « La cause du terrorisme est dans la guerre et l'argent » - Jean-Luc Mélenchon au Parlement européen

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#93]
# Video title

« La cause du terrorisme est dans la guerre et l'argent » - Jean-Luc Mélenchon au Parlement européen

# URL

https://www.youtube.com/watch?v=A3KM2oOi-Jc&t=5s

# Youtube subtitle language

Anglais

# Duration

3:26

# URL subtitles

https://www.youtube.com/timedtext_editor?tab=captions&ref=player&lang=en&v=A3KM2oOi-Jc&ui=hd&action_mde_edit_form=1&bl=vmp

**Comment by Flupignon** [comment]
Done!

**Comment by Ricyeam** [comment]
review done and approved
