### ISSUE TITLE
[subtitles] [eng] Syrie : un risque de guerre mondiale

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#94]
# Video title

Syrie : un risque de guerre mondiale

# URL

https://www.youtube.com/watch?v=NuXazR4EUnI

# Youtube subtitle language

Anglais

# Duration

4:14

# URL subtitles

https://www.youtube.com/timedtext_editor?bl=vmp&lang=en&ref=player&ui=hd&action_mde_edit_form=1&v=NuXazR4EUnI&tab=captions

**Comment by Flupignon** [comment]
1:10

**Comment by Flupignon** [comment]
Terminé, à toi de jouer @Ricyeam !

**Comment by Ricyeam** [comment]
Done! comme dhab super boulot @Flupignon , juste une ou deux fautes de frappe mais rien d'autre.

**Comment by Flupignon** [comment]
Merci ;)
