### ISSUE TITLE
[subtitles] [fr] PRÊTS : LES BANQUES DEVRAIENT AVOIR HONTE

### ISSUE THREAD

**Issue by Bentham** [jlm2017/jlm-video-subtitles#95]
# Video title
PRÊTS : LES BANQUES DEVRAIENT AVOIR HONTE

# URL
https://www.youtube.com/watch?v=f-nLhMheC90

# Youtube subtitles language
Français

# Duration
02:01

# Subtitles URL
https://www.youtube.com/timedtext_editor?ref=player&v=f-nLhMheC90&bl=vmp&lang=fr&action_mde_edit_form=1&tab=captions&ui=hd

**Comment by Bentham** [comment]
Je m'y mets !

**Comment by Bentham** [comment]
Fait :)

**Comment by bayasahra** [comment]
je suis dessus.

**Comment by bayasahra** [comment]
validé

**Comment by bayasahra** [comment]
en ligne d'ailleurs je clos l'issue
