### ISSUE TITLE
[subtitles] [FR] Syrie : un risque de guerre mondiale

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#96]
# Video title

Syrie : un risque de guerre mondiale

# URL

https://www.youtube.com/watch?v=NuXazR4EUnI

# Youtube subtitle language

Français

# Duration

4:14

# URL subtitles

https://www.youtube.com/timedtext_editor?v=NuXazR4EUnI&tab=captions&lang=fr&ui=hd&action_mde_edit_form=1&ref=player&bl=vmp

**Comment by Flupignon** [comment]
Je viens de terminer la version en anglais, j'ouvre celle en français parce qu'en ce moment, c'est un sujet sur lequel pas mal de gens vont se pencher. Je le laisse pour quelqu'un d'autre comme je me concentre plus sur l'anglais. Sauf si vous êtes sur autre chose...

**Comment by LucileDT** [comment]
Pas de soucis, il y aura probablement quelqu'un pour s'en occuper :)

**Comment by Ricyeam** [comment]
En effet, vidéo importante en ce moment. Pas plus tard que ce matin, un de mes contacts facebook qui il y a qq semaines ne disait pas vraiment du bien de jlm et du programme, a commenté ce matin 

> "J'ai fondamentalement un problème avec son approche de la Russie & de la Syrie => du reste de sa géopolitique. Pour le reste, ça me semble plutôt intéressant, au moins sur les sujets abordés."

On progresse on progresse :p 
(le gars en question a un esprit critique assez développé, et en général il s'informe avant de parler)

**Comment by Flupignon** [comment]
OK pour vérif !

**Comment by Albapringe** [comment]
Prêt pour dernière vérification, c'est rapide.

**Comment by Bentham** [comment]
Allez je fais ça en vitesse.

**Comment by Albapringe** [comment]
Wouah, plus vite que mon ombre ! :)

En passant, @Bentham est-ce que tu serais prêt à rejoindre le chat ou pas ?

**Comment by Bentham** [comment]
Corrigé, approuvé, publié ! 

Voilà les petites corrections, pour les curieux :
"al-Nosra" à la place de "Al Nosra"
"on est censés les avoir frappés" avec "censés" et "frappés" au pluriel
"Bachar el-Assad" au lieu de "Bachar El-Assad"

------
@Albapringe pour ce qui est du chat, c'est pas trop mon truc, j'ai toujours l'impression de perdre un peu mon temps quand je traîne sur ce genre de choses :) Je préfère aider ici, ça me paraît plus constructif. Mais j'irai sans doute faire un tour un de ces quatre !

**Comment by Albapringe** [comment]
Pas de souci. :)

Bon, les sous-titres sont publiés, il n'y a plus qu'à clore cette issue.
