### ISSUE TITLE
[Subtitles] [FR] MÉLENCHON - RÉUNION PUBLIQUE À CHAMBÉRY

### ISSUE THREAD

**Issue by Albapringe** [jlm2017/jlm-video-subtitles#97]
# Video title
MÉLENCHON - RÉUNION PUBLIQUE À CHAMBÉRY

# URL
https://www.youtube.com/watch?v=DH3HuoOh37w

# Youtube subtitles language
Français

# Duration
1:52:54

# Subtitles URL
https://www.youtube.com/timedtext_editor?v=DH3HuoOh37w&lang=fr&action_mde_edit_form=1&ref=player&bl=vmp&tab=captions

**Comment by Albapringe** [comment]
J'ai créé cette issue compte tenu du fait que j'avais déjà commencé les sous-titrages. Par contre, je n'ai pas les moyens d'y affecter des labels comme prévu dans les tutos. Est-ce lié à mon statut qui n'est pas encore "contributeur" ?

**Comment by Ricyeam** [comment]
Je viens de t'ajouter, tu as dû recevoir un mail je pense.

**Comment by Albapringe** [comment]
Super ! Merci. Je vais pouvoir continuer le job :)

**Comment by Albapringe** [comment]
J'ai terminé le sous-titrage, il manque cependant 3 courts passages que je n'ai pas réussi à traiter à cause d'un bruit de fond trop important (vidéoprojections durant la phase d'introduction) : 
- 5:53 à 6:27
- 7:07 à 8:37
- 12:26 à 13:41

Si une bonne âme se sent assez courageuse pour le faire, elle est la bienvenue :p

**Comment by LucileDT** [comment]
Il faut que tu cliques sur "Envoyer pour examen..." en haut à droite, juste au dessus de la pastille de la vidéo : 
![capture du 2016-12-25 20 13 37](https://cloud.githubusercontent.com/assets/23707217/21472514/a89dc008-cade-11e6-8366-9562383a0538.png)


Tant que tu ne l'as pas fait, nous n'aurons pas moyen d'accéder à ton travail :(

**Comment by Albapringe** [comment]
Merci pour l'info. Je viens de le faire.

**Comment by LucileDT** [comment]
Je suis en train de regarder pour les passages dont tu parles :)

**Comment by bayasahra** [comment]
je suis sur la première correction !

**Comment by LucileDT** [comment]
@bayasahra j'avais pas fini :o

**Comment by bayasahra** [comment]
LOL j'ai cru que t'avais oublié d'enlever .... ça faisait 16 heures lol !!! t'as pas dormi ??? et comme tu as pas parler de correction juste de regarder les passages qu'il avait pas compris... 16 h ça fait long ^^ tu fais quoi là exactement ??? t' es encore dessus ??? et tu fais quoi ?

**Comment by LucileDT** [comment]
C'était pour remplir les passages que @Albapringe a pas pu faire, et j'ai discuté avec mes parents au milieu, du coup j'ai pas eu le temps de finir dans la nuit, comme je le voulais :|

Pas grave, t'en fais pas, tu peux continuer, je n'avais pas beaucoup avancé de toute façon :)

**Comment by bayasahra** [comment]
oui :)... Donc enlève le label "someone is working" quand tu n'es plus dessus Lucile merci. Je ne m'étais pas trompée en pensant que tu n'étais pas dessus et en commençant la correction...je ne comprends pas ton mess qui me fais m'interrompre...c'est dommage j'ai perdu 40 minutes de temps que je pouvais consacrer à cette vidéo... Je reprendrai peut être ce soir si j'ai le temps.

**Comment by LucileDT** [comment]
Désolée :(

**Comment by Bentham** [comment]
Je regarde si je peux avancer les passages 5:53 à 6:27, 7:07 à 8:37, 12:26 à 13:41.

**Comment by Bentham** [comment]
C'est fait !

**Comment by bayasahra** [comment]
@Bentham Bon je vais me lancer dans la correction de celui ci ... tu te sentirais une préference ?? l'ortho ou le timing+retranscription ? :)... monsieur propose et je dispose

**Comment by bayasahra** [comment]
je suis dessus.
J'ai fait une pause je m'y remets.

**Comment by bayasahra** [comment]
Fini prêt pour la deuxième correction.

**Comment by bayasahra** [comment]
je clos l'issue ^^ elle est en ligne quelqu'un a du relire et faire la dernière validation.
