### ISSUE TITLE
[subtitles] [FR] J-10 POUR POUVOIR VOTER !

### ISSUE THREAD

**Issue by bayasahra** [jlm2017/jlm-video-subtitles#98]
# Video title

J-10 POUR POUVOIR VOTER !

# URL

https://www.youtube.com/watch?v=I_S7MZc8_qI&feature=em-uploademail

# Youtube subtitles language

Français

# Duration

3:37

# URL subtitles

https://www.youtube.com/timedtext_editor?ref=watch&bl=vmp&action_mde_edit_form=1&tab=captions&lang=fr&ui=hd&v=I_S7MZc8_qI

**Comment by bayasahra** [comment]
suis dessus !

**Comment by bayasahra** [comment]
fini. A toi de jouer mon ti Ben lol ^^

**Comment by Bentham** [comment]
Bentham à l'assaut !

**Comment by Bentham** [comment]
Fait ! Y'a plus qu'à passer derrière pour valider !

**Comment by bayasahra** [comment]
;) fait en ligne :)

**Comment by Bentham** [comment]
You're the best !
