### ISSUE TITLE
[subtitles] [eng] Mélenchon mouche les partisans de la guerre avec la Russie au Parlement européen

### ISSUE THREAD

**Issue by Flupignon** [jlm2017/jlm-video-subtitles#99]
# Video title

Mélenchon mouche les partisans de la guerre avec la Russie au Parlement européen

# URL

https://www.youtube.com/watch?v=Z2ft5y2nyqY

# Youtube subtitle language

English

# Duration

2:14

# URL subtitles

https://www.youtube.com/timedtext_editor?lang=en&tab=captions&action_mde_edit_form=1&bl=vmp&ui=hd&ref=player&v=Z2ft5y2nyqY

**Comment by Goutte** [comment]
ce sont des bavardages => they're just talking => they're just schmoozing

J'ai juste changé ça, et puis j'ai approuvé. :)
